'use strict';
const express=require('express');
const path=require('node:path');
const fs=require('node:fs');
const cors=require('cors');
const authRoutes=require('./routes/authRoutes');
const userRoutes=require('./routes/userRoutes');
const profileRoutes=require('./routes/profileRoutes');
const settingsRoutes=require('./routes/settingsRoutes');
const documentSecurityRoutes=require('./routes/documentSecurityRoutes');
const securityDashboardRoutes=require('./routes/securityDashboardRoutes');
const securityIncidentRoutes=require('./routes/securityIncidentRoutes');
const readinessRoutes=require('./routes/readinessRoutes');
const backgroundJobRoutes=require('./routes/backgroundJobRoutes');
const securityTelemetry=require('./controllers/securityTelemetryController');
const readiness=require('./controllers/readinessController');
const auth=require('./middleware/auth');
const pageAuth=require('./middleware/pageAuth');
const {injectGlobalBrand}=require('./services/globalBrandRenderer');
const urls=require('./config/urls');
const {corsOptions,csrfProtection,enforceHttps,rateLimitPolicy,safeApiResponses,securityHeaders,safeErrorHandler}=require('./middleware/securityMiddleware');
const {retiredRequest,retiredAsset}=require('./services/applicationRetirement');
const app=express();
const publicDir=path.join(__dirname,'public');
const pageCache=new Map();
const raw=(req,res,buffer)=>{req.rawBody=Buffer.from(buffer)};
app.disable('x-powered-by');app.set('trust proxy',1);app.set('query parser','simple');
app.use(enforceHttps);app.use(securityHeaders);app.use(safeApiResponses);
const applicationCors=cors(corsOptions());
app.use((req,res,next)=>req.method==='POST'&&req.path==='/api/security/csp-report'&&req.headers.origin==='null'?next():applicationCors(req,res,next));
app.use(rateLimitPolicy('authenticated_api'));
app.use('/api/auth',express.json({limit:'8kb',type:'application/json',verify:raw}));
app.use(express.json({limit:process.env.JSON_BODY_LIMIT||'1mb',type:['application/json','application/csp-report','application/reports+json'],verify:raw}));
app.use(express.urlencoded({extended:false,limit:process.env.FORM_BODY_LIMIT||'1mb'}));
app.post('/api/security/csp-report',rateLimitPolicy('csp_report'),securityTelemetry.recordCspViolation);
app.use(csrfProtection);
app.get('/api/health',readiness.health);app.get('/api/ready',readiness.ready);
app.use((req,res,next)=>{
 if(process.env.FORCE_CANONICAL_HOST!=='true'||['/api/health','/api/ready'].includes(req.path))return next();
 const host=String(req.hostname||'').toLowerCase(),canonical=new URL(urls.app).hostname;
 if(host!==String(process.env.RAILWAY_FALLBACK_HOST||'voxelveda-app-production.up.railway.app').toLowerCase()||host===canonical)return next();
 return res.redirect(302,new URL(req.originalUrl||'/',`${urls.app}/`).toString());
});
function noIndex(req,res,next){res.set('X-Robots-Tag','noindex, nofollow, noarchive').set('Cache-Control','private, no-store');next()}
function sendPage(filename,status=200){return(req,res)=>{
 const source=path.join(publicDir,filename);let html=pageCache.get(source);
 if(!html||process.env.NODE_ENV!=='production'){html=injectGlobalBrand(fs.readFileSync(source,'utf8'));if(process.env.NODE_ENV==='production')pageCache.set(source,html)}
 return res.status(status).type('html').send(html);
}}
function redirect(target){return(req,res)=>{const index=req.originalUrl.indexOf('?');return res.redirect(302,target+(index>=0?req.originalUrl.slice(index):''));}}
app.get('/',sendPage('index.html'));
app.get('/login',noIndex,sendPage('login.html'));
app.get('/register',noIndex,sendPage('register.html'));
app.get('/privacy',sendPage('privacy-policy.html'));
app.get('/terms',sendPage('terms.html'));
app.get('/support',sendPage('support.html'));
app.get('/careers',sendPage('careers.html'));
app.get('/forgot-password',noIndex,sendPage('forgot-password.html'));
app.get('/reset-password',noIndex,sendPage('reset-password.html'));
app.get('/accept-invite',noIndex,sendPage('accept-invite.html'));
app.get('/mfa',noIndex,sendPage('mfa.html'));
app.get('/security',noIndex,pageAuth({allowMfaSetup:true}),sendPage('security.html'));
app.get('/dashboard',noIndex,pageAuth(),sendPage('workspace.html'));
app.get('/profile',noIndex,pageAuth(),sendPage('profile.html'));
app.get(['/admin','/client','/portal/:role','/admin-dashboard.html','/staff-dashboard.html','/client-portal.html'],noIndex,pageAuth(),redirect('/dashboard'));
const aliases={'/index.html':'/','/login.html':'/login','/register.html':'/register','/privacy-policy.html':'/privacy','/profile.html':'/profile','/dashboard.html':'/dashboard','/workspace.html':'/dashboard','/security.html':'/security','/mfa.html':'/mfa','/forgot-password.html':'/forgot-password','/reset-password.html':'/reset-password','/accept-invite.html':'/accept-invite','/support.html':'/support','/terms.html':'/terms','/careers.html':'/careers'};
for(const [from,to] of Object.entries(aliases))app.get(from,redirect(to));
for(const status of [401,403,404,429,500])app.get('/'+status,noIndex,sendPage(status+'.html',status));
app.get('/maintenance',noIndex,sendPage('maintenance.html',503));
app.use((req,res,next)=>{
 if(!retiredRequest(req.path)&&!retiredAsset(req.path))return next();
 res.set('Cache-Control','private, no-store').set('X-Robots-Tag','noindex, nofollow, noarchive');
 if(req.path.startsWith('/api/'))return res.status(410).json({code:'MODULE_RETIRED',message:'This module has been removed from Voxel Veda.'});
 return sendPage('retired.html',410)(req,res);
});
app.use('/api/auth',authRoutes);
app.use('/api/users',auth,userRoutes);
app.use('/api/profile',auth,profileRoutes);
app.use('/api/settings',auth,settingsRoutes);
app.use('/api/documents',auth,documentSecurityRoutes);
app.use('/api/security/readiness',auth,readinessRoutes);
app.use('/api/security/workers',auth,backgroundJobRoutes);
app.use('/api/security',auth,securityDashboardRoutes);
app.use('/api/security',auth,securityIncidentRoutes);
const noStore=new Set(['workspace.html','workspace.js','workspace.css','workspace-theme.css','workspace-theme.js','style.css','global-brand.css','global-brand.js','public-pages.css','auth-entry.css','login.js','register.js','auth-lifecycle.js','mfa.js','security-page.js','profile.js','step-up.js','step-up.css','service-worker.js']);
app.use(express.static(publicDir,{dotfiles:'deny',index:false,setHeaders(res,file){res.set('X-Content-Type-Options','nosniff');if(noStore.has(path.basename(file)))res.set('Cache-Control','no-store, max-age=0')}}));
app.use((req,res)=>{if(!req.path.startsWith('/api/')&&req.accepts('html'))return sendPage('404.html',404)(req,res);return res.status(404).json({message:'Route not found'})});
app.use(safeErrorHandler);
module.exports=app;
