CREATE TABLE IF NOT EXISTS finance_cash_custody_cases (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  custody_uid CHAR(36) NOT NULL,
  source_type VARCHAR(24) NOT NULL,
  bank_account_id INT NULL,
  personal_wallet_id CHAR(36) NULL,
  ownership_scope VARCHAR(24) NOT NULL,
  currency CHAR(3) NOT NULL,
  custodian VARCHAR(160) NOT NULL,
  purpose VARCHAR(240) NULL,
  issued_amount DECIMAL(18,4) NOT NULL,
  issued_at DATETIME NOT NULL,
  due_at DATETIME NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'OPEN',
  note VARCHAR(700) NULL,
  created_by INT NOT NULL,
  closed_by INT NULL,
  closed_at DATETIME NULL,
  cancelled_by INT NULL,
  cancelled_at DATETIME NULL,
  cancel_reason VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_finance_cash_custody_uid (custody_uid),
  INDEX idx_finance_cash_custody_bank (bank_account_id,status,due_at),
  INDEX idx_finance_cash_custody_wallet (personal_wallet_id,status,due_at),
  INDEX idx_finance_cash_custody_custodian (custodian,status,due_at)
);

CREATE TABLE IF NOT EXISTS finance_cash_custody_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  event_uid CHAR(36) NOT NULL,
  custody_id BIGINT NOT NULL,
  event_type VARCHAR(32) NOT NULL,
  amount DECIMAL(18,4) NOT NULL,
  occurred_at DATETIME NOT NULL,
  bank_transaction_id BIGINT NULL,
  personal_money_entry_id CHAR(36) NULL,
  active_link_key VARCHAR(220) NULL,
  reversal_of_event_id BIGINT NULL,
  reference_text VARCHAR(240) NULL,
  note VARCHAR(500) NULL,
  recorded_by INT NOT NULL,
  reversed_by INT NULL,
  reversed_at DATETIME NULL,
  reversal_reason VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_finance_cash_custody_event_uid (event_uid),
  UNIQUE KEY uniq_finance_cash_custody_active_link (active_link_key),
  INDEX idx_finance_cash_custody_event_case (custody_id,occurred_at),
  INDEX idx_finance_cash_custody_event_bank (bank_transaction_id,event_type),
  INDEX idx_finance_cash_custody_event_personal (personal_money_entry_id,event_type)
);
