CREATE TABLE IF NOT EXISTS recovery_drill_records (
  id VARCHAR(36) NOT NULL,
  title VARCHAR(160) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  operator_label VARCHAR(120) NOT NULL,
  backup_identifier VARCHAR(255) NULL,
  backup_created_at DATETIME(3) NULL,
  recovery_environment VARCHAR(255) NULL,
  started_at DATETIME(3) NULL,
  restore_completed_at DATETIME(3) NULL,
  validation_completed_at DATETIME(3) NULL,
  restore_result VARCHAR(32) NULL,
  integrity_checks_json JSON NULL,
  evidence_refs_json JSON NULL,
  findings_json JSON NULL,
  actual_rpo_hours DECIMAL(12,3) NULL,
  actual_rto_hours DECIMAL(12,3) NULL,
  rpo_target_hours DECIMAL(12,3) NOT NULL DEFAULT 24,
  rto_target_hours DECIMAL(12,3) NOT NULL DEFAULT 4,
  rpo_objective_status VARCHAR(24) NULL,
  rto_objective_status VARCHAR(24) NULL,
  final_decision VARCHAR(40) NULL,
  decision_note TEXT NULL,
  next_drill_at DATETIME(3) NULL,
  created_by_user_id VARCHAR(191) NOT NULL,
  finalized_by_user_id VARCHAR(191) NULL,
  finalized_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_recovery_drill_status_created (status, created_at),
  KEY idx_recovery_drill_finalized (finalized_at),
  KEY idx_recovery_drill_next (next_drill_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS recovery_drill_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  drill_id VARCHAR(36) NOT NULL,
  actor_user_id VARCHAR(191) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  event_json JSON NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_recovery_drill_event_drill (drill_id, id),
  KEY idx_recovery_drill_event_created (created_at),
  CONSTRAINT fk_recovery_drill_event_drill FOREIGN KEY (drill_id) REFERENCES recovery_drill_records(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
