CREATE TABLE IF NOT EXISTS personal_asset_lifecycle_items (
  id CHAR(36) PRIMARY KEY,
  user_id VARCHAR(191) NOT NULL,
  asset_id CHAR(36) NULL,
  liability_id CHAR(36) NULL,
  item_type VARCHAR(40) NOT NULL,
  title VARCHAR(180) NOT NULL,
  provider VARCHAR(180) NULL,
  reference_no VARCHAR(120) NULL,
  currency CHAR(3) NOT NULL DEFAULT 'AUD',
  amount DECIMAL(18,4) NULL,
  start_date DATE NULL,
  due_date DATE NULL,
  renewal_frequency VARCHAR(30) NULL,
  reminder_days SMALLINT UNSIGNED NOT NULL DEFAULT 30,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  note VARCHAR(500) NULL,
  last_completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_pali_asset FOREIGN KEY (asset_id) REFERENCES personal_net_worth_assets(id),
  CONSTRAINT fk_pali_liability FOREIGN KEY (liability_id) REFERENCES personal_net_worth_liabilities(id),
  INDEX idx_pali_user_due (user_id, status, due_date),
  INDEX idx_pali_user_asset (user_id, asset_id),
  INDEX idx_pali_user_liability (user_id, liability_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS personal_asset_documents (
  id CHAR(36) PRIMARY KEY,
  user_id VARCHAR(191) NOT NULL,
  asset_id CHAR(36) NULL,
  liability_id CHAR(36) NULL,
  document_type VARCHAR(50) NOT NULL,
  title VARCHAR(180) NOT NULL,
  document_url VARCHAR(700) NOT NULL,
  expiry_date DATE NULL,
  note VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_pad_asset FOREIGN KEY (asset_id) REFERENCES personal_net_worth_assets(id),
  CONSTRAINT fk_pad_liability FOREIGN KEY (liability_id) REFERENCES personal_net_worth_liabilities(id),
  INDEX idx_pad_user_asset (user_id, asset_id),
  INDEX idx_pad_user_liability (user_id, liability_id),
  INDEX idx_pad_user_expiry (user_id, expiry_date)
) ENGINE=InnoDB;
