CREATE TABLE IF NOT EXISTS personal_finance_recovery_management_reviews (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(191) NOT NULL,
  review_month CHAR(7) NOT NULL,
  status ENUM('DRAFT','ACKNOWLEDGED','ATTESTED') NOT NULL DEFAULT 'DRAFT',
  reviewer_label VARCHAR(120) NULL,
  management_decision VARCHAR(500) NULL,
  evidence_checklist_json JSON NULL,
  carry_forward_json JSON NULL,
  snapshot_json JSON NOT NULL,
  snapshot_sha256 CHAR(64) NOT NULL,
  previous_review_sha256 CHAR(64) NULL,
  review_sha256 CHAR(64) NOT NULL,
  acknowledged_at DATETIME NULL,
  attested_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_pf_recovery_management_review_owner_month (user_id, review_month),
  KEY idx_pf_recovery_management_review_owner_created (user_id, created_at)
);
