ALTER TABLE users ADD COLUMN IF NOT EXISTS department VARCHAR(120) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS manager_id INT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS access_scope JSON NULL;
