CREATE TABLE statement_import_sessions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  import_uid VARCHAR(60) NOT NULL,
  bank_account_id INT NOT NULL,
  source_format VARCHAR(20) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  content_hash CHAR(64) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW',
  statement_start_date DATE NULL,
  statement_end_date DATE NULL,
  opening_balance DECIMAL(18,2) NULL,
  closing_balance DECIMAL(18,2) NULL,
  total_rows INT NOT NULL DEFAULT 0,
  valid_rows INT NOT NULL DEFAULT 0,
  warning_rows INT NOT NULL DEFAULT 0,
  duplicate_rows INT NOT NULL DEFAULT 0,
  rejected_rows INT NOT NULL DEFAULT 0,
  created_by INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_by INT NULL,
  reviewed_at DATETIME NULL,
  committed_by INT NULL,
  committed_at DATETIME NULL,
  rejection_reason TEXT NULL,
  UNIQUE KEY uniq_statement_session_uid (import_uid),
  UNIQUE KEY uniq_statement_session_account_hash (bank_account_id, content_hash),
  INDEX idx_statement_session_queue (status, created_at),
  INDEX idx_statement_session_account (bank_account_id, created_at)
);

CREATE TABLE statement_import_rows (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  import_session_id BIGINT NOT NULL,
  row_no INT NOT NULL,
  transaction_date DATE NULL,
  posting_date DATE NULL,
  description VARCHAR(500) NULL,
  reference VARCHAR(180) NULL,
  debit DECIMAL(18,2) NOT NULL DEFAULT 0,
  credit DECIMAL(18,2) NOT NULL DEFAULT 0,
  running_balance DECIMAL(18,2) NULL,
  merchant_name VARCHAR(255) NULL,
  category VARCHAR(120) NULL,
  currency CHAR(3) NULL,
  row_hash CHAR(64) NULL,
  validation_status VARCHAR(20) NOT NULL DEFAULT 'VALID',
  validation_message VARCHAR(500) NULL,
  selected TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_statement_session_row (import_session_id, row_no),
  INDEX idx_statement_rows_review (import_session_id, validation_status, selected),
  INDEX idx_statement_rows_hash (row_hash)
);
