CREATE TABLE IF NOT EXISTS finance_cash_counts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  count_uid CHAR(36) NOT NULL,
  source_type VARCHAR(24) NOT NULL,
  bank_account_id INT NULL,
  personal_wallet_id CHAR(36) NULL,
  ownership_scope VARCHAR(24) NOT NULL,
  currency CHAR(3) NOT NULL,
  expected_amount DECIMAL(18,4) NOT NULL DEFAULT 0,
  actual_amount DECIMAL(18,4) NOT NULL DEFAULT 0,
  variance_amount DECIMAL(18,4) NOT NULL DEFAULT 0,
  status VARCHAR(24) NOT NULL DEFAULT 'BALANCED',
  custodian VARCHAR(160) NULL,
  counted_at DATETIME NOT NULL,
  note VARCHAR(700) NULL,
  recorded_by INT NOT NULL,
  reviewed_by INT NULL,
  reviewed_at DATETIME NULL,
  review_note VARCHAR(700) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_finance_cash_count_uid (count_uid),
  INDEX idx_finance_cash_count_source (source_type,bank_account_id,personal_wallet_id,counted_at),
  INDEX idx_finance_cash_count_review (status,counted_at),
  INDEX idx_finance_cash_count_owner (recorded_by,counted_at)
);

CREATE TABLE IF NOT EXISTS finance_cash_transfer_links (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  transfer_uid CHAR(36) NOT NULL,
  bank_transaction_id BIGINT NOT NULL,
  personal_wallet_id CHAR(36) NOT NULL,
  personal_money_entry_id CHAR(36) NOT NULL,
  reversal_entry_id CHAR(36) NULL,
  direction VARCHAR(24) NOT NULL,
  amount DECIMAL(18,4) NOT NULL,
  currency CHAR(3) NOT NULL,
  previous_internal_transfer TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  note VARCHAR(500) NULL,
  linked_by INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reversed_by INT NULL,
  reversed_at DATETIME NULL,
  reversal_reason VARCHAR(500) NULL,
  UNIQUE KEY uniq_finance_cash_transfer_uid (transfer_uid),
  UNIQUE KEY uniq_finance_cash_transfer_entry (personal_money_entry_id),
  INDEX idx_finance_cash_transfer_bank (bank_transaction_id,status),
  INDEX idx_finance_cash_transfer_wallet (personal_wallet_id,status,created_at)
);
