'use strict';
const express=require('express');
const controller=require('../controllers/erpWorkspaceController');
const { requireAnyPermission }=require('../middleware/authorizationMiddleware');
const { bodyContract }=require('../middleware/requestContractMiddleware');
const { rateLimit }=require('../middleware/securityMiddleware');
const router=express.Router();
router.use(rateLimit({windowMs:60000,max:60,keyPrefix:'erp-workspace'}));
router.get('/workspace',requireAnyPermission('VIEW_DASHBOARD','VIEW_RFQS','VIEW_CUSTOMERS','VIEW_PROCUREMENT','VIEW_INVENTORY','VIEW_QMS','VIEW_COMPLIANCE','VIEW_STAFF_HR','VIEW_ATTENDANCE','VIEW_FINANCE','VIEW_APPROVALS'),controller.workspace);
const campaignFields=['name','channel','objective','status','start_date','end_date','currency','planned_budget','customer_id','rfq_id'];
router.post('/campaigns',requireAnyPermission('VIEW_CUSTOMERS'),requireAnyPermission('EDIT_CUSTOMERS'),bodyContract(campaignFields,{required:['name','channel','objective']}),controller.createCampaign);
router.put('/campaigns/:id',requireAnyPermission('VIEW_CUSTOMERS'),requireAnyPermission('EDIT_CUSTOMERS'),bodyContract([...campaignFields,'revision'],{required:['name','channel','objective','revision']}),controller.updateCampaign);
const viewProduction=requireAnyPermission('VIEW_QMS','VIEW_COMPLIANCE');
const editProduction=requireAnyPermission('MANAGE_JOBS','MANAGE_QMS','EDIT_COMPLIANCE');
router.post('/work-orders',viewProduction,editProduction,bodyContract(['part_no','part_description','quantity','sector','drawing_no','drawing_revision','rfq_id'],{required:['part_no','part_description','quantity']}),controller.createJob);
router.post('/work-orders/:id/operations',viewProduction,editProduction,bodyContract(['operation_name','machine_id','planned_start','planned_end','required_competency_code','work_instruction_ref'],{required:['operation_name','machine_id','planned_start','planned_end']}),controller.scheduleOperation);
module.exports=router;
