const express = require('express');
const fs = require('node:fs');
const path = require('node:path');
const multer = require('multer');
const controller = require('../controllers/financeController');
const operations = require('../controllers/financeOperationsController');
const intelligence = require('../controllers/financeIntelligenceController');
const bankAccountLifecycle = require('../controllers/bankAccountLifecycleController');
const statementReview = require('../controllers/statementImportController');
const statementData = require('../controllers/statementDataManagementController');
const transactionIntelligence = require('../controllers/financeTransactionIntelligenceController');
const reconciliationCenter = require('../controllers/financeReconciliationCenterController');
const bankingReadiness = require('../controllers/financeBankingReadinessController');
const bankingOS = require('../controllers/bankingOperatingSystemController');
const openBanking = require('../controllers/openBankingController');
const financeReceipt = require('../controllers/financeReceiptController');
const financeCashControl = require('../controllers/financeCashControlController');
const financeCloseAssurance = require('../controllers/financeCloseAssuranceController');
const financeTreasury = require('../controllers/financeTreasuryController');
const financePerformanceRisk = require('../controllers/financePerformanceRiskController');
const financeAnomalyExplain = require('../controllers/financeAnomalyExplainController');
const financePlanningControl = require('../controllers/financePlanningControlController');
const financeJobProfitability = require('../controllers/financeJobProfitabilityController');
const financeAccountantHandover = require('../controllers/financeAccountantHandoverController');
const financeAudit = require('../controllers/financeAuditController');
const financeRelationships = require('../controllers/financeRelationshipController');
const financeReportBuilder = require('../controllers/financeReportBuilderController');
const financeTransactionLifecycle = require('../controllers/financeTransactionLifecycleController');
const financeCategories = require('../controllers/financeCategoryController');
const financeUserPreferences = require('../controllers/financeUserPreferencesController');
const financeFx = require('../controllers/financeFxController');
const financeSearch = require('../controllers/financeSearchController');
const personalMoney = require('../controllers/personalMoneyController');
const personalMoneyAttention = require('../controllers/personalMoneyAttentionController');
const personalDebtPlanning = require('../controllers/personalDebtPlanningController');
const personalMoneySmart = require('../controllers/personalMoneySmartController');
const personalMoneyReview = require('../controllers/personalMoneyReviewController');
const personalMoneyHealth = require('../controllers/personalMoneyHealthController');
const personalMoneyDailyBriefing = require('../controllers/personalMoneyDailyBriefingController');
const personalFinanceSavedViews = require('../controllers/personalFinanceSavedViewsController');
const personalSpendingChallenges = require('../controllers/personalSpendingChallengeController');
const personalNetWorth = require('../controllers/personalNetWorthController');
const personalAssetLifecycle = require('../controllers/personalAssetLifecycleController');
const personalFinancialRoadmap = require('../controllers/personalFinancialRoadmapController');
const personalFinancialDataQuality = require('../controllers/personalFinancialDataQualityController');
const personalFinanceCanonicalBackup = require('../controllers/personalFinanceCanonicalBackupController');
const personalFinanceCanonicalRestore = require('../controllers/personalFinanceCanonicalRestoreController');
const personalFinanceRestoreTransport = require('../controllers/personalFinanceRestoreTransportController');
const personalFinancePostRestoreVerification = require('../controllers/personalFinancePostRestoreVerificationController');
const personalFinanceRecoveryCertification = require('../controllers/personalFinanceRecoveryCertificationController');
const requireInputPermission = require('../middleware/inputPermissionMiddleware');
const requirePermission = require('../middleware/permissionMiddleware');
const { requireAnyPermission } = require('../middleware/authorizationMiddleware');
const requireStepUp = require('../middleware/stepUpMiddleware');
const requireSensitiveExportApproval = require('../middleware/sensitiveExportMiddleware');
const highRiskPaymentGuard = require('../middleware/highRiskPaymentMiddleware');
const statementPreviewSanitizer = require('../middleware/statementPreviewSanitizer');
const financePrivacy = require('../middleware/financePrivacyMiddleware');
const { sanitizeUploadName, secureMulterOptions, validateUploadedFile } = require('../middleware/uploadSecurity');
const { financeCapabilities } = require('../services/financeCapabilityRegistry');

const router = express.Router();
const financeUploadDir = path.join(__dirname, '..', 'uploads', 'finance');
if (!fs.existsSync(financeUploadDir)) fs.mkdirSync(financeUploadDir, { recursive: true });
const financeReceiptStorage = multer.diskStorage({
  destination(req, file, cb) { cb(null, financeUploadDir); },
  filename(req, file, cb) { cb(null, `receipt_${req.params.id}_${Date.now()}_${sanitizeUploadName(file.originalname)}`); }
});
const financeReceiptUpload = multer(secureMulterOptions(financeReceiptStorage, 12));


router.use(financePrivacy.resolveBankingAccessScope);

router.get('/capabilities', requireAnyPermission('VIEW_BANKING'), (req, res) => res.json(financeCapabilities()));
router.get('/search', requireAnyPermission('VIEW_BANKING'), financeSearch.search);
router.get('/company-summary', requireAnyPermission('VIEW_BUSINESS_BANKING'), financeSearch.companySummary);
router.get('/job-profitability', requireAnyPermission('VIEW_BUSINESS_BANKING'), financeJobProfitability.getCenter);
router.get('/preferences', requireAnyPermission('VIEW_BANKING'), financeUserPreferences.get);
router.put('/preferences', requireAnyPermission('VIEW_BANKING'), financeUserPreferences.save);
router.get('/fx-rates', requireAnyPermission('VIEW_BANKING'), financeFx.list);
router.post('/fx-rates', requireAnyPermission('EDIT_FINANCE'), financeFx.save);
router.post('/fx-rates/:uid/archive', requireAnyPermission('EDIT_FINANCE'), financeFx.archive);
router.get('/overview', controller.getOverview);
router.get('/financial-years', controller.getFinancialYears);
router.post('/financial-years/:id/check', requireAnyPermission('EDIT_FINANCE'), controller.runYearEndCheck);
router.post('/financial-years/:id/status', requireAnyPermission('EDIT_FINANCE'), requireStepUp('CHANGE_FINANCIAL_YEAR_STATUS'), controller.updateFinancialYearStatus);
router.get('/issues', controller.getIssues);
router.post('/issues/:id', requireAnyPermission('EDIT_FINANCE'), controller.updateIssue);
router.get('/setup', controller.getSetup);
router.post('/setup', requireAnyPermission('EDIT_FINANCE'), requireStepUp('CHANGE_FINANCE_SETTINGS'), controller.updateSetup);
router.get('/transactions', controller.getTransactions);
router.get('/transactions/:id', controller.getTransaction);
router.post('/transactions', requireAnyPermission('EDIT_FINANCE'), controller.saveTransaction);
router.post('/transactions/:id/post', requireAnyPermission('POST_TRANSACTION'), requireStepUp('POST_FINANCIAL_TRANSACTION'), controller.postTransaction);
router.post('/transactions/:id/void', requireAnyPermission('VOID_TRANSACTION'), requireStepUp('VOID_FINANCIAL_TRANSACTION'), controller.voidTransaction);
router.get('/journals', controller.getJournals);
router.post('/journals', requireAnyPermission('EDIT_FINANCE'), requireStepUp('CREATE_MANUAL_JOURNAL'), controller.createJournal);
router.get('/categories', requireAnyPermission('VIEW_BANKING'), financeCategories.list);
router.post('/categories', requireAnyPermission('EDIT_FINANCE'), financeCategories.save);
router.post('/categories/:id/archive', requireAnyPermission('EDIT_FINANCE'), financeCategories.archive);
router.post('/categories/:id/restore', requireAnyPermission('EDIT_FINANCE'), financeCategories.restore);
router.get('/reports', controller.getReports);
router.get('/reports/builder', requireAnyPermission('VIEW_BANKING'), financeReportBuilder.generate);
router.get('/reports/builder.csv', requirePermission('EXPORT_FINANCIAL_DATA'), requireStepUp('EXPORT_FINANCIAL_DATA'), requireSensitiveExportApproval('FINANCE'), financeReportBuilder.csv);
router.get('/reports/builder.pdf', requirePermission('EXPORT_FINANCIAL_DATA'), requireStepUp('EXPORT_FINANCIAL_DATA'), requireSensitiveExportApproval('FINANCE'), financeReportBuilder.pdf);
router.get('/reports/builder.xlsx', requirePermission('EXPORT_FINANCIAL_DATA'), requireStepUp('EXPORT_FINANCIAL_DATA'), requireSensitiveExportApproval('FINANCE'), financeReportBuilder.xlsx);
router.get('/reports/saved', requireAnyPermission('VIEW_BANKING'), financeReportBuilder.listSaved);
router.post('/reports/saved', requireAnyPermission('VIEW_BANKING'), financeReportBuilder.save);
router.get('/reports/saved/:uid/run', requireAnyPermission('VIEW_BANKING'), financeReportBuilder.runSaved);
router.delete('/reports/saved/:uid', requireAnyPermission('VIEW_BANKING'), financeReportBuilder.remove);
router.get('/accountant-handover', requireAnyPermission('VIEW_BUSINESS_BANKING'), financeAccountantHandover.getCenter);
router.post('/accountant-handover/:financialYearId/snapshot', requireAnyPermission('VIEW_BUSINESS_BANKING'), requireAnyPermission('EDIT_FINANCE'), financeAccountantHandover.captureSnapshot);
router.get('/accountant-handover/:financialYearId.pdf', requireAnyPermission('VIEW_BUSINESS_BANKING'), requirePermission('EXPORT_FINANCIAL_DATA'), requireStepUp('EXPORT_ACCOUNTANT_PACK'), requireSensitiveExportApproval('ACCOUNTANT_PACK'), financeAccountantHandover.pdf);
router.get('/exports/trial-balance.csv', requirePermission('EXPORT_FINANCIAL_DATA'), requireStepUp('EXPORT_FINANCIAL_DATA'), requireSensitiveExportApproval('FINANCE'), controller.downloadTrialBalanceCsv);
router.get('/exports/accountant-review.pdf', requirePermission('EXPORT_FINANCIAL_DATA'), requireStepUp('EXPORT_ACCOUNTANT_PACK'), requireSensitiveExportApproval('ACCOUNTANT_PACK'), controller.downloadAccountantPdf);

router.get('/personal-money', requireAnyPermission('VIEW_BANKING'), personalMoney.getDashboard);
router.get('/personal-money/canonical-backup', requireAnyPermission('VIEW_BANKING'), requireStepUp('EXPORT_PERSONAL_FINANCE_BACKUP'), personalFinanceCanonicalBackup.getCanonicalBackup);
router.get('/personal-money/canonical-restore/status', requireAnyPermission('VIEW_BANKING'), personalFinanceCanonicalRestore.status);
router.post('/personal-money/canonical-restore/dry-run', requireAnyPermission('VIEW_BANKING'), requireStepUp('PREVIEW_PERSONAL_FINANCE_RESTORE'), personalFinanceCanonicalRestore.dryRun);
router.post('/personal-money/canonical-restore/execute', requireAnyPermission('EDIT_FINANCE'), requireStepUp('RESTORE_PERSONAL_FINANCE'), personalFinanceCanonicalRestore.execute);
router.post('/personal-money/canonical-restore/:id/rollback', requireAnyPermission('EDIT_FINANCE'), requireStepUp('ROLLBACK_PERSONAL_FINANCE_RESTORE'), personalFinanceCanonicalRestore.rollback);
router.get('/personal-money/canonical-restore/:id/verification', requireAnyPermission('VIEW_BANKING'), personalFinancePostRestoreVerification.get);
router.post('/personal-money/canonical-restore/:id/verification/initialize', requireAnyPermission('VIEW_BANKING'), personalFinancePostRestoreVerification.initialize);
router.get('/personal-money/canonical-restore/:id/certificates', requireAnyPermission('VIEW_BANKING'), personalFinanceRecoveryCertification.list);
router.post('/personal-money/canonical-restore/:id/certificates', requireAnyPermission('VIEW_BANKING'), requireStepUp('CERTIFY_PERSONAL_FINANCE_RECOVERY'), personalFinanceRecoveryCertification.generate);
router.get('/personal-money/canonical-restore/:id/certificates/:certificateId', requireAnyPermission('VIEW_BANKING'), requireStepUp('EXPORT_PERSONAL_FINANCE_RECOVERY_EVIDENCE'), personalFinanceRecoveryCertification.get);
router.post('/personal-money/canonical-restore-upload', requireAnyPermission('VIEW_BANKING'), requireStepUp('PREVIEW_PERSONAL_FINANCE_RESTORE'), personalFinanceRestoreTransport.start);
router.get('/personal-money/canonical-restore-upload/:id', requireAnyPermission('VIEW_BANKING'), personalFinanceRestoreTransport.status);
router.put('/personal-money/canonical-restore-upload/:id/chunks/:index', requireAnyPermission('VIEW_BANKING'), personalFinanceRestoreTransport.putChunk);
router.post('/personal-money/canonical-restore-upload/:id/finalize', requireAnyPermission('VIEW_BANKING'), personalFinanceRestoreTransport.finalize);
router.delete('/personal-money/canonical-restore-upload/:id', requireAnyPermission('VIEW_BANKING'), personalFinanceRestoreTransport.cancel);
router.post('/personal-money/canonical-restore-upload/:id/dry-run', requireAnyPermission('VIEW_BANKING'), requireStepUp('PREVIEW_PERSONAL_FINANCE_RESTORE'), personalFinanceRestoreTransport.dryRunFromUpload);
router.post('/personal-money/canonical-restore-upload/:id/execute', requireAnyPermission('EDIT_FINANCE'), requireStepUp('RESTORE_PERSONAL_FINANCE'), personalFinanceRestoreTransport.executeFromUpload);
router.post('/personal-money/wallets', requireAnyPermission('EDIT_FINANCE'), personalMoney.createWallet);
router.post('/personal-money/wallets/:id/active', requireAnyPermission('EDIT_FINANCE'), personalMoney.setWalletActive);
router.post('/personal-money/entries', requireAnyPermission('EDIT_FINANCE'), personalMoney.createEntry);
router.get('/personal-money/debt-planner', requireAnyPermission('VIEW_BANKING'), personalDebtPlanning.getPlanner);
router.post('/personal-money/debts', requireAnyPermission('EDIT_FINANCE'), personalMoney.createDebt);
router.get('/personal-money/debts/:id/statement', requireAnyPermission('VIEW_BANKING'), personalDebtPlanning.getStatement);
router.put('/personal-money/debts/:id/terms', requireAnyPermission('EDIT_FINANCE'), personalDebtPlanning.saveTerms);
router.get('/personal-money/debts/:id', requireAnyPermission('VIEW_BANKING'), personalMoney.getDebtDetail);
router.put('/personal-money/debts/:id', requireAnyPermission('EDIT_FINANCE'), personalMoney.updateDebtDetail);
router.post('/personal-money/debts/:id/payments', requireAnyPermission('EDIT_FINANCE'), personalMoney.recordDebtPayment);
router.post('/personal-money/budgets', requireAnyPermission('EDIT_FINANCE'), personalMoney.saveBudget);
router.delete('/personal-money/budgets/:id', requireAnyPermission('EDIT_FINANCE'), personalMoney.deleteBudget);
router.get('/personal-money/attention', requireAnyPermission('VIEW_BANKING'), personalMoneyAttention.getAttentionCenter);
router.post('/personal-money/recurring', requireAnyPermission('EDIT_FINANCE'), personalMoneyAttention.createRecurring);
router.post('/personal-money/recurring/:id/complete', requireAnyPermission('EDIT_FINANCE'), personalMoneyAttention.completeRecurring);
router.post('/personal-money/recurring/:id/active', requireAnyPermission('EDIT_FINANCE'), personalMoneyAttention.setRecurringActive);
router.post('/personal-money/goals', requireAnyPermission('EDIT_FINANCE'), personalMoneyAttention.createGoal);
router.post('/personal-money/goals/:id/contributions', requireAnyPermission('EDIT_FINANCE'), personalMoneyAttention.addGoalContribution);
router.post('/personal-money/goals/:id/status', requireAnyPermission('EDIT_FINANCE'), personalMoneyAttention.setGoalStatus);
router.get('/personal-money/smart', requireAnyPermission('VIEW_BANKING'), personalMoneySmart.getSmartCenter);
router.post('/personal-money/smart/recurring/:key/apply', requireAnyPermission('EDIT_FINANCE'), personalMoneySmart.applyRecurringSuggestion);
router.post('/personal-money/smart/safety-buffer', requireAnyPermission('EDIT_FINANCE'), personalMoneySmart.saveSafetyBuffer);
router.get('/personal-money/review-inbox', requireAnyPermission('VIEW_BANKING'), personalMoneyReview.getReviewInbox);
router.post('/personal-money/review-inbox/:recurringId/:transactionId/confirm', requireAnyPermission('EDIT_FINANCE'), personalMoneyReview.confirmMatch);
router.post('/personal-money/review-inbox/:recurringId/:transactionId/dismiss', requireAnyPermission('EDIT_FINANCE'), personalMoneyReview.dismissMatch);
router.get('/personal-money/health', requireAnyPermission('VIEW_BANKING'), personalMoneyHealth.getHealthDashboard);
router.get('/personal-money/daily-briefing', requireAnyPermission('VIEW_BANKING'), personalMoneyDailyBriefing.getDailyBriefing);
router.get('/personal-money/data-quality-integrity', requireAnyPermission('VIEW_BANKING'), personalFinancialDataQuality.getCenter);
router.get('/personal-money/saved-views', requireAnyPermission('VIEW_BANKING'), personalFinanceSavedViews.list);
router.post('/personal-money/saved-views', requireAnyPermission('EDIT_FINANCE'), personalFinanceSavedViews.create);
router.post('/personal-money/saved-views/:id', requireAnyPermission('EDIT_FINANCE'), personalFinanceSavedViews.update);
router.post('/personal-money/saved-views/:id/opened', requireAnyPermission('VIEW_BANKING'), personalFinanceSavedViews.opened);
router.delete('/personal-money/saved-views/:id', requireAnyPermission('EDIT_FINANCE'), personalFinanceSavedViews.remove);
router.get('/personal-money/spending-challenges', requireAnyPermission('VIEW_BANKING'), personalSpendingChallenges.list);
router.get('/personal-money/spending-challenges/progress', requireAnyPermission('VIEW_BANKING'), personalSpendingChallenges.progressData);
router.post('/personal-money/spending-challenges', requireAnyPermission('EDIT_FINANCE'), personalSpendingChallenges.create);
router.post('/personal-money/spending-challenges/:id/status', requireAnyPermission('EDIT_FINANCE'), personalSpendingChallenges.updateStatus);
router.get('/personal-money/net-worth', requireAnyPermission('VIEW_BANKING'), personalNetWorth.getDashboard);
router.post('/personal-money/net-worth/assets', requireAnyPermission('EDIT_FINANCE'), personalNetWorth.createAsset);
router.post('/personal-money/net-worth/assets/:id/value', requireAnyPermission('EDIT_FINANCE'), personalNetWorth.updateAssetValue);
router.post('/personal-money/net-worth/assets/:id/archive', requireAnyPermission('EDIT_FINANCE'), personalNetWorth.archiveAsset);
router.post('/personal-money/net-worth/liabilities', requireAnyPermission('EDIT_FINANCE'), personalNetWorth.createLiability);
router.post('/personal-money/net-worth/liabilities/:id/balance', requireAnyPermission('EDIT_FINANCE'), personalNetWorth.updateLiabilityBalance);
router.post('/personal-money/net-worth/liabilities/:id/archive', requireAnyPermission('EDIT_FINANCE'), personalNetWorth.archiveLiability);
router.post('/personal-money/net-worth/snapshot', requireAnyPermission('EDIT_FINANCE'), personalNetWorth.saveSnapshot);
router.get('/personal-money/net-worth/lifecycle', requireAnyPermission('VIEW_BANKING'), personalAssetLifecycle.getCenter);
router.post('/personal-money/net-worth/lifecycle/items', requireAnyPermission('EDIT_FINANCE'), personalAssetLifecycle.createItem);
router.post('/personal-money/net-worth/lifecycle/items/:id/complete', requireAnyPermission('EDIT_FINANCE'), personalAssetLifecycle.completeItem);
router.post('/personal-money/net-worth/lifecycle/items/:id/archive', requireAnyPermission('EDIT_FINANCE'), personalAssetLifecycle.archiveItem);
router.post('/personal-money/net-worth/lifecycle/documents', requireAnyPermission('EDIT_FINANCE'), personalAssetLifecycle.addDocument);
router.delete('/personal-money/net-worth/lifecycle/documents/:id', requireAnyPermission('EDIT_FINANCE'), personalAssetLifecycle.deleteDocument);
router.get('/personal-money/roadmaps', requireAnyPermission('VIEW_BANKING'), personalFinancialRoadmap.getCenter);
router.post('/personal-money/roadmaps', requireAnyPermission('EDIT_FINANCE'), personalFinancialRoadmap.createRoadmap);
router.post('/personal-money/roadmaps/:roadmapId/milestones/:milestoneId/progress', requireAnyPermission('EDIT_FINANCE'), personalFinancialRoadmap.recordProgress);
router.post('/personal-money/roadmaps/:id/status', requireAnyPermission('EDIT_FINANCE'), personalFinancialRoadmap.updateStatus);

router.get('/banking-os', requireAnyPermission('VIEW_BANKING'), bankingOS.getDashboard);
router.get('/banking-os/command-center', requireAnyPermission('VIEW_BANKING'), bankingOS.getCommandCenter);
router.get('/banking-os/approval-inbox', requireAnyPermission('VIEW_BANKING'), bankingOS.getApprovalInbox);
router.get('/banking-os/cashflow-calendar', requireAnyPermission('VIEW_BANKING'), bankingOS.getCashflowCalendar);
router.get('/banking-os/accounts/:id', requireAnyPermission('VIEW_BANKING'), bankingOS.getAccountDetail);
router.get('/banking-os/capabilities', requireAnyPermission('VIEW_BANKING'), bankingOS.capabilities);
router.post('/banking-os/spaces', requireAnyPermission('VIEW_BANKING'), bankingOS.createSpace);
router.post('/banking-os/spaces/:uid', requireAnyPermission('VIEW_BANKING'), bankingOS.updateSpace);
router.post('/banking-os/spaces/:uid/archive', requireAnyPermission('VIEW_BANKING'), bankingOS.archiveSpace);
router.post('/banking-os/beneficiaries', requireAnyPermission('VIEW_BANKING'), requireStepUp('CHANGE_BANK_BENEFICIARY'), bankingOS.createBeneficiary);
router.post('/banking-os/payments', requireAnyPermission('VIEW_BANKING'), bankingOS.createPayment);
router.post('/banking-os/payments/:uid/submit', requireAnyPermission('VIEW_BANKING'), requireStepUp('SUBMIT_BANK_PAYMENT'), bankingOS.submitPayment);
router.post('/banking-os/payments/:uid/cancel', requireAnyPermission('VIEW_BANKING'), requireStepUp('CANCEL_BANK_PAYMENT'), bankingOS.cancelPayment);
router.post('/banking-os/payments/:uid/decision', requireAnyPermission('APPROVE_PAYMENT'), requireStepUp('APPROVE_BANK_PAYMENT'), bankingOS.decidePayment);
router.get('/banking-os/team', requireAnyPermission('VIEW_BANKING'), bankingOS.getTeam);
router.post('/banking-os/team/:userId/access', requireAnyPermission('EDIT_BANK_DETAILS'), requireStepUp('CHANGE_BANKING_USER_ACCESS'), bankingOS.saveTeamAccess);
router.post('/banking-os/alerts', requireAnyPermission('VIEW_BANKING'), bankingOS.saveAlerts);

router.get('/intelligence/overview', requireAnyPermission('VIEW_BANKING'), intelligence.getOverview);
router.get('/intelligence/banking-dashboard', requireAnyPermission('VIEW_BANKING'), intelligence.getBankingDashboard);
router.get('/intelligence/transactions', requireAnyPermission('VIEW_BANKING'), intelligence.getTransactions);
router.post('/intelligence/transactions', requireAnyPermission('EDIT_FINANCE'), intelligence.createManualTransaction);
router.get('/intelligence/transactions/:id', requireAnyPermission('VIEW_BANKING'), intelligence.getTransactionDetail);
router.post('/intelligence/transactions/:id', requireAnyPermission('EDIT_FINANCE'), intelligence.updateTransaction);
router.post('/intelligence/transactions/bulk/review', requireAnyPermission('EDIT_FINANCE'), intelligence.bulkReviewTransactions);
router.post('/intelligence/transactions/bulk/category', requireAnyPermission('EDIT_FINANCE'), intelligence.bulkCategorizeTransactions);
router.get('/intelligence/statements', requireAnyPermission('VIEW_BANKING'), intelligence.getStatementLibrary);
router.get('/intelligence/statements/:uid/report', requireAnyPermission('VIEW_BANKING'), financePrivacy.statementUid('uid'), intelligence.getStatementReport);
router.get('/intelligence/statements-removed', requireAnyPermission('VIEW_BANKING'), statementData.listRemoved);
router.post('/intelligence/statements/:uid/remove', requireAnyPermission('EDIT_FINANCE'), financePrivacy.statementUid('uid'), requireStepUp('DELETE_BANK_STATEMENT'), statementData.remove);
router.post('/intelligence/statements/:uid/restore', requireAnyPermission('EDIT_FINANCE'), financePrivacy.statementUid('uid'), requireStepUp('RESTORE_BANK_STATEMENT'), statementData.restore);
router.delete('/intelligence/statements/:uid/purge', requireAnyPermission('EDIT_BANK_DETAILS'), financePrivacy.statementUid('uid'), requireStepUp('PURGE_BANK_STATEMENT'), statementData.purge);
router.post('/intelligence/accounts/:id/clear-statements', requireAnyPermission('EDIT_FINANCE'), financePrivacy.accountParam('id'), requireStepUp('CLEAR_BANK_STATEMENT_HISTORY'), statementData.clearAccountStatements);
router.get('/intelligence/reports/spending', requireAnyPermission('VIEW_BANKING'), intelligence.getSpendingReport);
router.get('/intelligence/reports/portfolio-history', requireAnyPermission('VIEW_BANKING'), intelligence.getPortfolioHistoryReport);
router.get('/intelligence/statement-warehouse', requireAnyPermission('VIEW_BANKING'), intelligence.getStatementWarehouse);
router.get('/intelligence/budgets', requireAnyPermission('VIEW_BANKING'), intelligence.getBankingBudgets);
router.post('/intelligence/budgets', requireAnyPermission('EDIT_FINANCE'), intelligence.saveBankingBudget);
router.delete('/intelligence/budgets/:uid', requireAnyPermission('EDIT_FINANCE'), intelligence.deleteBankingBudget);
router.get('/intelligence/active-overview', requireAnyPermission('VIEW_BANKING'), bankAccountLifecycle.getActiveOverview);
router.get('/intelligence/accounts', requireAnyPermission('VIEW_BANKING'), intelligence.getAccounts);
router.get('/intelligence/accounts/:id/lifecycle', requireAnyPermission('VIEW_BANKING'), financePrivacy.accountParam('id'), bankAccountLifecycle.getLifecycle);
router.post('/intelligence/accounts', requireAnyPermission('EDIT_BANK_DETAILS'), financePrivacy.accountBody('id'), financePrivacy.protectScopeConversion('id', 'ownership_scope'), requireStepUp('CHANGE_BANK_DETAILS'), intelligence.saveAccount);
router.post('/intelligence/accounts/:id/archive', requireAnyPermission('EDIT_BANK_DETAILS'), financePrivacy.accountParam('id'), requireStepUp('CHANGE_BANK_DETAILS'), bankAccountLifecycle.archive);
router.post('/intelligence/accounts/:id/inactive', requireAnyPermission('EDIT_BANK_DETAILS'), financePrivacy.accountParam('id'), requireStepUp('CHANGE_BANK_DETAILS'), bankAccountLifecycle.deactivate);
router.post('/intelligence/accounts/:id/restore', requireAnyPermission('EDIT_BANK_DETAILS'), financePrivacy.accountParam('id'), requireStepUp('CHANGE_BANK_DETAILS'), bankAccountLifecycle.restore);
router.delete('/intelligence/accounts/:id', requireAnyPermission('EDIT_BANK_DETAILS'), financePrivacy.accountParam('id'), requireStepUp('CHANGE_BANK_DETAILS'), bankAccountLifecycle.remove);
router.post('/intelligence/accounts/:id/statements/import', requireAnyPermission('EDIT_FINANCE'), financePrivacy.accountParam('id'), requireStepUp('IMPORT_BANK_TRANSACTIONS'), intelligence.importStatementRows);
router.post('/intelligence/accounts/:id/statements/preview', requireAnyPermission('EDIT_FINANCE'), financePrivacy.accountParam('id'), requireStepUp('IMPORT_BANK_TRANSACTIONS'), statementPreviewSanitizer, statementReview.preview);
router.get('/intelligence/statement-reviews', requireAnyPermission('VIEW_BANKING'), financePrivacy.filterStatementList, statementReview.list);
router.get('/intelligence/statement-reviews/:uid', requireAnyPermission('VIEW_BANKING'), financePrivacy.statementUid('uid'), statementReview.get);
router.post('/intelligence/statement-reviews/:uid/rows/:rowId/select', requireAnyPermission('EDIT_FINANCE'), financePrivacy.statementUid('uid'), statementReview.updateRowSelection);
router.post('/intelligence/statement-reviews/:uid/rows/:rowId/override', requireAnyPermission('EDIT_FINANCE'), financePrivacy.statementUid('uid'), requireStepUp('IMPORT_BANK_TRANSACTIONS'), statementReview.overrideRejectedRow);
router.post('/intelligence/statement-reviews/:uid/commit', requireAnyPermission('EDIT_FINANCE'), financePrivacy.statementUid('uid'), requireStepUp('IMPORT_BANK_TRANSACTIONS'), statementReview.commit);
router.post('/intelligence/statement-reviews/:uid/reject', requireAnyPermission('EDIT_FINANCE'), financePrivacy.statementUid('uid'), requireStepUp('IMPORT_BANK_TRANSACTIONS'), statementReview.reject);
router.get('/intelligence/history-coverage', requireAnyPermission('VIEW_BANKING'), intelligence.getHistoryCoverage);
router.get('/intelligence/data-quality', requireAnyPermission('VIEW_BANKING'), intelligence.getDataQuality);
router.get('/intelligence/bank-connections', requireAnyPermission('VIEW_BANKING'), intelligence.getConnectionStatus);
router.get('/intelligence/banking-readiness', requireAnyPermission('VIEW_BANKING'), bankingReadiness.getReadiness);
router.get('/intelligence/open-banking/providers', requireAnyPermission('VIEW_BANKING'), openBanking.getProviders);
router.get('/intelligence/open-banking/sessions', requireAnyPermission('VIEW_BANKING'), openBanking.getSessions);
router.post('/intelligence/open-banking/consent', requireAnyPermission('EDIT_BANK_DETAILS'), requireStepUp('CHANGE_BANK_DETAILS'), openBanking.startConsent);
router.post('/intelligence/open-banking/sessions/:uid/cancel', requireAnyPermission('EDIT_BANK_DETAILS'), requireStepUp('CHANGE_BANK_DETAILS'), openBanking.cancelConsent);
router.post('/intelligence/bank-connections/connect', requireAnyPermission('EDIT_BANK_DETAILS'), requireStepUp('CHANGE_BANK_DETAILS'), openBanking.startConsent);
router.post('/intelligence/analyse', requireAnyPermission('VIEW_BANKING'), transactionIntelligence.runAnalysis);
router.get('/intelligence/insights', requireAnyPermission('VIEW_BANKING'), transactionIntelligence.getInsights);
router.post('/intelligence/insights/:id/apply', requireAnyPermission('EDIT_FINANCE'), financePrivacy.insightParam('id'), requireStepUp('APPLY_FINANCE_INTELLIGENCE'), transactionIntelligence.applyInsight);
router.post('/intelligence/insights/:id/dismiss', requireAnyPermission('EDIT_FINANCE'), financePrivacy.insightParam('id'), transactionIntelligence.dismissInsight);
router.get('/intelligence/rules', requireAnyPermission('VIEW_BANKING'), transactionIntelligence.getRules);
router.post('/intelligence/rules/:id', requireAnyPermission('EDIT_FINANCE'), transactionIntelligence.updateRule);
router.delete('/intelligence/rules/:id', requireAnyPermission('EDIT_FINANCE'), transactionIntelligence.deleteRule);
router.get('/intelligence/reconciliation', requireAnyPermission('VIEW_BANKING'), reconciliationCenter.getCenter);
router.get('/intelligence/reconciliation/:id/candidates', requireAnyPermission('VIEW_BANKING'), financePrivacy.bankTransactionParam('id'), reconciliationCenter.getCandidates);
router.post('/intelligence/reconciliation/:id/classify', requireAnyPermission('EDIT_FINANCE'), financePrivacy.bankTransactionParam('id'), requireStepUp('APPLY_FINANCE_INTELLIGENCE'), reconciliationCenter.classify);

router.get('/supplier-bills', operations.getSupplierBills);
router.get('/supplier-bills/:id', operations.getSupplierBill);
router.post('/supplier-bills', requireAnyPermission('EDIT_FINANCE'), operations.saveSupplierBill);
router.post('/supplier-bills/:id/status', requireInputPermission((req) => (String(req.body.status || '').toUpperCase() === 'VOID' ? 'VOID_TRANSACTION' : 'POST_TRANSACTION')), requireStepUp('CHANGE_SUPPLIER_BILL_STATUS'), operations.updateSupplierBillStatus);
router.post('/supplier-bills/:id/payments', requireAnyPermission('POST_TRANSACTION'), requireStepUp('RECORD_SUPPLIER_PAYMENT'), highRiskPaymentGuard, operations.recordSupplierPayment);

router.get('/bank-accounts', requireAnyPermission('VIEW_BANKING'), financePrivacy.filterAccountList, operations.getBankAccounts);
router.post('/bank-accounts', requireAnyPermission('EDIT_BANK_DETAILS'), financePrivacy.accountBody('id'), financePrivacy.protectScopeConversion('id', 'ownership_scope'), requireStepUp('CHANGE_BANK_DETAILS'), operations.saveBankAccount);
router.get('/bank-accounts/:id/transactions', requireAnyPermission('VIEW_BANKING'), financePrivacy.accountParam('id'), operations.getBankTransactions);
router.post('/bank-accounts/:id/import', requireAnyPermission('EDIT_FINANCE'), financePrivacy.accountParam('id'), requireStepUp('IMPORT_BANK_TRANSACTIONS'), operations.importBankTransactions);
router.get('/treasury-control', requireAnyPermission('VIEW_BUSINESS_BANKING'), financeTreasury.getCenter);
router.get('/performance-risk-control', requireAnyPermission('VIEW_BANKING'), financePerformanceRisk.getCenter);
router.get('/anomaly-explain-control', requireAnyPermission('VIEW_BANKING'), financeAnomalyExplain.getCenter);
router.get('/planning-control', requireAnyPermission('VIEW_BANKING'), financePlanningControl.getCenter);
router.post('/planning-control/plans', requireAnyPermission('EDIT_FINANCE'), financePlanningControl.createPlan);
router.post('/planning-control/plans/:uid/clone', requireAnyPermission('EDIT_FINANCE'), financePlanningControl.clonePlan);
router.put('/planning-control/plans/:uid/lines', requireAnyPermission('EDIT_FINANCE'), financePlanningControl.saveLine);
router.delete('/planning-control/plans/:uid/lines/:lineId', requireAnyPermission('EDIT_FINANCE'), financePlanningControl.deleteLine);
router.post('/planning-control/plans/:uid/status', requireAnyPermission('EDIT_FINANCE'), requireStepUp('CHANGE_FINANCE_PLAN_STATUS'), financePlanningControl.setStatus);
router.get('/close-assurance', requireAnyPermission('VIEW_BUSINESS_BANKING'), financeCloseAssurance.getCenter);
router.post('/close-assurance/:periodId/snapshot', requireAnyPermission('EDIT_FINANCE'), financeCloseAssurance.captureSnapshot);
router.post('/close-assurance/:periodId/certify', requireAnyPermission('EDIT_FINANCE'), requireStepUp('CHANGE_ACCOUNTING_PERIOD'), financeCloseAssurance.certify);
router.post('/close-assurance/:periodId/reopen', requireAnyPermission('EDIT_FINANCE'), requireStepUp('CHANGE_ACCOUNTING_PERIOD'), financeCloseAssurance.reopen);
router.get('/cash-control', requireAnyPermission('VIEW_BANKING'), financeCashControl.getCenter);
router.post('/cash-control/counts', requireAnyPermission('EDIT_FINANCE'), financeCashControl.recordCount);
router.post('/cash-control/counts/:uid/review', requireAnyPermission('EDIT_FINANCE'), requireStepUp('REVIEW_CASH_VARIANCE'), financeCashControl.reviewCount);
router.post('/cash-control/transfers', requireAnyPermission('EDIT_FINANCE'), requireStepUp('RECORD_CASH_TRANSFER'), financeCashControl.createTransfer);
router.post('/cash-control/transfers/:uid/reverse', requireAnyPermission('EDIT_FINANCE'), requireStepUp('REVERSE_CASH_TRANSFER'), financeCashControl.reverseTransfer);
router.get('/receipts', requireAnyPermission('VIEW_BANKING'), financeReceipt.center);
router.get('/bank-transactions-archived', requireAnyPermission('VIEW_BANKING'), financeTransactionLifecycle.listArchived);
router.post('/bank-transactions/:id/archive', requireAnyPermission('EDIT_FINANCE'), financePrivacy.bankTransactionParam('id'), financeTransactionLifecycle.archive);
router.post('/bank-transactions/:id/restore', requireAnyPermission('EDIT_FINANCE'), financePrivacy.bankTransactionParam('id'), requireStepUp('RESTORE_BANK_TRANSACTION'), financeTransactionLifecycle.restore);
router.get('/bank-transactions/:id/original', requireAnyPermission('VIEW_BANKING'), financePrivacy.bankTransactionParam('id'), statementReview.getOriginalBankTransaction);
router.get('/bank-transactions/:id/audit', requireAnyPermission('VIEW_BANKING'), financePrivacy.bankTransactionParam('id'), financeAudit.transactionTimeline);
router.get('/bank-transactions/:id/transfer-links', requireAnyPermission('VIEW_BANKING'), financePrivacy.bankTransactionParam('id'), financeRelationships.getTransferLinks);
router.post('/bank-transactions/:id/transfer-links', requireAnyPermission('EDIT_FINANCE'), financePrivacy.bankTransactionParam('id'), financeRelationships.linkTransfer);
router.delete('/bank-transactions/:id/transfer-links/:linkId', requireAnyPermission('EDIT_FINANCE'), financePrivacy.bankTransactionParam('id'), financeRelationships.unlinkTransfer);
router.get('/bank-transactions/:id/splits', requireAnyPermission('VIEW_BANKING'), financePrivacy.bankTransactionParam('id'), financeRelationships.getSplits);
router.put('/bank-transactions/:id/splits', requireAnyPermission('EDIT_FINANCE'), financePrivacy.bankTransactionParam('id'), financeRelationships.replaceSplits);
router.get('/bank-transactions/:id/refund-links', requireAnyPermission('VIEW_BANKING'), financePrivacy.bankTransactionParam('id'), financeRelationships.getRefundLinks);
router.post('/bank-transactions/:id/refund-links', requireAnyPermission('EDIT_FINANCE'), financePrivacy.bankTransactionParam('id'), financeRelationships.linkRefund);
router.delete('/bank-transactions/:id/refund-links/:linkId', requireAnyPermission('EDIT_FINANCE'), financePrivacy.bankTransactionParam('id'), financeRelationships.unlinkRefund);
router.get('/relationship-candidates/transfers', requireAnyPermission('VIEW_BANKING'), financeRelationships.listTransferCandidates);
router.get('/relationship-candidates/refunds', requireAnyPermission('VIEW_BANKING'), financeRelationships.listRefundCandidates);
router.get('/reimbursements', requireAnyPermission('VIEW_BANKING'), financeRelationships.listReimbursements);
router.get('/reimbursements/:id', requireAnyPermission('VIEW_BANKING'), financeRelationships.getReimbursement);
router.post('/reimbursements', requireAnyPermission('EDIT_FINANCE'), financeRelationships.createReimbursement);
router.post('/reimbursements/:id/submit', requireAnyPermission('EDIT_FINANCE'), (req,res,next)=>{req.params.action='submit';next();}, financeRelationships.transitionReimbursement);
router.post('/reimbursements/:id/approve', requireAnyPermission('EDIT_FINANCE'), requireStepUp('APPROVE_REIMBURSEMENT'), (req,res,next)=>{req.params.action='approve';next();}, financeRelationships.transitionReimbursement);
router.post('/reimbursements/:id/reject', requireAnyPermission('EDIT_FINANCE'), requireStepUp('APPROVE_REIMBURSEMENT'), (req,res,next)=>{req.params.action='reject';next();}, financeRelationships.transitionReimbursement);
router.post('/reimbursements/:id/payments', requireAnyPermission('EDIT_FINANCE'), requireStepUp('LINK_REIMBURSEMENT_PAYMENT'), financeRelationships.addReimbursementPayment);
router.get('/bank-transactions/:id/receipts', requireAnyPermission('VIEW_BANKING'), financePrivacy.bankTransactionParam('id'), financeReceipt.list);
router.post('/bank-transactions/:id/receipts', requireAnyPermission('EDIT_FINANCE'), financePrivacy.bankTransactionParam('id'), financeReceiptUpload.single('file'), validateUploadedFile, financeReceipt.upload);
router.patch('/bank-transactions/:id/receipt-status', requireAnyPermission('EDIT_FINANCE'), financePrivacy.bankTransactionParam('id'), financeReceipt.setStatus);
router.delete('/bank-transactions/:id/receipts/:documentId', requireAnyPermission('EDIT_FINANCE'), financePrivacy.bankTransactionParam('id'), financeReceipt.unlink);
router.post('/bank-transactions/:id/receipts/:documentId/restore', requireAnyPermission('EDIT_FINANCE'), financePrivacy.bankTransactionParam('id'), requireStepUp('RESTORE_FINANCE_DOCUMENT'), financeReceipt.restore);
router.post('/bank-transactions/:id/reconcile', requireAnyPermission('EDIT_FINANCE'), financePrivacy.bankTransactionParam('id'), requireStepUp('RECONCILE_BANK_TRANSACTION'), operations.reconcileBankTransaction);
router.post('/bank-transactions/:id/ignore', requireAnyPermission('EDIT_FINANCE'), financePrivacy.bankTransactionParam('id'), requireStepUp('IGNORE_BANK_TRANSACTION'), operations.ignoreBankTransaction);

router.get('/accounting-periods', operations.getAccountingPeriods);
router.post('/accounting-periods/:id/status', requireAnyPermission('EDIT_FINANCE'), requireStepUp('CHANGE_ACCOUNTING_PERIOD'), operations.updateAccountingPeriod);
router.get('/accountant-queries', operations.getAccountantQueries);
router.post('/accountant-queries', requireAnyPermission('EDIT_FINANCE'), operations.saveAccountantQuery);
router.post('/accountant-queries/:id', requireAnyPermission('EDIT_FINANCE'), operations.updateAccountantQuery);
router.get('/assets', operations.getAssets);
router.post('/assets', requireAnyPermission('EDIT_FINANCE'), operations.saveAsset);

module.exports = router;
