const express = require('express');
const { requireAnyPermission } = require('../middleware/authorizationMiddleware');
const requireStepUp = require('../middleware/stepUpMiddleware');
const controller = require('../controllers/qmsEnterpriseController');
const evidence = require('../controllers/qmsEvidenceController');
const shopFloor = require('../controllers/qmsShopFloorController');
const facility = require('../controllers/qmsFacilityController');
const router = express.Router();
router.get('/command-centre', controller.commandCentre);
router.get('/audits', controller.listAudits);
router.post('/audits', requireAnyPermission('MANAGE_INTERNAL_AUDIT','MANAGE_QMS','EDIT_COMPLIANCE'), controller.createAudit);
router.post('/audits/:id/findings', requireAnyPermission('MANAGE_INTERNAL_AUDIT','MANAGE_QMS','EDIT_COMPLIANCE'), controller.addAuditFinding);
router.get('/management-reviews', controller.listManagementReviews);
router.post('/management-reviews', requireAnyPermission('MANAGE_QMS','EDIT_COMPLIANCE'), controller.createManagementReview);
router.post('/management-reviews/:id/actions', requireAnyPermission('MANAGE_QMS','EDIT_COMPLIANCE'), facility.addReviewAction);
router.post('/management-reviews/:id/close', requireAnyPermission('APPROVE_QMS','MANAGE_QMS','EDIT_COMPLIANCE'), requireStepUp('qms:close-management-review'), facility.closeManagementReview);
router.get('/chemicals', controller.listChemicals);
router.post('/chemicals', requireAnyPermission('MANAGE_CHEMICALS','MANAGE_QMS','EDIT_COMPLIANCE'), controller.createChemical);
router.post('/chemicals/:id/sds', requireAnyPermission('MANAGE_CHEMICALS','MANAGE_QMS','EDIT_COMPLIANCE'), facility.addSds);
router.post('/chemicals/:id/transactions', requireAnyPermission('MANAGE_CHEMICALS','MANAGE_QMS','EDIT_COMPLIANCE'), facility.chemicalTransaction);
router.get('/visitors/active', controller.activeVisitors);
router.post('/visitors/check-in', requireAnyPermission('MANAGE_SAFETY','MANAGE_QMS','EDIT_COMPLIANCE'), controller.checkInVisitor);
router.post('/visitors/:id/check-out', requireAnyPermission('MANAGE_SAFETY','MANAGE_QMS','EDIT_COMPLIANCE'), controller.checkOutVisitor);
router.post('/emergencies', requireAnyPermission('MANAGE_SAFETY','MANAGE_QMS','EDIT_COMPLIANCE'), requireStepUp('qms:start-emergency'), controller.startEmergency);
router.get('/emergencies/:id/rollcall', controller.emergencyRollcall);
router.post('/emergencies/:id/rollcall/:itemId/accounted', requireAnyPermission('MANAGE_SAFETY','MANAGE_QMS','EDIT_COMPLIANCE'), controller.markAccounted);
router.get('/continuity', controller.listContinuity);
router.post('/continuity/services', requireAnyPermission('MANAGE_QMS','MANAGE_SECURITY','EDIT_COMPLIANCE'), controller.createCriticalService);
router.post('/continuity/exercises', requireAnyPermission('MANAGE_QMS','MANAGE_SECURITY','EDIT_COMPLIANCE'), controller.recordContinuityExercise);
router.get('/regulatory-reviews', controller.listRegulatoryReviews);
router.post('/regulatory-reviews', requireAnyPermission('REGULATORY_REVIEW','EXPORT_CONTROL_REVIEW','MANAGE_QMS','EDIT_COMPLIANCE'), controller.createRegulatoryReview);
router.post('/regulatory-reviews/:id/decision', requireAnyPermission('REGULATORY_REVIEW','EXPORT_CONTROL_REVIEW','MANAGE_QMS'), requireStepUp('qms:regulatory-decision'), controller.decideRegulatoryReview);
router.get('/notifications', controller.listNotifications);
router.post('/notifications/generate', requireAnyPermission('MANAGE_QMS','EDIT_COMPLIANCE'), controller.generateNotifications);
router.post('/notifications/:id/acknowledge', controller.acknowledgeNotification);
router.get('/recall/material/:materialLotId', controller.recallImpact);
router.get('/evidence/:type/:id', evidence.list);
router.post('/evidence', requireAnyPermission('MANAGE_QMS','VIEW_SECURITY_EVIDENCE','EDIT_COMPLIANCE'), evidence.register);
router.get('/shop-floor/jobs/:id', shopFloor.jobContext);
router.get('/shop-floor/machines/:id', shopFloor.machineContext);
router.get('/shop-floor/materials/:id', shopFloor.materialContext);
router.post('/shop-floor/operations/:id/transition', requireAnyPermission('MANAGE_JOBS','MANAGE_TEAM_JOBS','EDIT_QMS_RECORD','EDIT_COMPLIANCE'), shopFloor.transitionOperation);
module.exports = router;
