const express = require('express');
const { requireAnyPermission } = require('../middleware/authorizationMiddleware');
const requireStepUp = require('../middleware/stepUpMiddleware');
const controller = require('../controllers/qmsEnterpriseController');
const router = express.Router();
router.get('/command-centre', controller.commandCentre);
router.get('/audits', controller.listAudits);
router.post('/audits', requireAnyPermission('MANAGE_INTERNAL_AUDIT','MANAGE_QMS','EDIT_COMPLIANCE'), controller.createAudit);
router.post('/audits/:id/findings', requireAnyPermission('MANAGE_INTERNAL_AUDIT','MANAGE_QMS','EDIT_COMPLIANCE'), controller.addAuditFinding);
router.get('/management-reviews', controller.listManagementReviews);
router.post('/management-reviews', requireAnyPermission('MANAGE_QMS','EDIT_COMPLIANCE'), controller.createManagementReview);
router.get('/chemicals', controller.listChemicals);
router.post('/chemicals', requireAnyPermission('MANAGE_CHEMICALS','MANAGE_QMS','EDIT_COMPLIANCE'), controller.createChemical);
router.get('/visitors/active', controller.activeVisitors);
router.post('/visitors/check-in', requireAnyPermission('MANAGE_SAFETY','MANAGE_QMS','EDIT_COMPLIANCE'), controller.checkInVisitor);
router.post('/visitors/:id/check-out', requireAnyPermission('MANAGE_SAFETY','MANAGE_QMS','EDIT_COMPLIANCE'), controller.checkOutVisitor);
router.post('/emergencies', requireAnyPermission('MANAGE_SAFETY','MANAGE_QMS','EDIT_COMPLIANCE'), requireStepUp('qms:start-emergency'), controller.startEmergency);
router.get('/emergencies/:id/rollcall', controller.emergencyRollcall);
router.post('/emergencies/:id/rollcall/:itemId/accounted', requireAnyPermission('MANAGE_SAFETY','MANAGE_QMS','EDIT_COMPLIANCE'), controller.markAccounted);
router.get('/continuity', controller.listContinuity);
router.post('/continuity/services', requireAnyPermission('MANAGE_QMS','MANAGE_SECURITY','EDIT_COMPLIANCE'), controller.createCriticalService);
router.post('/continuity/exercises', requireAnyPermission('MANAGE_QMS','MANAGE_SECURITY','EDIT_COMPLIANCE'), controller.recordContinuityExercise);
router.get('/regulatory-reviews', controller.listRegulatoryReviews);
router.post('/regulatory-reviews', requireAnyPermission('REGULATORY_REVIEW','EXPORT_CONTROL_REVIEW','MANAGE_QMS','EDIT_COMPLIANCE'), controller.createRegulatoryReview);
router.post('/regulatory-reviews/:id/decision', requireAnyPermission('REGULATORY_REVIEW','EXPORT_CONTROL_REVIEW','MANAGE_QMS'), requireStepUp('qms:regulatory-decision'), controller.decideRegulatoryReview);
router.get('/notifications', controller.listNotifications);
router.post('/notifications/generate', requireAnyPermission('MANAGE_QMS','EDIT_COMPLIANCE'), controller.generateNotifications);
router.post('/notifications/:id/acknowledge', controller.acknowledgeNotification);
router.get('/recall/material/:materialLotId', controller.recallImpact);
module.exports = router;
