const pool=require('../config/db');
const reporting=require('./personalFinanceRecoveryGovernanceReportingController')._test;

function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Recovery CAPA analytics failed.',e);return res.status(s).json({message:s>=500?'Recovery CAPA analytics failed.':e.message,code:e.code||'RECOVERY_CAPA_ANALYTICS_FAILED'});}
function clampMonths(v){const n=Number(v||12);return Number.isFinite(n)?Math.max(1,Math.min(24,Math.trunc(n))):12;}
function hours(a,b){if(!a||!b)return null;return Math.max(0,(new Date(b)-new Date(a))/3600000);}
function avg(v){const x=v.filter(Number.isFinite);return x.length?Math.round((x.reduce((a,b)=>a+b,0)/x.length)*10)/10:null;}
function pct(n,d){return d?Math.round((n/d)*1000)/10:null;}
function month(v){const d=new Date(v);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;}
function category(type){return reporting.category(type);}

async function build(userId,months){const [capas]=await pool.query(`SELECT id,source_category,action_type,status,due_at,implemented_at,effectiveness_checked_at,effectiveness_result,closed_at,created_at FROM personal_finance_recovery_capa WHERE user_id=? AND created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL ? MONTH) ORDER BY created_at ASC`,[userId,months]);const [incidents]=await pool.query(`SELECT id,status,source_signal_type,opened_at,closed_at FROM personal_finance_recovery_incident_cases WHERE user_id=? AND opened_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL ? MONTH) ORDER BY opened_at ASC`,[userId,months]);
const now=new Date();const rows=capas.map(c=>{const recurrence=incidents.filter(i=>category(i.source_signal_type)===c.source_category&&c.closed_at&&new Date(i.opened_at)>new Date(c.closed_at));const overdue=c.status!=='CLOSED'&&c.due_at&&new Date(c.due_at)<now;return {...c,implementation_hours:hours(c.created_at,c.implemented_at),effectiveness_hours:hours(c.implemented_at,c.effectiveness_checked_at),closure_hours:hours(c.created_at,c.closed_at),post_closure_recurrence:recurrence.length,overdue:Boolean(overdue)};});
const checked=rows.filter(x=>x.effectiveness_checked_at),closed=rows.filter(x=>x.status==='CLOSED'),effective=checked.filter(x=>x.effectiveness_result==='EFFECTIVE'),effectiveWithoutRecurrence=closed.filter(x=>x.effectiveness_result==='EFFECTIVE'&&x.post_closure_recurrence===0);
const summary={capas:rows.length,open:rows.filter(x=>x.status!=='CLOSED').length,overdue:rows.filter(x=>x.overdue).length,ineffective:rows.filter(x=>x.effectiveness_result==='NOT_EFFECTIVE').length,insufficient_evidence:rows.filter(x=>x.effectiveness_result==='INSUFFICIENT_EVIDENCE').length,effectiveness_checked:checked.length,effective_pct:pct(effective.length,checked.length),closed_effective_without_observed_recurrence_pct:pct(effectiveWithoutRecurrence.length,closed.length),avg_implementation_hours:avg(rows.map(x=>x.implementation_hours)),avg_effectiveness_hours:avg(rows.map(x=>x.effectiveness_hours)),avg_closure_hours:avg(rows.map(x=>x.closure_hours)),corrective:rows.filter(x=>x.action_type==='CORRECTIVE').length,preventive:rows.filter(x=>x.action_type==='PREVENTIVE').length,both:rows.filter(x=>x.action_type==='BOTH').length};
const cmap={};for(const x of rows){const k=x.source_category;cmap[k]??={category:k,capas:0,closed:0,effective:0,not_effective:0,overdue:0,post_closure_recurrence:0};const c=cmap[k];c.capas++;if(x.status==='CLOSED')c.closed++;if(x.effectiveness_result==='EFFECTIVE')c.effective++;if(x.effectiveness_result==='NOT_EFFECTIVE')c.not_effective++;if(x.overdue)c.overdue++;c.post_closure_recurrence+=x.post_closure_recurrence;}const categories=Object.values(cmap).map(c=>({...c,effective_pct:pct(c.effective,c.closed||c.capas)})).sort((a,b)=>b.capas-a.capas);
const mmap={};for(const x of rows){const k=month(x.created_at);mmap[k]??={month:k,opened:0,implemented:0,closed:0,effective:0,not_effective:0,preventive:0,corrective:0,both:0,overdue:0};const m=mmap[k];m.opened++;if(x.implemented_at)m.implemented++;if(x.status==='CLOSED')m.closed++;if(x.effectiveness_result==='EFFECTIVE')m.effective++;if(x.effectiveness_result==='NOT_EFFECTIVE')m.not_effective++;if(x.action_type==='PREVENTIVE')m.preventive++;if(x.action_type==='CORRECTIVE')m.corrective++;if(x.action_type==='BOTH')m.both++;if(x.overdue)m.overdue++;}
const monthly=Object.values(mmap);
const monitor=categories.map(c=>({category:c.category,state:c.not_effective||c.post_closure_recurrence?'NEEDS_REVIEW':c.overdue?'ACTION_SOON':c.closed&&c.effective===c.closed?'CONTROLLED':'MONITOR',observed_capa_count:c.capas,not_effective:c.not_effective,overdue:c.overdue,post_closure_recurrence:c.post_closure_recurrence,evidence_boundary:'Observed CAPA and recovery incident evidence only; no root cause or causal effect is inferred.'}));
return {scope:'PERSONAL_ONLY',read_only:true,finance_mutations:false,months,generated_at:new Date().toISOString(),summary,categories,monthly,control_monitor:monitor,management_review_signal:{requires_attention:monitor.some(x=>x.state==='NEEDS_REVIEW'||x.state==='ACTION_SOON'),attention_categories:monitor.filter(x=>x.state!=='CONTROLLED'&&x.state!=='MONITOR').map(x=>x.category),evidence_only:true,no_inferred_root_cause:true}};}
exports.get=async(req,res)=>{try{return res.json(await build(uid(req),clampMonths(req.query.months)));}catch(e){return fail(res,e);}};
exports._test={clampMonths,hours,avg,pct,month,category,build};
