const crypto=require('node:crypto');
const pool=require('../config/db');
function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function err(message,statusCode=400,code='RECOVERY_KNOWLEDGE_REVIEW_FAILED'){return Object.assign(new Error(message),{statusCode,code});}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Recovery knowledge review failed.',e);return res.status(s).json({message:s>=500?'Knowledge review action failed.':e.message,code:e.code||'RECOVERY_KNOWLEDGE_REVIEW_FAILED'});}
function text(v,max=1600){return String(v??'').trim().slice(0,max);}
function refs(v,max=40){if(!Array.isArray(v))return [];return [...new Set(v.map(x=>text(x,240)).filter(Boolean))].slice(0,max);}
function parse(v,f){if(v===null||v===undefined||v==='')return f;if(typeof v==='object')return v;try{return JSON.parse(v);}catch{return f;}}
function addDays(base,count){const d=new Date(base);d.setUTCDate(d.getUTCDate()+Number(count));return d;}
function timing(plan,now=new Date()){if(!plan)return {maintenance_state:'UNOWNED',days_until_review:null};if(plan.last_review_result&&plan.last_review_result!=='CURRENT')return {maintenance_state:'REVALIDATION_REQUIRED',days_until_review:0};const next=new Date(plan.next_review_at),delta=Math.ceil((next-now)/86400000);if(delta<0)return {maintenance_state:'OVERDUE',days_until_review:delta};if(delta<=30)return {maintenance_state:'DUE_30',days_until_review:delta};if(delta<=60)return {maintenance_state:'DUE_60',days_until_review:delta};if(delta<=90)return {maintenance_state:'DUE_90',days_until_review:delta};return {maintenance_state:'PLANNED',days_until_review:delta};}
function planView(r){if(!r)return null;return {...timing(r),id:r.id,lesson_id:r.lesson_id,owner_label:r.owner_label,cadence_days:Number(r.cadence_days),next_review_at:r.next_review_at,last_reviewed_at:r.last_reviewed_at||null,last_review_result:r.last_review_result||null,last_reviewer_label:r.last_reviewer_label||null,last_review_note:r.last_review_note||null,last_evidence_refs:refs(parse(r.last_evidence_refs_json,[])),created_at:r.created_at,updated_at:r.updated_at,calculation_note:'Maintenance state is calculated when this view is refreshed; there is no hidden background scheduler.'};}
async function reusableLesson(userId,id){const [[r]]=await pool.query("SELECT id,title,discrepancy_code,status,effectiveness_result,closed_at,effectiveness_checked_at FROM personal_finance_recovery_lessons WHERE id=? AND user_id=? LIMIT 1",[id,userId]);if(!r)throw err('Lesson record was not found.',404,'RECOVERY_LESSON_NOT_FOUND');if(r.status!=='CLOSED'||r.effectiveness_result!=='EFFECTIVE')throw err('Knowledge maintenance planning is available only for CLOSED lessons with an EFFECTIVE result.',409,'RECOVERY_KNOWLEDGE_NOT_REUSABLE');return r;}
async function event(db,userId,planId,lessonId,type,payload){await db.query('INSERT INTO personal_finance_recovery_knowledge_review_events (plan_id,user_id,lesson_id,event_type,event_json) VALUES (?,?,?,?,?)',[planId,userId,lessonId,type,JSON.stringify(payload||{})]);}
async function planRow(userId,lessonId){const [[r]]=await pool.query('SELECT * FROM personal_finance_recovery_knowledge_review_plans WHERE user_id=? AND lesson_id=? LIMIT 1',[userId,lessonId]);return r||null;}
exports.attachPlans=async(userId,items)=>{if(!items.length)return items;const ids=items.map(x=>String(x.id));const [rows]=await pool.query(`SELECT * FROM personal_finance_recovery_knowledge_review_plans WHERE user_id=? AND lesson_id IN (${ids.map(()=>'?').join(',')})`,[String(userId),...ids]);const by=new Map(rows.map(r=>[String(r.lesson_id),r]));return items.map(x=>({...x,knowledge_review_plan:planView(by.get(String(x.id))||null)}));};
async function savePlan(req,res){const userId=uid(req),lessonId=text(req.body?.lesson_id,36),lesson=await reusableLesson(userId,lessonId),owner=text(req.body?.knowledge_owner_label,120),cadence=Number(req.body?.cadence_days||120);if(!owner)throw err('A knowledge owner is required.');if(!Number.isInteger(cadence)||cadence<30||cadence>365)throw err('Review cadence must be between 30 and 365 days.');let next=req.body?.next_review_at?new Date(req.body.next_review_at):addDays(new Date(),cadence);if(Number.isNaN(next.getTime()))throw err('next_review_at is invalid.');if(next<=new Date())throw err('next_review_at must be in the future.');let r=await planRow(userId,lessonId),id=r?.id||crypto.randomUUID(),db=await pool.getConnection();try{await db.beginTransaction();if(r){await db.query('UPDATE personal_finance_recovery_knowledge_review_plans SET owner_label=?,cadence_days=?,next_review_at=? WHERE id=? AND user_id=?',[owner,cadence,next,id,userId]);}else{await db.query('INSERT INTO personal_finance_recovery_knowledge_review_plans (id,user_id,lesson_id,owner_label,cadence_days,next_review_at) VALUES (?,?,?,?,?,?)',[id,userId,lessonId,owner,cadence,next]);}await event(db,userId,id,lessonId,r?'KNOWLEDGE_REVIEW_PLAN_UPDATED':'KNOWLEDGE_REVIEW_PLAN_CREATED',{owner_label:owner,cadence_days:cadence,next_review_at:next.toISOString(),lesson_title:lesson.title,lesson_modified:false,automatic_revalidation:false,financial_records_changed:false});await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}r=await planRow(userId,lessonId);return res.json({knowledge_review_plan:planView(r),lesson_modified:false,automatic_revalidation:false,automatic_capa_creation:false,financial_records_changed:false});}
async function review(req,res){const userId=uid(req),lessonId=text(req.body?.lesson_id,36);await reusableLesson(userId,lessonId);const r=await planRow(userId,lessonId);if(!r)throw err('Save a knowledge review plan before recording a review.',409,'RECOVERY_KNOWLEDGE_PLAN_REQUIRED');const result=String(req.body?.review_result||'').toUpperCase(),reviewer=text(req.body?.reviewer_label,120),note=text(req.body?.review_note,1600),evidence=refs(req.body?.review_evidence_refs);if(!['CURRENT','REVALIDATION_REQUIRED','RETIRE_CANDIDATE','INSUFFICIENT_EVIDENCE'].includes(result))throw err('review_result must be CURRENT, REVALIDATION_REQUIRED, RETIRE_CANDIDATE, or INSUFFICIENT_EVIDENCE.');if(!reviewer||!note)throw err('Independent reviewer and review note are required.');if(reviewer.toLowerCase()===String(r.owner_label||'').trim().toLowerCase())throw err('Independent reviewer must be different from the knowledge owner.',409,'RECOVERY_KNOWLEDGE_REVIEW_INDEPENDENCE_REQUIRED');if(result!=='INSUFFICIENT_EVIDENCE'&&!evidence.length)throw err('Evidence references are required for this review result.',409,'RECOVERY_KNOWLEDGE_REVIEW_EVIDENCE_REQUIRED');const next=result==='CURRENT'?addDays(new Date(),Number(r.cadence_days)):new Date(),db=await pool.getConnection();try{await db.beginTransaction();await db.query('UPDATE personal_finance_recovery_knowledge_review_plans SET last_reviewed_at=NOW(3),last_review_result=?,last_reviewer_label=?,last_review_note=?,last_evidence_refs_json=?,next_review_at=? WHERE id=? AND user_id=?',[result,reviewer,note,JSON.stringify(evidence),next,r.id,userId]);await event(db,userId,r.id,lessonId,'KNOWLEDGE_REVALIDATION_REVIEWED',{review_result:result,reviewer_label:reviewer,evidence_ref_count:evidence.length,next_review_at:next.toISOString(),lesson_modified:false,automatic_revalidation:false,automatic_capa_creation:false,financial_records_changed:false,causation_proven:false});await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}return res.json({knowledge_review_plan:planView(await planRow(userId,lessonId)),lesson_modified:false,automatic_revalidation:false,automatic_capa_creation:false,financial_records_changed:false,causation_proven:false});}
exports.action=async(req,res)=>{try{const action=String(req.body?.knowledge_review_action||'').toUpperCase();if(action==='PLAN')return await savePlan(req,res);if(action==='REVIEW')return await review(req,res);throw err('knowledge_review_action must be PLAN or REVIEW.');}catch(e){return fail(res,e);}};
exports.history=async(req,res)=>{try{const userId=uid(req),lessonId=text(req.query?.lesson_id,36);await reusableLesson(userId,lessonId);const r=await planRow(userId,lessonId);if(!r)return res.json({lesson_id:lessonId,events:[]});const [rows]=await pool.query('SELECT id,event_type,event_json,created_at FROM personal_finance_recovery_knowledge_review_events WHERE user_id=? AND plan_id=? ORDER BY id ASC',[userId,r.id]);return res.json({lesson_id:lessonId,plan_id:r.id,events:rows.map(x=>({id:x.id,event_type:x.event_type,event:parse(x.event_json,{}),created_at:x.created_at}))});}catch(e){return fail(res,e);}};
exports._test={timing,planView,refs};
