const crypto=require('node:crypto');
const pool=require('../config/db');
const canonical=require('./personalFinanceCanonicalBackupController')._test;
const verification=require('./personalFinancePostRestoreVerificationController')._test;
const recoveryWatch=require('./personalFinanceRecoveryIntegrityWatchController');
const recoveryCases=require('./personalFinanceRecoveryIncidentCaseController');
const recoveryGovernanceReporting=require('./personalFinanceRecoveryGovernanceReportingController');
const recoveryManagementReviews=require('./personalFinanceRecoveryManagementReviewController');
const recoveryCapa=require('./personalFinanceRecoveryCapaController');
const recoveryCapaAnalytics=require('./personalFinanceRecoveryCapaAnalyticsController');
const recoveryCapaRiskAssurance=require('./personalFinanceRecoveryCapaRiskAssuranceController');
const recoveryControlTesting=require('./personalFinanceRecoveryControlTestingController');
const recoveryControlScheduling=require('./personalFinanceRecoveryControlSchedulingController');

const FORMAT='VOXEL_VEDA_PERSONAL_FINANCE_RECOVERY_CERTIFICATE';
const VERSION=1;

function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function hash(v){return canonical.hash(v);}
function parse(v,fallback){if(v===null||v===undefined||v==='')return fallback;if(typeof v==='object')return v;try{return JSON.parse(v);}catch{return fallback;}}
function appError(message,statusCode=400,code='RECOVERY_CERTIFICATION_FAILED'){return Object.assign(new Error(message),{statusCode,code});}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Personal Finance recovery certification failed.',e);return res.status(s).json({message:s>=500?'Personal Finance recovery certification failed.':e.message,code:e.code||'RECOVERY_CERTIFICATION_FAILED'});}
function ownerBinding(userId){return hash(`voxelveda-personal-owner-v1:${userId}`);}
function hashedRecordRef(value){return value?hash(`voxelveda-recovery-record-ref-v1:${value}`):null;}

async function ownedRun(userId,runId){const [[run]]=await pool.query(`SELECT * FROM personal_finance_restore_runs WHERE id=? AND user_id=? LIMIT 1`,[runId,userId]);if(!run)throw appError('Restore run was not found.',404,'RESTORE_RUN_NOT_FOUND');return run;}
async function auditRefs(userId,runId){const [rows]=await pool.query(`SELECT id,action,result,integrity_hash,previous_integrity_hash,created_at FROM audit_logs WHERE actor_id=? AND module='personal_finance_restore' AND record_type='restore_run' AND record_id=? ORDER BY id`,[userId,runId]);return rows.map(r=>({audit_id:Number(r.id),action:r.action,result:r.result||'UNKNOWN',created_at:r.created_at,integrity_sha256:r.integrity_hash||null,previous_integrity_sha256:r.previous_integrity_hash||null}));}
async function checkpointRefs(userId,runId){const [rows]=await pool.query(`SELECT dataset_name,checkpoint_sha256,created_at FROM personal_finance_restore_checkpoints WHERE restore_run_id=? AND user_id=? ORDER BY id`,[runId,userId]);return rows.map(r=>({dataset:r.dataset_name,checkpoint_sha256:r.checkpoint_sha256,created_at:r.created_at}));}
function sanitizeVerification(v){return {overall_status:v.overall_status,generated_at:v.generated_at,summary:v.summary||{},currencies:v.currencies||[],datasets:(v.datasets||[]).map(d=>({dataset:d.dataset,action:d.action,status:d.status,expected:Number(d.expected||0),matched:Number(d.matched||0),missing:Number(d.missing||0),mismatched:Number(d.mismatched||0),current_owner_dataset_records:Number(d.current_owner_dataset_records||0),mismatch_examples:(d.examples||[]).map(x=>({record_ref_sha256:hashedRecordRef(x.id),status:x.status,expected_sha256:x.expected_sha256||null,actual_sha256:x.actual_sha256||null}))})),critical_mismatches:(v.critical_mismatches||[]).map(x=>({type:x.type,dataset:x.dataset||null,count:Number(x.count||0),record_ref_sha256:hashedRecordRef(x.record_id),message:x.message})),needs_review:(v.needs_review||[]).map(x=>({type:x.type,count:Number(x.count||0),message:x.message})),checks:v.checks||{},currency_rule:v.currency_rule};}
async function buildEvidence(userId,runId){const run=await ownedRun(userId,runId);if(run.status!=='SUCCEEDED')throw appError(`Recovery certification requires a successful restore. Current status: ${run.status}.`,409,'RESTORE_NOT_CERTIFIABLE');const verified=await verification.verifyRun(userId,runId);if(!['VERIFIED','NEEDS_REVIEW','CRITICAL_MISMATCH'].includes(verified.overall_status))throw appError(`Verification status ${verified.overall_status} cannot be certified yet.`,409,'VERIFICATION_NOT_CERTIFIABLE');const checkpoints=await checkpointRefs(userId,runId),audits=await auditRefs(userId,runId);const now=new Date(),rollbackExpiry=run.rollback_expires_at?new Date(run.rollback_expires_at):null;return {format:FORMAT,format_version:VERSION,generated_at:now.toISOString(),scope:'PERSONAL_ONLY',owner_binding_sha256:ownerBinding(userId),privacy:'Recovery evidence only. No backup passwords, approval tokens, raw transaction records, secret credentials, company accounting records or checkpoint row contents are included.',restore:{run_id:run.id,status:run.status,package_sha256:run.package_sha256,schema_version:run.schema_version,created_at:run.created_at,executed_at:run.executed_at||null,requested_actions:parse(run.requested_actions_json,{}),dry_run_summary:parse(run.dry_run_summary_json,{}),rollback:{expires_at:run.rollback_expires_at||null,available:Boolean(rollbackExpiry&&rollbackExpiry.getTime()>now.getTime()&&run.status==='SUCCEEDED'),checkpoint_count:checkpoints.length,checkpoint_integrity:checkpoints}},verification:sanitizeVerification(verified),audit_references:audits,controls:{read_only_evidence:true,finance_mutations:false,company_finance_included:false,currencies_combined:false,automatic_reconciliation:false,automatic_money_movement:false,certificate_chain_algorithm:'SHA-256',record_identifiers_in_mismatch_examples:'One-way SHA-256 references only'}};}

async function dispatchCaseAction(req,res){const action=String(req.body?.case_action||'').toUpperCase();if(!action)return false;req.body={...(req.body||{}),run_id:req.body?.run_id||req.params.id};req.params={...(req.params||{}),id:req.body?.case_id||req.params.caseId||req.params.id};if(action==='OPEN')return recoveryCases.createFromSignal(req,res);if(action==='NOTE')return recoveryCases.addNote(req,res);if(action==='UPDATE')return recoveryCases.update(req,res);if(action==='GOVERNANCE')return recoveryCases.updateGovernance(req,res);if(action==='VERIFY_RESOLUTION')return recoveryCases.verifyResolution(req,res);if(action==='LINK_CERTIFICATE')return recoveryCases.linkCertificate(req,res);if(action==='CLOSE')return recoveryCases.close(req,res);return res.status(400).json({message:'Unknown recovery incident case action.',code:'RECOVERY_CASE_ACTION_INVALID'});}
async function dispatchReviewAction(req,res){const action=String(req.body?.review_action||'').toUpperCase();if(!action)return false;if(action==='GENERATE')return recoveryManagementReviews.generate(req,res);return recoveryManagementReviews.update(req,res);}
async function dispatchCapaAction(req,res){const action=String(req.body?.capa_action||'').toUpperCase();if(!action)return false;if(action==='CREATE')return recoveryCapa.create(req,res);if(action==='UPDATE')return recoveryCapa.update(req,res);if(action==='EFFECTIVENESS')return recoveryCapa.effectiveness(req,res);if(action==='CLOSE')return recoveryCapa.close(req,res);return res.status(400).json({message:'Unknown recovery CAPA action.',code:'RECOVERY_CAPA_ACTION_INVALID'});}
async function dispatchControlTestAction(req,res){const action=String(req.body?.control_test_action||'').toUpperCase();if(!action)return false;if(action==='CREATE')return recoveryControlTesting.create(req,res);if(action==='EXECUTE')return recoveryControlTesting.execute(req,res);if(action==='REVIEW')return recoveryControlTesting.review(req,res);if(action==='SIGN_OFF')return recoveryControlTesting.signOff(req,res);return res.status(400).json({message:'Unknown recovery control test action.',code:'RECOVERY_CONTROL_TEST_ACTION_INVALID'});}
async function dispatchControlScheduleAction(req,res){const action=String(req.body?.control_schedule_action||'').toUpperCase();if(!action)return false;if(action==='CREATE_REQUEST')return recoveryControlScheduling.createRequest(req,res);if(action==='COMPLETE_REQUEST')return recoveryControlScheduling.completeRequest(req,res);if(action==='CANCEL_REQUEST')return recoveryControlScheduling.cancelRequest(req,res);return res.status(400).json({message:'Unknown recovery control scheduling action.',code:'RECOVERY_CONTROL_SCHEDULING_ACTION_INVALID'});}

exports.generate=async(req,res)=>{if(req.body?.control_schedule_action)return dispatchControlScheduleAction(req,res);if(req.body?.control_test_action)return dispatchControlTestAction(req,res);if(req.body?.capa_action)return dispatchCapaAction(req,res);if(req.body?.review_action)return dispatchReviewAction(req,res);if(req.body?.case_action)return dispatchCaseAction(req,res);const userId=uid(req),runId=String(req.params.id||'');try{const evidence=await buildEvidence(userId,runId),db=await pool.getConnection();try{await db.beginTransaction();const [[last]]=await db.query(`SELECT sequence_no,certificate_sha256 FROM personal_finance_recovery_certificates WHERE restore_run_id=? AND user_id=? ORDER BY sequence_no DESC LIMIT 1 FOR UPDATE`,[runId,userId]);const sequence=Number(last?.sequence_no||0)+1,previous=last?.certificate_sha256||null,id=crypto.randomUUID();evidence.certificate={id,sequence_no:sequence,previous_certificate_sha256:previous};const certificateSha=hash({previous_certificate_sha256:previous,evidence});evidence.certificate.certificate_sha256=certificateSha;await db.query(`INSERT INTO personal_finance_recovery_certificates (id,restore_run_id,user_id,sequence_no,verification_status,package_sha256,previous_certificate_sha256,certificate_sha256,evidence_json) VALUES (?,?,?,?,?,?,?,?,?)`,[id,runId,userId,sequence,evidence.verification.overall_status,evidence.restore.package_sha256,previous,certificateSha,JSON.stringify(evidence)]);await db.commit();return res.status(201).json({certificate_id:id,sequence_no:sequence,certificate_sha256:certificateSha,previous_certificate_sha256:previous,verification_status:evidence.verification.overall_status,generated_at:evidence.generated_at});}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}}catch(e){return fail(res,e);}};
exports.list=async(req,res)=>{if(String(req.query.control_scheduling||'')==='1'){if(String(req.query.history||'')==='1')return recoveryControlScheduling.history(req,res);return recoveryControlScheduling.list(req,res);}if(String(req.query.control_testing||'')==='1'){if(String(req.query.history||'')==='1')return recoveryControlTesting.history(req,res);return recoveryControlTesting.list(req,res);}if(String(req.query.capa_risk_assurance||'')==='1')return recoveryCapaRiskAssurance.get(req,res);if(String(req.query.capa_analytics||'')==='1')return recoveryCapaAnalytics.get(req,res);if(String(req.query.capa||'')==='1'){if(String(req.query.history||'')==='1')return recoveryCapa.history(req,res);return recoveryCapa.list(req,res);}if(String(req.query.watch||'')==='1')return recoveryWatch.get(req,res);if(String(req.query.governance_review||'')==='1')return recoveryManagementReviews.list(req,res);if(String(req.query.governance_report||'')==='1')return recoveryGovernanceReporting.get(req,res);if(String(req.query.cases||'')==='1')return recoveryCases.list(req,res);try{const userId=uid(req),runId=String(req.params.id||'');await ownedRun(userId,runId);const [rows]=await pool.query(`SELECT id,sequence_no,verification_status,package_sha256,previous_certificate_sha256,certificate_sha256,generated_at FROM personal_finance_recovery_certificates WHERE restore_run_id=? AND user_id=? ORDER BY sequence_no DESC`,[runId,userId]);return res.json({run_id:runId,certificates:rows,read_only:true});}catch(e){return fail(res,e);}};
exports.get=async(req,res)=>{try{const userId=uid(req),runId=String(req.params.id||''),certificateId=String(req.params.certificateId||'');await ownedRun(userId,runId);const [[row]]=await pool.query(`SELECT * FROM personal_finance_recovery_certificates WHERE id=? AND restore_run_id=? AND user_id=? LIMIT 1`,[certificateId,runId,userId]);if(!row)throw appError('Recovery certificate was not found.',404,'RECOVERY_CERTIFICATE_NOT_FOUND');const evidence=parse(row.evidence_json,null);if(!evidence)throw appError('Stored recovery certificate is unreadable.',409,'RECOVERY_CERTIFICATE_UNREADABLE');const stored=evidence.certificate?.certificate_sha256,withoutHash=JSON.parse(JSON.stringify(evidence));if(withoutHash.certificate)delete withoutHash.certificate.certificate_sha256;const computed=hash({previous_certificate_sha256:row.previous_certificate_sha256||null,evidence:withoutHash});if(stored!==row.certificate_sha256||computed!==row.certificate_sha256)throw appError('Recovery certificate integrity verification failed.',409,'RECOVERY_CERTIFICATE_HASH_MISMATCH');return res.json({...evidence,integrity:{verified:true,algorithm:'SHA-256',certificate_sha256:row.certificate_sha256,previous_certificate_sha256:row.previous_certificate_sha256||null}});}catch(e){return fail(res,e);}};
exports._test={FORMAT,VERSION,buildEvidence,sanitizeVerification};
