const pool=require('../config/db');
const canonical=require('./personalFinanceCanonicalBackupController')._test;
const management=require('./personalFinanceRecoveryManagementReviewController')._test;

function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function parse(v,f){if(v===null||v===undefined||v==='')return f;if(typeof v==='object')return v;try{return JSON.parse(v);}catch{return f;}}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Recovery evidence integrity verification failed.',e);return res.status(s).json({message:s>=500?'Recovery evidence integrity verification failed.':e.message,code:e.code||'RECOVERY_EVIDENCE_INTEGRITY_FAILED'});}
function certCheck(row,expectedPrevious){const evidence=parse(row.evidence_json,null),issues=[];if(!evidence){issues.push('CERTIFICATE_EVIDENCE_UNREADABLE');return {id:row.id,restore_run_id:row.restore_run_id,sequence_no:Number(row.sequence_no),state:'FAILED',issues};}const embedded=evidence.certificate?.certificate_sha256||null,withoutHash=JSON.parse(JSON.stringify(evidence));if(withoutHash.certificate)delete withoutHash.certificate.certificate_sha256;const computed=canonical.hash({previous_certificate_sha256:row.previous_certificate_sha256||null,evidence:withoutHash});if(embedded!==row.certificate_sha256)issues.push('EMBEDDED_CERTIFICATE_HASH_MISMATCH');if(computed!==row.certificate_sha256)issues.push('RECOMPUTED_CERTIFICATE_HASH_MISMATCH');if((row.previous_certificate_sha256||null)!==(expectedPrevious||null))issues.push('CERTIFICATE_CHAIN_PREVIOUS_HASH_MISMATCH');if(String(evidence.restore?.run_id||'')!==String(row.restore_run_id||''))issues.push('CERTIFICATE_RESTORE_RUN_MISMATCH');if(String(evidence.restore?.package_sha256||'')!==String(row.package_sha256||''))issues.push('CERTIFICATE_PACKAGE_HASH_MISMATCH');return {id:row.id,restore_run_id:row.restore_run_id,sequence_no:Number(row.sequence_no),verification_status:row.verification_status,state:issues.length?'FAILED':'VERIFIED',certificate_sha256:row.certificate_sha256,previous_certificate_sha256:row.previous_certificate_sha256||null,issues};}
function reviewCheck(row,expectedPrevious){const issues=[],computed=management.hashCore(row);if(computed!==row.review_sha256)issues.push('MANAGEMENT_REVIEW_HASH_MISMATCH');if((row.previous_review_sha256||null)!==(expectedPrevious||null))issues.push('MANAGEMENT_REVIEW_CHAIN_MISMATCH');const snapshot=parse(row.snapshot_json,null);if(!snapshot||canonical.hash(snapshot)!==row.snapshot_sha256)issues.push('MANAGEMENT_REVIEW_SNAPSHOT_HASH_MISMATCH');return {id:row.id,review_month:row.review_month,status:row.status,state:issues.length?'FAILED':'VERIFIED',review_sha256:row.review_sha256,previous_review_sha256:row.previous_review_sha256||null,issues};}

exports.get=async(req,res)=>{try{const userId=uid(req);const [[certRows],[reviewRows],[tests],[capas],[cases],[runs]]=await Promise.all([
  pool.query(`SELECT * FROM personal_finance_recovery_certificates WHERE user_id=? ORDER BY restore_run_id,sequence_no ASC`,[userId]),
  pool.query(`SELECT * FROM personal_finance_recovery_management_reviews WHERE user_id=? ORDER BY review_month ASC,created_at ASC`,[userId]),
  pool.query(`SELECT id,control_category,linked_capa_ids_json,linked_review_id,evidence_refs_json,lifecycle_status,result FROM personal_finance_recovery_control_tests WHERE user_id=?`,[userId]),
  pool.query(`SELECT id,source_case_ids_json,source_review_id,status FROM personal_finance_recovery_capa WHERE user_id=?`,[userId]),
  pool.query(`SELECT id,restore_run_id,linked_certificate_id,status FROM personal_finance_recovery_incident_cases WHERE user_id=?`,[userId]),
  pool.query(`SELECT id,status,package_sha256,schema_version FROM personal_finance_restore_runs WHERE user_id=?`,[userId])
]);
const certs=[],prevByRun=new Map();for(const r of certRows){const prev=prevByRun.get(String(r.restore_run_id))||null,c=certCheck(r,prev);certs.push(c);prevByRun.set(String(r.restore_run_id),r.certificate_sha256);}const reviews=[];let prevReview=null;for(const r of reviewRows){reviews.push(reviewCheck(r,prevReview));prevReview=r.review_sha256;}
const certMap=new Map(certRows.map(x=>[String(x.id),x])),reviewMap=new Map(reviewRows.map(x=>[String(x.id),x])),capaMap=new Map(capas.map(x=>[String(x.id),x])),caseMap=new Map(cases.map(x=>[String(x.id),x])),runMap=new Map(runs.map(x=>[String(x.id),x])),references=[];
for(const t of tests){const issues=[],capaIds=parse(t.linked_capa_ids_json,[]).map(String);for(const id of capaIds)if(!capaMap.has(id))issues.push(`MISSING_CAPA:${id}`);if(t.linked_review_id&&!reviewMap.has(String(t.linked_review_id)))issues.push(`MISSING_MANAGEMENT_REVIEW:${t.linked_review_id}`);references.push({type:'CONTROL_TEST',id:t.id,category:t.control_category,state:issues.length?'FAILED':'VERIFIED',issues});}
for(const c of capas){const issues=[],caseIds=parse(c.source_case_ids_json,[]).map(String);for(const id of caseIds)if(!caseMap.has(id))issues.push(`MISSING_INCIDENT_CASE:${id}`);if(c.source_review_id&&!reviewMap.has(String(c.source_review_id)))issues.push(`MISSING_SOURCE_REVIEW:${c.source_review_id}`);references.push({type:'CAPA',id:c.id,state:issues.length?'FAILED':'VERIFIED',issues});}
for(const c of cases){const issues=[];if(!runMap.has(String(c.restore_run_id)))issues.push(`MISSING_RESTORE_RUN:${c.restore_run_id}`);if(c.linked_certificate_id){const cert=certMap.get(String(c.linked_certificate_id));if(!cert)issues.push(`MISSING_CERTIFICATE:${c.linked_certificate_id}`);else if(String(cert.restore_run_id)!==String(c.restore_run_id))issues.push('INCIDENT_CERTIFICATE_RESTORE_RUN_MISMATCH');}references.push({type:'INCIDENT_CASE',id:c.id,state:issues.length?'FAILED':'VERIFIED',issues});}
const failed=[...certs,...reviews,...references].filter(x=>x.state==='FAILED'),summary={certificate_records:certs.length,certificate_failures:certs.filter(x=>x.state==='FAILED').length,management_reviews:reviews.length,management_review_failures:reviews.filter(x=>x.state==='FAILED').length,reference_records:references.length,reference_failures:references.filter(x=>x.state==='FAILED').length,total_failures:failed.length};
return res.json({scope:'PERSONAL_ONLY',read_only:true,finance_mutations:false,generated_at:new Date().toISOString(),integrity_state:failed.length?'ATTENTION_REQUIRED':'VERIFIED',summary,certificates:certs,management_reviews:reviews,references,controls:{sha256_recomputed:true,certificate_chain_verified:true,management_review_chain_verified:true,cross_record_ids_verified:true,no_automatic_repair:true,no_finance_changes:true,no_causation_inference:true},boundary:'Integrity verification confirms stored hashes and references match the current owner-scoped governance records. It does not prove why a record changed, does not infer a root cause, and does not repair or mutate any finance record.'});}catch(e){return fail(res,e);}};
exports._test={certCheck,reviewCheck};
