const crypto=require('node:crypto');
const pool=require('../config/db');

const RESULTS=new Set(['PASS','FAIL','NEEDS_REVIEW']);
const CATEGORIES=new Set(['RESTORE_FIDELITY','DEPENDENCY_INTEGRITY','CERTIFICATE_INTEGRITY','ROLLBACK_PROTECTION','VERIFICATION_INITIALIZATION','OTHER_EVIDENCE_CONDITION']);
function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function appError(message,statusCode=400,code='RECOVERY_CONTROL_TEST_FAILED'){return Object.assign(new Error(message),{statusCode,code});}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Recovery control testing failed.',e);return res.status(s).json({message:s>=500?'Recovery control testing failed.':e.message,code:e.code||'RECOVERY_CONTROL_TEST_FAILED'});}
function parse(v,fallback){if(v===null||v===undefined||v==='')return fallback;if(typeof v==='object')return v;try{return JSON.parse(v);}catch{return fallback;}}
function arr(v){const x=parse(v,[]);return Array.isArray(x)?x:[];}
function text(v,max){return String(v??'').trim().slice(0,max);}
function frequency(v){const n=Math.trunc(Number(v||90));if(!Number.isFinite(n)||n<7||n>730)throw appError('Test frequency must be between 7 and 730 days.',400,'CONTROL_TEST_FREQUENCY_INVALID');return n;}
function assuranceState(r,now=Date.now()){if(r.result==='FAIL')return 'CONTROL_FAILED';if(r.result==='NEEDS_REVIEW')return 'NEEDS_REVIEW';if(r.lifecycle_status==='ASSURED'&&r.next_retest_at&&new Date(r.next_retest_at).getTime()<now)return 'RETEST_OVERDUE';if(r.lifecycle_status==='ASSURED')return 'ASSURED_UNTIL_RETEST';if(r.lifecycle_status==='REVIEWED'&&r.result==='PASS')return 'ASSURANCE_SIGNOFF_PENDING';if(r.lifecycle_status==='EXECUTED')return 'REVIEW_PENDING';return 'TEST_NOT_EXECUTED';}
async function owned(userId,id,db=pool){const [[r]]=await db.query(`SELECT * FROM personal_finance_recovery_control_tests WHERE id=? AND user_id=? LIMIT 1`,[id,userId]);if(!r)throw appError('Recovery control test was not found.',404,'CONTROL_TEST_NOT_FOUND');return r;}
async function validateLinks(userId,capaIds,reviewId,db=pool){for(const id of capaIds){const [[c]]=await db.query(`SELECT id FROM personal_finance_recovery_capa WHERE id=? AND user_id=? LIMIT 1`,[id,userId]);if(!c)throw appError(`Linked CAPA ${id} was not found for this owner.`,409,'CONTROL_TEST_CAPA_LINK_INVALID');}if(reviewId){const [[r]]=await db.query(`SELECT id,status FROM personal_finance_recovery_management_reviews WHERE id=? AND user_id=? LIMIT 1`,[reviewId,userId]);if(!r)throw appError('Linked management review was not found for this owner.',409,'CONTROL_TEST_REVIEW_LINK_INVALID');return r;}return null;}
async function event(db,userId,id,type,payload){await db.query(`INSERT INTO personal_finance_recovery_control_test_events (control_test_id,user_id,event_type,event_json) VALUES (?,?,?,?)`,[id,userId,type,JSON.stringify(payload||{})]);}
function publicRow(r){return {...r,test_procedure:parse(r.test_procedure_json,[]),expected_evidence:parse(r.expected_evidence_json,[]),evidence_refs:arr(r.evidence_refs_json),linked_capa_ids:arr(r.linked_capa_ids_json),assurance_state:assuranceState(r),read_only_finance:true};}

exports.list=async(req,res)=>{try{const userId=uid(req);const [rows]=await pool.query(`SELECT * FROM personal_finance_recovery_control_tests WHERE user_id=? ORDER BY FIELD(lifecycle_status,'DRAFT','EXECUTED','REVIEWED','ASSURED'),COALESCE(next_retest_at,'9999-12-31'),created_at DESC`,[userId]);const tests=rows.map(publicRow),summary={tests:tests.length,assured:tests.filter(x=>x.assurance_state==='ASSURED_UNTIL_RETEST').length,failed:tests.filter(x=>x.assurance_state==='CONTROL_FAILED').length,needs_review:tests.filter(x=>['NEEDS_REVIEW','REVIEW_PENDING','ASSURANCE_SIGNOFF_PENDING'].includes(x.assurance_state)).length,retest_overdue:tests.filter(x=>x.assurance_state==='RETEST_OVERDUE').length};return res.json({scope:'PERSONAL_ONLY',read_only_finance:true,finance_mutations:false,summary,tests,controls:{test_results:['PASS','FAIL','NEEDS_REVIEW'],assurance_requires_pass:true,assurance_requires_evidence:true,assurance_requires_reviewer:true,assurance_requires_attested_management_review:true,no_automatic_finance_changes:true}});}catch(e){return fail(res,e);}};

exports.create=async(req,res)=>{const userId=uid(req);let db;try{const category=String(req.body?.control_category||'').toUpperCase(),name=text(req.body?.test_name,180),procedure=arr(req.body?.test_procedure),expected=arr(req.body?.expected_evidence),capaIds=arr(req.body?.linked_capa_ids).map(String),reviewId=text(req.body?.linked_review_id,36)||null;if(!CATEGORIES.has(category))throw appError('Select a valid recovery-control category.',400,'CONTROL_TEST_CATEGORY_INVALID');if(!name||procedure.length===0||expected.length===0)throw appError('Test name, procedure steps and expected evidence are required.',400,'CONTROL_TEST_DEFINITION_INCOMPLETE');const freq=frequency(req.body?.frequency_days);await validateLinks(userId,capaIds,reviewId);db=await pool.getConnection();await db.beginTransaction();const id=crypto.randomUUID();await db.query(`INSERT INTO personal_finance_recovery_control_tests (id,user_id,control_category,test_name,test_procedure_json,expected_evidence_json,frequency_days,linked_capa_ids_json,linked_review_id) VALUES (?,?,?,?,?,?,?,?,?)`,[id,userId,category,name,JSON.stringify(procedure),JSON.stringify(expected),freq,JSON.stringify(capaIds),reviewId]);await event(db,userId,id,'CONTROL_TEST_CREATED',{control_category:category,test_name:name,frequency_days:freq,linked_capa_ids:capaIds,linked_review_id:reviewId});await db.commit();return res.status(201).json({id,message:'Recovery control test created.'});}catch(e){if(db)await db.rollback().catch(()=>{});return fail(res,e);}finally{if(db)db.release();}};

exports.execute=async(req,res)=>{const userId=uid(req);let db;try{const id=text(req.body?.control_test_id,36),result=String(req.body?.result||'').toUpperCase(),tester=text(req.body?.tester_label,120),evidence=arr(req.body?.evidence_refs).map(x=>text(x,500)).filter(Boolean);if(!RESULTS.has(result))throw appError('Test result must be PASS, FAIL or NEEDS_REVIEW.',400,'CONTROL_TEST_RESULT_INVALID');if(!tester||evidence.length===0)throw appError('Tester and at least one evidence reference are required.',400,'CONTROL_TEST_EXECUTION_EVIDENCE_REQUIRED');db=await pool.getConnection();await db.beginTransaction();const row=await owned(userId,id,db);if(row.lifecycle_status==='ASSURED')throw appError('An assured test is immutable; create a new test execution after its retest date.',409,'CONTROL_TEST_ALREADY_ASSURED');const next=new Date(Date.now()+frequency(row.frequency_days)*86400000);await db.query(`UPDATE personal_finance_recovery_control_tests SET lifecycle_status='EXECUTED',result=?,tester_label=?,evidence_refs_json=?,executed_at=UTC_TIMESTAMP(),reviewer_label=NULL,review_note=NULL,reviewed_at=NULL,assurance_signed_at=NULL,assurance_note=NULL,next_retest_at=? WHERE id=? AND user_id=?`,[result,tester,JSON.stringify(evidence),next,id,userId]);await event(db,userId,id,'CONTROL_TEST_EXECUTED',{result,tester_label:tester,evidence_count:evidence.length,next_retest_at:next.toISOString()});await db.commit();return res.json({message:'Control test execution recorded.',result,next_retest_at:next});}catch(e){if(db)await db.rollback().catch(()=>{});return fail(res,e);}finally{if(db)db.release();}};

exports.review=async(req,res)=>{const userId=uid(req);let db;try{const id=text(req.body?.control_test_id,36),reviewer=text(req.body?.reviewer_label,120),note=text(req.body?.review_note,500);if(!reviewer||!note)throw appError('Reviewer and review note are required.',400,'CONTROL_TEST_REVIEW_REQUIRED');db=await pool.getConnection();await db.beginTransaction();const row=await owned(userId,id,db);if(row.lifecycle_status!=='EXECUTED')throw appError('Only an executed test can be reviewed.',409,'CONTROL_TEST_NOT_EXECUTED');await db.query(`UPDATE personal_finance_recovery_control_tests SET lifecycle_status='REVIEWED',reviewer_label=?,review_note=?,reviewed_at=UTC_TIMESTAMP() WHERE id=? AND user_id=?`,[reviewer,note,id,userId]);await event(db,userId,id,'CONTROL_TEST_REVIEWED',{reviewer_label:reviewer,result:row.result,review_note:note});await db.commit();return res.json({message:'Control test review recorded.',result:row.result});}catch(e){if(db)await db.rollback().catch(()=>{});return fail(res,e);}finally{if(db)db.release();}};

exports.signOff=async(req,res)=>{const userId=uid(req);let db;try{const id=text(req.body?.control_test_id,36),note=text(req.body?.assurance_note,500);if(!note)throw appError('Assurance sign-off note is required.',400,'CONTROL_TEST_SIGNOFF_NOTE_REQUIRED');db=await pool.getConnection();await db.beginTransaction();const row=await owned(userId,id,db);if(row.lifecycle_status!=='REVIEWED'||row.result!=='PASS')throw appError('Assurance sign-off requires a reviewed PASS result.',409,'CONTROL_TEST_NOT_SIGNOFF_READY');if(!row.reviewer_label||arr(row.evidence_refs_json).length===0)throw appError('Reviewer acknowledgement and test evidence are required for assurance sign-off.',409,'CONTROL_TEST_SIGNOFF_EVIDENCE_MISSING');if(!row.linked_review_id)throw appError('Link an ATTESTED management review before assurance sign-off.',409,'CONTROL_TEST_ATTESTED_REVIEW_REQUIRED');const review=await validateLinks(userId,arr(row.linked_capa_ids_json),row.linked_review_id,db);if(review?.status!=='ATTESTED')throw appError('The linked management review must be ATTESTED before assurance sign-off.',409,'CONTROL_TEST_REVIEW_NOT_ATTESTED');if(!row.next_retest_at||new Date(row.next_retest_at).getTime()<=Date.now())throw appError('The next retest date must still be in the future.',409,'CONTROL_TEST_RETEST_OVERDUE');await db.query(`UPDATE personal_finance_recovery_control_tests SET lifecycle_status='ASSURED',assurance_signed_at=UTC_TIMESTAMP(),assurance_note=? WHERE id=? AND user_id=?`,[note,id,userId]);await event(db,userId,id,'CONTROL_TEST_ASSURANCE_SIGNED',{result:row.result,reviewer_label:row.reviewer_label,linked_review_id:row.linked_review_id,next_retest_at:row.next_retest_at,assurance_note:note});await db.commit();return res.json({message:'Control assurance sign-off recorded.',assurance_state:'ASSURED_UNTIL_RETEST',next_retest_at:row.next_retest_at});}catch(e){if(db)await db.rollback().catch(()=>{});return fail(res,e);}finally{if(db)db.release();}};

exports.history=async(req,res)=>{try{const userId=uid(req),id=text(req.query.control_test_id,36);await owned(userId,id);const [rows]=await pool.query(`SELECT id,event_type,event_json,created_at FROM personal_finance_recovery_control_test_events WHERE user_id=? AND control_test_id=? ORDER BY id DESC LIMIT 200`,[userId,id]);return res.json({control_test_id:id,events:rows.map(x=>({...x,event:parse(x.event_json,{})})),read_only:true});}catch(e){return fail(res,e);}};
exports._test={frequency,assuranceState,validateLinks};
