const pool=require('../config/db');
const reporting=require('./personalFinanceRecoveryGovernanceReportingController')._test;

function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Recovery CAPA risk assurance failed.',e);return res.status(s).json({message:s>=500?'Recovery CAPA risk assurance failed.':e.message,code:e.code||'RECOVERY_CAPA_RISK_ASSURANCE_FAILED'});}
function clampMonths(v){const n=Number(v||12);return Number.isFinite(n)?Math.max(1,Math.min(24,Math.trunc(n))):12;}
function category(type){return reporting.category(type);}
function daysOverdue(row,now=Date.now()){if(row.status==='CLOSED'||!row.due_at)return 0;const ms=now-new Date(row.due_at).getTime();return ms>0?Math.floor(ms/86400000):0;}
function priorityFromFactors(f){if(f.open_critical_incidents>0||f.max_overdue_days>=14||f.not_effective_capas>0)return 'PRIORITY_1';if(f.post_closure_recurrence>0||f.max_overdue_days>=7||f.open_action_soon_incidents>0)return 'PRIORITY_2';if(f.max_overdue_days>0||f.insufficient_evidence_capas>0||f.unattested_linked_reviews>0)return 'PRIORITY_3';return 'MONITOR';}
function assuranceFromFactors(f){if(f.not_effective_capas>0||f.post_closure_recurrence>0||f.open_critical_incidents>0)return 'ASSURANCE_GAP';if(f.closed_capas===0||f.effective_closed_capas===0)return 'ASSURANCE_PENDING';if(f.effective_closed_capas===f.closed_capas&&f.attested_linked_reviews>0&&f.open_action_soon_incidents===0&&f.max_overdue_days===0)return 'ASSURED_BY_CURRENT_EVIDENCE';return 'PARTIAL_ASSURANCE';}
function reasons(f){const out=[];if(f.open_critical_incidents)out.push(`${f.open_critical_incidents} open Critical incident(s)`);if(f.open_action_soon_incidents)out.push(`${f.open_action_soon_incidents} open Action Soon incident(s)`);if(f.not_effective_capas)out.push(`${f.not_effective_capas} CAPA marked Not Effective`);if(f.post_closure_recurrence)out.push(`${f.post_closure_recurrence} observed post-closure recurrence(s)`);if(f.max_overdue_days)out.push(`oldest open CAPA ${f.max_overdue_days} day(s) overdue`);if(f.insufficient_evidence_capas)out.push(`${f.insufficient_evidence_capas} CAPA with insufficient effectiveness evidence`);if(f.unattested_linked_reviews)out.push(`${f.unattested_linked_reviews} linked management review(s) not attested`);if(!out.length)out.push('No elevated factor observed in the selected window');return out;}

async function build(userId,months){const [capas]=await pool.query(`SELECT c.id,c.source_category,c.action_type,c.status,c.due_at,c.implemented_at,c.effectiveness_checked_at,c.effectiveness_result,c.closed_at,c.created_at,c.source_review_id,m.status AS review_status,m.review_month,m.attested_at FROM personal_finance_recovery_capa c LEFT JOIN personal_finance_recovery_management_reviews m ON m.id=c.source_review_id AND m.user_id=c.user_id WHERE c.user_id=? AND c.created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL ? MONTH) ORDER BY c.created_at ASC`,[userId,months]);const [incidents]=await pool.query(`SELECT id,status,source_level,source_signal_type,opened_at,closed_at FROM personal_finance_recovery_incident_cases WHERE user_id=? AND opened_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL ? MONTH) ORDER BY opened_at ASC`,[userId,months]);const [reviews]=await pool.query(`SELECT id,status,review_month,attested_at,created_at FROM personal_finance_recovery_management_reviews WHERE user_id=? AND created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL ? MONTH) ORDER BY review_month ASC`,[userId,months]);
const categories=[...new Set([...capas.map(x=>x.source_category),...incidents.map(x=>category(x.source_signal_type))].filter(Boolean))];const controls=categories.map(k=>{const cs=capas.filter(x=>x.source_category===k),ins=incidents.filter(x=>category(x.source_signal_type)===k),closed=cs.filter(x=>x.status==='CLOSED'),effectiveClosed=closed.filter(x=>x.effectiveness_result==='EFFECTIVE'),notEffective=cs.filter(x=>x.effectiveness_result==='NOT_EFFECTIVE'),insufficient=cs.filter(x=>x.effectiveness_result==='INSUFFICIENT_EVIDENCE'),openCritical=ins.filter(x=>x.status!=='CLOSED'&&x.source_level==='CRITICAL'),openSoon=ins.filter(x=>x.status!=='CLOSED'&&x.source_level==='ACTION_SOON'),postClosure=closed.reduce((n,c)=>n+ins.filter(i=>new Date(i.opened_at)>new Date(c.closed_at)).length,0),overdueDays=cs.map(x=>daysOverdue(x)),linked=cs.filter(x=>x.source_review_id),attested=linked.filter(x=>x.review_status==='ATTESTED'),unattested=linked.filter(x=>x.review_status&&x.review_status!=='ATTESTED');const f={capa_count:cs.length,open_capas:cs.filter(x=>x.status!=='CLOSED').length,closed_capas:closed.length,effective_closed_capas:effectiveClosed.length,not_effective_capas:notEffective.length,insufficient_evidence_capas:insufficient.length,open_critical_incidents:openCritical.length,open_action_soon_incidents:openSoon.length,post_closure_recurrence:postClosure,max_overdue_days:Math.max(0,...overdueDays),linked_management_reviews:linked.length,attested_linked_reviews:attested.length,unattested_linked_reviews:unattested.length};return {category:k,priority:priorityFromFactors(f),assurance:assuranceFromFactors(f),factors:f,why_priority:reasons(f),latest_attested_review_month:attested.map(x=>x.review_month).filter(Boolean).sort().at(-1)||null,evidence_boundary:'Priority is rule-based from visible factors, not an opaque score. Assurance describes current observed evidence only; it is not a guarantee of future control performance.'};}).sort((a,b)=>{const rank={PRIORITY_1:0,PRIORITY_2:1,PRIORITY_3:2,MONITOR:3};return rank[a.priority]-rank[b.priority]||b.factors.open_critical_incidents-a.factors.open_critical_incidents||b.factors.max_overdue_days-a.factors.max_overdue_days;});
const summary={controls:controls.length,priority_1:controls.filter(x=>x.priority==='PRIORITY_1').length,priority_2:controls.filter(x=>x.priority==='PRIORITY_2').length,priority_3:controls.filter(x=>x.priority==='PRIORITY_3').length,monitor:controls.filter(x=>x.priority==='MONITOR').length,assurance_gap:controls.filter(x=>x.assurance==='ASSURANCE_GAP').length,assured_by_current_evidence:controls.filter(x=>x.assurance==='ASSURED_BY_CURRENT_EVIDENCE').length,attested_management_reviews:reviews.filter(x=>x.status==='ATTESTED').length};
return {scope:'PERSONAL_ONLY',read_only:true,finance_mutations:false,capa_mutations:false,months,generated_at:new Date().toISOString(),model:{type:'TRANSPARENT_RULES',opaque_score:false,priority_order:['PRIORITY_1','PRIORITY_2','PRIORITY_3','MONITOR'],priority_rules:{PRIORITY_1:'Open Critical incident, CAPA 14+ days overdue, or Not Effective CAPA.',PRIORITY_2:'Observed post-closure recurrence, CAPA 7+ days overdue, or open Action Soon incident.',PRIORITY_3:'Any overdue CAPA, insufficient effectiveness evidence, or linked review not yet attested.',MONITOR:'No elevated factor observed in the selected evidence window.'}},summary,controls,management_review_history:{total:reviews.length,attested:reviews.filter(x=>x.status==='ATTESTED').length,latest_attested_month:reviews.filter(x=>x.status==='ATTESTED').map(x=>x.review_month).filter(Boolean).sort().at(-1)||null},governance_signal:{attention_required:controls.some(x=>x.priority!=='MONITOR'||x.assurance==='ASSURANCE_GAP'),priority_categories:controls.filter(x=>x.priority!=='MONITOR').map(x=>({category:x.category,priority:x.priority,assurance:x.assurance})),evidence_only:true,no_inferred_root_cause:true,no_causal_claim:true}};}
exports.get=async(req,res)=>{try{return res.json(await build(uid(req),clampMonths(req.query.months)));}catch(e){return fail(res,e);}};
exports._test={clampMonths,daysOverdue,priorityFromFactors,assuranceFromFactors,reasons,build};
