const crypto = require('node:crypto');
const pool = require('../config/db');

function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function fail(res,e,msg){const s=Number(e?.statusCode||500);if(s>=500)console.error(msg,e);return res.status(s).json({message:s>=500?msg:e.message});}
function text(v,max=180){const s=String(v||'').trim();return s?s.slice(0,max):null;}
function code(v){const c=String(v||'AUD').trim().toUpperCase();if(!/^[A-Z]{3}$/.test(c))throw Object.assign(new Error('Currency must be a three-letter code.'),{statusCode:400});return c;}
function money(v,label){const n=Number(v);if(!Number.isFinite(n)||n<0||n>1e12)throw Object.assign(new Error(`${label} is invalid.`),{statusCode:400});return Math.round(n*10000)/10000;}
function dateOnly(v,label){const s=String(v||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw Object.assign(new Error(`${label} is invalid.`),{statusCode:400});return s;}
function addMonths(date,n){const d=new Date(`${date}T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+n);return d.toISOString().slice(0,10);}
function monthSpan(start,end){const a=new Date(`${start}T00:00:00Z`),b=new Date(`${end}T00:00:00Z`);let m=(b.getUTCFullYear()-a.getUTCFullYear())*12+(b.getUTCMonth()-a.getUTCMonth());if(b.getUTCDate()>a.getUTCDate())m+=1;return Math.max(1,Math.min(120,m));}
function status(direction,actual,planned){if(actual===null||actual===undefined)return 'NOT_RECORDED';const a=Number(actual),p=Number(planned);if(direction==='DECREASE')return a<=p?'ON_TRACK':'BEHIND';return a>=p?'ON_TRACK':'BEHIND';}
async function ownedRoadmap(conn,userId,id,lock=false){const [[r]]=await conn.query(`SELECT * FROM personal_financial_roadmaps WHERE id=? AND user_id=? LIMIT 1${lock?' FOR UPDATE':''}`,[id,userId]);if(!r)throw Object.assign(new Error('Roadmap not found.'),{statusCode:404});return r;}

exports.getCenter=async(req,res)=>{try{const u=uid(req);const [plans,milestones]=await Promise.all([
 pool.query(`SELECT id,name,plan_type,currency,direction,starting_value,target_value,monthly_target,start_date,target_date,status,note,created_at,updated_at FROM personal_financial_roadmaps WHERE user_id=? AND status<>'ARCHIVED' ORDER BY FIELD(status,'ACTIVE','COMPLETED','PAUSED'),target_date`,[u]).then(([r])=>r),
 pool.query(`SELECT m.id,m.roadmap_id,m.milestone_no,m.due_date,m.planned_value,m.actual_value,m.actual_recorded_at,m.note,r.direction,r.currency,r.name roadmap_name FROM personal_financial_roadmap_milestones m JOIN personal_financial_roadmaps r ON r.id=m.roadmap_id AND r.user_id=m.user_id WHERE m.user_id=? AND r.status<>'ARCHIVED' ORDER BY m.due_date,m.milestone_no`,[u]).then(([r])=>r)
]);
 const grouped={};milestones.forEach(m=>{m.planned_value=Number(m.planned_value);m.actual_value=m.actual_value===null?null:Number(m.actual_value);m.progress_status=status(m.direction,m.actual_value,m.planned_value);(grouped[m.roadmap_id]||(grouped[m.roadmap_id]=[])).push(m);});
 const roadmaps=plans.map(p=>{const ms=grouped[p.id]||[],recorded=ms.filter(m=>m.actual_value!==null),latest=recorded.at(-1)||null;return {...p,starting_value:Number(p.starting_value),target_value:Number(p.target_value),monthly_target:p.monthly_target===null?null:Number(p.monthly_target),milestones:ms,summary:{total_milestones:ms.length,recorded:recorded.length,on_track:recorded.filter(m=>m.progress_status==='ON_TRACK').length,behind:recorded.filter(m=>m.progress_status==='BEHIND').length,latest_status:latest?.progress_status||'NOT_RECORDED'}};});
 return res.json({privacy:'Roadmaps are private to the signed-in user.',explanation:'Roadmaps track intentions and progress only. They do not move money, alter loan balances, create payments or post company accounting entries.',roadmaps});
}catch(e){return fail(res,e,'Failed to load Financial Roadmap Center.');}};

exports.createRoadmap=async(req,res)=>{const c=await pool.getConnection();try{const u=uid(req),name=text(req.body.name);if(!name)throw Object.assign(new Error('Roadmap name is required.'),{statusCode:400});const type=String(req.body.plan_type||'OTHER').toUpperCase();if(!new Set(['GOAL','DEBT_PAYOFF','EMERGENCY','INVESTMENT','SUPER','OTHER']).has(type))throw Object.assign(new Error('Choose a valid roadmap type.'),{statusCode:400});const currency=code(req.body.currency),direction=String(req.body.direction||'INCREASE').toUpperCase();if(!['INCREASE','DECREASE'].includes(direction))throw Object.assign(new Error('Direction must be INCREASE or DECREASE.'),{statusCode:400});const start=money(req.body.starting_value,'Starting value'),target=money(req.body.target_value,'Target value'),startDate=dateOnly(req.body.start_date,'Start date'),targetDate=dateOnly(req.body.target_date,'Target date');if(targetDate<startDate)throw Object.assign(new Error('Target date must be after the start date.'),{statusCode:400});const months=monthSpan(startDate,targetDate),id=crypto.randomUUID(),monthly=req.body.monthly_target===''||req.body.monthly_target==null?null:money(req.body.monthly_target,'Monthly target');let scenario=null;if(req.body.scenario&&typeof req.body.scenario==='object')scenario=JSON.stringify(req.body.scenario).slice(0,12000);await c.beginTransaction();await c.query(`INSERT INTO personal_financial_roadmaps (id,user_id,name,plan_type,currency,direction,starting_value,target_value,monthly_target,start_date,target_date,scenario_json,note) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,[id,u,name,type,currency,direction,start,target,monthly,startDate,targetDate,scenario,text(req.body.note,500)]);for(let i=1;i<=months;i++){const ratio=i/months,planned=start+(target-start)*ratio;await c.query(`INSERT INTO personal_financial_roadmap_milestones (id,roadmap_id,user_id,milestone_no,due_date,planned_value) VALUES (?,?,?,?,?,?)`,[crypto.randomUUID(),id,u,i,i===months?targetDate:addMonths(startDate,i),Math.round(planned*10000)/10000]);}await c.commit();return res.status(201).json({message:`Roadmap saved with ${months} monthly checkpoint${months===1?'':'s'}. No money or accounting record was changed.`,id});}catch(e){await c.rollback().catch(()=>{});return fail(res,e,'Failed to save roadmap.');}finally{c.release();}};

exports.recordProgress=async(req,res)=>{const c=await pool.getConnection();try{const u=uid(req),value=money(req.body.actual_value,'Actual value');await c.beginTransaction();const roadmap=await ownedRoadmap(c,u,req.params.roadmapId,true);const [[m]]=await c.query(`SELECT * FROM personal_financial_roadmap_milestones WHERE id=? AND roadmap_id=? AND user_id=? LIMIT 1 FOR UPDATE`,[req.params.milestoneId,roadmap.id,u]);if(!m)throw Object.assign(new Error('Milestone not found.'),{statusCode:404});await c.query(`UPDATE personal_financial_roadmap_milestones SET actual_value=?,actual_recorded_at=NOW(),note=? WHERE id=? AND user_id=?`,[value,text(req.body.note,500),m.id,u]);const state=status(roadmap.direction,value,Number(m.planned_value));await c.commit();return res.json({message:`Progress recorded: ${state==='ON_TRACK'?'on track or ahead':'behind this checkpoint'}. This did not move money or alter any real balance.`,progress_status:state});}catch(e){await c.rollback().catch(()=>{});return fail(res,e,'Failed to record roadmap progress.');}finally{c.release();}};

exports.updateStatus=async(req,res)=>{try{const u=uid(req),state=String(req.body.status||'').toUpperCase();if(!['ACTIVE','PAUSED','COMPLETED','ARCHIVED'].includes(state))return res.status(400).json({message:'Choose Active, Paused, Completed or Archived.'});const [r]=await pool.query(`UPDATE personal_financial_roadmaps SET status=? WHERE id=? AND user_id=?`,[state,req.params.id,u]);if(!r.affectedRows)return res.status(404).json({message:'Roadmap not found.'});return res.json({message:`Roadmap marked ${state.toLowerCase()}.`});}catch(e){return fail(res,e,'Failed to update roadmap.');}};
