const crypto=require('node:crypto');
const pool=require('../config/db');

const CATEGORIES=['RESTORE_FIDELITY','DEPENDENCY_INTEGRITY','CERTIFICATE_INTEGRITY','ROLLBACK_PROTECTION','VERIFICATION_INITIALIZATION','OTHER_EVIDENCE_CONDITION'];
const RESULTS=['PENDING','PASS','FAIL','NEEDS_REVIEW'];
function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function text(v,max){return String(v??'').trim().slice(0,max);}
function parse(v,fallback){if(v===null||v===undefined||v==='')return fallback;if(typeof v==='object')return v;try{return JSON.parse(v);}catch{return fallback;}}
function arr(v,max=20,itemMax=300){const a=Array.isArray(v)?v:[];return a.map(x=>text(x,itemMax)).filter(Boolean).slice(0,max);}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Recovery control testing failed.',e);return res.status(s).json({message:s>=500?'Recovery control testing failed.':e.message,code:e.code||'RECOVERY_CONTROL_TESTING_FAILED'});}
function appError(message,statusCode=400,code='RECOVERY_CONTROL_TESTING_FAILED'){return Object.assign(new Error(message),{statusCode,code});}
function frequency(v){const n=Math.trunc(Number(v));if(!Number.isFinite(n)||n<7||n>365)throw appError('Test frequency must be between 7 and 365 days.');return n;}
function nextRetest(testedAt,days){return new Date(new Date(testedAt).getTime()+days*86400000);}
async function owned(userId,id){const [[r]]=await pool.query(`SELECT * FROM personal_finance_recovery_control_tests WHERE id=? AND user_id=? LIMIT 1`,[id,userId]);if(!r)throw appError('Control test was not found.',404,'CONTROL_TEST_NOT_FOUND');return r;}
async function event(db,userId,id,type,note,evidence){await db.query(`INSERT INTO personal_finance_recovery_control_test_events (id,control_test_id,user_id,event_type,note,evidence_json) VALUES (?,?,?,?,?,?)`,[crypto.randomUUID(),id,userId,type,text(note,1200)||null,evidence?JSON.stringify(evidence):null]);}
async function verifyLinks(userId,capaId,reviewId){if(capaId){const [[c]]=await pool.query(`SELECT id FROM personal_finance_recovery_capa WHERE id=? AND user_id=? LIMIT 1`,[capaId,userId]);if(!c)throw appError('Linked CAPA must belong to the current owner.',409,'CONTROL_TEST_CAPA_SCOPE_MISMATCH');}if(reviewId){const [[r]]=await pool.query(`SELECT id,status FROM personal_finance_recovery_management_reviews WHERE id=? AND user_id=? LIMIT 1`,[reviewId,userId]);if(!r)throw appError('Linked management review must belong to the current owner.',409,'CONTROL_TEST_REVIEW_SCOPE_MISMATCH');return r;}return null;}
function hydrate(r){return {...r,procedure_steps:parse(r.procedure_steps_json,[]),expected_evidence:parse(r.expected_evidence_json,[]),evidence_refs:parse(r.evidence_refs_json,[]),procedure_steps_json:undefined,expected_evidence_json:undefined,evidence_refs_json:undefined,immutable:Boolean(r.signed_off_at),overdue:Boolean(!r.signed_off_at&&new Date(r.scheduled_at)<new Date()),retest_due:Boolean(r.next_retest_at&&new Date(r.next_retest_at)<=new Date())};}

exports.list=async(req,res)=>{try{const userId=uid(req);const [rows]=await pool.query(`SELECT * FROM personal_finance_recovery_control_tests WHERE user_id=? ORDER BY signed_off_at IS NULL DESC,scheduled_at ASC,created_at DESC LIMIT 200`,[userId]);const items=rows.map(hydrate);const [events]=await pool.query(`SELECT e.control_test_id,e.event_type,e.note,e.created_at FROM personal_finance_recovery_control_test_events e JOIN personal_finance_recovery_control_tests t ON t.id=e.control_test_id AND t.user_id=e.user_id WHERE e.user_id=? ORDER BY e.created_at DESC LIMIT 100`,[userId]);return res.json({scope:'PERSONAL_ONLY',finance_mutations:false,items,summary:{total:items.length,pending:items.filter(x=>x.result==='PENDING').length,failed:items.filter(x=>x.result==='FAIL').length,needs_review:items.filter(x=>x.result==='NEEDS_REVIEW').length,signed_off_pass:items.filter(x=>x.result==='PASS'&&x.signed_off_at).length,overdue:items.filter(x=>x.overdue).length,retest_due:items.filter(x=>x.retest_due).length},recent_events:events});}catch(e){return fail(res,e);}};
exports.create=async(req,res)=>{try{const userId=uid(req),category=text(req.body?.control_category,80),title=text(req.body?.procedure_title,180),steps=arr(req.body?.procedure_steps,30,500),expected=arr(req.body?.expected_evidence,30,300),freq=frequency(req.body?.frequency_days),scheduled=new Date(req.body?.scheduled_at||Date.now()),tester=text(req.body?.tester_label,120)||null,reviewer=text(req.body?.reviewer_label,120)||null,capaId=text(req.body?.linked_capa_id,36)||null,reviewId=text(req.body?.linked_review_id,36)||null;if(!CATEGORIES.includes(category))throw appError('Invalid control category.');if(!title||!steps.length||!expected.length||Number.isNaN(scheduled.getTime()))throw appError('Title, procedure steps, expected evidence and a valid schedule are required.');await verifyLinks(userId,capaId,reviewId);const id=crypto.randomUUID();await pool.query(`INSERT INTO personal_finance_recovery_control_tests (id,user_id,control_category,procedure_title,procedure_steps_json,frequency_days,expected_evidence_json,scheduled_at,tester_label,reviewer_label,linked_capa_id,linked_review_id,evidence_refs_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,[id,userId,category,title,JSON.stringify(steps),freq,JSON.stringify(expected),scheduled,tester,reviewer,capaId,reviewId,JSON.stringify([])]);await event(pool,userId,id,'CONTROL_TEST_CREATED','Control test cycle created.',{control_category:category,frequency_days:freq,scheduled_at:scheduled});return res.status(201).json({item:hydrate(await owned(userId,id))});}catch(e){return fail(res,e);}};
exports.update=async(req,res)=>{try{const userId=uid(req),id=text(req.body?.control_test_id,36),r=await owned(userId,id);if(r.signed_off_at)throw appError('Signed-off control tests are immutable. Create a new retest cycle instead.',409,'CONTROL_TEST_IMMUTABLE');const title=text(req.body?.procedure_title||r.procedure_title,180),steps=req.body?.procedure_steps?arr(req.body.procedure_steps,30,500):parse(r.procedure_steps_json,[]),expected=req.body?.expected_evidence?arr(req.body.expected_evidence,30,300):parse(r.expected_evidence_json,[]),freq=req.body?.frequency_days?frequency(req.body.frequency_days):Number(r.frequency_days),scheduled=req.body?.scheduled_at?new Date(req.body.scheduled_at):new Date(r.scheduled_at),tester=text(req.body?.tester_label??r.tester_label,120)||null,reviewer=text(req.body?.reviewer_label??r.reviewer_label,120)||null,capaId=text(req.body?.linked_capa_id??r.linked_capa_id,36)||null,reviewId=text(req.body?.linked_review_id??r.linked_review_id,36)||null;if(Number.isNaN(scheduled.getTime()))throw appError('Invalid scheduled date.');await verifyLinks(userId,capaId,reviewId);await pool.query(`UPDATE personal_finance_recovery_control_tests SET procedure_title=?,procedure_steps_json=?,frequency_days=?,expected_evidence_json=?,scheduled_at=?,tester_label=?,reviewer_label=?,linked_capa_id=?,linked_review_id=? WHERE id=? AND user_id=?`,[title,JSON.stringify(steps),freq,JSON.stringify(expected),scheduled,tester,reviewer,capaId,reviewId,id,userId]);await event(pool,userId,id,'CONTROL_TEST_UPDATED','Control test procedure or ownership metadata updated.',null);return res.json({item:hydrate(await owned(userId,id))});}catch(e){return fail(res,e);}};
exports.recordResult=async(req,res)=>{try{const userId=uid(req),id=text(req.body?.control_test_id,36),r=await owned(userId,id);if(r.signed_off_at)throw appError('Signed-off control tests are immutable.',409,'CONTROL_TEST_IMMUTABLE');const result=text(req.body?.result,32).toUpperCase(),note=text(req.body?.result_note,1200),evidence=arr(req.body?.evidence_refs,30,300),tester=text(req.body?.tester_label||r.tester_label,120)||null;if(!RESULTS.includes(result)||result==='PENDING')throw appError('Result must be PASS, FAIL or NEEDS_REVIEW.');if(!tester)throw appError('Tester is required before recording a result.');if(!note)throw appError('A result note is required.');const tested=new Date(),next=nextRetest(tested,Number(r.frequency_days));await pool.query(`UPDATE personal_finance_recovery_control_tests SET result=?,result_note=?,evidence_refs_json=?,tester_label=?,tested_at=?,next_retest_at=? WHERE id=? AND user_id=?`,[result,note,JSON.stringify(evidence),tester,tested,next,id,userId]);await event(pool,userId,id,'CONTROL_TEST_RESULT_RECORDED',note,{result,evidence_reference_count:evidence.length,next_retest_at:next});return res.json({item:hydrate(await owned(userId,id))});}catch(e){return fail(res,e);}};
exports.signOff=async(req,res)=>{try{const userId=uid(req),id=text(req.body?.control_test_id,36),r=await owned(userId,id);if(r.signed_off_at)return res.json({item:hydrate(r),already_signed_off:true});if(r.result!=='PASS')throw appError('Only a PASS result can receive assurance sign-off.',409,'CONTROL_TEST_PASS_REQUIRED');const reviewer=text(req.body?.reviewer_label||r.reviewer_label,120),evidence=parse(r.evidence_refs_json,[]);if(!reviewer)throw appError('Reviewer is required for assurance sign-off.');if(!evidence.length)throw appError('At least one evidence reference is required before assurance sign-off.',409,'CONTROL_TEST_EVIDENCE_REQUIRED');if(!r.linked_review_id)throw appError('Link an attested management review before assurance sign-off.',409,'CONTROL_TEST_REVIEW_REQUIRED');const review=await verifyLinks(userId,r.linked_capa_id,r.linked_review_id);if(review?.status!=='ATTESTED')throw appError('The linked management review must be ATTESTED before assurance sign-off.',409,'CONTROL_TEST_ATTESTED_REVIEW_REQUIRED');await pool.query(`UPDATE personal_finance_recovery_control_tests SET reviewer_label=?,signed_off_at=NOW() WHERE id=? AND user_id=?`,[reviewer,id,userId]);await event(pool,userId,id,'CONTROL_TEST_SIGNED_OFF','PASS control test signed off as assurance evidence.',{reviewer_label:reviewer,linked_review_id:r.linked_review_id,result:r.result});return res.json({item:hydrate(await owned(userId,id))});}catch(e){return fail(res,e);}};
exports._test={CATEGORIES,RESULTS,frequency,nextRetest,hydrate};