const pool=require('../config/db');
const canonical=require('./personalFinanceCanonicalBackupController')._test;
const verification=require('./personalFinancePostRestoreVerificationController')._test;

const MAX_RUNS=5;
const DEFAULT_RUNS=3;
const ROLLBACK_SOON_DAYS=7;
function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function hash(v){return canonical.hash(v);}
function parse(v,fallback){if(v===null||v===undefined||v==='')return fallback;if(typeof v==='object')return v;try{return JSON.parse(v);}catch{return fallback;}}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Personal Finance recovery integrity watch failed.',e);return res.status(s).json({message:s>=500?'Personal Finance recovery integrity watch failed.':e.message,code:e.code||'RECOVERY_INTEGRITY_WATCH_FAILED'});}
function certificateComputed(row){const evidence=parse(row.evidence_json,null);if(!evidence)return {ok:false,reason:'Certificate evidence is unreadable.'};const stored=evidence.certificate?.certificate_sha256,copy=JSON.parse(JSON.stringify(evidence));if(copy.certificate)delete copy.certificate.certificate_sha256;const computed=hash({previous_certificate_sha256:row.previous_certificate_sha256||null,evidence:copy});return {ok:stored===row.certificate_sha256&&computed===row.certificate_sha256,evidence,computed};}
async function certificateChain(userId,runId){const [rows]=await pool.query(`SELECT id,sequence_no,verification_status,previous_certificate_sha256,certificate_sha256,evidence_json,generated_at FROM personal_finance_recovery_certificates WHERE restore_run_id=? AND user_id=? ORDER BY sequence_no ASC`,[runId,userId]);let previous=null,expectedSequence=1;const failures=[];for(const row of rows){const c=certificateComputed(row);if(Number(row.sequence_no)!==expectedSequence)failures.push(`Certificate sequence expected ${expectedSequence} but found ${row.sequence_no}.`);if((row.previous_certificate_sha256||null)!==previous)failures.push(`Certificate #${row.sequence_no} previous-hash link does not match.`);if(!c.ok)failures.push(`Certificate #${row.sequence_no} SHA-256 integrity failed.`);previous=row.certificate_sha256||null;expectedSequence++;}const latest=rows.length?rows[rows.length-1]:null;return {count:rows.length,valid:failures.length===0,failures,latest:latest?{id:latest.id,sequence_no:Number(latest.sequence_no),verification_status:latest.verification_status,certificate_sha256:latest.certificate_sha256,generated_at:latest.generated_at}:null};}
function rollbackState(run,now=Date.now()){if(run.status!=='SUCCEEDED'||!run.rollback_expires_at)return {available:false,state:'NOT_AVAILABLE',days_remaining:null};const expiry=new Date(run.rollback_expires_at).getTime();if(!Number.isFinite(expiry))return {available:false,state:'UNKNOWN',days_remaining:null};const ms=expiry-now;if(ms<=0)return {available:false,state:'EXPIRED',days_remaining:0,expires_at:run.rollback_expires_at};const days=Math.ceil(ms/86400000);return {available:true,state:days<=ROLLBACK_SOON_DAYS?'EXPIRING_SOON':'AVAILABLE',days_remaining:days,expires_at:run.rollback_expires_at};}
function signalsFor(run,verify,cert,rollback){const signals=[];if(verify.overall_status==='CRITICAL_MISMATCH')signals.push({level:'CRITICAL',type:'RESTORE_DRIFT',message:'Current canonical records no longer fully match the approved restore target or a required dependency is broken.'});if(!cert.valid)signals.push({level:'CRITICAL',type:'CERTIFICATE_CHAIN_INTEGRITY',message:'One or more stored recovery certificates failed SHA-256 chain validation.'});if(verify.overall_status==='INITIALIZATION_REQUIRED')signals.push({level:'ACTION_SOON',type:'VERIFICATION_NOT_INITIALIZED',message:'This successful restore has no initialized post-restore verification target set.'});if(verify.overall_status==='NEEDS_REVIEW')signals.push({level:'ACTION_SOON',type:'VERIFICATION_REVIEW',message:`Current verification has ${Number(verify.summary?.review_findings||0)} review finding(s).`});if(cert.count===0&&['VERIFIED','NEEDS_REVIEW','CRITICAL_MISMATCH'].includes(verify.overall_status))signals.push({level:'ACTION_SOON',type:'CERTIFICATE_MISSING',message:'No recovery certificate has been generated for the current restore verification.'});if(cert.latest&&cert.latest.verification_status!==verify.overall_status)signals.push({level:'ACTION_SOON',type:'STATUS_CHANGED_SINCE_CERTIFICATE',message:`Latest certificate recorded ${cert.latest.verification_status}; current verification is ${verify.overall_status}. Generate a new certificate if you want to preserve the latest state.`});if(rollback.state==='EXPIRING_SOON')signals.push({level:'ACTION_SOON',type:'ROLLBACK_EXPIRING',message:`Rollback protection expires in about ${rollback.days_remaining} day(s).`});if(!signals.length)signals.push({level:'HEALTHY',type:'RECOVERY_HEALTHY',message:'Restore fidelity, dependency checks and certificate integrity currently show no watch condition.'});return signals;}
function overall(signals){if(signals.some(x=>x.level==='CRITICAL'))return 'CRITICAL';if(signals.some(x=>x.level==='ACTION_SOON'))return 'ACTION_SOON';return 'HEALTHY';}
function remediationPlan(verify,cert,rollback,signals){const steps=[],affected=new Set();for(const d of verify.datasets||[]){if(d.status==='CRITICAL_MISMATCH')affected.add(d.dataset);}for(const c of verify.critical_mismatches||[]){if(c.dataset)affected.add(c.dataset);}const has=t=>signals.some(s=>s.type===t);if(has('RESTORE_DRIFT')){steps.push({priority:'CRITICAL',action:'INVESTIGATE_CURRENT_STATE',title:'Investigate restore drift before changing anything',why:'One or more current records or dependencies no longer match the approved recovery target.',evidence:(verify.critical_mismatches||[]).slice(0,8).map(x=>({type:x.type,dataset:x.dataset||null,count:Number(x.count||0),message:x.message})),cause_boundary:'Verification proves the current state differs from the approved target. It does not prove which later user action, import, integration, or process caused the difference.'});steps.push({priority:'CRITICAL',action:'PRESERVE_FRESH_BACKUP',title:'Create a fresh canonical backup before any remediation',why:'Preserving the current state gives you a separate recovery point before rollback or re-restore decisions.'});if(rollback.available)steps.push({priority:'CRITICAL',action:'CONSIDER_CONTROLLED_ROLLBACK',title:'Review the existing rollback option',why:`The governed rollback checkpoint is still available${rollback.days_remaining!==null?` for about ${rollback.days_remaining} day(s)`:''}.`,approval:'Rollback still requires EDIT_FINANCE, fresh step-up authentication and the exact rollback confirmation in the existing Restore Executor.'});else steps.push({priority:'ACTION_SOON',action:'PREPARE_NEW_RESTORE',title:'Rollback is unavailable — prepare a new governed restore if needed',why:'Use a verified canonical backup, server dry-run, explicit dataset actions and the existing restore approval flow. Do not recreate records manually from dashboard summaries.'});}
if(has('CERTIFICATE_CHAIN_INTEGRITY'))steps.push({priority:'CRITICAL',action:'PRESERVE_CERTIFICATE_EVIDENCE',title:'Treat the certificate chain as untrusted until reviewed',why:'At least one stored recovery certificate failed sequence, previous-hash, or certificate SHA-256 validation.',evidence:cert.failures.slice(0,8),approval:'Do not delete or overwrite certificate evidence. Generate new evidence only after the underlying integrity problem is understood.'});
if(has('VERIFICATION_NOT_INITIALIZED'))steps.push({priority:'ACTION_SOON',action:'INITIALIZE_VERIFICATION',title:'Initialize post-restore verification targets',why:'The restore completed before a usable expected-hash target set was available. Initialization requires the matching verified canonical package; it does not alter finance records.'});
if(has('VERIFICATION_REVIEW'))steps.push({priority:'ACTION_SOON',action:'REVIEW_NON_CRITICAL_FINDINGS',title:'Review non-critical recovery findings',why:'These signals can be legitimate and must not be auto-corrected.',evidence:(verify.needs_review||[]).slice(0,8).map(x=>({type:x.type,count:Number(x.count||0),message:x.message}))});
if(has('CERTIFICATE_MISSING'))steps.push({priority:'ACTION_SOON',action:'CERTIFY_CURRENT_STATE',title:'Generate a recovery certificate after reviewing verification',why:'A certificate freezes the current verification result into tamper-evident evidence. It does not change finance data.'});
if(has('STATUS_CHANGED_SINCE_CERTIFICATE'))steps.push({priority:'ACTION_SOON',action:'COMPARE_WITH_LATEST_CERTIFICATE',title:'Compare the latest certificate with current verification',why:`The latest certificate records ${cert.latest?.verification_status||'UNKNOWN'} while current verification is ${verify.overall_status}. Preserve a new certificate only after reviewing the change.`});
if(has('ROLLBACK_EXPIRING'))steps.push({priority:'ACTION_SOON',action:'DECIDE_BEFORE_ROLLBACK_EXPIRY',title:'Make a recovery decision before rollback protection expires',why:`The current rollback window has about ${rollback.days_remaining} day(s) remaining. Expiry does not change your finance data, but removes this checkpoint-based rollback option.`});
if(!steps.length)steps.push({priority:'HEALTHY',action:'NO_REMEDIATION_REQUIRED',title:'No remediation is currently required',why:'Current restore hashes, dependencies and certificate chain show no watch condition.'});return {generated_from:'Current owner-only post-restore verification + certificate-chain validation + rollback metadata.',affected_datasets:[...affected].sort(),steps,controls:{planner_read_only:true,automatic_repair:false,automatic_rollback:false,automatic_restore:false,explicit_approval_required_for_future_mutation:true}};}
async function monitorRun(userId,run){const cert=await certificateChain(userId,run.id);let verify;if(run.status==='ROLLED_BACK')verify={run_id:run.id,overall_status:'NOT_APPLICABLE',summary:{},datasets:[],currencies:[],critical_mismatches:[],needs_review:[]};else verify=await verification.verifyRun(userId,run.id);const rollback=rollbackState(run);const signals=run.status==='ROLLED_BACK'?[{level:'HEALTHY',type:'ROLLED_BACK',message:'This restore was rolled back; active restore-fidelity monitoring is no longer applicable.'}]:signalsFor(run,verify,cert,rollback);return {run_id:run.id,restore_status:run.status,executed_at:run.executed_at||run.created_at,package_sha256:run.package_sha256,schema_version:run.schema_version,health:overall(signals),verification:{overall_status:verify.overall_status,summary:verify.summary||{},datasets:verify.datasets||[],currencies:verify.currencies||[],critical_count:(verify.critical_mismatches||[]).length,review_count:(verify.needs_review||[]).length,critical_mismatches:verify.critical_mismatches||[],needs_review:verify.needs_review||[]},certificates:{count:cert.count,chain_valid:cert.valid,latest:cert.latest,failures:cert.failures},rollback,signals,remediation_plan:remediationPlan(verify,cert,rollback,signals)};}
exports.get=async(req,res)=>{try{const userId=uid(req),requested=Math.max(1,Math.min(MAX_RUNS,Number(req.query.limit)||DEFAULT_RUNS));const [runs]=await pool.query(`SELECT id,status,package_sha256,schema_version,created_at,executed_at,rollback_expires_at FROM personal_finance_restore_runs WHERE user_id=? AND status IN ('SUCCEEDED','ROLLED_BACK') ORDER BY COALESCE(executed_at,created_at) DESC LIMIT ?`,[userId,requested]);const monitored=[];for(const run of runs)monitored.push(await monitorRun(userId,run));const counts={critical:0,action_soon:0,healthy:0};for(const r of monitored){if(r.health==='CRITICAL')counts.critical++;else if(r.health==='ACTION_SOON')counts.action_soon++;else counts.healthy++;}return res.json({generated_at:new Date().toISOString(),scope:'PERSONAL_ONLY',read_only:true,finance_mutations:false,continuous_mode:'Refreshes current owner-only recovery integrity when requested. The browser UI rechecks every 5 minutes only while the page is visible.',currency_rule:'Currencies remain separate. Monitoring and remediation planning never create a cross-currency total or inferred FX conversion.',summary:{runs_monitored:monitored.length,...counts},runs:monitored,controls:{automatic_repairs:false,automatic_reconciliation:false,automatic_money_movement:false,automatic_restore:false,automatic_rollback:false,company_finance_included:false,certificate_chain_algorithm:'SHA-256',rollback_warning_days:ROLLBACK_SOON_DAYS}});}catch(e){return fail(res,e);}};
exports._test={certificateComputed,rollbackState,signalsFor,overall,remediationPlan,monitorRun,certificateChain,MAX_RUNS,ROLLBACK_SOON_DAYS};
