const pool=require('../config/db');

function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Recovery assurance calendar failed.',e);return res.status(s).json({message:s>=500?'Recovery assurance calendar failed.':e.message,code:e.code||'RECOVERY_ASSURANCE_CALENDAR_FAILED'});}
function days(v,now=Date.now()){if(!v)return null;return Math.ceil((new Date(v).getTime()-now)/86400000);}
function dayKey(v){return new Date(v).toISOString().slice(0,10);}
function monthKey(v){return new Date(v).toISOString().slice(0,7);}
function workload(count){return count>=6?'HEAVY':count>=3?'BUSY':count>=1?'MANAGEABLE':'CLEAR';}
function nextMonthMarkers(now=new Date(),count=3){const out=[];for(let i=1;i<=count;i++){const d=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+i,1,9,0,0));out.push(d.toISOString());}return out;}
function event(type,date,title,source_id,extra={}){return {event_type:type,event_at:new Date(date).toISOString(),date:dayKey(date),month:monthKey(date),title,source_id,...extra};}
function within(d,horizon,now=Date.now()){const x=days(d,now);return x!==null&&x>=0&&x<=horizon;}

async function build(userId,nowInput=Date.now()){const now=Number(nowInput)||Date.now();const [tests]=await pool.query(`SELECT id,control_category,test_name,lifecycle_status,result,next_retest_at,frequency_days FROM personal_finance_recovery_control_tests WHERE user_id=?`,[userId]);const [capas]=await pool.query(`SELECT id,source_category,title,status,due_at,owner_label FROM personal_finance_recovery_capa WHERE user_id=? AND status<>'CLOSED'`,[userId]);const [requests]=await pool.query(`SELECT id,control_test_id,request_type,status,due_at,request_note FROM personal_finance_recovery_control_evidence_requests WHERE user_id=? AND status='OPEN'`,[userId]);const [reviews]=await pool.query(`SELECT id,review_month,status,reviewer_label,created_at FROM personal_finance_recovery_management_reviews WHERE user_id=? ORDER BY review_month DESC LIMIT 24`,[userId]);
  const events=[];
  for(const t of tests)if(t.next_retest_at)events.push(event(t.lifecycle_status==='ASSURED'?'ASSURANCE_EXPIRY_RETEST':'CONTROL_RETEST',t.next_retest_at,`${t.test_name} — ${t.lifecycle_status==='ASSURED'?'assurance expires / retest due':'retest due'}`,t.id,{category:t.control_category,result:t.result,lifecycle_status:t.lifecycle_status}));
  for(const c of capas)if(c.due_at)events.push(event('CAPA_DUE',c.due_at,`${c.title} — CAPA due`,c.id,{category:c.source_category,owner_label:c.owner_label||null,status:c.status}));
  for(const r of requests)if(r.due_at)events.push(event('EVIDENCE_REQUEST_DUE',r.due_at,`${r.request_type} request due`,r.id,{control_test_id:r.control_test_id,request_type:r.request_type,note:r.request_note||null}));
  for(const r of reviews)if(r.status!=='ATTESTED')events.push(event('MANAGEMENT_REVIEW_OPEN',r.created_at,`Management review ${r.review_month} — ${r.status}`,r.id,{review_month:r.review_month,status:r.status,planning_marker:false}));
  for(const d of nextMonthMarkers(new Date(now),3))events.push(event('MANAGEMENT_REVIEW_PLANNING_MARKER',d,`Monthly recovery governance review planning marker`,null,{planning_marker:true,not_an_enforced_deadline:true}));
  events.sort((a,b)=>new Date(a.event_at)-new Date(b.event_at));
  const overdue=events.filter(x=>days(x.event_at,now)<0&&!x.planning_marker).map(x=>({...x,days_from_now:days(x.event_at,now)}));
  const future=events.filter(x=>days(x.event_at,now)>=0).map(x=>({...x,days_from_now:days(x.event_at,now)}));
  const horizons={days_30:future.filter(x=>within(x.event_at,30,now)),days_60:future.filter(x=>within(x.event_at,60,now)),days_90:future.filter(x=>within(x.event_at,90,now))};
  const dayMap={};for(const x of future.filter(e=>within(e.event_at,90,now))){dayMap[x.date]??=[];dayMap[x.date].push(x);}const conflicts=Object.entries(dayMap).filter(([,v])=>v.length>=2).map(([date,items])=>({date,count:items.length,severity:items.length>=4?'HIGH':'MEDIUM',items:items.map(x=>({event_type:x.event_type,title:x.title,source_id:x.source_id}))}));
  const monthMap={};for(const x of future.filter(e=>within(e.event_at,90,now))){monthMap[x.month]??={month:x.month,events:0,tests_retests:0,capa_due:0,evidence_requests:0,management_reviews:0,conflict_days:0};const m=monthMap[x.month];m.events++;if(['CONTROL_RETEST','ASSURANCE_EXPIRY_RETEST'].includes(x.event_type))m.tests_retests++;else if(x.event_type==='CAPA_DUE')m.capa_due++;else if(x.event_type==='EVIDENCE_REQUEST_DUE')m.evidence_requests++;else if(x.event_type.startsWith('MANAGEMENT_REVIEW'))m.management_reviews++;}
  for(const c of conflicts){const m=monthMap[c.date.slice(0,7)];if(m)m.conflict_days++;}const monthly=Object.values(monthMap).sort((a,b)=>a.month.localeCompare(b.month)).map(m=>({...m,workload:workload(m.events)}));
  const byType=list=>list.reduce((a,x)=>(a[x.event_type]=(a[x.event_type]||0)+1,a),{});
  const summary={overdue:overdue.length,next_30:horizons.days_30.length,next_60:horizons.days_60.length,next_90:horizons.days_90.length,conflict_days:conflicts.length,heavy_months:monthly.filter(x=>x.workload==='HEAVY').length};
  return {scope:'PERSONAL_ONLY',read_only:true,finance_mutations:false,deadline_mutations:false,generated_at:new Date().toISOString(),summary,horizons:{days_30:{count:horizons.days_30.length,by_type:byType(horizons.days_30)},days_60:{count:horizons.days_60.length,by_type:byType(horizons.days_60)},days_90:{count:horizons.days_90.length,by_type:byType(horizons.days_90)}},overdue,calendar_90_days:future.filter(x=>within(x.event_at,90,now)),conflicts,monthly_planning:monthly,planning_pack:{title:'Voxel Veda Personal Finance Recovery Assurance Forward Plan',generated_at:new Date().toISOString(),window_days:90,summary,monthly,conflicts,events:future.filter(x=>within(x.event_at,90,now)),controls:{read_only:true,deadlines_auto_moved:false,financial_records_changed:false,management_review_markers_are_planning_markers_not_enforced_deadlines:true}},controls:{automatic_deadline_changes:false,automatic_test_changes:false,automatic_assurance_changes:false,management_review_marker_rule:'First day of each upcoming month, 09:00 UTC, planning marker only — not an enforced deadline.'}};}
exports.get=async(req,res)=>{try{return res.json(await build(uid(req)));}catch(e){return fail(res,e);}};
exports._test={days,dayKey,monthKey,workload,nextMonthMarkers,within,build};
