const crypto=require('node:crypto');
const pool=require('../config/db');
const canonical=require('./personalFinanceCanonicalBackupController')._test;

const MAX_TOTAL_BYTES=50*1024*1024;
const MAX_CHUNKS=512;
const MAX_CHUNK_BYTES=256*1024;
const UPLOAD_MINUTES=30;

function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function appError(message,statusCode=400,code='RESTORE_UPLOAD_VALIDATION_FAILED'){return Object.assign(new Error(message),{statusCode,code});}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Personal Finance restore transport failed.',e);return res.status(s).json({message:s>=500?'Personal Finance restore transport failed.':e.message,code:e.code||'PERSONAL_FINANCE_RESTORE_UPLOAD_ERROR'});}
function sha(v){return crypto.createHash('sha256').update(v).digest('hex');}
function assertHex(value,label){if(!/^[a-f0-9]{64}$/i.test(String(value||'')))throw appError(`${label} must be a SHA-256 value.`);return String(value).toLowerCase();}
async function purgeExpired(){await pool.query(`UPDATE personal_finance_restore_uploads SET status='EXPIRED' WHERE status='UPLOADING' AND expires_at<UTC_TIMESTAMP()`);await pool.query(`DELETE FROM personal_finance_restore_uploads WHERE expires_at<DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 DAY)`);}

async function uploadRow(userId,id,forUpdate=false,db=pool){let sql=`SELECT * FROM personal_finance_restore_uploads WHERE id=? AND user_id=?`;if(forUpdate)sql+=' FOR UPDATE';const [[row]]=await db.query(sql,[id,userId]);if(!row)throw appError('Restore upload session was not found.',404,'RESTORE_UPLOAD_NOT_FOUND');if(new Date(row.expires_at).getTime()<Date.now()||row.status==='EXPIRED')throw appError('Restore upload session expired. Start a new upload.',409,'RESTORE_UPLOAD_EXPIRED');return row;}

exports.start=async(req,res)=>{try{await purgeExpired();const userId=uid(req),totalBytes=Number(req.body?.total_bytes),totalChunks=Number(req.body?.total_chunks),transportSha=assertHex(req.body?.transport_sha256,'Transport checksum'),packageSha=assertHex(req.body?.package_sha256,'Package checksum');if(!Number.isInteger(totalBytes)||totalBytes<2||totalBytes>MAX_TOTAL_BYTES)throw appError(`Canonical restore transport must be between 2 bytes and ${MAX_TOTAL_BYTES} bytes.`);if(!Number.isInteger(totalChunks)||totalChunks<1||totalChunks>MAX_CHUNKS)throw appError(`Chunk count must be between 1 and ${MAX_CHUNKS}.`);if(Math.ceil(totalBytes/totalChunks)>MAX_CHUNK_BYTES)throw appError(`Chunks are too large. Use ${MAX_CHUNK_BYTES} bytes or less per chunk.`);const id=crypto.randomUUID();await pool.query(`INSERT INTO personal_finance_restore_uploads (id,user_id,transport_sha256,package_sha256,total_bytes,total_chunks,expires_at) VALUES (?,?,?,?,?,?,DATE_ADD(UTC_TIMESTAMP(),INTERVAL ? MINUTE))`,[id,userId,transportSha,packageSha,totalBytes,totalChunks,UPLOAD_MINUTES]);return res.json({upload_id:id,max_chunk_bytes:MAX_CHUNK_BYTES,expires_in_minutes:UPLOAD_MINUTES,total_chunks:totalChunks});}catch(e){return fail(res,e);}};

exports.putChunk=async(req,res)=>{let db;try{const userId=uid(req),uploadId=String(req.params.id||''),index=Number(req.params.index),declared=assertHex(req.body?.chunk_sha256,'Chunk checksum');if(!Number.isInteger(index)||index<0||index>=MAX_CHUNKS)throw appError('Chunk index is invalid.');let data;try{data=Buffer.from(String(req.body?.data_b64||''),'base64');}catch{throw appError('Chunk data is invalid.');}if(!data.length||data.length>MAX_CHUNK_BYTES)throw appError(`Chunk must be between 1 and ${MAX_CHUNK_BYTES} bytes.`);if(sha(data)!==declared)throw appError('Chunk SHA-256 verification failed.',409,'RESTORE_CHUNK_HASH_MISMATCH');db=await pool.getConnection();await db.beginTransaction();const up=await uploadRow(userId,uploadId,true,db);if(up.status!=='UPLOADING')throw appError(`Upload is ${up.status} and no longer accepts chunks.`,409,'RESTORE_UPLOAD_STATE');if(index>=Number(up.total_chunks))throw appError('Chunk index exceeds the declared chunk count.');const [[existing]]=await db.query(`SELECT chunk_sha256,chunk_bytes FROM personal_finance_restore_upload_chunks WHERE upload_id=? AND chunk_index=? FOR UPDATE`,[uploadId,index]);if(existing){if(existing.chunk_sha256!==declared||Number(existing.chunk_bytes)!==data.length)throw appError('A different chunk already exists at this index.',409,'RESTORE_CHUNK_CONFLICT');await db.rollback();return res.json({upload_id:uploadId,chunk_index:index,already_received:true});}await db.query(`INSERT INTO personal_finance_restore_upload_chunks (upload_id,chunk_index,chunk_sha256,chunk_bytes,chunk_data) VALUES (?,?,?,?,?)`,[uploadId,index,declared,data]);await db.query(`UPDATE personal_finance_restore_uploads SET received_chunks=received_chunks+1,received_bytes=received_bytes+? WHERE id=?`,[data.length,uploadId]);await db.commit();return res.json({upload_id:uploadId,chunk_index:index,received:true});}catch(e){if(db)await db.rollback().catch(()=>{});return fail(res,e);}finally{if(db)db.release();}};

exports.status=async(req,res)=>{try{const userId=uid(req),up=await uploadRow(userId,String(req.params.id||''));const [rows]=await pool.query(`SELECT chunk_index,chunk_sha256,chunk_bytes FROM personal_finance_restore_upload_chunks WHERE upload_id=? ORDER BY chunk_index`,[up.id]);return res.json({upload_id:up.id,status:up.status,total_bytes:Number(up.total_bytes),received_bytes:Number(up.received_bytes),total_chunks:Number(up.total_chunks),received_chunks:Number(up.received_chunks),received_indexes:rows.map(r=>Number(r.chunk_index)),expires_at:up.expires_at,verified_at:up.verified_at});}catch(e){return fail(res,e);}};

async function assemble(userId,uploadId,requireVerified=false){const up=await uploadRow(userId,uploadId);if(requireVerified&&up.status!=='VERIFIED')throw appError('Restore upload must be verified first.',409,'RESTORE_UPLOAD_NOT_VERIFIED');if(!requireVerified&&up.status!=='UPLOADING'&&up.status!=='VERIFIED')throw appError(`Restore upload is ${up.status}.`,409,'RESTORE_UPLOAD_STATE');const [chunks]=await pool.query(`SELECT chunk_index,chunk_sha256,chunk_bytes,chunk_data FROM personal_finance_restore_upload_chunks WHERE upload_id=? ORDER BY chunk_index`,[uploadId]);if(chunks.length!==Number(up.total_chunks))throw appError(`Upload is incomplete: ${chunks.length}/${up.total_chunks} chunks received.`,409,'RESTORE_UPLOAD_INCOMPLETE');for(let i=0;i<chunks.length;i++){const c=chunks[i];if(Number(c.chunk_index)!==i)throw appError(`Chunk ${i} is missing.`,409,'RESTORE_UPLOAD_GAP');const b=Buffer.from(c.chunk_data);if(b.length!==Number(c.chunk_bytes)||sha(b)!==c.chunk_sha256)throw appError(`Stored chunk ${i} failed integrity verification.`,409,'RESTORE_CHUNK_HASH_MISMATCH');}const full=Buffer.concat(chunks.map(c=>Buffer.from(c.chunk_data)));if(full.length!==Number(up.total_bytes)||sha(full)!==up.transport_sha256)throw appError('Reassembled transport SHA-256 verification failed.',409,'RESTORE_TRANSPORT_HASH_MISMATCH');let pack;try{pack=JSON.parse(full.toString('utf8'));}catch{throw appError('Reassembled canonical package is not valid JSON.',409,'RESTORE_TRANSPORT_JSON_INVALID');}if(String(pack?.manifest?.package_sha256||'').toLowerCase()!==String(up.package_sha256).toLowerCase())throw appError('Reassembled package checksum does not match the declared package.',409,'RESTORE_PACKAGE_DECLARATION_MISMATCH');return {upload:up,backup:pack,bytes:full.length};}

exports.finalize=async(req,res)=>{try{const userId=uid(req),result=await assemble(userId,String(req.params.id||''),false);if(result.upload.status==='VERIFIED')return res.json({upload_id:result.upload.id,status:'VERIFIED',total_bytes:result.bytes,package_sha256:result.upload.package_sha256});await pool.query(`UPDATE personal_finance_restore_uploads SET status='VERIFIED',verified_at=UTC_TIMESTAMP() WHERE id=? AND user_id=? AND status='UPLOADING'`,[result.upload.id,userId]);return res.json({upload_id:result.upload.id,status:'VERIFIED',total_bytes:result.bytes,package_sha256:result.upload.package_sha256});}catch(e){return fail(res,e);}};

exports.cancel=async(req,res)=>{try{const userId=uid(req),id=String(req.params.id||'');const [r]=await pool.query(`DELETE FROM personal_finance_restore_uploads WHERE id=? AND user_id=?`,[id,userId]);if(!r.affectedRows)throw appError('Restore upload session was not found.',404,'RESTORE_UPLOAD_NOT_FOUND');return res.json({message:'Restore upload discarded.'});}catch(e){return fail(res,e);}};

exports.loadVerifiedPackage=async(userId,uploadId)=>{const result=await assemble(String(userId),String(uploadId),true);return result.backup;};
exports._test={MAX_TOTAL_BYTES,MAX_CHUNKS,MAX_CHUNK_BYTES,UPLOAD_MINUTES,sha};
