const pool=require('../config/db');
const canonical=require('./personalFinanceCanonicalBackupController')._test;
const restore=require('./personalFinanceCanonicalRestoreController')._test;
const transport=require('./personalFinanceRestoreTransportController');

const DATASETS=canonical.DATASETS;
const MAX_VERIFY_RECORDS=250000;

function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function appError(message,statusCode=400,code='POST_RESTORE_VERIFICATION_FAILED'){return Object.assign(new Error(message),{statusCode,code});}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Post-restore Personal Finance verification failed.',e);return res.status(s).json({message:s>=500?'Post-restore Personal Finance verification failed.':e.message,code:e.code||'POST_RESTORE_VERIFICATION_FAILED'});}
function recordId(row){return String(row.id??row.import_uid??row.connection_uid??'');}
function publicRow(row){return canonical.publicRow(row);}
function hash(v){return canonical.hash(v);}
function parse(v,fallback){if(v===null||v===undefined||v==='')return fallback;if(typeof v==='object')return v;try{return JSON.parse(v);}catch{return fallback;}}
function num(v){const n=Number(v);return Number.isFinite(n)?n:0;}

async function ownedRun(userId,runId){const [[run]]=await pool.query(`SELECT * FROM personal_finance_restore_runs WHERE id=? AND user_id=? LIMIT 1`,[runId,userId]);if(!run)throw appError('Restore run was not found.',404,'RESTORE_RUN_NOT_FOUND');return run;}
async function loadOwnerDatasets(userId){const out={};let total=0;for(const def of DATASETS){const [rows]=await pool.query(def.query,def.params(userId));total+=rows.length;if(total>MAX_VERIFY_RECORDS)throw appError(`Verification exceeds the ${MAX_VERIFY_RECORDS.toLocaleString()} record safety limit.`,413,'VERIFICATION_RECORD_LIMIT');out[def.name]=rows.map(r=>publicRow(r));}return out;}
function mapRows(rows){return new Map(rows.map(r=>[recordId(r),r]));}
function dependencyFindings(data){const findings=[],maps=Object.fromEntries(Object.entries(data).map(([name,rows])=>[name,mapRows(rows)]));const exists=(dataset,id)=>!id||Boolean(maps[dataset]?.has(String(id)));const check=(child,field,parent,required=true)=>{for(const row of data[child]||[]){const value=row[field];if((value===null||value===undefined||value==='')&&!required)continue;if(!exists(parent,value))findings.push({severity:'CRITICAL_MISMATCH',type:'MISSING_DEPENDENCY',dataset:child,record_id:recordId(row),message:`${child}.${field} references missing ${parent} record ${String(value||'blank')}.`});}};
  check('bank_transactions','bank_account_id','bank_accounts');
  check('statement_import_files','bank_account_id','bank_accounts');
  check('personal_money_entries','wallet_id','personal_money_wallets');
  check('personal_money_debt_payments','debt_id','personal_money_debts');
  check('personal_money_debt_payments','wallet_id','personal_money_wallets',false);
  check('personal_money_recurring_matches','recurring_item_id','personal_money_recurring_items');
  check('personal_money_recurring_matches','bank_transaction_id','bank_transactions');
  check('personal_money_goal_contributions','goal_id','personal_money_savings_goals');
  check('personal_net_worth_asset_values','asset_id','personal_net_worth_assets');
  check('personal_net_worth_liability_values','liability_id','personal_net_worth_liabilities');
  check('personal_asset_lifecycle_items','asset_id','personal_net_worth_assets',false);
  check('personal_asset_lifecycle_items','liability_id','personal_net_worth_liabilities',false);
  check('personal_asset_documents','asset_id','personal_net_worth_assets',false);
  check('personal_asset_documents','liability_id','personal_net_worth_liabilities',false);
  check('personal_financial_roadmap_milestones','roadmap_id','personal_financial_roadmaps');
  return findings;
}
function reviewFindings(data){const items=[];const txGroups=new Map();for(const r of data.bank_transactions||[]){const key=[r.bank_account_id,String(r.transaction_date||'').slice(0,10),r.currency,num(r.debit),num(r.credit),String(r.description||'').trim().toLowerCase()].join('|');txGroups.set(key,(txGroups.get(key)||0)+1);}const duplicateGroups=[...txGroups.values()].filter(n=>n>1).length;if(duplicateGroups)items.push({severity:'NEEDS_REVIEW',type:'POSSIBLE_DUPLICATES',count:duplicateGroups,message:'Possible duplicate bank-transaction groups remain after recovery. Similar legitimate transactions can look identical, so review before changing anything.'});
  const wallets=mapRows(data.personal_money_wallets||[]);let missingFx=0;for(const r of data.personal_money_entries||[]){const w=wallets.get(String(r.wallet_id));if(w&&r.currency&&w.currency&&String(r.currency)!==String(w.currency)&&!(num(r.fx_rate_to_wallet)>0))missingFx++;}if(missingFx)items.push({severity:'NEEDS_REVIEW',type:'MISSING_FX_CONTEXT',count:missingFx,message:'Cross-currency Personal Money entries were found without a positive recorded FX rate.'});
  let debtIssues=0;for(const d of data.personal_money_debts||[]){const p=num(d.principal_amount),o=num(d.outstanding_amount);if(o<-.0001||o>p+.0001)debtIssues++;}if(debtIssues)items.push({severity:'NEEDS_REVIEW',type:'DEBT_BALANCE_CONSISTENCY',count:debtIssues,message:'Debt records have outstanding balances outside the expected 0-to-principal range.'});
  let goalIssues=0;for(const g of data.personal_money_savings_goals||[]){const t=num(g.target_amount),c=num(g.current_amount);if(c<-.0001||c>t+.0001)goalIssues++;}if(goalIssues)items.push({severity:'NEEDS_REVIEW',type:'SAVINGS_GOAL_CONSISTENCY',count:goalIssues,message:'Savings goals have progress outside the expected 0-to-target range.'});
  const currencies=new Set(),invalid=[];for(const [dataset,rows] of Object.entries(data)){for(const r of rows){if(r.currency!==undefined&&r.currency!==null&&r.currency!==''){const c=String(r.currency).toUpperCase();if(/^[A-Z]{3}$/.test(c))currencies.add(c);else invalid.push({dataset,record_id:recordId(r),currency:String(r.currency)});}}}if(invalid.length)items.push({severity:'NEEDS_REVIEW',type:'INVALID_CURRENCY_CODE',count:invalid.length,message:'Some restored records contain currency values that are not three-letter currency codes.'});return {items,currencies:[...currencies].sort()};}

async function verifyRun(userId,runId){const run=await ownedRun(userId,runId);if(run.status==='ROLLED_BACK')return {run_id:runId,restore_status:run.status,overall_status:'NOT_APPLICABLE',read_only:true,message:'This restore was rolled back; post-restore fidelity verification is no longer applicable.'};if(run.status!=='SUCCEEDED')throw appError(`Verification is available only for a successful restore. Current status: ${run.status}.`,409,'RESTORE_NOT_SUCCESSFUL');const [targets]=await pool.query(`SELECT dataset_name,restore_action,expected_count,expected_records_json,target_sha256 FROM personal_finance_restore_verification_targets WHERE restore_run_id=? AND user_id=? ORDER BY id`,[runId,userId]);if(!targets.length)return {run_id:runId,restore_status:run.status,overall_status:'INITIALIZATION_REQUIRED',read_only:true,message:'Verification targets have not been initialized for this successful restore.'};const data=await loadOwnerDatasets(userId);const datasets=[];const critical=[];let verifiedRecords=0,missingRecords=0,mismatchedRecords=0;for(const target of targets){const expected=parse(target.expected_records_json,[]);if(hash(expected)!==target.target_sha256){critical.push({severity:'CRITICAL_MISMATCH',type:'TARGET_LEDGER_INTEGRITY',dataset:target.dataset_name,message:'Stored verification target checksum does not match.'});continue;}const current=mapRows(data[target.dataset_name]||[]);let matched=0,missing=0,mismatched=0;const examples=[];for(const e of expected){const row=current.get(String(e.id));if(!row){missing++;if(examples.length<8)examples.push({id:String(e.id),status:'MISSING'});continue;}const actual=hash(publicRow(row));if(actual!==e.sha){mismatched++;if(examples.length<8)examples.push({id:String(e.id),status:'HASH_MISMATCH',expected_sha256:String(e.sha).slice(0,12),actual_sha256:actual.slice(0,12)});}else matched++;}verifiedRecords+=matched;missingRecords+=missing;mismatchedRecords+=mismatched;const status=missing||mismatched?'CRITICAL_MISMATCH':'VERIFIED';if(status==='CRITICAL_MISMATCH')critical.push({severity:'CRITICAL_MISMATCH',type:'RESTORE_FIDELITY',dataset:target.dataset_name,count:missing+mismatched,message:`${missing} expected record(s) missing and ${mismatched} record(s) no longer match the approved backup.`});datasets.push({dataset:target.dataset_name,action:target.restore_action,status,expected:Number(target.expected_count),matched,missing,mismatched,current_owner_dataset_records:(data[target.dataset_name]||[]).length,examples});}
  critical.push(...dependencyFindings(data));const review=reviewFindings(data);const overall=critical.length?'CRITICAL_MISMATCH':review.items.length?'NEEDS_REVIEW':'VERIFIED';return {run_id:runId,restore_status:run.status,package_sha256:run.package_sha256,schema_version:run.schema_version,generated_at:new Date().toISOString(),read_only:true,finance_mutations:false,privacy:'Owner-only PERSONAL post-recovery verification. Voxel Veda company accounting is excluded.',currency_rule:'Currencies remain separate. This verification never creates a cross-currency total or inferred FX conversion.',overall_status:overall,summary:{datasets_verified:datasets.length,expected_records:datasets.reduce((n,d)=>n+d.expected,0),matched_records:verifiedRecords,missing_records:missingRecords,mismatched_records:mismatchedRecords,critical_findings:critical.length,review_findings:review.items.length},datasets,critical_mismatches:critical,needs_review:review.items,currencies:review.currencies,checks:{restore_fidelity:'Per-record SHA-256 against the approved canonical backup target set.',dependencies:'Owner-scoped parent/child references checked across canonical Personal Finance datasets.',duplicates:'Similarity-only bank transaction duplicate review signal.',debt_consistency:'Outstanding debt must remain between zero and principal.',savings_consistency:'Goal progress must remain between zero and target.',currency_separation:'Currency codes are reported separately; no currencies are combined.'}};}

exports.initialize=async(req,res)=>{try{const userId=uid(req),runId=String(req.params.id||''),run=await ownedRun(userId,runId);if(run.status!=='SUCCEEDED')throw appError('Verification targets can be initialized only after a successful restore.',409,'RESTORE_NOT_SUCCESSFUL');let backup;if(req.body?.upload_id)backup=await transport.loadVerifiedPackage(userId,String(req.body.upload_id));else backup=req.body?.backup;const validated=restore.validatePackage(backup,userId);if(validated.manifest.package_sha256!==run.package_sha256)throw appError('Verification backup does not match the successful restore package.',409,'VERIFICATION_PACKAGE_MISMATCH');const actions=parse(run.requested_actions_json,{});const [checkpoints]=await pool.query(`SELECT dataset_name,checkpoint_sha256,before_rows_json FROM personal_finance_restore_checkpoints WHERE restore_run_id=? AND user_id=?`,[runId,userId]);const cpMap=new Map(checkpoints.map(c=>[c.dataset_name,c]));const db=await pool.getConnection();try{await db.beginTransaction();await db.query(`DELETE FROM personal_finance_restore_verification_targets WHERE restore_run_id=? AND user_id=?`,[runId,userId]);for(const name of validated.payload.dependency_order){const action=String(actions[name]||'KEEP_CURRENT').toUpperCase();if(!['ADD','REPLACE'].includes(action))continue;const cp=cpMap.get(name);if(!cp)throw appError(`Missing rollback checkpoint for restored dataset ${name}.`,409,'VERIFICATION_CHECKPOINT_MISSING');const checkpoint=parse(cp.before_rows_json,null);if(!checkpoint||hash(checkpoint)!==cp.checkpoint_sha256)throw appError(`Rollback checkpoint integrity failed for ${name}.`,409,'VERIFICATION_CHECKPOINT_HASH_MISMATCH');const beforeIds=new Set((checkpoint.before_rows||[]).map(r=>String(recordId(r))));const records=validated.payload.datasets[name].records||[];const selected=records.filter(r=>action==='REPLACE'||!beforeIds.has(String(r.id))).map(r=>({id:String(r.id),sha:String(r.record_sha256)}));const targetSha=hash(selected);await db.query(`INSERT INTO personal_finance_restore_verification_targets (restore_run_id,user_id,dataset_name,restore_action,expected_count,expected_records_json,target_sha256) VALUES (?,?,?,?,?,?,?)`,[runId,userId,name,action,selected.length,JSON.stringify(selected),targetSha]);}await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}return res.json(await verifyRun(userId,runId));}catch(e){return fail(res,e);}};
exports.get=async(req,res)=>{try{return res.json(await verifyRun(uid(req),String(req.params.id||'')));}catch(e){return fail(res,e);}};
exports._test={verifyRun,dependencyFindings,reviewFindings,MAX_VERIFY_RECORDS};
