const crypto=require('node:crypto');
const pool=require('../config/db');

const REQUEST_TYPES=new Set(['EVIDENCE','REVIEW','RETEST','ASSURANCE']);
function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function appError(message,statusCode=400,code='RECOVERY_CONTROL_SCHEDULING_FAILED'){return Object.assign(new Error(message),{statusCode,code});}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Recovery control scheduling failed.',e);return res.status(s).json({message:s>=500?'Recovery control scheduling failed.':e.message,code:e.code||'RECOVERY_CONTROL_SCHEDULING_FAILED'});}
function parse(v,f){if(v===null||v===undefined||v==='')return f;if(typeof v==='object')return v;try{return JSON.parse(v);}catch{return f;}}
function arr(v){const x=parse(v,[]);return Array.isArray(x)?x:[];}
function text(v,max){return String(v??'').trim().slice(0,max);}
function daysUntil(v,now=Date.now()){if(!v)return null;return Math.ceil((new Date(v).getTime()-now)/86400000);}
function ageDays(v,now=Date.now()){if(!v)return 0;return Math.max(0,Math.floor((now-new Date(v).getTime())/86400000));}
function requestEscalation(r,now=Date.now()){if(r.status!=='OPEN'||!r.due_at)return 'L0';const d=-daysUntil(r.due_at,now);if(d>=14)return 'L3';if(d>=7)return 'L2';if(d>0)return 'L1';return 'L0';}
function classify(test,requests=[],now=Date.now()){const retest=daysUntil(test.next_retest_at,now),waiting=ageDays(test.executed_at,now),openReq=requests.filter(r=>r.status==='OPEN'),reqLevels=openReq.map(r=>requestEscalation(r,now));let state='ON_TRACK',level='L0',next='Continue monitoring against the defined test frequency.';
  if(test.result==='FAIL'){state='FAILED';level='L3';next='Investigate the failed control, preserve evidence and link remediation/CAPA before retesting.';}
  else if(test.result==='NEEDS_REVIEW'){state='NEEDS_REVIEW';level='L2';next='Resolve the documented uncertainty and obtain reviewer direction before assurance.';}
  else if(test.lifecycle_status==='EXECUTED'){state='AWAITING_REVIEWER';level=waiting>=7?'L2':waiting>=3?'L1':'L0';next='Obtain an independent reviewer check; execution alone cannot establish assurance.';}
  else if(test.lifecycle_status==='REVIEWED'&&test.result==='PASS'){state='ASSURANCE_SIGNOFF_PENDING';level='L1';next='Complete assurance sign-off only after all existing assurance gates remain satisfied.';}
  else if(retest!==null&&retest<0){state='OVERDUE';const o=Math.abs(retest);level=o>=14?'L3':o>=7?'L2':'L1';next='Perform the required retest; prior assurance is no longer current.';}
  else if(test.lifecycle_status==='ASSURED'&&retest!==null&&retest<=14){state='ASSURANCE_EXPIRING';level=retest<=7?'L1':'L0';next='Prepare the next evidence set and schedule the retest before assurance expires.';}
  else if(retest!==null&&retest<=30){state='DUE_SOON';level=retest<=7?'L1':'L0';next='Prepare the expected evidence and schedule the upcoming retest.';}
  else if(test.lifecycle_status==='DRAFT'){state='NOT_YET_EXECUTED';next='Collect the expected evidence and perform the first formal control test.';}
  const requestLevel=reqLevels.includes('L3')?'L3':reqLevels.includes('L2')?'L2':reqLevels.includes('L1')?'L1':'L0';const rank={L0:0,L1:1,L2:2,L3:3};if(rank[requestLevel]>rank[level])level=requestLevel;
  return {queue_state:state,escalation_level:level,days_to_retest:retest,review_wait_days:test.lifecycle_status==='EXECUTED'?waiting:null,next_action:next,open_request_count:openReq.length,open_request_overdue:openReq.filter(r=>r.due_at&&daysUntil(r.due_at,now)<0).length};
}
async function ownedTest(userId,id,db=pool){const [[r]]=await db.query(`SELECT * FROM personal_finance_recovery_control_tests WHERE id=? AND user_id=? LIMIT 1`,[id,userId]);if(!r)throw appError('Recovery control test was not found.',404,'CONTROL_TEST_NOT_FOUND');return r;}
async function ownedRequest(userId,id,db=pool){const [[r]]=await db.query(`SELECT * FROM personal_finance_recovery_control_evidence_requests WHERE id=? AND user_id=? LIMIT 1`,[id,userId]);if(!r)throw appError('Evidence request was not found.',404,'CONTROL_EVIDENCE_REQUEST_NOT_FOUND');return r;}
async function event(db,userId,id,type,payload){await db.query(`INSERT INTO personal_finance_recovery_control_evidence_request_events (request_id,user_id,event_type,event_json) VALUES (?,?,?,?)`,[id,userId,type,JSON.stringify(payload||{})]);}
function publicRequest(r){return {...r,required_items:arr(r.required_items_json),collected_refs:arr(r.collected_refs_json),escalation_level:requestEscalation(r)};}

exports.list=async(req,res)=>{try{const userId=uid(req);const [tests]=await pool.query(`SELECT * FROM personal_finance_recovery_control_tests WHERE user_id=? ORDER BY COALESCE(next_retest_at,'9999-12-31'),created_at DESC`,[userId]);const [requests]=await pool.query(`SELECT * FROM personal_finance_recovery_control_evidence_requests WHERE user_id=? ORDER BY FIELD(status,'OPEN','COMPLETED','CANCELLED'),COALESCE(due_at,'9999-12-31'),created_at DESC LIMIT 500`,[userId]);const requestRows=requests.map(publicRequest),rows=tests.map(t=>{const rs=requestRows.filter(r=>r.control_test_id===t.id),q=classify(t,rs);return {...t,test_procedure:arr(t.test_procedure_json),expected_evidence:arr(t.expected_evidence_json),evidence_refs:arr(t.evidence_refs_json),linked_capa_ids:arr(t.linked_capa_ids_json),...q,evidence_checklist:arr(t.expected_evidence_json).map((item,i)=>({item_no:i+1,item,status:'REQUIRED'})),open_requests:rs.filter(r=>r.status==='OPEN')};});const summary={tests:rows.length,due_soon:rows.filter(x=>x.queue_state==='DUE_SOON').length,overdue:rows.filter(x=>x.queue_state==='OVERDUE').length,failed:rows.filter(x=>x.queue_state==='FAILED').length,needs_review:rows.filter(x=>x.queue_state==='NEEDS_REVIEW').length,awaiting_reviewer:rows.filter(x=>x.queue_state==='AWAITING_REVIEWER').length,assurance_expiring:rows.filter(x=>x.queue_state==='ASSURANCE_EXPIRING').length,open_evidence_requests:requestRows.filter(x=>x.status==='OPEN').length,overdue_evidence_requests:requestRows.filter(x=>x.status==='OPEN'&&x.due_at&&daysUntil(x.due_at)<0).length};return res.json({scope:'PERSONAL_ONLY',finance_mutations:false,automatic_test_pass:false,automatic_assurance:false,summary,queue:rows,requests:requestRows,controls:{states:['DUE_SOON','OVERDUE','FAILED','NEEDS_REVIEW','AWAITING_REVIEWER','ASSURANCE_EXPIRING','ASSURANCE_SIGNOFF_PENDING','NOT_YET_EXECUTED','ON_TRACK'],escalation_levels:['L0','L1','L2','L3'],evidence_requests_are_governance_metadata_only:true,completion_does_not_change_control_test_result:true}});}catch(e){return fail(res,e);}};

exports.createRequest=async(req,res)=>{const userId=uid(req);let db;try{const testId=text(req.body?.control_test_id,36),type=String(req.body?.request_type||'EVIDENCE').toUpperCase(),note=text(req.body?.request_note,500);if(!REQUEST_TYPES.has(type))throw appError('Select a valid evidence request type.',400,'CONTROL_EVIDENCE_REQUEST_TYPE_INVALID');const test=await ownedTest(userId,testId),required=arr(req.body?.required_items).map(x=>text(x,500)).filter(Boolean);const items=required.length?required:arr(test.expected_evidence_json).map(x=>text(x,500)).filter(Boolean);const due=req.body?.due_at?new Date(req.body.due_at):new Date(Date.now()+7*86400000);if(Number.isNaN(due.getTime()))throw appError('Evidence request due date is invalid.',400,'CONTROL_EVIDENCE_REQUEST_DUE_INVALID');const [[dup]]=await pool.query(`SELECT id FROM personal_finance_recovery_control_evidence_requests WHERE user_id=? AND control_test_id=? AND request_type=? AND status='OPEN' LIMIT 1`,[userId,testId,type]);if(dup)throw appError('An open request of this type already exists for this control test.',409,'CONTROL_EVIDENCE_REQUEST_DUPLICATE');db=await pool.getConnection();await db.beginTransaction();const id=crypto.randomUUID();await db.query(`INSERT INTO personal_finance_recovery_control_evidence_requests (id,user_id,control_test_id,request_type,request_note,required_items_json,due_at) VALUES (?,?,?,?,?,?,?)`,[id,userId,testId,type,note||null,JSON.stringify(items),due]);await event(db,userId,id,'EVIDENCE_REQUEST_CREATED',{control_test_id:testId,request_type:type,due_at:due.toISOString(),required_item_count:items.length});await db.commit();return res.status(201).json({id,message:'Evidence request created.',due_at:due,automatic_test_pass:false});}catch(e){if(db)await db.rollback().catch(()=>{});return fail(res,e);}finally{if(db)db.release();}};

exports.completeRequest=async(req,res)=>{const userId=uid(req);let db;try{const id=text(req.body?.request_id,36),note=text(req.body?.completion_note,500),refs=arr(req.body?.collected_refs).map(x=>text(x,500)).filter(Boolean);db=await pool.getConnection();await db.beginTransaction();const r=await ownedRequest(userId,id,db);if(r.status!=='OPEN')throw appError('Only an open evidence request can be completed.',409,'CONTROL_EVIDENCE_REQUEST_NOT_OPEN');if(r.request_type==='EVIDENCE'&&refs.length===0)throw appError('Evidence requests require at least one collected evidence reference.',400,'CONTROL_EVIDENCE_REQUEST_REFS_REQUIRED');if(!note)throw appError('Completion note is required.',400,'CONTROL_EVIDENCE_REQUEST_COMPLETION_NOTE_REQUIRED');await db.query(`UPDATE personal_finance_recovery_control_evidence_requests SET status='COMPLETED',collected_refs_json=?,completion_note=?,completed_at=UTC_TIMESTAMP() WHERE id=? AND user_id=?`,[JSON.stringify(refs),note,id,userId]);await event(db,userId,id,'EVIDENCE_REQUEST_COMPLETED',{request_type:r.request_type,collected_ref_count:refs.length,completion_note:note,control_test_result_unchanged:true});await db.commit();return res.json({message:'Evidence request completed. Control-test result and assurance were not changed.',automatic_test_pass:false,automatic_assurance:false});}catch(e){if(db)await db.rollback().catch(()=>{});return fail(res,e);}finally{if(db)db.release();}};

exports.cancelRequest=async(req,res)=>{const userId=uid(req);let db;try{const id=text(req.body?.request_id,36),reason=text(req.body?.cancel_reason,500);if(!reason)throw appError('Cancellation reason is required.',400,'CONTROL_EVIDENCE_REQUEST_CANCEL_REASON_REQUIRED');db=await pool.getConnection();await db.beginTransaction();const r=await ownedRequest(userId,id,db);if(r.status!=='OPEN')throw appError('Only an open evidence request can be cancelled.',409,'CONTROL_EVIDENCE_REQUEST_NOT_OPEN');await db.query(`UPDATE personal_finance_recovery_control_evidence_requests SET status='CANCELLED',cancel_reason=?,cancelled_at=UTC_TIMESTAMP() WHERE id=? AND user_id=?`,[reason,id,userId]);await event(db,userId,id,'EVIDENCE_REQUEST_CANCELLED',{request_type:r.request_type,cancel_reason:reason});await db.commit();return res.json({message:'Evidence request cancelled.'});}catch(e){if(db)await db.rollback().catch(()=>{});return fail(res,e);}finally{if(db)db.release();}};

exports.history=async(req,res)=>{try{const userId=uid(req),id=text(req.query.request_id,36);await ownedRequest(userId,id);const [rows]=await pool.query(`SELECT id,event_type,event_json,created_at FROM personal_finance_recovery_control_evidence_request_events WHERE user_id=? AND request_id=? ORDER BY id DESC LIMIT 200`,[userId,id]);return res.json({request_id:id,events:rows.map(x=>({...x,event:parse(x.event_json,{})})),read_only:true});}catch(e){return fail(res,e);}};
exports._test={daysUntil,ageDays,requestEscalation,classify};
