const crypto=require('crypto');
const pool=require('../config/db');
const watch=require('./personalFinanceRecoveryIntegrityWatchController')._test;

const STATUSES=['OPEN','INVESTIGATING','ACTION_PLANNED','RESOLVED','CLOSED'];
const DECISIONS=['NO_ACTION','MONITOR','CREATE_FRESH_BACKUP','CERTIFY_CURRENT_STATE','PREPARE_NEW_RESTORE','CONSIDER_ROLLBACK','OTHER'];
function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function appError(message,statusCode=400,code='RECOVERY_INCIDENT_CASE_FAILED'){return Object.assign(new Error(message),{statusCode,code});}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Recovery incident case failed.',e);return res.status(s).json({message:s>=500?'Recovery incident case operation failed.':e.message,code:e.code||'RECOVERY_INCIDENT_CASE_FAILED'});}
function text(v,max){return String(v??'').trim().slice(0,max);}
function caseKey(runId,type){return crypto.createHash('sha256').update(`${runId}|${type}`).digest('hex');}
async function ownedCase(userId,id){const [[row]]=await pool.query(`SELECT * FROM personal_finance_recovery_incident_cases WHERE id=? AND user_id=? LIMIT 1`,[id,userId]);if(!row)throw appError('Incident case was not found.',404,'RECOVERY_CASE_NOT_FOUND');return row;}
async function event(db,userId,caseId,eventType,note,evidence){await db.query(`INSERT INTO personal_finance_recovery_incident_case_events (id,case_id,user_id,event_type,note,evidence_json) VALUES (?,?,?,?,?,?)`,[crypto.randomUUID(),caseId,userId,eventType,text(note,1200)||null,evidence?JSON.stringify(evidence):null]);}
async function getRun(userId,runId){const [[run]]=await pool.query(`SELECT id,status,package_sha256,schema_version,created_at,executed_at,rollback_expires_at FROM personal_finance_restore_runs WHERE id=? AND user_id=? LIMIT 1`,[runId,userId]);if(!run)throw appError('Restore run was not found.',404,'RESTORE_RUN_NOT_FOUND');return run;}
async function currentSignal(userId,runId,signalType){const run=await getRun(userId,runId);const monitored=await watch.monitorRun(userId,run);const signal=(monitored.signals||[]).find(s=>s.type===signalType);if(!signal||signal.level==='HEALTHY')throw appError('That recovery condition is not currently active.',409,'RECOVERY_SIGNAL_NOT_ACTIVE');return {monitored,signal};}
async function hydrate(userId,row){const [events]=await pool.query(`SELECT id,event_type,note,evidence_json,created_at FROM personal_finance_recovery_incident_case_events WHERE case_id=? AND user_id=? ORDER BY created_at ASC,id ASC`,[row.id,userId]);return {...row,events:events.map(e=>({...e,evidence:e.evidence_json?(typeof e.evidence_json==='object'?e.evidence_json:JSON.parse(e.evidence_json)):null,evidence_json:undefined}))};}
exports.list=async(req,res)=>{try{const userId=uid(req);const status=text(req.query.status,32);const params=[userId];let sql=`SELECT * FROM personal_finance_recovery_incident_cases WHERE user_id=?`;if(status){if(!STATUSES.includes(status))throw appError('Invalid case status.');sql+=` AND status=?`;params.push(status);}sql+=` ORDER BY FIELD(status,'OPEN','INVESTIGATING','ACTION_PLANNED','RESOLVED','CLOSED'),updated_at DESC LIMIT 100`;const [rows]=await pool.query(sql,params);const cases=[];for(const r of rows)cases.push(await hydrate(userId,r));return res.json({scope:'PERSONAL_ONLY',finance_mutations:false,cases});}catch(e){return fail(res,e);}};
exports.createFromSignal=async(req,res)=>{try{const userId=uid(req),runId=text(req.body?.run_id,36),signalType=text(req.body?.signal_type,64);if(!runId||!signalType)throw appError('run_id and signal_type are required.');const {monitored,signal}=await currentSignal(userId,runId,signalType);const key=caseKey(runId,signalType);const [[existing]]=await pool.query(`SELECT * FROM personal_finance_recovery_incident_cases WHERE user_id=? AND case_key=? LIMIT 1`,[userId,key]);if(existing)return res.json({created:false,case:await hydrate(userId,existing)});const id=crypto.randomUUID(),title=text(`${signal.level.replaceAll('_',' ')} · ${signalType.replaceAll('_',' ')}`,220);const db=await pool.getConnection();try{await db.beginTransaction();await db.query(`INSERT INTO personal_finance_recovery_incident_cases (id,user_id,restore_run_id,case_key,source_level,source_signal_type,title,status) VALUES (?,?,?,?,?,?,?,'OPEN')`,[id,userId,runId,key,signal.level,signalType,title]);await event(db,userId,id,'CASE_OPENED','Incident case opened from current recovery-watch evidence.',{signal,health:monitored.health,verification_status:monitored.verification?.overall_status,affected_datasets:monitored.remediation_plan?.affected_datasets||[],certificate_count:monitored.certificates?.count||0,rollback:monitored.rollback||null});await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}return res.status(201).json({created:true,case:await hydrate(userId,await ownedCase(userId,id))});}catch(e){return fail(res,e);}};
exports.addNote=async(req,res)=>{try{const userId=uid(req),id=text(req.params.id,36),note=text(req.body?.note,1200);if(!note)throw appError('A note is required.');await ownedCase(userId,id);await event(pool,userId,id,'NOTE_ADDED',note,{reference:text(req.body?.evidence_reference,220)||null});return res.json({case:await hydrate(userId,await ownedCase(userId,id))});}catch(e){return fail(res,e);}};
exports.update=async(req,res)=>{try{const userId=uid(req),id=text(req.params.id,36),row=await ownedCase(userId,id);const status=text(req.body?.status||row.status,32).toUpperCase(),decision=text(req.body?.remediation_decision||row.remediation_decision,64).toUpperCase()||null;if(!STATUSES.includes(status))throw appError('Invalid case status.');if(decision&&!DECISIONS.includes(decision))throw appError('Invalid remediation decision.');if(status==='CLOSED')throw appError('Use the protected close action to close an incident case.',409,'USE_CASE_CLOSE');await pool.query(`UPDATE personal_finance_recovery_incident_cases SET status=?,remediation_decision=?,resolved_at=CASE WHEN ?='RESOLVED' THEN COALESCE(resolved_at,NOW()) ELSE resolved_at END WHERE id=? AND user_id=?`,[status,decision,status,id,userId]);await event(pool,userId,id,'CASE_UPDATED',text(req.body?.note,1200)||'Case status or remediation decision updated.',{previous_status:row.status,status,remediation_decision:decision});return res.json({case:await hydrate(userId,await ownedCase(userId,id))});}catch(e){return fail(res,e);}};
exports.verifyResolution=async(req,res)=>{try{const userId=uid(req),id=text(req.params.id,36),row=await ownedCase(userId,id);const run=await getRun(userId,row.restore_run_id);const monitored=await watch.monitorRun(userId,run);const active=(monitored.signals||[]).find(s=>s.type===row.source_signal_type&&s.level!=='HEALTHY');const verificationStatus=active?'STILL_ACTIVE':'CLEARED';await pool.query(`UPDATE personal_finance_recovery_incident_cases SET resolution_verification_status=?,status=CASE WHEN ?='CLEARED' AND status='ACTION_PLANNED' THEN 'RESOLVED' ELSE status END,resolved_at=CASE WHEN ?='CLEARED' THEN COALESCE(resolved_at,NOW()) ELSE resolved_at END WHERE id=? AND user_id=?`,[verificationStatus,verificationStatus,verificationStatus,id,userId]);await event(pool,userId,id,'RESOLUTION_VERIFIED',active?'Original recovery condition is still active.':'Original recovery condition is no longer active in the current watch.',{verification_status:verificationStatus,current_health:monitored.health,current_verification:monitored.verification?.overall_status});return res.json({case:await hydrate(userId,await ownedCase(userId,id)),current_watch:{health:monitored.health,signal_active:Boolean(active)}});}catch(e){return fail(res,e);}};
exports.linkCertificate=async(req,res)=>{try{const userId=uid(req),id=text(req.params.id,36),certificateId=text(req.body?.certificate_id,36);if(!certificateId)throw appError('certificate_id is required.');const row=await ownedCase(userId,id);const [[cert]]=await pool.query(`SELECT id,restore_run_id,verification_status,certificate_sha256,generated_at FROM personal_finance_recovery_certificates WHERE id=? AND user_id=? LIMIT 1`,[certificateId,userId]);if(!cert||String(cert.restore_run_id)!==String(row.restore_run_id))throw appError('Certificate must belong to this owner and restore run.',409,'CERTIFICATE_CASE_MISMATCH');await pool.query(`UPDATE personal_finance_recovery_incident_cases SET linked_certificate_id=? WHERE id=? AND user_id=?`,[certificateId,id,userId]);await event(pool,userId,id,'CERTIFICATE_LINKED','Post-resolution recovery certificate linked to the case.',{certificate_id:cert.id,verification_status:cert.verification_status,certificate_sha256:String(cert.certificate_sha256).slice(0,16)});return res.json({case:await hydrate(userId,await ownedCase(userId,id))});}catch(e){return fail(res,e);}};
exports.close=async(req,res)=>{try{const userId=uid(req),id=text(req.params.id,36),reason=text(req.body?.closure_reason,500),row=await ownedCase(userId,id);if(!reason)throw appError('A closure reason is required.');if(row.resolution_verification_status!=='CLEARED')throw appError('Run resolution verification and clear the original recovery condition before closing the case.',409,'CASE_NOT_VERIFIED_RESOLVED');if(!row.linked_certificate_id)throw appError('Link a post-resolution recovery certificate before closing the case.',409,'CASE_CERTIFICATE_REQUIRED');await pool.query(`UPDATE personal_finance_recovery_incident_cases SET status='CLOSED',closure_reason=?,closed_at=NOW(),resolved_at=COALESCE(resolved_at,NOW()) WHERE id=? AND user_id=?`,[reason,id,userId]);await event(pool,userId,id,'CASE_CLOSED',reason,{linked_certificate_id:row.linked_certificate_id,approval_history_note:'Closure changes case metadata only; no finance records were changed.'});return res.json({case:await hydrate(userId,await ownedCase(userId,id))});}catch(e){return fail(res,e);}};
exports._test={caseKey,STATUSES,DECISIONS};
