const pool=require('../config/db');

function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Personal finance command search failed',e);return res.status(s).json({message:s>=500?'Failed to search Personal Money.':e.message});}
function clean(v,max=120){return String(v||'').trim().slice(0,max);}
function ymd(d){return d.toISOString().slice(0,10);}
function addMonths(date,n){const d=new Date(`${date}T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+n);return ymd(d);}
function startOfMonth(date){return `${String(date).slice(0,7)}-01`;}
function parseRange(q,today){const lower=q.toLowerCase();if(/this month/.test(lower))return {from:startOfMonth(today),to:today,label:'this month'};if(/last month/.test(lower)){const current=startOfMonth(today),prev=addMonths(current,-1);const end=new Date(`${current}T00:00:00Z`);end.setUTCDate(end.getUTCDate()-1);return {from:prev,to:ymd(end),label:'last month'};}const m=lower.match(/(?:last|past)\s+(\d{1,2})\s+months?/);if(m){const n=Math.min(24,Math.max(1,Number(m[1])));return {from:addMonths(today,-n),to:today,label:`last ${n} months`};}if(/3 months|three months/.test(lower))return {from:addMonths(today,-3),to:today,label:'last 3 months'};if(/6 months|six months/.test(lower))return {from:addMonths(today,-6),to:today,label:'last 6 months'};if(/this year/.test(lower))return {from:`${today.slice(0,4)}-01-01`,to:today,label:'this year'};return {from:addMonths(today,-1),to:today,label:'last month to today'};}
function amountThreshold(q){const m=q.match(/(?:over|above|more than|greater than)\s*\$?\s*([0-9]+(?:\.[0-9]{1,2})?)/i);return m?Number(m[1]):null;}
function keyword(q){let s=q.toLowerCase().replace(/[?$,.]/g,' ');s=s.replace(/\b(show|find|tell|me|all|my|how|much|did|i|spend|spent|spending|on|payments?|transactions?|bills?|subscriptions?|this|last|past|month|months|year|over|above|more|than|greater|duplicate|duplicates|looking|money|lent|borrowed|people|why|is|higher|lower|food|category|in|the|of|for)\b/g,' ').replace(/\b\d+\b/g,' ').replace(/\s+/g,' ').trim();return s.slice(0,60);}
function foodTerms(q){return /\b(food|grocer|groceries|restaurant|dining|takeaway|cafe|coffee)\b/i.test(q);}
function intent(q){const l=q.toLowerCase();if(/\bduplicate/.test(l))return 'DUPLICATES';if(/\b(lent|loaned).*\b(money|people)|money\s+i\s+lent/.test(l))return 'LENT';if(/\bborrowed|money\s+i\s+owe/.test(l))return 'BORROWED';if(/\bwhy\b.*\bspend|spending.*\b(higher|lower)|why.*spending/.test(l))return 'SPENDING_EXPLANATION';if(/\bbill|subscription/.test(l))return 'BILLS';return 'TRANSACTIONS';}
function currencyGroups(rows,amountField){const out={};rows.forEach(r=>{const c=String(r.currency||'AUD').toUpperCase();out[c]=(out[c]||0)+Number(r[amountField]||0);});return Object.fromEntries(Object.entries(out).map(([c,v])=>[c,Math.round(v*100)/100]));}

async function txSearch(userId,q,range){const key=keyword(q),food=foodTerms(q),params=[userId,range.from,range.to];let extra='';if(key){extra=' AND (LOWER(COALESCE(bt.merchant_name,\'\')) LIKE ? OR LOWER(COALESCE(bt.description,\'\')) LIKE ? OR LOWER(COALESCE(bt.reference,\'\')) LIKE ?)';params.push(`%${key}%`,`%${key}%`,`%${key}%`);}else if(food){extra=` AND (LOWER(CONCAT_WS(' ',bt.merchant_name,bt.description)) REGEXP 'food|grocery|grocer|restaurant|cafe|coffee|bakery|pizza|burger|takeaway|ubereats|doordash|menulog')`;}
const [rows]=await pool.query(`SELECT bt.id,bt.transaction_date,bt.description,bt.merchant_name,bt.debit,bt.credit,bt.currency,ba.nickname account_name FROM bank_transactions bt JOIN bank_accounts ba ON ba.id=bt.bank_account_id WHERE ba.created_by=? AND ba.ownership_scope='PERSONAL' AND bt.ownership_scope='PERSONAL' AND bt.is_internal_transfer=0 AND bt.transaction_date BETWEEN ? AND ?${extra} ORDER BY bt.transaction_date DESC,bt.id DESC LIMIT 100`,params);const spending=currencyGroups(rows.filter(r=>Number(r.debit)>0),'debit'),income=currencyGroups(rows.filter(r=>Number(r.credit)>0),'credit');return {type:'TRANSACTIONS',summary:{spending,income,count:rows.length},rows:rows.slice(0,30).map(r=>({id:r.id,date:String(r.transaction_date).slice(0,10),description:r.merchant_name||r.description||'Transaction',amount:Number(r.debit||r.credit||0),direction:Number(r.debit)>0?'OUT':'IN',currency:r.currency,account_name:r.account_name})),filters:{keyword:key|| (food?'food-related merchants':null),period:range.label},target:'personalMoneyPanel'};}
async function bills(userId,q){const min=amountThreshold(q);const params=[userId];let extra='';if(min!==null){extra=' AND amount>?';params.push(min);}const [rows]=await pool.query(`SELECT id,name,item_type,amount,currency,frequency,next_due_date,counterparty FROM personal_money_recurring_items WHERE user_id=? AND active=1 AND item_type<>'INCOME'${extra} ORDER BY next_due_date,amount DESC LIMIT 50`,params);return {type:'BILLS',summary:{count:rows.length,totals:currencyGroups(rows,'amount')},rows:rows.map(r=>({...r,amount:Number(r.amount),date:String(r.next_due_date).slice(0,10)})),filters:{minimum_amount:min},target:'personalMoneyAttentionPanel'};}
async function debts(userId,direction){const [rows]=await pool.query(`SELECT id,direction,counterparty,original_amount,outstanding_amount,currency,due_date,status FROM personal_money_debts WHERE user_id=? AND direction=? AND status<>'SETTLED' ORDER BY COALESCE(due_date,'9999-12-31'),outstanding_amount DESC`,[userId,direction]);return {type:direction,summary:{count:rows.length,outstanding:currencyGroups(rows,'outstanding_amount')},rows:rows.map(r=>({...r,original_amount:Number(r.original_amount||0),outstanding_amount:Number(r.outstanding_amount||0),due_date:r.due_date?String(r.due_date).slice(0,10):null})),filters:{direction},target:'personalMoneyPanel'};}
async function duplicates(userId,range){const [rows]=await pool.query(`SELECT a.id,a.transaction_date,a.description,a.merchant_name,a.debit,a.currency,ba.nickname account_name,b.id possible_duplicate_id,b.transaction_date possible_duplicate_date FROM bank_transactions a JOIN bank_accounts ba ON ba.id=a.bank_account_id JOIN bank_transactions b ON b.bank_account_id=a.bank_account_id AND b.id<a.id AND b.debit=a.debit AND b.credit=a.credit AND ABS(DATEDIFF(a.transaction_date,b.transaction_date))<=3 AND LOWER(COALESCE(a.description,''))=LOWER(COALESCE(b.description,'')) WHERE ba.created_by=? AND ba.ownership_scope='PERSONAL' AND a.ownership_scope='PERSONAL' AND b.ownership_scope='PERSONAL' AND a.is_internal_transfer=0 AND b.is_internal_transfer=0 AND a.transaction_date BETWEEN ? AND ? ORDER BY a.transaction_date DESC LIMIT 50`,[userId,range.from,range.to]);return {type:'DUPLICATES',summary:{count:rows.length},rows:rows.map(r=>({id:r.id,date:String(r.transaction_date).slice(0,10),description:r.merchant_name||r.description||'Transaction',amount:Number(r.debit||0),currency:r.currency,account_name:r.account_name,possible_duplicate_id:r.possible_duplicate_id,possible_duplicate_date:String(r.possible_duplicate_date).slice(0,10)})),filters:{period:range.label,rule:'same account + same amount + same description within 3 days'},target:'personalMoneyReviewPanel'};}
async function spendingExplanation(userId){const [rows]=await pool.query(`SELECT DATE_FORMAT(bt.transaction_date,'%Y-%m') month_key,bt.currency,COALESCE(SUM(bt.debit),0) spent FROM bank_transactions bt JOIN bank_accounts ba ON ba.id=bt.bank_account_id WHERE ba.created_by=? AND ba.ownership_scope='PERSONAL' AND bt.ownership_scope='PERSONAL' AND bt.is_internal_transfer=0 AND bt.debit>0 AND bt.transaction_date>=DATE_FORMAT(DATE_SUB(CURRENT_DATE,INTERVAL 1 MONTH),'%Y-%m-01') GROUP BY month_key,bt.currency ORDER BY month_key`,[userId]);const by={};rows.forEach(r=>{const c=r.currency;by[c]=by[c]||{};by[c][r.month_key]=Number(r.spent||0);});const result=Object.entries(by).map(([currency,months])=>{const keys=Object.keys(months).sort(),previous=months[keys[0]]||0,current=months[keys[keys.length-1]]||0;return {currency,current,previous,change_amount:Math.round((current-previous)*100)/100,change_percent:previous>0?Math.round(((current-previous)/previous)*1000)/10:null};});return {type:'SPENDING_EXPLANATION',summary:{by_currency:result},rows:[],filters:{comparison:'current month so far vs previous calendar month'},note:'Current month may be incomplete, so this is a pace/context comparison rather than a like-for-like full-month conclusion.',target:'personalMoneyHealthPanel'};}

exports.search=async(req,res)=>{try{const userId=uid(req),q=clean(req.query.q,180);if(q.length<2)throw Object.assign(new Error('Type at least two characters or choose an example question.'),{statusCode:400});const today=/^\d{4}-\d{2}-\d{2}$/.test(String(req.query.date||''))?String(req.query.date):new Date().toISOString().slice(0,10);const range=parseRange(q,today),kind=intent(q);let result;if(kind==='BILLS')result=await bills(userId,q);else if(kind==='LENT')result=await debts(userId,'LENT');else if(kind==='BORROWED')result=await debts(userId,'BORROWED');else if(kind==='DUPLICATES')result=await duplicates(userId,range);else if(kind==='SPENDING_EXPLANATION')result=await spendingExplanation(userId);else result=await txSearch(userId,q,range);return res.json({query:q,interpreted_as:kind,privacy:'Search uses only the signed-in user’s PERSONAL finance data. Business and mixed accounts are excluded.',currency_rule:'Currencies are never added together.',read_only:true,...result});}catch(e){return fail(res,e);}};