const crypto=require('node:crypto');
const pool=require('../config/db');
const reporting=require('./personalFinanceRecoveryGovernanceReportingController')._test;

const CATEGORIES=['CERTIFICATE_INTEGRITY','DEPENDENCY_INTEGRITY','ROLLBACK_PROTECTION','RESTORE_FIDELITY','VERIFICATION_INITIALIZATION','OTHER_EVIDENCE_CONDITION'];
const ACTION_TYPES=['CORRECTIVE','PREVENTIVE','BOTH'];
const STATUSES=['OPEN','IN_PROGRESS','IMPLEMENTED','EFFECTIVENESS_REVIEW','CLOSED'];
function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function err(message,statusCode=400,code='RECOVERY_CAPA_FAILED'){return Object.assign(new Error(message),{statusCode,code});}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Recovery CAPA failed.',e);return res.status(s).json({message:s>=500?'Recovery CAPA failed.':e.message,code:e.code||'RECOVERY_CAPA_FAILED'});}
function text(v,max){return String(v??'').trim().slice(0,max);}
function parse(v,fallback){if(v===null||v===undefined||v==='')return fallback;if(typeof v==='object')return v;try{return JSON.parse(v);}catch{return fallback;}}
function ids(v){return [...new Set((Array.isArray(v)?v:[]).map(x=>text(x,64)).filter(Boolean))].slice(0,50);}
function strings(v,maxItems=50,maxLen=300){return (Array.isArray(v)?v:[]).map(x=>text(x,maxLen)).filter(Boolean).slice(0,maxItems);}
function category(type){return reporting.category(type);}
function dueState(row,now=new Date()){if(row.status==='CLOSED'||!row.due_at)return {overdue:false,days_overdue:0,escalation:'L0'};const ms=now-new Date(row.due_at),days=Math.max(0,Math.floor(ms/86400000));if(ms<=0)return {overdue:false,days_overdue:0,escalation:'L0'};return {overdue:true,days_overdue:days,escalation:days>=14?'L3':days>=7?'L2':'L1'};}
function view(row){return {...row,source_case_ids:ids(parse(row.source_case_ids_json,[])),action_plan:strings(parse(row.action_plan_json,[])),evidence_refs:strings(parse(row.evidence_refs_json,[])),...dueState(row)};}
async function owned(userId,id){const [[row]]=await pool.query(`SELECT * FROM personal_finance_recovery_capa WHERE id=? AND user_id=? LIMIT 1`,[id,userId]);if(!row)throw err('CAPA item was not found.',404,'RECOVERY_CAPA_NOT_FOUND');return row;}
async function event(db,userId,id,type,data){await db.query(`INSERT INTO personal_finance_recovery_capa_events (capa_id,user_id,event_type,event_json) VALUES (?,?,?,?)`,[id,userId,type,JSON.stringify(data||{})]);}
async function validateCases(userId,caseIds){if(!caseIds.length)return [];const placeholders=caseIds.map(()=>'?').join(',');const [rows]=await pool.query(`SELECT id,status,source_signal_type,opened_at,closed_at FROM personal_finance_recovery_incident_cases WHERE user_id=? AND id IN (${placeholders})`,[userId,...caseIds]);if(rows.length!==caseIds.length)throw err('One or more linked incident cases do not belong to the current owner.',409,'RECOVERY_CAPA_CASE_SCOPE_MISMATCH');return rows;}
async function validateReview(userId,reviewId,requireAttested=false){if(!reviewId)return null;const [[row]]=await pool.query(`SELECT id,status,review_month,attested_at FROM personal_finance_recovery_management_reviews WHERE id=? AND user_id=? LIMIT 1`,[reviewId,userId]);if(!row)throw err('Linked management review was not found.',404,'RECOVERY_CAPA_REVIEW_NOT_FOUND');if(requireAttested&&row.status!=='ATTESTED')throw err('CAPA closure requires an attested management review.',409,'RECOVERY_CAPA_ATTESTED_REVIEW_REQUIRED');return row;}
async function currentCategoryRecurrence(userId,sourceCategory,since){const [rows]=await pool.query(`SELECT id,status,source_signal_type,opened_at FROM personal_finance_recovery_incident_cases WHERE user_id=? AND opened_at>=?`,[userId,since]);return rows.filter(r=>category(r.source_signal_type)===sourceCategory&&r.status!=='CLOSED');}

exports.list=async(req,res)=>{try{const userId=uid(req);const [rows]=await pool.query(`SELECT * FROM personal_finance_recovery_capa WHERE user_id=? ORDER BY CASE status WHEN 'CLOSED' THEN 1 ELSE 0 END, due_at IS NULL, due_at ASC, created_at DESC LIMIT 200`,[userId]);const items=rows.map(view),summary={total:items.length,open:items.filter(x=>x.status!=='CLOSED').length,overdue:items.filter(x=>x.overdue).length,effectiveness_review:items.filter(x=>x.status==='EFFECTIVENESS_REVIEW').length,not_effective:items.filter(x=>x.effectiveness_result==='NOT_EFFECTIVE').length,closed_effective:items.filter(x=>x.status==='CLOSED'&&x.effectiveness_result==='EFFECTIVE').length};return res.json({scope:'PERSONAL_ONLY',finance_mutations:false,capa_metadata_writes_only:true,summary,items});}catch(e){return fail(res,e);}};
exports.create=async(req,res)=>{try{const userId=uid(req),sourceCategory=text(req.body?.source_category,64).toUpperCase(),title=text(req.body?.title,180),description=text(req.body?.description,1000),actionType=text(req.body?.action_type||'BOTH',16).toUpperCase(),owner=text(req.body?.owner_label,120)||null,caseIds=ids(req.body?.source_case_ids),reviewId=text(req.body?.source_review_id,36)||null,plan=strings(req.body?.action_plan),evidence=strings(req.body?.evidence_refs),due=req.body?.due_at?new Date(req.body.due_at):null;if(!CATEGORIES.includes(sourceCategory))throw err('Choose a valid evidence-backed recovery condition category.');if(!title)throw err('CAPA title is required.');if(!ACTION_TYPES.includes(actionType))throw err('Choose CORRECTIVE, PREVENTIVE or BOTH.');if(due&&Number.isNaN(due.getTime()))throw err('Due date is invalid.');const cases=await validateCases(userId,caseIds);for(const c of cases)if(category(c.source_signal_type)!==sourceCategory)throw err('Linked incident evidence does not match the selected CAPA category.',409,'RECOVERY_CAPA_EVIDENCE_CATEGORY_MISMATCH');await validateReview(userId,reviewId,false);const key=text(req.body?.capa_key,191)||`${sourceCategory}:${title.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,80)}`,id=crypto.randomUUID(),db=await pool.getConnection();try{await db.beginTransaction();await db.query(`INSERT INTO personal_finance_recovery_capa (id,user_id,capa_key,source_category,title,description,action_type,status,owner_label,due_at,source_case_ids_json,source_review_id,action_plan_json,evidence_refs_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[id,userId,key,sourceCategory,title,description||null,actionType,'OPEN',owner,due||null,JSON.stringify(caseIds),reviewId,JSON.stringify(plan),JSON.stringify(evidence)]);await event(db,userId,id,'CAPA_OPENED',{source_category:sourceCategory,source_case_ids:caseIds,source_review_id:reviewId});await db.commit();}catch(e){await db.rollback().catch(()=>{});if(e?.code==='ER_DUP_ENTRY')throw err('An active CAPA with this evidence key already exists.',409,'RECOVERY_CAPA_DUPLICATE');throw e;}finally{db.release();}return res.status(201).json({item:view(await owned(userId,id))});}catch(e){return fail(res,e);}};
exports.update=async(req,res)=>{try{const userId=uid(req),id=text(req.body?.capa_id,36),row=await owned(userId,id);if(row.status==='CLOSED')throw err('Closed CAPA records are immutable. Create a new CAPA for new recurrence.',409,'RECOVERY_CAPA_IMMUTABLE');const status=text(req.body?.status||row.status,32).toUpperCase();if(!STATUSES.includes(status)||status==='CLOSED')throw err('Use the governed closure action to close a CAPA.');const owner=text(req.body?.owner_label??row.owner_label,120)||null,description=text(req.body?.description??row.description,1000)||null,plan=req.body?.action_plan!==undefined?strings(req.body.action_plan):strings(parse(row.action_plan_json,[])),evidence=req.body?.evidence_refs!==undefined?strings(req.body.evidence_refs):strings(parse(row.evidence_refs_json,[])),reviewId=req.body?.source_review_id!==undefined?(text(req.body.source_review_id,36)||null):row.source_review_id,due=req.body?.due_at!==undefined?(req.body.due_at?new Date(req.body.due_at):null):row.due_at;if(due&&Number.isNaN(new Date(due).getTime()))throw err('Due date is invalid.');await validateReview(userId,reviewId,false);let implemented=row.implemented_at;if(status==='IMPLEMENTED'&&!implemented){if(!plan.length)throw err('Record at least one action-plan item before marking CAPA implemented.',409,'RECOVERY_CAPA_PLAN_REQUIRED');implemented=new Date();}const db=await pool.getConnection();try{await db.beginTransaction();await db.query(`UPDATE personal_finance_recovery_capa SET status=?,owner_label=?,description=?,due_at=?,source_review_id=?,action_plan_json=?,evidence_refs_json=?,implemented_at=? WHERE id=? AND user_id=?`,[status,owner,description,due||null,reviewId,JSON.stringify(plan),JSON.stringify(evidence),implemented,id,userId]);await event(db,userId,id,'CAPA_UPDATED',{status,owner_label:owner,due_at:due||null,source_review_id:reviewId});await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}return res.json({item:view(await owned(userId,id))});}catch(e){return fail(res,e);}};
exports.effectiveness=async(req,res)=>{try{const userId=uid(req),id=text(req.body?.capa_id,36),row=await owned(userId,id);if(!['IMPLEMENTED','EFFECTIVENESS_REVIEW'].includes(row.status))throw err('Mark CAPA implemented before checking effectiveness.',409,'RECOVERY_CAPA_IMPLEMENTATION_REQUIRED');const caseIds=ids(parse(row.source_case_ids_json,[])),linked=await validateCases(userId,caseIds),allLinkedClosed=linked.length>0&&linked.every(c=>c.status==='CLOSED'),since=row.implemented_at||row.updated_at||row.created_at,recurrence=await currentCategoryRecurrence(userId,row.source_category,since);let result='INSUFFICIENT_EVIDENCE';if(linked.length){result=allLinkedClosed&&recurrence.length===0?'EFFECTIVE':'NOT_EFFECTIVE';}const db=await pool.getConnection();try{await db.beginTransaction();await db.query(`UPDATE personal_finance_recovery_capa SET status='EFFECTIVENESS_REVIEW',effectiveness_result=?,effectiveness_checked_at=UTC_TIMESTAMP() WHERE id=? AND user_id=?`,[result,id,userId]);await event(db,userId,id,'EFFECTIVENESS_CHECKED',{result,linked_cases:linked.length,all_linked_cases_closed:allLinkedClosed,post_implementation_open_recurrence:recurrence.length});await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}return res.json({item:view(await owned(userId,id)),effectiveness_evidence:{result,linked_cases:linked.length,all_linked_cases_closed:allLinkedClosed,post_implementation_open_recurrence:recurrence.length,observed_only:true,no_inferred_root_cause:true}});}catch(e){return fail(res,e);}};
exports.close=async(req,res)=>{try{const userId=uid(req),id=text(req.body?.capa_id,36),row=await owned(userId,id),reason=text(req.body?.closure_reason,500);if(row.status==='CLOSED')return res.json({item:view(row),already_closed:true});if(row.effectiveness_result!=='EFFECTIVE')throw err('CAPA can close only after an EFFECTIVE effectiveness check.',409,'RECOVERY_CAPA_EFFECTIVENESS_REQUIRED');const evidence=strings(parse(row.evidence_refs_json,[]));if(!evidence.length)throw err('Add at least one supporting evidence reference before CAPA closure.',409,'RECOVERY_CAPA_EVIDENCE_REQUIRED');if(!row.source_review_id)throw err('Link an attested management review before CAPA closure.',409,'RECOVERY_CAPA_REVIEW_REQUIRED');await validateReview(userId,row.source_review_id,true);if(!reason)throw err('Closure reason is required.');const db=await pool.getConnection();try{await db.beginTransaction();await db.query(`UPDATE personal_finance_recovery_capa SET status='CLOSED',closed_at=UTC_TIMESTAMP(),closure_reason=? WHERE id=? AND user_id=?`,[reason,id,userId]);await event(db,userId,id,'CAPA_CLOSED',{closure_reason:reason,effectiveness_result:'EFFECTIVE',source_review_id:row.source_review_id});await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}return res.json({item:view(await owned(userId,id))});}catch(e){return fail(res,e);}};
exports.history=async(req,res)=>{try{const userId=uid(req),id=text(req.params.id||req.query.capa_id,36);await owned(userId,id);const [rows]=await pool.query(`SELECT id,event_type,event_json,created_at FROM personal_finance_recovery_capa_events WHERE capa_id=? AND user_id=? ORDER BY id`,[id,userId]);return res.json({capa_id:id,events:rows.map(r=>({...r,event:parse(r.event_json,{})})),read_only:true});}catch(e){return fail(res,e);}};
exports._test={CATEGORIES,ACTION_TYPES,STATUSES,category,dueState};
