const crypto=require('node:crypto');
const pool=require('../config/db');
const canonical=require('./personalFinanceCanonicalBackupController')._test;
const reporting=require('./personalFinanceRecoveryGovernanceReportingController')._test;

const CHECKS=['REPORT_REVIEWED','SLA_REVIEWED','RECURRENCE_REVIEWED','OPEN_RISKS_REVIEWED','DECISION_RECORDED'];
const STATUSES=['DRAFT','ACKNOWLEDGED','ATTESTED'];
function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function err(message,statusCode=400,code='RECOVERY_MANAGEMENT_REVIEW_FAILED'){return Object.assign(new Error(message),{statusCode,code});}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Recovery management review failed.',e);return res.status(s).json({message:s>=500?'Recovery management review failed.':e.message,code:e.code||'RECOVERY_MANAGEMENT_REVIEW_FAILED'});}
function text(v,max){return String(v??'').trim().slice(0,max);}
function parse(v,fallback){if(v===null||v===undefined||v==='')return fallback;if(typeof v==='object')return v;try{return JSON.parse(v);}catch{return fallback;}}
function reviewMonth(d=new Date()){return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;}
function checklist(v){const raw=parse(v,{}),out={};for(const k of CHECKS)out[k]=Boolean(raw?.[k]);return out;}
function carry(v){if(!Array.isArray(v))return [];return v.map(x=>text(x,220)).filter(Boolean).slice(0,20);}
function hashCore(row){return canonical.hash({review_month:row.review_month,status:row.status,reviewer_label:row.reviewer_label||null,management_decision:row.management_decision||null,evidence_checklist:checklist(row.evidence_checklist_json),carry_forward:carry(parse(row.carry_forward_json,[])),snapshot_sha256:row.snapshot_sha256,previous_review_sha256:row.previous_review_sha256||null,acknowledged_at:row.acknowledged_at||null,attested_at:row.attested_at||null});}
function view(row){const snapshot=parse(row.snapshot_json,{}),checks=checklist(row.evidence_checklist_json),items=carry(parse(row.carry_forward_json,[])),computed=hashCore(row);return {id:row.id,review_month:row.review_month,status:row.status,reviewer_label:row.reviewer_label||null,management_decision:row.management_decision||null,evidence_checklist:checks,evidence_complete:CHECKS.every(k=>checks[k]),carry_forward:items,snapshot,snapshot_sha256:row.snapshot_sha256,previous_review_sha256:row.previous_review_sha256||null,review_sha256:row.review_sha256,integrity:{verified:computed===row.review_sha256,algorithm:'SHA-256'},acknowledged_at:row.acknowledged_at||null,attested_at:row.attested_at||null,created_at:row.created_at,updated_at:row.updated_at};}
async function owned(userId,id){const [[row]]=await pool.query(`SELECT * FROM personal_finance_recovery_management_reviews WHERE id=? AND user_id=? LIMIT 1`,[id,userId]);if(!row)throw err('Management review was not found.',404,'RECOVERY_MANAGEMENT_REVIEW_NOT_FOUND');return row;}
async function saveHash(db,userId,id){const [[row]]=await db.query(`SELECT * FROM personal_finance_recovery_management_reviews WHERE id=? AND user_id=? LIMIT 1`,[id,userId]);const h=hashCore(row);await db.query(`UPDATE personal_finance_recovery_management_reviews SET review_sha256=? WHERE id=? AND user_id=?`,[h,id,userId]);return h;}
exports.list=async(req,res)=>{try{const userId=uid(req);const [rows]=await pool.query(`SELECT * FROM personal_finance_recovery_management_reviews WHERE user_id=? ORDER BY review_month DESC,created_at DESC LIMIT 24`,[userId]);return res.json({scope:'PERSONAL_ONLY',finance_mutations:false,review_metadata_writes_only:true,checklist_keys:CHECKS,reviews:rows.map(view)});}catch(e){return fail(res,e);}};
exports.generate=async(req,res)=>{try{const userId=uid(req),month=reviewMonth();const [[existing]]=await pool.query(`SELECT * FROM personal_finance_recovery_management_reviews WHERE user_id=? AND review_month=? LIMIT 1`,[userId,month]);if(existing)return res.json({created:false,review:view(existing)});const report=await reporting.buildReport(userId,12),snapshot={format:'VOXEL_VEDA_PERSONAL_FINANCE_RECOVERY_MANAGEMENT_REVIEW',version:1,review_month:month,frozen_at:new Date().toISOString(),report:report.review_pack,summary:report.summary,condition_categories:report.condition_categories,monthly:report.monthly,scope:'PERSONAL_ONLY',controls:{financial_records_changed:false,company_finance_included:false,no_inferred_root_cause:true}};const snapshotSha=canonical.hash(snapshot),id=crypto.randomUUID(),db=await pool.getConnection();try{await db.beginTransaction();const [[last]]=await db.query(`SELECT review_sha256 FROM personal_finance_recovery_management_reviews WHERE user_id=? ORDER BY review_month DESC,created_at DESC LIMIT 1 FOR UPDATE`,[userId]);const prev=last?.review_sha256||null,base={review_month:month,status:'DRAFT',reviewer_label:null,management_decision:null,evidence_checklist_json:JSON.stringify(checklist({})),carry_forward_json:JSON.stringify([]),snapshot_sha256:snapshotSha,previous_review_sha256:prev,acknowledged_at:null,attested_at:null},reviewSha=hashCore(base);await db.query(`INSERT INTO personal_finance_recovery_management_reviews (id,user_id,review_month,status,evidence_checklist_json,carry_forward_json,snapshot_json,snapshot_sha256,previous_review_sha256,review_sha256) VALUES (?,?,?,?,?,?,?,?,?,?)`,[id,userId,month,'DRAFT',base.evidence_checklist_json,base.carry_forward_json,JSON.stringify(snapshot),snapshotSha,prev,reviewSha]);await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}return res.status(201).json({created:true,review:view(await owned(userId,id))});}catch(e){return fail(res,e);}};
exports.update=async(req,res)=>{try{const userId=uid(req),id=text(req.body?.review_id,36),action=text(req.body?.review_action,32).toUpperCase();if(!id)throw err('review_id is required.');const row=await owned(userId,id);if(row.status==='ATTESTED')throw err('An attested management review is immutable. Generate the next monthly review for new decisions.',409,'RECOVERY_REVIEW_IMMUTABLE');const checks=checklist(row.evidence_checklist_json),incoming=req.body?.evidence_checklist&&typeof req.body.evidence_checklist==='object'?req.body.evidence_checklist:{};for(const k of Object.keys(incoming))if(CHECKS.includes(k))checks[k]=Boolean(incoming[k]);const reviewer=text(req.body?.reviewer_label??row.reviewer_label,120)||null,decision=text(req.body?.management_decision??row.management_decision,500)||null,carryItems=req.body?.carry_forward!==undefined?carry(req.body.carry_forward):carry(parse(row.carry_forward_json,[]));let status=row.status,ack=row.acknowledged_at,att=row.attested_at;if(action==='ACKNOWLEDGE'){if(!reviewer)throw err('Reviewer label is required before acknowledgement.');if(!checks.REPORT_REVIEWED||!checks.SLA_REVIEWED||!checks.RECURRENCE_REVIEWED||!checks.OPEN_RISKS_REVIEWED)throw err('Review the report, SLA, recurrence and open-risk evidence before acknowledgement.',409,'RECOVERY_REVIEW_EVIDENCE_INCOMPLETE');status='ACKNOWLEDGED';ack=ack||new Date();}else if(action==='ATTEST'){if(row.status!=='ACKNOWLEDGED')throw err('Acknowledge the review before final attestation.',409,'RECOVERY_REVIEW_ACK_REQUIRED');checks.DECISION_RECORDED=Boolean(decision);if(!CHECKS.every(k=>checks[k]))throw err('Complete the management-review evidence checklist before attestation.',409,'RECOVERY_REVIEW_EVIDENCE_INCOMPLETE');const snap=parse(row.snapshot_json,{});if(Number(snap?.summary?.open||0)>0&&!carryItems.length)throw err('Open recovery incidents require at least one carry-forward item before attestation.',409,'RECOVERY_REVIEW_CARRY_FORWARD_REQUIRED');if(!decision)throw err('A management decision is required before attestation.');status='ATTESTED';att=new Date();}else if(action!=='SAVE')throw err('Unknown management review action.');const db=await pool.getConnection();try{await db.beginTransaction();await db.query(`UPDATE personal_finance_recovery_management_reviews SET status=?,reviewer_label=?,management_decision=?,evidence_checklist_json=?,carry_forward_json=?,acknowledged_at=?,attested_at=? WHERE id=? AND user_id=?`,[status,reviewer,decision,JSON.stringify(checks),JSON.stringify(carryItems),ack,att,id,userId]);await saveHash(db,userId,id);await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}return res.json({review:view(await owned(userId,id))});}catch(e){return fail(res,e);}};
exports._test={CHECKS,STATUSES,reviewMonth,checklist,carry,hashCore,view};
