const crypto=require('node:crypto');
const pool=require('../config/db');
const management=require('./personalFinanceRecoveryManagementReviewController')._test;

function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function err(message,statusCode=400,code='RECOVERY_EVIDENCE_INVESTIGATION_FAILED'){return Object.assign(new Error(message),{statusCode,code});}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Recovery evidence investigation failed.',e);return res.status(s).json({message:s>=500?'Recovery evidence investigation failed.':e.message,code:e.code||'RECOVERY_EVIDENCE_INVESTIGATION_FAILED'});}
function text(v,max=1000){return String(v??'').trim().slice(0,max);}
function parse(v,f){if(v===null||v===undefined||v==='')return f;if(typeof v==='object')return v;try{return JSON.parse(v);}catch{return f;}}
function refs(v){if(!Array.isArray(v))return [];return [...new Set(v.map(x=>text(x,240)).filter(Boolean))].slice(0,30);}
function codeBase(v){return text(v,120).split(':')[0].toUpperCase();}
function severityFor(code){const c=codeBase(code);if(['SERVER_HASH_VERIFICATION_FAILED','MANAGEMENT_REVIEW_HASH_MISMATCH','PREVIOUS_REVIEW_HASH_MISMATCH','CERTIFICATE_SEQUENCE_GAP','PREVIOUS_CERTIFICATE_HASH_MISMATCH','CERTIFICATE_RESTORE_RUN_MISMATCH'].includes(c))return 'CRITICAL';if(['PACKAGE_HASH_CHANGED_WITHIN_RUN','CERTIFICATE_HASH_MISSING','MISSING_RESTORE_RUN','MISSING_CERTIFICATE'].includes(c))return 'HIGH';if(['MISSING_CAPA','MISSING_REVIEW','MISSING_SOURCE_REVIEW','MISSING_INCIDENT','MISSING_INCIDENT_CASE'].includes(c))return 'MEDIUM';return 'LOW';}
function slaFor(severity){const map={CRITICAL:{response_hours:2,resolution_hours:24},HIGH:{response_hours:8,resolution_hours:72},MEDIUM:{response_hours:24,resolution_hours:168},LOW:{response_hours:72,resolution_hours:336}};return map[severity]||map.LOW;}
function addHours(d,h){return new Date(new Date(d).getTime()+Number(h)*3600000);}
function escalationFor(row,repeatCount=1,now=new Date()){if(row.status==='CLOSED')return {level:'L0',reason:'Closed investigation'};const responseOverdue=!row.first_response_at&&row.response_due_at&&now>new Date(row.response_due_at),resolutionOverdue=row.resolution_due_at&&now>new Date(row.resolution_due_at);if(row.severity==='CRITICAL'&&row.resolution_due_at&&now>addHours(row.resolution_due_at,24))return {level:'L3',reason:'Critical investigation remains open more than 24 hours beyond resolution target'};if(repeatCount>=3&&['CRITICAL','HIGH'].includes(row.severity))return {level:'L3',reason:'Same evidence discrepancy has recurred at least three times'};if(resolutionOverdue)return {level:'L2',reason:'Resolution SLA is overdue'};if(responseOverdue)return {level:'L1',reason:'Initial response SLA is overdue'};if(repeatCount>=2)return {level:'L1',reason:'Repeat discrepancy observed'};return {level:'L0',reason:'Within current SLA targets'};}
function cleanHypotheses(v){if(!Array.isArray(v))return [];return v.slice(0,20).map((x,i)=>({id:text(x?.id||`H${i+1}`,40),hypothesis:text(x?.hypothesis,500),status:['UNTESTED','SUPPORTED','CONTRADICTED','INCONCLUSIVE'].includes(String(x?.status||'').toUpperCase())?String(x.status).toUpperCase():'UNTESTED',evidence_refs:refs(x?.evidence_refs)})).filter(x=>x.hypothesis);}
function evidenceConclusion(hypotheses,causeEvidence){const supported=hypotheses.filter(x=>x.status==='SUPPORTED');if(supported.some(x=>x.evidence_refs.length)&&causeEvidence.length)return 'EVIDENCE_SUPPORTED_CONTRIBUTOR';if(hypotheses.some(x=>x.status==='CONTRADICTED')&&!supported.length)return 'EVIDENCE_CONTRADICTED';if(hypotheses.length||causeEvidence.length)return 'INSUFFICIENT_EVIDENCE';return 'NOT_ASSESSED';}
function view(r,repeatCount=1){const notes=parse(r.investigation_notes_json,[]),preservation=refs(parse(r.preservation_refs_json,[])),hypotheses=cleanHypotheses(parse(r.hypotheses_json,[])),causeEvidence=refs(parse(r.cause_evidence_json,[])),esc=escalationFor(r,repeatCount);return {id:r.id,source_type:r.source_type,source_id:r.source_id,affected_ref_id:r.affected_ref_id||null,discrepancy_code:r.discrepancy_code,severity:r.severity,status:r.status,owner_label:r.owner_label||null,first_response_at:r.first_response_at||null,response_due_at:r.response_due_at||null,resolution_due_at:r.resolution_due_at||null,escalation_level:esc.level,escalation_reason:esc.reason,repeat_discrepancy_count:repeatCount,observed_details:parse(r.observed_details_json,{}),investigation_notes:notes,preservation_refs:preservation,hypotheses,cause_evidence_refs:causeEvidence,cause_conclusion:r.cause_conclusion||evidenceConclusion(hypotheses,causeEvidence),reviewer_label:r.reviewer_label||null,review_status:r.review_status||'NOT_REVIEWED',review_note:r.review_note||null,reviewed_at:r.reviewed_at||null,resolution_note:r.resolution_note||null,verification_status:r.verification_status,verification_details:parse(r.verification_details_json,{}),verified_at:r.verified_at||null,closed_at:r.closed_at||null,created_at:r.created_at,updated_at:r.updated_at,age_days:Math.max(0,Math.floor((Date.now()-new Date(r.created_at).getTime())/86400000)),boundary:'Cause hypotheses are evidence-tracking aids only. The system does not infer or declare a root cause; an evidence-supported contributor requires explicit supporting references and reviewer approval.'};}
async function owned(userId,id){const [[r]]=await pool.query(`SELECT * FROM personal_finance_recovery_evidence_investigations WHERE id=? AND user_id=? LIMIT 1`,[id,userId]);if(!r)throw err('Evidence investigation was not found.',404,'RECOVERY_EVIDENCE_INVESTIGATION_NOT_FOUND');return r;}
async function event(db,userId,id,type,payload){await db.query(`INSERT INTO personal_finance_recovery_evidence_investigation_events (investigation_id,user_id,event_type,event_json) VALUES (?,?,?,?)`,[id,userId,type,JSON.stringify(payload||{})]);}
async function exists(table,userId,id){const allowed=new Set(['personal_finance_recovery_capa','personal_finance_recovery_management_reviews','personal_finance_recovery_incident_cases','personal_finance_recovery_certificates','personal_finance_restore_runs']);if(!allowed.has(table))return false;const [[r]]=await pool.query(`SELECT id FROM ${table} WHERE id=? AND user_id=? LIMIT 1`,[id,userId]);return Boolean(r);}
async function repeatCount(userId,row){const [[r]]=await pool.query(`SELECT COUNT(*) AS n FROM personal_finance_recovery_evidence_investigations WHERE user_id=? AND discrepancy_code=? AND source_type=? AND created_at>=DATE_SUB(?,INTERVAL 180 DAY)`,[userId,row.discrepancy_code,row.source_type,row.created_at]);return Math.max(1,Number(r?.n||1));}
async function currentCondition(userId,row){const code=codeBase(row.discrepancy_code),ref=String(row.affected_ref_id||'');
  if(code==='MISSING_CAPA')return {status:(await exists('personal_finance_recovery_capa',userId,ref))?'CLEARED':'STILL_PRESENT',check:'Referenced CAPA exists'};
  if(code==='MISSING_REVIEW'||code==='MISSING_SOURCE_REVIEW')return {status:(await exists('personal_finance_recovery_management_reviews',userId,ref))?'CLEARED':'STILL_PRESENT',check:'Referenced management review exists'};
  if(code==='MISSING_INCIDENT'||code==='MISSING_INCIDENT_CASE')return {status:(await exists('personal_finance_recovery_incident_cases',userId,ref))?'CLEARED':'STILL_PRESENT',check:'Referenced incident case exists'};
  if(code==='MISSING_CERTIFICATE')return {status:(await exists('personal_finance_recovery_certificates',userId,ref))?'CLEARED':'STILL_PRESENT',check:'Referenced recovery certificate exists'};
  if(code==='MISSING_RESTORE_RUN')return {status:(await exists('personal_finance_restore_runs',userId,ref))?'CLEARED':'STILL_PRESENT',check:'Referenced restore run exists'};
  if(row.source_type==='MANAGEMENT_REVIEW'){
    const [[r]]=await pool.query(`SELECT * FROM personal_finance_recovery_management_reviews WHERE id=? AND user_id=? LIMIT 1`,[row.source_id,userId]);if(!r)return {status:'UNVERIFIABLE',check:'Source management review is missing'};
    if(code==='SERVER_HASH_VERIFICATION_FAILED'||code==='MANAGEMENT_REVIEW_HASH_MISMATCH')return {status:management.hashCore(r)===r.review_sha256?'CLEARED':'STILL_PRESENT',check:'Management review SHA-256 recomputation'};
    if(code==='PREVIOUS_REVIEW_HASH_MISMATCH'){const [[p]]=await pool.query(`SELECT review_sha256 FROM personal_finance_recovery_management_reviews WHERE user_id=? AND (review_month<? OR (review_month=? AND created_at<?)) ORDER BY review_month DESC,created_at DESC LIMIT 1`,[userId,r.review_month,r.review_month,r.created_at]);return {status:(r.previous_review_sha256||null)===(p?.review_sha256||null)?'CLEARED':'STILL_PRESENT',check:'Previous management-review hash continuity'};}
  }
  if(row.source_type==='CERTIFICATE'){
    const [[c]]=await pool.query(`SELECT * FROM personal_finance_recovery_certificates WHERE id=? AND user_id=? LIMIT 1`,[row.source_id,userId]);if(!c)return {status:'UNVERIFIABLE',check:'Source certificate is missing'};const [all]=await pool.query(`SELECT id,sequence_no,package_sha256,previous_certificate_sha256,certificate_sha256 FROM personal_finance_recovery_certificates WHERE restore_run_id=? AND user_id=? ORDER BY sequence_no ASC`,[c.restore_run_id,userId]);const idx=all.findIndex(x=>String(x.id)===String(c.id)),prev=idx>0?all[idx-1]:null;
    if(code==='CERTIFICATE_SEQUENCE_GAP')return {status:all.every((x,i)=>Number(x.sequence_no)===i+1)?'CLEARED':'STILL_PRESENT',check:'Certificate sequence continuity'};
    if(code==='PREVIOUS_CERTIFICATE_HASH_MISMATCH')return {status:(c.previous_certificate_sha256||null)===(prev?.certificate_sha256||null)?'CLEARED':'STILL_PRESENT',check:'Previous certificate hash continuity'};
    if(code==='PACKAGE_HASH_CHANGED_WITHIN_RUN')return {status:new Set(all.map(x=>String(x.package_sha256||''))).size<=1?'CLEARED':'STILL_PRESENT',check:'Package hash consistency within restore run'};
    if(code==='CERTIFICATE_HASH_MISSING')return {status:c.certificate_sha256?'CLEARED':'STILL_PRESENT',check:'Certificate SHA-256 presence'};
  }
  if(row.source_type==='INCIDENT_CASE'&&code==='CERTIFICATE_RESTORE_RUN_MISMATCH'){
    const [[i]]=await pool.query(`SELECT restore_run_id,linked_certificate_id FROM personal_finance_recovery_incident_cases WHERE id=? AND user_id=? LIMIT 1`,[row.source_id,userId]);if(!i||!i.linked_certificate_id)return {status:'UNVERIFIABLE',check:'Incident/certificate link is unavailable'};const [[c]]=await pool.query(`SELECT restore_run_id FROM personal_finance_recovery_certificates WHERE id=? AND user_id=? LIMIT 1`,[i.linked_certificate_id,userId]);if(!c)return {status:'STILL_PRESENT',check:'Linked recovery certificate is missing'};return {status:String(i.restore_run_id)===String(c.restore_run_id)?'CLEARED':'STILL_PRESENT',check:'Incident and certificate restore-run consistency'};
  }
  return {status:'UNVERIFIABLE',check:'No deterministic verifier exists for this discrepancy type yet'};
}

exports.list=async(req,res)=>{try{const userId=uid(req);const [rows]=await pool.query(`SELECT * FROM personal_finance_recovery_evidence_investigations WHERE user_id=? ORDER BY CASE severity WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2 WHEN 'MEDIUM' THEN 3 ELSE 4 END, CASE status WHEN 'CLOSED' THEN 2 ELSE 1 END, created_at DESC LIMIT 250`,[userId]);const items=[];for(const r of rows)items.push(view(r,await repeatCount(userId,r)));return res.json({scope:'PERSONAL_ONLY',finance_mutations:false,investigation_metadata_writes_only:true,summary:{total:items.length,open:items.filter(x=>x.status!=='CLOSED').length,critical_open:items.filter(x=>x.status!=='CLOSED'&&x.severity==='CRITICAL').length,response_sla_overdue:items.filter(x=>x.status!=='CLOSED'&&!x.first_response_at&&x.response_due_at&&Date.now()>new Date(x.response_due_at).getTime()).length,resolution_sla_overdue:items.filter(x=>x.status!=='CLOSED'&&x.resolution_due_at&&Date.now()>new Date(x.resolution_due_at).getTime()).length,escalated:items.filter(x=>x.status!=='CLOSED'&&x.escalation_level!=='L0').length,repeat_discrepancies:items.filter(x=>x.repeat_discrepancy_count>=2).length,review_approved:items.filter(x=>x.review_status==='APPROVED').length,closed:items.filter(x=>x.status==='CLOSED').length},items,sla_rules:{CRITICAL:'2h response / 24h resolution',HIGH:'8h response / 72h resolution',MEDIUM:'24h response / 7d resolution',LOW:'72h response / 14d resolution'},cause_framework:'Hypotheses remain UNTESTED, SUPPORTED, CONTRADICTED or INCONCLUSIVE. The system does not infer a root cause. EVIDENCE_SUPPORTED_CONTRIBUTOR requires recorded evidence references and reviewer approval.',boundary:'Investigation governance does not repair evidence, alter finance records, or infer root cause.'});}catch(e){return fail(res,e);}};
exports.history=async(req,res)=>{try{const userId=uid(req),id=text(req.query.investigation_id,36);await owned(userId,id);const [rows]=await pool.query(`SELECT id,event_type,event_json,created_at FROM personal_finance_recovery_evidence_investigation_events WHERE investigation_id=? AND user_id=? ORDER BY id ASC`,[id,userId]);return res.json({investigation_id:id,events:rows.map(x=>({id:x.id,event_type:x.event_type,event:parse(x.event_json,{}),created_at:x.created_at}))});}catch(e){return fail(res,e);}};
exports.create=async(req,res)=>{try{const userId=uid(req),sourceType=text(req.body?.source_type,64).toUpperCase(),sourceId=text(req.body?.source_id,191),rawCode=text(req.body?.discrepancy_code,120).toUpperCase();if(!sourceType||!sourceId||!rawCode)throw err('source_type, source_id and discrepancy_code are required.');const parts=rawCode.split(':'),code=parts[0],affected=text(req.body?.affected_ref_id||parts.slice(1).join(':'),191)||null,key=`${sourceType}:${sourceId}:${code}:${affected||''}`.slice(0,255);const [[existing]]=await pool.query(`SELECT * FROM personal_finance_recovery_evidence_investigations WHERE user_id=? AND discrepancy_key=? AND status<>'CLOSED' ORDER BY created_at DESC LIMIT 1`,[userId,key]);if(existing)return res.json({created:false,deduplicated:true,investigation:view(existing,await repeatCount(userId,existing))});const id=crypto.randomUUID(),severity=severityFor(code),sla=slaFor(severity),now=new Date(),responseDue=addHours(now,sla.response_hours),resolutionDue=addHours(now,sla.resolution_hours),details=req.body?.observed_details&&typeof req.body.observed_details==='object'?req.body.observed_details:{};const db=await pool.getConnection();try{await db.beginTransaction();await db.query(`INSERT INTO personal_finance_recovery_evidence_investigations (id,user_id,discrepancy_key,source_type,source_id,affected_ref_id,discrepancy_code,severity,observed_details_json,response_due_at,resolution_due_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)`,[id,userId,key,sourceType,sourceId,affected,code,severity,JSON.stringify(details),responseDue,resolutionDue]);await event(db,userId,id,'INVESTIGATION_OPENED',{source_type:sourceType,source_id:sourceId,affected_ref_id:affected,discrepancy_code:code,severity,sla,automatic_repair:false});await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}const row=await owned(userId,id);return res.status(201).json({created:true,investigation:view(row,await repeatCount(userId,row))});}catch(e){return fail(res,e);}};
exports.update=async(req,res)=>{try{const userId=uid(req),id=text(req.body?.investigation_id,36),row=await owned(userId,id);if(row.status==='CLOSED')throw err('Closed evidence investigations are immutable.',409,'RECOVERY_EVIDENCE_INVESTIGATION_IMMUTABLE');let status=text(req.body?.status||row.status,32).toUpperCase();if(!['OPEN','INVESTIGATING','RESOLUTION_PENDING'].includes(status))status=row.status;const owner=text(req.body?.owner_label??row.owner_label,120)||null,notes=parse(row.investigation_notes_json,[]),note=text(req.body?.note,1000),preservation=refs(req.body?.preservation_refs!==undefined?req.body.preservation_refs:parse(row.preservation_refs_json,[])),firstResponse=row.first_response_at||((owner||note||status!=='OPEN')?new Date():null);if(note)notes.push({at:new Date().toISOString(),note});const db=await pool.getConnection();try{await db.beginTransaction();await db.query(`UPDATE personal_finance_recovery_evidence_investigations SET status=?,owner_label=?,first_response_at=?,investigation_notes_json=?,preservation_refs_json=? WHERE id=? AND user_id=?`,[status,owner,firstResponse,JSON.stringify(notes.slice(-100)),JSON.stringify(preservation),id,userId]);await event(db,userId,id,'INVESTIGATION_UPDATED',{status,owner_label:owner,first_response_recorded:Boolean(firstResponse&&!row.first_response_at),note_added:Boolean(note),preservation_ref_count:preservation.length});await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}const updated=await owned(userId,id);return res.json({investigation:view(updated,await repeatCount(userId,updated))});}catch(e){return fail(res,e);}};
exports.updateCause=async(req,res)=>{try{const userId=uid(req),id=text(req.body?.investigation_id,36),row=await owned(userId,id);if(row.status==='CLOSED')throw err('Closed evidence investigations are immutable.',409,'RECOVERY_EVIDENCE_INVESTIGATION_IMMUTABLE');const hypotheses=cleanHypotheses(req.body?.hypotheses),causeEvidence=refs(req.body?.cause_evidence_refs),conclusion=evidenceConclusion(hypotheses,causeEvidence);const db=await pool.getConnection();try{await db.beginTransaction();await db.query(`UPDATE personal_finance_recovery_evidence_investigations SET hypotheses_json=?,cause_evidence_json=?,cause_conclusion=?,review_status='NOT_REVIEWED',reviewer_label=NULL,review_note=NULL,reviewed_at=NULL WHERE id=? AND user_id=?`,[JSON.stringify(hypotheses),JSON.stringify(causeEvidence),conclusion,id,userId]);await event(db,userId,id,'CAUSE_EVIDENCE_UPDATED',{hypothesis_count:hypotheses.length,cause_evidence_ref_count:causeEvidence.length,cause_conclusion:conclusion,root_cause_declared:false});await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}const updated=await owned(userId,id);return res.json({investigation:view(updated,await repeatCount(userId,updated)),root_cause_declared:false});}catch(e){return fail(res,e);}};
exports.review=async(req,res)=>{try{const userId=uid(req),id=text(req.body?.investigation_id,36),row=await owned(userId,id);if(row.status==='CLOSED')throw err('Closed evidence investigations are immutable.',409,'RECOVERY_EVIDENCE_INVESTIGATION_IMMUTABLE');const reviewer=text(req.body?.reviewer_label,120),decision=text(req.body?.review_status,32).toUpperCase(),note=text(req.body?.review_note,1000);if(!reviewer)throw err('Reviewer label is required.');if(!['APPROVED','CHANGES_REQUIRED'].includes(decision))throw err('Review status must be APPROVED or CHANGES_REQUIRED.');if(decision==='APPROVED'&&row.cause_conclusion==='EVIDENCE_SUPPORTED_CONTRIBUTOR'){const hs=cleanHypotheses(parse(row.hypotheses_json,[])),ce=refs(parse(row.cause_evidence_json,[]));if(!hs.some(x=>x.status==='SUPPORTED'&&x.evidence_refs.length)||!ce.length)throw err('Evidence-supported contributor approval requires a supported hypothesis with evidence references and investigation-level cause evidence.',409,'RECOVERY_CAUSE_EVIDENCE_REQUIRED');}const db=await pool.getConnection();try{await db.beginTransaction();await db.query(`UPDATE personal_finance_recovery_evidence_investigations SET reviewer_label=?,review_status=?,review_note=?,reviewed_at=NOW() WHERE id=? AND user_id=?`,[reviewer,decision,note||null,id,userId]);await event(db,userId,id,'INVESTIGATION_REVIEWED',{reviewer_label:reviewer,review_status:decision,review_note:note||null,root_cause_declared:false});await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}const updated=await owned(userId,id);return res.json({investigation:view(updated,await repeatCount(userId,updated)),root_cause_declared:false});}catch(e){return fail(res,e);}};
exports.verify=async(req,res)=>{try{const userId=uid(req),id=text(req.body?.investigation_id,36),row=await owned(userId,id);if(row.status==='CLOSED')throw err('Closed evidence investigations are immutable.',409,'RECOVERY_EVIDENCE_INVESTIGATION_IMMUTABLE');const result=await currentCondition(userId,row),now=new Date(),status=result.status==='CLEARED'?'VERIFIED':row.status==='OPEN'?'INVESTIGATING':row.status;const db=await pool.getConnection();try{await db.beginTransaction();await db.query(`UPDATE personal_finance_recovery_evidence_investigations SET status=?,verification_status=?,verification_details_json=?,verified_at=? WHERE id=? AND user_id=?`,[status,result.status,JSON.stringify({...result,checked_at:now.toISOString(),automatic_repair:false}),now,id,userId]);await event(db,userId,id,'DISCREPANCY_RECHECKED',{verification_status:result.status,check:result.check,underlying_evidence_changed:false,automatic_repair:false});await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}const updated=await owned(userId,id);return res.json({investigation:view(updated,await repeatCount(userId,updated)),automatic_repair:false,financial_records_changed:false});}catch(e){return fail(res,e);}};
exports.close=async(req,res)=>{try{const userId=uid(req),id=text(req.body?.investigation_id,36),row=await owned(userId,id);if(row.status==='CLOSED')return res.json({investigation:view(row,await repeatCount(userId,row))});if(row.verification_status!=='CLEARED'||row.status!=='VERIFIED')throw err('Re-check the discrepancy and confirm it is cleared before closure.',409,'RECOVERY_EVIDENCE_INVESTIGATION_VERIFICATION_REQUIRED');if(row.review_status!=='APPROVED')throw err('Reviewer approval is required before investigation closure.',409,'RECOVERY_EVIDENCE_INVESTIGATION_REVIEW_REQUIRED');const preservation=refs(parse(row.preservation_refs_json,[])),resolution=text(req.body?.resolution_note,1000);if(!preservation.length)throw err('At least one preserved evidence reference is required before closure.',409,'RECOVERY_EVIDENCE_PRESERVATION_REQUIRED');if(!resolution)throw err('A resolution note is required before closure.');const db=await pool.getConnection();try{await db.beginTransaction();await db.query(`UPDATE personal_finance_recovery_evidence_investigations SET status='CLOSED',resolution_note=?,closed_at=NOW() WHERE id=? AND user_id=?`,[resolution,id,userId]);await event(db,userId,id,'INVESTIGATION_CLOSED',{resolution_note:resolution,preservation_ref_count:preservation.length,verified_cleared:true,review_approved:true,automatic_repair:false,root_cause_declared:false});await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}const updated=await owned(userId,id);return res.json({investigation:view(updated,await repeatCount(userId,updated)),underlying_evidence_changed:false,financial_records_changed:false,root_cause_declared:false});}catch(e){return fail(res,e);}};
exports._test={severityFor,slaFor,escalationFor,codeBase,currentCondition,evidenceConclusion,cleanHypotheses};
