const crypto = require('node:crypto');
const pool = require('../config/db');

function userId(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function fail(res,error,message){const status=Number(error?.statusCode||500);if(status>=500)console.error(message,error);return res.status(status).json({message:status>=500?message:error.message});}
function clean(v,max=200){const s=String(v||'').trim();return s?s.slice(0,max):null;}
function dateOnly(v,required=false){if(!v&&!required)return null;const s=String(v||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw Object.assign(new Error('Date must use YYYY-MM-DD.'),{statusCode:400});return s;}
function currency(v){const s=String(v||'AUD').trim().toUpperCase();if(!/^[A-Z]{3}$/.test(s))throw Object.assign(new Error('Currency must be a three-letter code.'),{statusCode:400});return s;}
function amount(v){if(v===''||v===null||v===undefined)return null;const n=Number(v);if(!Number.isFinite(n)||n<0||n>999999999999)throw Object.assign(new Error('Amount must be zero or positive.'),{statusCode:400});return Math.round(n*100)/100;}
function choice(v,allowed,label){const s=String(v||'').trim().toUpperCase();if(!allowed.has(s))throw Object.assign(new Error(`Choose a valid ${label}.`),{statusCode:400});return s;}
async function assertOwnedAsset(user,id){if(!id)return null;const [[r]]=await pool.query('SELECT id,name,currency,current_value,purchase_value,purchase_date FROM personal_net_worth_assets WHERE id=? AND user_id=? AND active=1 LIMIT 1',[id,user]);if(!r)throw Object.assign(new Error('Asset not found.'),{statusCode:404});return r;}
async function assertOwnedLiability(user,id){if(!id)return null;const [[r]]=await pool.query('SELECT id,name,currency,current_balance,original_balance FROM personal_net_worth_liabilities WHERE id=? AND user_id=? AND active=1 LIMIT 1',[id,user]);if(!r)throw Object.assign(new Error('Liability not found.'),{statusCode:404});return r;}
function nextDate(date,frequency){if(!date||!frequency)return null;const d=new Date(`${date}T00:00:00Z`);if(Number.isNaN(d.getTime()))return null;switch(frequency){case'MONTHLY':d.setUTCMonth(d.getUTCMonth()+1);break;case'QUARTERLY':d.setUTCMonth(d.getUTCMonth()+3);break;case'BIANNUAL':d.setUTCMonth(d.getUTCMonth()+6);break;case'ANNUAL':d.setUTCFullYear(d.getUTCFullYear()+1);break;case'TWO_YEAR':d.setUTCFullYear(d.getUTCFullYear()+2);break;default:return null;}return d.toISOString().slice(0,10);}

exports.getCenter=async(req,res)=>{try{const u=userId(req);const [assets,liabilities,items,documents,valueHistory]=await Promise.all([
 pool.query('SELECT id,asset_type,name,currency,current_value,purchase_value,purchase_date,institution FROM personal_net_worth_assets WHERE user_id=? AND active=1 ORDER BY current_value DESC',[u]).then(([r])=>r),
 pool.query('SELECT id,liability_type,name,currency,current_balance,minimum_payment,due_day,institution FROM personal_net_worth_liabilities WHERE user_id=? AND active=1 ORDER BY current_balance DESC',[u]).then(([r])=>r),
 pool.query(`SELECT l.*,a.name asset_name,n.name liability_name,DATEDIFF(l.due_date,CURRENT_DATE) days_until_due FROM personal_asset_lifecycle_items l LEFT JOIN personal_net_worth_assets a ON a.id=l.asset_id AND a.user_id=l.user_id LEFT JOIN personal_net_worth_liabilities n ON n.id=l.liability_id AND n.user_id=l.user_id WHERE l.user_id=? AND l.status<>'ARCHIVED' ORDER BY CASE WHEN l.due_date IS NULL THEN 1 ELSE 0 END,l.due_date,l.created_at DESC`,[u]).then(([r])=>r),
 pool.query(`SELECT d.*,a.name asset_name,n.name liability_name,DATEDIFF(d.expiry_date,CURRENT_DATE) days_until_expiry FROM personal_asset_documents d LEFT JOIN personal_net_worth_assets a ON a.id=d.asset_id AND a.user_id=d.user_id LEFT JOIN personal_net_worth_liabilities n ON n.id=d.liability_id AND n.user_id=d.user_id WHERE d.user_id=? ORDER BY CASE WHEN d.expiry_date IS NULL THEN 1 ELSE 0 END,d.expiry_date,d.created_at DESC`,[u]).then(([r])=>r),
 pool.query(`SELECT v.asset_id,v.value_amount,v.value_date,a.name,a.purchase_value,a.purchase_date FROM personal_net_worth_asset_values v JOIN personal_net_worth_assets a ON a.id=v.asset_id AND a.user_id=v.user_id WHERE v.user_id=? AND a.active=1 ORDER BY v.asset_id,v.value_date DESC,v.created_at DESC`,[u]).then(([r])=>r)
]);const alerts=[];for(const i of items){const d=i.days_until_due===null?null:Number(i.days_until_due);if(d!==null&&d<0)alerts.push({kind:'OVERDUE',priority:'HIGH',title:i.title,detail:`Overdue by ${Math.abs(d)} day(s).`,item_id:i.id});else if(d!==null&&d<=Number(i.reminder_days||30))alerts.push({kind:'DUE_SOON',priority:d<=7?'HIGH':'MEDIUM',title:i.title,detail:d===0?'Due today.':`Due in ${d} day(s).`,item_id:i.id});}for(const d of documents){const x=d.days_until_expiry===null?null:Number(d.days_until_expiry);if(x!==null&&x<0)alerts.push({kind:'DOCUMENT_EXPIRED',priority:'HIGH',title:d.title,detail:`Expired ${Math.abs(x)} day(s) ago.`,document_id:d.id});else if(x!==null&&x<=30)alerts.push({kind:'DOCUMENT_EXPIRY',priority:x<=7?'HIGH':'MEDIUM',title:d.title,detail:x===0?'Expires today.':`Expires in ${x} day(s).`,document_id:d.id});}const byAsset={};for(const h of valueHistory){if(!byAsset[h.asset_id])byAsset[h.asset_id]=[];if(byAsset[h.asset_id].length<2)byAsset[h.asset_id].push(h);}const value_changes=Object.entries(byAsset).map(([asset_id,rows])=>{const latest=rows[0],previous=rows[1];if(!previous)return null;const latestValue=Number(latest.value_amount||0),previousValue=Number(previous.value_amount||0);const change=previousValue?((latestValue-previousValue)/previousValue)*100:null;return {asset_id,name:latest.name,latest_value:latestValue,latest_date:latest.value_date,previous_value:previousValue,previous_date:previous.value_date,change_percent:change===null?null:Math.round(change*10)/10};}).filter(Boolean);return res.json({privacy:'Owner-only lifecycle records. Company finance users cannot see another user’s asset protection data.',assets,liabilities,items,documents,alerts,value_changes,rules:['Nothing renews or pays automatically.','Mark completed only advances a schedule when a recurrence is configured.','Document links are references only; this feature does not make public files.','Currencies remain separate.']});}catch(e){return fail(res,e,'Failed to load Asset Protection Center.');}};
exports.createItem=async(req,res)=>{try{const u=userId(req);const assetId=clean(req.body.asset_id,36),liabilityId=clean(req.body.liability_id,36);if(assetId&&liabilityId)throw Object.assign(new Error('Link an item to either an asset or a liability, not both.'),{statusCode:400});await assertOwnedAsset(u,assetId);await assertOwnedLiability(u,liabilityId);const itemType=choice(req.body.item_type,new Set(['INSURANCE','REGISTRATION','WARRANTY','SERVICE','LOAN_PAYMENT','RATE_REVIEW','TAX','OTHER']),'item type');const title=clean(req.body.title,180);if(!title)throw Object.assign(new Error('Title is required.'),{statusCode:400});const frequency=req.body.renewal_frequency?choice(req.body.renewal_frequency,new Set(['MONTHLY','QUARTERLY','BIANNUAL','ANNUAL','TWO_YEAR','NONE']),'renewal frequency'):'NONE';const reminder=Math.max(0,Math.min(365,Number(req.body.reminder_days??30)||0));const id=crypto.randomUUID();await pool.query(`INSERT INTO personal_asset_lifecycle_items (id,user_id,asset_id,liability_id,item_type,title,provider,reference_no,currency,amount,start_date,due_date,renewal_frequency,reminder_days,note) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[id,u,assetId,liabilityId,itemType,title,clean(req.body.provider,180),clean(req.body.reference_no,120),currency(req.body.currency),amount(req.body.amount),dateOnly(req.body.start_date),dateOnly(req.body.due_date),frequency,reminder,clean(req.body.note,500)]);return res.status(201).json({message:'Protection or lifecycle item added.',id});}catch(e){return fail(res,e,'Failed to add lifecycle item.');}};
exports.completeItem=async(req,res)=>{const c=await pool.getConnection();try{const u=userId(req);await c.beginTransaction();const [[row]]=await c.query("SELECT * FROM personal_asset_lifecycle_items WHERE id=? AND user_id=? AND status<>'ARCHIVED' LIMIT 1 FOR UPDATE",[req.params.id,u]);if(!row)throw Object.assign(new Error('Lifecycle item not found.'),{statusCode:404});const next=nextDate(row.due_date,row.renewal_frequency);await c.query(`UPDATE personal_asset_lifecycle_items SET last_completed_at=NOW(),due_date=?,status=? WHERE id=? AND user_id=?`,[next,next?'ACTIVE':'COMPLETED',row.id,u]);await c.commit();return res.json({message:next?`Marked complete. Next due date: ${next}.`:'Marked complete. No automatic payment was created.',next_due_date:next});}catch(e){await c.rollback().catch(()=>{});return fail(res,e,'Failed to complete lifecycle item.');}finally{c.release();}};
exports.archiveItem=async(req,res)=>{try{const u=userId(req);const [r]=await pool.query(`UPDATE personal_asset_lifecycle_items SET status='ARCHIVED' WHERE id=? AND user_id=?`,[req.params.id,u]);if(!r.affectedRows)return res.status(404).json({message:'Lifecycle item not found.'});return res.json({message:'Lifecycle item archived.'});}catch(e){return fail(res,e,'Failed to archive lifecycle item.');}};
exports.addDocument=async(req,res)=>{try{const u=userId(req);const assetId=clean(req.body.asset_id,36),liabilityId=clean(req.body.liability_id,36);if(assetId&&liabilityId)throw Object.assign(new Error('Link a document to either an asset or a liability, not both.'),{statusCode:400});await assertOwnedAsset(u,assetId);await assertOwnedLiability(u,liabilityId);const title=clean(req.body.title,180),url=clean(req.body.document_url,700);if(!title||!url)throw Object.assign(new Error('Document title and link are required.'),{statusCode:400});if(!/^https:\/\//i.test(url))throw Object.assign(new Error('Document link must use HTTPS.'),{statusCode:400});const id=crypto.randomUUID();await pool.query(`INSERT INTO personal_asset_documents (id,user_id,asset_id,liability_id,document_type,title,document_url,expiry_date,note) VALUES (?,?,?,?,?,?,?,?,?)`,[id,u,assetId,liabilityId,choice(req.body.document_type,new Set(['POLICY','REGISTRATION','WARRANTY','LOAN','VALUATION','RECEIPT','TITLE','OTHER']),'document type'),title,url,dateOnly(req.body.expiry_date),clean(req.body.note,500)]);return res.status(201).json({message:'Document reference added privately.',id});}catch(e){return fail(res,e,'Failed to add document reference.');}};
exports.deleteDocument=async(req,res)=>{try{const u=userId(req);const [r]=await pool.query('DELETE FROM personal_asset_documents WHERE id=? AND user_id=?',[req.params.id,u]);if(!r.affectedRows)return res.status(404).json({message:'Document not found.'});return res.json({message:'Document reference removed. The external file itself was not deleted.'});}catch(e){return fail(res,e,'Failed to remove document reference.');}};
