const crypto=require('node:crypto');
const pool=require('../config/db');

function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function clean(v,max=200){return String(v||'').trim().slice(0,max);}
function currency(v){const s=String(v||'AUD').trim().toUpperCase();if(!/^[A-Z]{3}$/.test(s))throw Object.assign(new Error('Currency must use a three-letter code such as AUD.'),{statusCode:400});return s;}
function dateOnly(v,label){const s=String(v||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw Object.assign(new Error(`${label} must use YYYY-MM-DD.`),{statusCode:400});return s;}
function amount(v,label,allowZero=false){if(v===undefined||v===null||v==='')return null;const n=Number(v);if(!Number.isFinite(n)||(allowZero?n<0:n<=0)||n>999999999999)throw Object.assign(new Error(`${label} is invalid.`),{statusCode:400});return Math.round(n*10000)/10000;}
function percent(v){if(v===undefined||v===null||v==='')return null;const n=Number(v);if(!Number.isFinite(n)||n<=0||n>=100)throw Object.assign(new Error('Reduction percent must be greater than 0 and less than 100.'),{statusCode:400});return Math.round(n*1000)/1000;}
function fail(res,e,fallback){const s=Number(e?.statusCode||500);if(s>=500)console.error(fallback,e);return res.status(s).json({message:s>=500?fallback:e.message});}
const TYPES=new Set(['CATEGORY_CAP','NO_SPEND','REDUCE_PERCENT','SAVE_VS_BASELINE']);
const STATUSES=new Set(['ACTIVE','PAUSED','COMPLETED','ARCHIVED']);

exports.list=async(req,res)=>{try{const user=uid(req);const [rows]=await pool.query(`SELECT id,name,challenge_type,category,currency,target_amount,baseline_amount,target_percent,start_date,end_date,status,note,created_at,updated_at FROM personal_spending_challenges WHERE user_id=? AND status<>'ARCHIVED' ORDER BY FIELD(status,'ACTIVE','PAUSED','COMPLETED'), end_date, created_at DESC`,[user]);res.json({privacy:'Owner-private challenge metadata only. Progress is recalculated from current Personal Money data.',challenges:rows.map(r=>({...r,target_amount:r.target_amount===null?null:Number(r.target_amount),baseline_amount:r.baseline_amount===null?null:Number(r.baseline_amount),target_percent:r.target_percent===null?null:Number(r.target_percent)}))});}catch(e){return fail(res,e,'Failed to load spending challenges.');}};

exports.progressData=async(req,res)=>{try{const user=uid(req);const today=new Date();const defaultFrom=new Date(today.getTime()-120*86400000).toISOString().slice(0,10);const from=dateOnly(req.query.from||defaultFrom,'From date');const to=dateOnly(req.query.to||today.toISOString().slice(0,10),'To date');if(to<from)throw Object.assign(new Error('To date must be on or after from date.'),{statusCode:400});const span=Math.floor((new Date(`${to}T00:00:00Z`)-new Date(`${from}T00:00:00Z`))/86400000)+1;if(span>400)throw Object.assign(new Error('Progress data is limited to 400 days per request.'),{statusCode:400});const [bank,manual]=await Promise.all([
  pool.query(`SELECT bt.id,DATE_FORMAT(bt.transaction_date,'%Y-%m-%d') transaction_date,bt.debit,bt.category confirmed_category,bt.description,bt.merchant_name,ba.currency,fi.suggested_category FROM bank_transactions bt JOIN bank_accounts ba ON ba.id=bt.bank_account_id LEFT JOIN finance_transaction_insights fi ON fi.id=(SELECT fi2.id FROM finance_transaction_insights fi2 WHERE fi2.bank_transaction_id=bt.id AND fi2.status<>'DISMISSED' ORDER BY fi2.generated_at DESC,fi2.id DESC LIMIT 1) WHERE ba.created_by=? AND ba.ownership_scope='PERSONAL' AND bt.ownership_scope='PERSONAL' AND bt.is_internal_transfer=0 AND bt.debit>0 AND bt.transaction_date BETWEEN ? AND ? ORDER BY bt.transaction_date,bt.id`,[user,from,to]).then(([r])=>r),
  pool.query(`SELECT e.id,DATE_FORMAT(e.occurred_at,'%Y-%m-%d') transaction_date,e.wallet_amount debit,e.category confirmed_category,e.counterparty merchant_name,e.note description,w.currency FROM personal_money_entries e JOIN personal_money_wallets w ON w.id=e.wallet_id AND w.user_id=e.user_id WHERE e.user_id=? AND e.entry_type IN ('EXPENSE','CASH_OUT') AND DATE(e.occurred_at) BETWEEN ? AND ? ORDER BY e.occurred_at,e.id`,[user,from,to]).then(([r])=>r)
]);res.json({privacy:'Progress feed contains only the signed-in owner’s PERSONAL spending. Business/mixed bank activity and internal transfers are excluded.',from,to,bank_transactions:bank.map(r=>({...r,debit:Number(r.debit||0),source:'BANK'})),manual_cash:manual.map(r=>({...r,debit:Number(r.debit||0),source:'MANUAL_CASH'})),currency_rule:'Currencies remain separate. No exchange rate is assumed.'});}catch(e){return fail(res,e,'Failed to load spending challenge progress.');}};

exports.create=async(req,res)=>{try{const user=uid(req),type=String(req.body.challenge_type||'').trim().toUpperCase();if(!TYPES.has(type))throw Object.assign(new Error('Choose a valid challenge type.'),{statusCode:400});const name=clean(req.body.name,140);if(!name)throw Object.assign(new Error('Challenge name is required.'),{statusCode:400});const category=clean(req.body.category,100)||'ALL',cur=currency(req.body.currency),start=dateOnly(req.body.start_date,'Start date'),end=dateOnly(req.body.end_date,'End date');if(end<start)throw Object.assign(new Error('End date must be on or after the start date.'),{statusCode:400});const span=Math.floor((new Date(`${end}T00:00:00Z`)-new Date(`${start}T00:00:00Z`))/86400000)+1;if(span<1||span>366)throw Object.assign(new Error('Challenge length must be between 1 and 366 days.'),{statusCode:400});let target=amount(req.body.target_amount,'Target amount',type==='NO_SPEND'),baseline=amount(req.body.baseline_amount,'Baseline amount'),pct=percent(req.body.target_percent);if(type==='CATEGORY_CAP'&&target===null)throw Object.assign(new Error('Category limit amount is required.'),{statusCode:400});if(type==='NO_SPEND'){target=0;baseline=null;pct=null;}if(type==='REDUCE_PERCENT'&&(baseline===null||pct===null))throw Object.assign(new Error('Reduction challenges require a baseline amount and reduction percent.'),{statusCode:400});if(type==='SAVE_VS_BASELINE'&&(baseline===null||target===null))throw Object.assign(new Error('Save-vs-normal challenges require a baseline amount and savings target.'),{statusCode:400});const id=crypto.randomUUID();await pool.query(`INSERT INTO personal_spending_challenges (id,user_id,name,challenge_type,category,currency,target_amount,baseline_amount,target_percent,start_date,end_date,status,note) VALUES (?,?,?,?,?,?,?,?,?,?,?,'ACTIVE',?)`,[id,user,name,type,category,cur,target,baseline,pct,start,end,clean(req.body.note,300)||null]);res.status(201).json({message:'Spending challenge saved. It does not block payments or move money.',id});}catch(e){return fail(res,e,'Failed to save spending challenge.');}};

exports.updateStatus=async(req,res)=>{try{const user=uid(req),status=String(req.body.status||'').trim().toUpperCase();if(!STATUSES.has(status))throw Object.assign(new Error('Choose a valid challenge status.'),{statusCode:400});const [r]=await pool.query(`UPDATE personal_spending_challenges SET status=? WHERE id=? AND user_id=?`,[status,req.params.id,user]);if(!r.affectedRows)throw Object.assign(new Error('Spending challenge not found.'),{statusCode:404});res.json({message:`Challenge ${status.toLowerCase()}.`});}catch(e){return fail(res,e,'Failed to update spending challenge.');}};
