const pool=require('../config/db');

function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Recovery governance reporting failed.',e);return res.status(s).json({message:s>=500?'Recovery governance reporting failed.':e.message,code:e.code||'RECOVERY_GOVERNANCE_REPORT_FAILED'});}
function clampMonths(v){const n=Number(v||12);return Number.isFinite(n)?Math.max(1,Math.min(24,Math.trunc(n))):12;}
function hoursBetween(a,b){if(!a||!b)return null;return Math.max(0,(new Date(b).getTime()-new Date(a).getTime())/3600000);}
function avg(values){const x=values.filter(v=>Number.isFinite(v));return x.length?Math.round((x.reduce((a,b)=>a+b,0)/x.length)*10)/10:null;}
function pct(n,d){return d?Math.round((n/d)*1000)/10:null;}
function monthKey(v){const d=new Date(v);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;}
function category(type){const t=String(type||'').toUpperCase();if(t.includes('CERTIFICATE'))return 'CERTIFICATE_INTEGRITY';if(t.includes('DEPEND'))return 'DEPENDENCY_INTEGRITY';if(t.includes('ROLLBACK'))return 'ROLLBACK_PROTECTION';if(t.includes('VERIFY')||t.includes('MISMATCH')||t.includes('HASH')||t.includes('DRIFT'))return 'RESTORE_FIDELITY';if(t.includes('INIT'))return 'VERIFICATION_INITIALIZATION';return 'OTHER_EVIDENCE_CONDITION';}

exports.get=async(req,res)=>{try{const userId=uid(req),months=clampMonths(req.query.months);const [rows]=await pool.query(`SELECT id,restore_run_id,source_level,source_signal_type,status,opened_at,first_response_at,response_due_at,resolution_due_at,resolved_at,closed_at,escalation_level,approval_checkpoint,linked_certificate_id,closure_reason,assignee_label FROM personal_finance_recovery_incident_cases WHERE user_id=? AND opened_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL ? MONTH) ORDER BY opened_at ASC`,[userId,months]);const cases=rows.map(r=>{const responseHours=hoursBetween(r.opened_at,r.first_response_at),resolutionHours=hoursBetween(r.opened_at,r.resolved_at||r.closed_at);return {...r,response_hours:responseHours,resolution_hours:resolutionHours,response_met:Boolean(r.first_response_at&&r.response_due_at&&new Date(r.first_response_at)<=new Date(r.response_due_at)),resolution_met:Boolean((r.resolved_at||r.closed_at)&&r.resolution_due_at&&new Date(r.resolved_at||r.closed_at)<=new Date(r.resolution_due_at)),condition_category:category(r.source_signal_type)};});const responded=cases.filter(c=>c.first_response_at),resolved=cases.filter(c=>c.resolved_at||c.closed_at),closed=cases.filter(c=>c.status==='CLOSED');const summary={cases:cases.length,critical:cases.filter(c=>c.source_level==='CRITICAL').length,action_soon:cases.filter(c=>c.source_level==='ACTION_SOON').length,response_sla_compliance_pct:pct(responded.filter(c=>c.response_met).length,responded.length),resolution_sla_compliance_pct:pct(resolved.filter(c=>c.resolution_met).length,resolved.length),avg_response_hours:avg(responded.map(c=>c.response_hours)),avg_resolution_hours:avg(resolved.map(c=>c.resolution_hours)),escalated:cases.filter(c=>String(c.escalation_level||'L0')!=='L0').length,closed:closed.length,closure_with_certificate_pct:pct(closed.filter(c=>c.linked_certificate_id).length,closed.length),closure_ready_approval_pct:pct(closed.filter(c=>c.approval_checkpoint==='CLOSURE_READY').length,closed.length)};
const categoryMap={};for(const c of cases){const k=c.condition_category;categoryMap[k]??={category:k,count:0,critical:0,closed:0};categoryMap[k].count++;if(c.source_level==='CRITICAL')categoryMap[k].critical++;if(c.status==='CLOSED')categoryMap[k].closed++;}
const recurrence=Object.values(categoryMap).sort((a,b)=>b.count-a.count);
const monthlyMap={};for(const c of cases){const k=monthKey(c.opened_at);monthlyMap[k]??={month:k,opened:0,critical:0,closed:0,escalated:0,response_met:0,response_total:0,resolution_met:0,resolution_total:0};const m=monthlyMap[k];m.opened++;if(c.source_level==='CRITICAL')m.critical++;if(c.status==='CLOSED')m.closed++;if(String(c.escalation_level||'L0')!=='L0')m.escalated++;if(c.first_response_at){m.response_total++;if(c.response_met)m.response_met++;}if(c.resolved_at||c.closed_at){m.resolution_total++;if(c.resolution_met)m.resolution_met++;}}
const monthly=Object.values(monthlyMap).map(m=>({...m,response_sla_pct:pct(m.response_met,m.response_total),resolution_sla_pct:pct(m.resolution_met,m.resolution_total)}));
return res.json({scope:'PERSONAL_ONLY',read_only:true,finance_mutations:false,months,generated_at:new Date().toISOString(),summary,condition_categories:recurrence,monthly,review_pack:{title:'Voxel Veda Personal Finance Recovery Management Review',period_months:months,generated_at:new Date().toISOString(),metrics:summary,condition_categories:recurrence,monthly,controls:{evidence_based_categories:true,no_inferred_root_cause:true,company_finance_included:false,financial_records_changed:false}}});}catch(e){return fail(res,e);}};

exports._test={clampMonths,hoursBetween,avg,pct,monthKey,category};
