const crypto=require('node:crypto');
const pool=require('../config/db');
function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function err(message,statusCode=400,code='RECOVERY_KNOWLEDGE_DISPOSITION_FAILED'){return Object.assign(new Error(message),{statusCode,code});}
function fail(res,e){const s=Number(e?.statusCode||500);if(s>=500)console.error('Recovery knowledge disposition failed.',e);return res.status(s).json({message:s>=500?'Knowledge disposition action failed.':e.message,code:e.code||'RECOVERY_KNOWLEDGE_DISPOSITION_FAILED'});}
function text(v,max=1600){return String(v??'').trim().slice(0,max);}
function refs(v,max=40){if(!Array.isArray(v))return [];return [...new Set(v.map(x=>text(x,240)).filter(Boolean))].slice(0,max);}
function parse(v,f){if(v===null||v===undefined||v==='')return f;if(typeof v==='object')return v;try{return JSON.parse(v);}catch{return f;}}
function view(r){if(!r)return null;const state=r.status==='PENDING'?'PENDING_DISPOSITION':r.decision==='RETIRE'?'RETIRED':r.decision==='SUPERSEDE'?'SUPERSEDED':'ACTIVE';return {id:r.id,lesson_id:r.lesson_id,proposed_action:r.proposed_action,proposer_label:r.proposer_label,proposal_note:r.proposal_note,proposal_evidence_refs:refs(parse(r.proposal_evidence_refs_json,[])),superseding_lesson_id:r.superseding_lesson_id||null,status:r.status,decision:r.decision||null,decision_maker_label:r.decision_maker_label||null,decision_note:r.decision_note||null,decision_evidence_refs:refs(parse(r.decision_evidence_refs_json,[])),decided_at:r.decided_at||null,created_at:r.created_at,updated_at:r.updated_at,knowledge_state:state,reuse_allowed:state==='ACTIVE',lesson_deleted:false};}
async function reusableLesson(userId,id){const [[r]]=await pool.query("SELECT id,title,status,effectiveness_result FROM personal_finance_recovery_lessons WHERE id=? AND user_id=? LIMIT 1",[id,userId]);if(!r)throw err('Lesson record was not found.',404,'RECOVERY_LESSON_NOT_FOUND');if(r.status!=='CLOSED'||r.effectiveness_result!=='EFFECTIVE')throw err('Knowledge disposition is available only for CLOSED lessons with an EFFECTIVE result.',409,'RECOVERY_KNOWLEDGE_NOT_REUSABLE');return r;}
async function plan(userId,lessonId){const [[r]]=await pool.query('SELECT * FROM personal_finance_recovery_knowledge_review_plans WHERE user_id=? AND lesson_id=? LIMIT 1',[userId,lessonId]);return r||null;}
async function row(userId,lessonId){const [[r]]=await pool.query('SELECT * FROM personal_finance_recovery_knowledge_dispositions WHERE user_id=? AND lesson_id=? LIMIT 1',[userId,lessonId]);return r||null;}
async function event(db,userId,id,lessonId,type,payload){await db.query('INSERT INTO personal_finance_recovery_knowledge_disposition_events (disposition_id,user_id,lesson_id,event_type,event_json) VALUES (?,?,?,?,?)',[id,userId,lessonId,type,JSON.stringify(payload||{})]);}
async function validateSuperseding(userId,sourceId,targetId){if(!targetId)throw err('A superseding lesson is required for SUPERSEDE.');if(sourceId===targetId)throw err('A lesson cannot supersede itself.');return reusableLesson(userId,targetId);}
exports.attachDispositions=async(userId,items)=>{if(!items.length)return items;const ids=items.map(x=>String(x.id));const [rows]=await pool.query(`SELECT * FROM personal_finance_recovery_knowledge_dispositions WHERE user_id=? AND lesson_id IN (${ids.map(()=>'?').join(',')})`,[String(userId),...ids]);const by=new Map(rows.map(r=>[String(r.lesson_id),r]));return items.map(x=>({...x,knowledge_disposition:view(by.get(String(x.id))||null)}));};
async function propose(req,res){const userId=uid(req),lessonId=text(req.body?.lesson_id,36);await reusableLesson(userId,lessonId);const p=await plan(userId,lessonId);if(!p)throw err('Record a knowledge review before proposing disposition.',409,'RECOVERY_KNOWLEDGE_REVIEW_REQUIRED');if(!['RETIRE_CANDIDATE','REVALIDATION_REQUIRED','INSUFFICIENT_EVIDENCE'].includes(String(p.last_review_result||'')))throw err('Disposition proposal requires a latest review result of RETIRE_CANDIDATE, REVALIDATION_REQUIRED, or INSUFFICIENT_EVIDENCE.',409,'RECOVERY_KNOWLEDGE_DISPOSITION_REVIEW_GATE');const action=String(req.body?.proposed_action||'').toUpperCase(),proposer=text(req.body?.proposer_label,120),note=text(req.body?.proposal_note,1600),evidence=refs(req.body?.proposal_evidence_refs),target=text(req.body?.superseding_lesson_id,36)||null;if(!['RETAIN','RETIRE','SUPERSEDE'].includes(action))throw err('proposed_action must be RETAIN, RETIRE, or SUPERSEDE.');if(!proposer||!note||!evidence.length)throw err('Proposer, proposal rationale, and evidence references are required.');if(action==='SUPERSEDE')await validateSuperseding(userId,lessonId,target);let current=await row(userId,lessonId),id=current?.id||crypto.randomUUID(),db=await pool.getConnection();try{await db.beginTransaction();if(current){await db.query('UPDATE personal_finance_recovery_knowledge_dispositions SET proposed_action=?,proposer_label=?,proposal_note=?,proposal_evidence_refs_json=?,superseding_lesson_id=?,status=\'PENDING\',decision=NULL,decision_maker_label=NULL,decision_note=NULL,decision_evidence_refs_json=NULL,decided_at=NULL WHERE id=? AND user_id=?',[action,proposer,note,JSON.stringify(evidence),action==='SUPERSEDE'?target:null,id,userId]);}else{await db.query('INSERT INTO personal_finance_recovery_knowledge_dispositions (id,user_id,lesson_id,proposed_action,proposer_label,proposal_note,proposal_evidence_refs_json,superseding_lesson_id) VALUES (?,?,?,?,?,?,?,?)',[id,userId,lessonId,action,proposer,note,JSON.stringify(evidence),action==='SUPERSEDE'?target:null]);}await event(db,userId,id,lessonId,'KNOWLEDGE_DISPOSITION_PROPOSED',{proposed_action:action,proposer_label:proposer,evidence_ref_count:evidence.length,superseding_lesson_id:action==='SUPERSEDE'?target:null,lesson_modified:false,financial_records_changed:false});await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}return res.json({knowledge_disposition:view(await row(userId,lessonId)),lesson_modified:false,lesson_deleted:false,automatic_decision:false,financial_records_changed:false});}
async function decide(req,res){const userId=uid(req),lessonId=text(req.body?.lesson_id,36);await reusableLesson(userId,lessonId);const current=await row(userId,lessonId);if(!current||current.status!=='PENDING')throw err('A pending disposition proposal is required before decision.',409,'RECOVERY_KNOWLEDGE_DISPOSITION_PROPOSAL_REQUIRED');const decision=String(req.body?.decision||'').toUpperCase(),maker=text(req.body?.decision_maker_label,120),note=text(req.body?.decision_note,1600),evidence=refs(req.body?.decision_evidence_refs);if(!['RETAIN','RETIRE','SUPERSEDE'].includes(decision))throw err('decision must be RETAIN, RETIRE, or SUPERSEDE.');if(decision!==current.proposed_action)throw err('Decision must resolve the currently proposed action. Submit a new proposal to change the requested disposition.',409,'RECOVERY_KNOWLEDGE_DISPOSITION_DECISION_MISMATCH');if(!maker||!note||!evidence.length)throw err('Independent decision maker, decision rationale, and evidence references are required.');if(maker.toLowerCase()===String(current.proposer_label||'').trim().toLowerCase())throw err('Decision maker must be different from the proposer.',409,'RECOVERY_KNOWLEDGE_DISPOSITION_INDEPENDENCE_REQUIRED');if(decision==='SUPERSEDE')await validateSuperseding(userId,lessonId,current.superseding_lesson_id);const db=await pool.getConnection();try{await db.beginTransaction();await db.query('UPDATE personal_finance_recovery_knowledge_dispositions SET status=\'DECIDED\',decision=?,decision_maker_label=?,decision_note=?,decision_evidence_refs_json=?,decided_at=NOW(3) WHERE id=? AND user_id=?',[decision,maker,note,JSON.stringify(evidence),current.id,userId]);await event(db,userId,current.id,lessonId,'KNOWLEDGE_DISPOSITION_DECIDED',{decision,decision_maker_label:maker,evidence_ref_count:evidence.length,superseding_lesson_id:decision==='SUPERSEDE'?current.superseding_lesson_id:null,lesson_modified:false,lesson_deleted:false,automatic_decision:false,financial_records_changed:false});await db.commit();}catch(e){await db.rollback().catch(()=>{});throw e;}finally{db.release();}return res.json({knowledge_disposition:view(await row(userId,lessonId)),lesson_modified:false,lesson_deleted:false,automatic_decision:false,financial_records_changed:false});}
exports.action=async(req,res)=>{try{const action=String(req.body?.knowledge_disposition_action||'').toUpperCase();if(action==='PROPOSE')return await propose(req,res);if(action==='DECIDE')return await decide(req,res);throw err('knowledge_disposition_action must be PROPOSE or DECIDE.');}catch(e){return fail(res,e);}};
exports.history=async(req,res)=>{try{const userId=uid(req),lessonId=text(req.query?.lesson_id,36);await reusableLesson(userId,lessonId);const current=await row(userId,lessonId);if(!current)return res.json({lesson_id:lessonId,events:[]});const [rows]=await pool.query('SELECT id,event_type,event_json,created_at FROM personal_finance_recovery_knowledge_disposition_events WHERE user_id=? AND disposition_id=? ORDER BY id ASC',[userId,current.id]);return res.json({lesson_id:lessonId,disposition_id:current.id,events:rows.map(x=>({id:x.id,event_type:x.event_type,event:parse(x.event_json,{}),created_at:x.created_at}))});}catch(e){return fail(res,e);}};
exports._test={view,refs};
