const pool = require('../config/db');

function uid(req){const v=req.user?.id??req.user?.user_id;if(v===undefined||v===null||v==='')throw Object.assign(new Error('User identity unavailable.'),{statusCode:401});return String(v);}
function fail(res,error,message){const status=Number(error?.statusCode||500);if(status>=500)console.error(message,error);return res.status(status).json({message:status>=500?message:error.message});}
function num(v,label,{min=0,max=1e12,required=true}={}){if((v===''||v===null||v===undefined)&&!required)return null;const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)throw Object.assign(new Error(`${label} is invalid.`),{statusCode:400});return n;}
function currency(v){const c=String(v||'AUD').trim().toUpperCase();if(!/^[A-Z]{3}$/.test(c))throw Object.assign(new Error('Currency must be a three-letter code.'),{statusCode:400});return c;}
function round(v,d=2){const f=10**d;return Math.round((Number(v||0)+Number.EPSILON)*f)/f;}
function monthsBetween(date){if(!date)return null;const target=new Date(`${date}T00:00:00Z`);if(Number.isNaN(target.getTime()))return null;const now=new Date();let months=(target.getUTCFullYear()-now.getUTCFullYear())*12+(target.getUTCMonth()-now.getUTCMonth());if(target.getUTCDate()>now.getUTCDate())months+=1;return Math.max(0,months);}
function futureValue(start,monthly,annualPct,months){const r=(annualPct/100)/12;if(months<=0)return start;if(Math.abs(r)<1e-12)return start+monthly*months;return start*((1+r)**months)+monthly*(((1+r)**months-1)/r);}
function payoff(balance,annualPct,payment){if(balance<=0)return {months:0,total_interest:0,total_paid:0};const r=(annualPct/100)/12;if(payment<=0)throw Object.assign(new Error('Monthly repayment must be greater than zero.'),{statusCode:400});if(r>0&&payment<=balance*r)throw Object.assign(new Error('Monthly repayment is too low to reduce this balance at the entered interest rate.'),{statusCode:400});let b=balance,interest=0,months=0;while(b>0.005&&months<1200){const i=b*r;interest+=i;b=Math.max(0,b+i-payment);months+=1;}if(months>=1200&&b>0.005)throw Object.assign(new Error('This scenario takes longer than 100 years. Increase the repayment or check the assumptions.'),{statusCode:400});return {months,total_interest:round(interest),total_paid:round(balance+interest)};}

exports.getCenter=async(req,res)=>{try{const u=uid(req);const [balances,assets,liabilities,goals,buffers,spend]=await Promise.all([
 pool.query(`SELECT currency,COALESCE(SUM(COALESCE(available_balance,current_ledger_balance,0)),0) bank_balance FROM bank_accounts WHERE created_by=? AND ownership_scope='PERSONAL' AND status='ACTIVE' GROUP BY currency`,[u]).then(([r])=>r),
 pool.query(`SELECT id,asset_type,name,currency,current_value FROM personal_net_worth_assets WHERE user_id=? AND active=1 AND asset_type IN ('SUPER','INVESTMENT','PROPERTY') ORDER BY current_value DESC`,[u]).then(([r])=>r),
 pool.query(`SELECT id,liability_type,name,currency,current_balance,interest_rate_percent,minimum_payment FROM personal_net_worth_liabilities WHERE user_id=? AND active=1 ORDER BY current_balance DESC`,[u]).then(([r])=>r),
 pool.query(`SELECT id,name,currency,target_amount,current_amount,target_date FROM personal_money_goals WHERE user_id=? AND status='ACTIVE' ORDER BY target_date IS NULL,target_date`,[u]).then(([r])=>r),
 pool.query(`SELECT currency,reserve_amount FROM personal_money_safety_buffers WHERE user_id=?`,[u]).then(([r])=>r),
 pool.query(`SELECT bt.currency,COALESCE(SUM(bt.debit),0)/3 avg_monthly_spend FROM bank_transactions bt JOIN bank_accounts ba ON ba.id=bt.bank_account_id WHERE ba.created_by=? AND ba.ownership_scope='PERSONAL' AND bt.ownership_scope='PERSONAL' AND bt.is_internal_transfer=0 AND bt.debit>0 AND bt.transaction_date>=DATE_SUB(CURRENT_DATE,INTERVAL 90 DAY) GROUP BY bt.currency`,[u]).then(([r])=>r)
 ]);
 const context={};const ensure=(c)=>context[c]||(context[c]={currency:c,bank_balance:0,safety_buffer:0,average_monthly_spending_90d:0});
 balances.forEach(r=>ensure(currency(r.currency)).bank_balance=round(r.bank_balance));buffers.forEach(r=>ensure(currency(r.currency)).safety_buffer=round(r.reserve_amount));spend.forEach(r=>ensure(currency(r.currency)).average_monthly_spending_90d=round(r.avg_monthly_spend));
 return res.json({privacy:'Owner-private planning context uses only the signed-in user’s PERSONAL money and Net Worth records.',currency_rule:'Currencies are never combined or converted automatically.',warning:'Planning results are illustrations based on the assumptions shown. They are not guaranteed outcomes, market valuations, tax advice or financial advice.',context_by_currency:context,assets:assets.map(r=>({...r,current_value:Number(r.current_value||0)})),liabilities:liabilities.map(r=>({...r,current_balance:Number(r.current_balance||0),interest_rate_percent:r.interest_rate_percent===null?null:Number(r.interest_rate_percent),minimum_payment:r.minimum_payment===null?null:Number(r.minimum_payment)})),goals:goals.map(r=>({...r,target_amount:Number(r.target_amount||0),current_amount:Number(r.current_amount||0),months_remaining:monthsBetween(r.target_date)}))});
}catch(e){return fail(res,e,'Failed to load Wealth Planning Center.');}};

exports.simulate=async(req,res)=>{try{uid(req);const kind=String(req.body.kind||'').toUpperCase();const code=currency(req.body.currency);let result;
 if(kind==='GOAL'){
  const target=num(req.body.target_amount,'Target amount'),current=num(req.body.current_amount,'Current amount'),months=Math.round(num(req.body.months,'Months',{min:1,max:1200}));const gap=Math.max(0,target-current);result={kind,currency:code,target_amount:round(target),current_amount:round(current),gap:round(gap),months,required_monthly:round(gap/months),assumptions:['No investment return is assumed in this goal calculation.','No inflation, fees or tax are included.']};
 }else if(kind==='LOAN'){
  const balance=num(req.body.balance,'Loan balance'),annual=num(req.body.annual_rate_percent,'Annual interest rate',{min:0,max:100}),payment=num(req.body.monthly_payment,'Monthly repayment',{min:0.01});const p=payoff(balance,annual,payment);result={kind,currency:code,balance:round(balance),annual_rate_percent:round(annual,3),monthly_payment:round(payment),...p,estimated_years:round(p.months/12,1),assumptions:['Interest is modelled monthly at the entered annual rate.','The rate, repayment and fees are assumed not to change.','Extra fees, redraws and lender-specific calculation rules are not included.']};
 }else if(kind==='GROWTH'||kind==='SUPER'){
  const start=num(req.body.starting_balance,'Starting balance'),monthly=num(req.body.monthly_contribution,'Monthly contribution'),annual=num(req.body.annual_return_percent,'Annual return',{min:0,max:50}),years=num(req.body.years,'Years',{min:0.1,max:80}),months=Math.round(years*12),fv=futureValue(start,monthly,annual,months),contributed=start+monthly*months;result={kind,currency:code,starting_balance:round(start),monthly_contribution:round(monthly),annual_return_percent:round(annual,2),years:round(years,1),projected_value:round(fv),contributions:round(contributed),illustrative_growth:round(fv-contributed),assumptions:['Return is an entered assumption, not a forecast or guaranteed rate.','A constant monthly compounded return is used.','Inflation, tax, fees, insurance premiums and market volatility are not modelled.']};
 }else if(kind==='EMERGENCY'){
  const monthly=num(req.body.monthly_spending,'Monthly spending'),months=num(req.body.coverage_months,'Coverage months',{min:1,max:24}),available=num(req.body.available_cash,'Available liquid funds');const target=monthly*months;result={kind,currency:code,monthly_spending:round(monthly),coverage_months:round(months,1),target:round(target),available_cash:round(available),gap:round(Math.max(0,target-available)),coverage_now_months:monthly>0?round(available/monthly,1):null,assumptions:['Uses the monthly spending amount you entered.','Does not assume future income, investment access or borrowing capacity.']};
 }else throw Object.assign(new Error('Choose a valid scenario: GOAL, LOAN, GROWTH, SUPER or EMERGENCY.'),{statusCode:400});
 return res.json({message:'Scenario calculated. No balances, payments or accounting records were changed.',result});
}catch(e){return fail(res,e,'Failed to calculate wealth scenario.');}};
