const crypto = require('crypto');
const pool = require('../config/db');
const { ensureQmsEnterpriseCompletionSchema } = require('../services/qmsEnterpriseCompletionSchema');
const { ensureQmsAdvancedSchema } = require('../services/qmsAdvancedSchema');
const { ensureQmsQualityGovernanceSchema } = require('../services/qmsQualityGovernanceSchema');
const { logAudit } = require('../services/auditService');
function actor(req){return Number(req.user?.id||req.user?.user_id||0)||null}
function clean(v,max=4000){return String(v??'').trim().slice(0,max)}
function seq(prefix,id){return `${prefix}-${new Date().getUTCFullYear()}-${String(id).padStart(6,'0')}`}
function audit(req){return{actorId:actor(req),ipAddress:req.ip,userAgent:req.get('user-agent'),requestId:req.id||req.get('x-request-id')||null,sessionId:req.session?.id||null}}
async function ready(){await ensureQmsAdvancedSchema();await ensureQmsQualityGovernanceSchema();await ensureQmsEnterpriseCompletionSchema()}

async function commandCentre(req,res,next){try{await ready();const q=async(sql,p=[])=>Number((await pool.query(sql,p))[0][0]?.n||0);const metrics={openNcr:await q("SELECT COUNT(*) n FROM ncrs WHERE status<>'CLOSED'"),openCapa:await q("SELECT COUNT(*) n FROM capas WHERE status<>'CLOSED'"),qualityHolds:await q("SELECT COUNT(*) n FROM quality_holds WHERE released_at IS NULL"),overdueCalibration:await q("SELECT COUNT(*) n FROM measurement_equipment WHERE status='ACTIVE' AND next_due IS NOT NULL AND next_due<CURDATE()"),overdueMaintenance:await q("SELECT COUNT(*) n FROM maintenance_work_orders WHERE status NOT IN('COMPLETE','CANCELLED') AND due_at<NOW()"),trainingDue:await q("SELECT COUNT(*) n FROM employee_competencies WHERE status='ACTIVE' AND expires_at IS NOT NULL AND expires_at<DATE_ADD(NOW(),INTERVAL 30 DAY)"),openScars:await q("SELECT COUNT(*) n FROM supplier_scars WHERE status<>'CLOSED'"),openAuditFindings:await q("SELECT COUNT(*) n FROM audit_findings WHERE status<>'CLOSED'"),documentReviewsDue:await q("SELECT COUNT(*) n FROM controlled_documents WHERE next_review IS NOT NULL AND next_review<=DATE_ADD(CURDATE(),INTERVAL 30 DAY)"),activeVisitors:await q("SELECT COUNT(*) n FROM site_visitors WHERE checked_out_at IS NULL"),openRegulatoryReviews:await q("SELECT COUNT(*) n FROM regulatory_reviews WHERE status IN('PENDING','UNDER_REVIEW','ESCALATED')"),unacknowledgedNotifications:await q("SELECT COUNT(*) n FROM qms_notifications WHERE acknowledged_at IS NULL")};return res.json({metrics,generated_at:new Date().toISOString()})}catch(e){return next(e)}}

async function createAudit(req,res,next){try{await ready();if(!clean(req.body.title,255))return res.status(400).json({message:'title is required.'});const [r]=await pool.query('INSERT INTO internal_audits(audit_no,title,scope,criteria,auditor_user_id,area_owner_user_id,scheduled_at,created_by) VALUES(NULL,?,?,?,?,?,?,?)',[clean(req.body.title,255),clean(req.body.scope),clean(req.body.criteria),req.body.auditor_user_id||null,req.body.area_owner_user_id||null,req.body.scheduled_at||null,actor(req)]);const no=seq('AUD',r.insertId);await pool.query('UPDATE internal_audits SET audit_no=? WHERE id=?',[no,r.insertId]);await logAudit(pool,{...audit(req),action:'QMS_AUDIT_CREATED',module:'QMS',recordType:'INTERNAL_AUDIT',recordId:no,newValue:{title:clean(req.body.title,255)}});return res.status(201).json({id:r.insertId,audit_no:no,status:'PLANNED'})}catch(e){return next(e)}}
async function listAudits(req,res,next){try{await ready();const [rows]=await pool.query('SELECT * FROM internal_audits ORDER BY created_at DESC LIMIT 300');return res.json({audits:rows})}catch(e){return next(e)}}
async function addAuditFinding(req,res,next){try{await ready();if(!clean(req.body.finding,4000))return res.status(400).json({message:'finding is required.'});const type=clean(req.body.finding_type,20).toUpperCase()||'OFI';const [r]=await pool.query('INSERT INTO audit_findings(audit_id,finding_no,finding_type,requirement_ref,evidence,finding,capa_id,owner_user_id,due_date,created_by) VALUES(?,NULL,?,?,?,?,?,?,?,?,?)',[req.params.id,type,clean(req.body.requirement_ref,255)||null,clean(req.body.evidence)||null,clean(req.body.finding),req.body.capa_id||null,req.body.owner_user_id||null,req.body.due_date||null,actor(req)]);const no=seq('FND',r.insertId);await pool.query('UPDATE audit_findings SET finding_no=? WHERE id=?',[no,r.insertId]);return res.status(201).json({id:r.insertId,finding_no:no,status:'OPEN'})}catch(e){return next(e)}}

async function createManagementReview(req,res,next){try{await ready();const title=clean(req.body.title,255)||'Management Review';const inputs={customer_feedback:req.body.customer_feedback||null,quality_kpis:req.body.quality_kpis||null,ncr_capa_trends:req.body.ncr_capa_trends||null,supplier_performance:req.body.supplier_performance||null,audit_results:req.body.audit_results||null,resources_capacity:req.body.resources_capacity||null,risks_opportunities:req.body.risks_opportunities||null,qms_changes:req.body.qms_changes||null,improvements:req.body.improvements||null};const [r]=await pool.query('INSERT INTO management_reviews(review_no,title,period_start,period_end,scheduled_at,status,inputs_json,chair_user_id,created_by) VALUES(NULL,?,?,?,?,\'DRAFT\',?,?,?)',[title,req.body.period_start||null,req.body.period_end||null,req.body.scheduled_at||null,JSON.stringify(inputs),req.body.chair_user_id||null,actor(req)]);const no=seq('MR',r.insertId);await pool.query('UPDATE management_reviews SET review_no=? WHERE id=?',[no,r.insertId]);return res.status(201).json({id:r.insertId,review_no:no,status:'DRAFT'})}catch(e){return next(e)}}
async function listManagementReviews(req,res,next){try{await ready();const [rows]=await pool.query('SELECT * FROM management_reviews ORDER BY created_at DESC LIMIT 200');return res.json({reviews:rows})}catch(e){return next(e)}}

async function createChemical(req,res,next){try{await ready();if(!clean(req.body.product_name,255))return res.status(400).json({message:'product_name is required.'});const [r]=await pool.query('INSERT INTO chemical_products(chemical_code,product_name,manufacturer,supplier_id,hazard_classification,dg_classification,maximum_quantity,current_quantity,unit,storage_location,ppe_requirements,spill_controls,responsible_user_id) VALUES(NULL,?,?,?,?,?,?,?,?,?,?,?,?)',[clean(req.body.product_name,255),clean(req.body.manufacturer,255)||null,req.body.supplier_id||null,clean(req.body.hazard_classification,500)||null,clean(req.body.dg_classification,255)||null,req.body.maximum_quantity??null,req.body.current_quantity??0,clean(req.body.unit,30)||null,clean(req.body.storage_location,255)||null,clean(req.body.ppe_requirements)||null,clean(req.body.spill_controls)||null,req.body.responsible_user_id||null]);const code=seq('CHEM',r.insertId);await pool.query('UPDATE chemical_products SET chemical_code=? WHERE id=?',[code,r.insertId]);return res.status(201).json({id:r.insertId,chemical_code:code,status:'ACTIVE'})}catch(e){return next(e)}}
async function listChemicals(req,res,next){try{await ready();const [rows]=await pool.query(`SELECT c.*,s.version_label sds_version,s.issue_date sds_issue_date,s.review_due sds_review_due,s.status sds_status FROM chemical_products c LEFT JOIN sds_versions s ON s.id=(SELECT s2.id FROM sds_versions s2 WHERE s2.chemical_id=c.id ORDER BY s2.id DESC LIMIT 1) ORDER BY c.product_name`);const warnings=rows.filter(x=>x.maximum_quantity!==null&&Number(x.current_quantity)>Number(x.maximum_quantity)).map(x=>({chemical_code:x.chemical_code,message:'Configured internal maximum quantity exceeded; compliance review required.'}));return res.json({chemicals:rows,warnings,advisory:'Automated quantity warnings are internal review triggers and are not definitive legal or dangerous-goods advice.'})}catch(e){return next(e)}}

async function checkInVisitor(req,res,next){try{await ready();if(!clean(req.body.visitor_name,255))return res.status(400).json({message:'visitor_name is required.'});const uuid=crypto.randomUUID();const [r]=await pool.query('INSERT INTO site_visitors(visit_uuid,visitor_name,company,visitor_type,host_user_id,purpose,nda_required,induction_required,induction_completed,permitted_zones_json,badge_no,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[uuid,clean(req.body.visitor_name,255),clean(req.body.company,255)||null,clean(req.body.visitor_type,20).toUpperCase()==='CONTRACTOR'?'CONTRACTOR':'VISITOR',req.body.host_user_id||null,clean(req.body.purpose,1000)||null,req.body.nda_required?1:0,req.body.induction_required?1:0,req.body.induction_completed?1:0,JSON.stringify(req.body.permitted_zones||[]),clean(req.body.badge_no,80)||null,actor(req)]);return res.status(201).json({id:r.insertId,visit_uuid:uuid,checked_in:true})}catch(e){return next(e)}}
async function checkOutVisitor(req,res,next){try{await ready();const [r]=await pool.query('UPDATE site_visitors SET checked_out_at=NOW() WHERE id=? AND checked_out_at IS NULL',[req.params.id]);if(!r.affectedRows)return res.status(404).json({message:'Active visitor record not found.'});return res.json({id:Number(req.params.id),checked_out:true})}catch(e){return next(e)}}
async function activeVisitors(req,res,next){try{await ready();const [rows]=await pool.query('SELECT * FROM site_visitors WHERE checked_out_at IS NULL ORDER BY checked_in_at');return res.json({visitors:rows})}catch(e){return next(e)}}

async function startEmergency(req,res,next){try{await ready();const title=clean(req.body.title,255)||'Emergency / Evacuation';const type=['DRILL','EVACUATION','FIRE','CHEMICAL_SPILL','OTHER'].includes(clean(req.body.event_type,30).toUpperCase())?clean(req.body.event_type,30).toUpperCase():'OTHER';const [r]=await pool.query('INSERT INTO emergency_events(event_no,event_type,title,assembly_point,started_by) VALUES(NULL,?,?,?,?)',[type,title,clean(req.body.assembly_point,255)||null,actor(req)]);const no=seq('EMG',r.insertId);await pool.query('UPDATE emergency_events SET event_no=? WHERE id=?',[no,r.insertId]);const [visitors]=await pool.query('SELECT id,visitor_name,visitor_type FROM site_visitors WHERE checked_out_at IS NULL');for(const v of visitors)await pool.query('INSERT IGNORE INTO emergency_rollcall(emergency_event_id,person_type,person_ref,display_name) VALUES(?,?,?,?)',[r.insertId,v.visitor_type,String(v.id),v.visitor_name]);const [staff]=await pool.query(`SELECT DISTINCT u.id,u.name FROM users u LEFT JOIN attendance a ON a.user_id=u.id WHERE u.status='active'`);for(const s of staff)await pool.query('INSERT IGNORE INTO emergency_rollcall(emergency_event_id,person_type,person_ref,display_name) VALUES(?,?,?,?)',[r.insertId,'STAFF',String(s.id),s.name||`User ${s.id}`]);return res.status(201).json({id:r.insertId,event_no:no,status:'ACTIVE',rollcall_count:visitors.length+staff.length})}catch(e){return next(e)}}
async function emergencyRollcall(req,res,next){try{await ready();const [rows]=await pool.query('SELECT * FROM emergency_rollcall WHERE emergency_event_id=? ORDER BY person_type,display_name',[req.params.id]);const summary=rows.reduce((a,x)=>{a.total++;if(x.accounted)a.accounted++;else a.missing++;return a},{total:0,accounted:0,missing:0});return res.json({rollcall:rows,summary})}catch(e){return next(e)}}
async function markAccounted(req,res,next){try{await ready();const [r]=await pool.query('UPDATE emergency_rollcall SET accounted=1,accounted_by=?,accounted_at=NOW() WHERE id=?',[actor(req),req.params.itemId]);if(!r.affectedRows)return res.status(404).json({message:'Roll-call item not found.'});return res.json({accounted:true})}catch(e){return next(e)}}

async function createCriticalService(req,res,next){try{await ready();if(!clean(req.body.service_name,255))return res.status(400).json({message:'service_name is required.'});const [r]=await pool.query('INSERT INTO critical_services(service_code,service_name,owner_user_id,criticality,rto_minutes,rpo_minutes,dependency_json,alternate_method) VALUES(NULL,?,?,?,?,?,?,?)',[clean(req.body.service_name,255),req.body.owner_user_id||null,clean(req.body.criticality,20).toUpperCase()||'MEDIUM',req.body.rto_minutes??null,req.body.rpo_minutes??null,JSON.stringify(req.body.dependencies||[]),clean(req.body.alternate_method)||null]);const code=seq('SVC',r.insertId);await pool.query('UPDATE critical_services SET service_code=? WHERE id=?',[code,r.insertId]);return res.status(201).json({id:r.insertId,service_code:code})}catch(e){return next(e)}}
async function listContinuity(req,res,next){try{await ready();const [services]=await pool.query('SELECT * FROM critical_services ORDER BY criticality DESC,service_name');const [exercises]=await pool.query('SELECT * FROM continuity_exercises ORDER BY performed_at DESC LIMIT 200');return res.json({services,exercises,assurance_note:'Backup/restore configuration is not treated as successful evidence unless an actual exercise/evidence record exists.'})}catch(e){return next(e)}}
async function recordContinuityExercise(req,res,next){try{await ready();if(!clean(req.body.scenario))return res.status(400).json({message:'scenario is required.'});const [r]=await pool.query('INSERT INTO continuity_exercises(exercise_no,service_id,exercise_type,scenario,result,actual_rto_minutes,actual_rpo_minutes,evidence_ref,lessons,performed_by,next_due) VALUES(NULL,?,?,?,?,?,?,?,?,?,?)',[req.body.service_id||null,clean(req.body.exercise_type,30).toUpperCase()||'TABLETOP',clean(req.body.scenario),clean(req.body.result,20).toUpperCase()||'PARTIAL',req.body.actual_rto_minutes??null,req.body.actual_rpo_minutes??null,clean(req.body.evidence_ref,255)||null,clean(req.body.lessons)||null,actor(req),req.body.next_due||null]);const no=seq('BCP',r.insertId);await pool.query('UPDATE continuity_exercises SET exercise_no=? WHERE id=?',[no,r.insertId]);return res.status(201).json({id:r.insertId,exercise_no:no})}catch(e){return next(e)}}

async function createRegulatoryReview(req,res,next){try{await ready();const sector=['GENERAL','AEROSPACE','DEFENCE','MEDICAL','AUTOMOTIVE','OTHER'].includes(clean(req.body.sector,20).toUpperCase())?clean(req.body.sector,20).toUpperCase():'GENERAL';const flags={sensitive_technical_data:Boolean(req.body.sensitive_technical_data),export_review_required:Boolean(req.body.export_review_required),customer_confidential:Boolean(req.body.customer_confidential),medical_review_required:Boolean(req.body.medical_review_required),aerospace_quality_requirements:Boolean(req.body.aerospace_quality_requirements)};const status=(flags.export_review_required||flags.medical_review_required||sector==='DEFENCE')?'ESCALATED':'PENDING';const [r]=await pool.query('INSERT INTO regulatory_reviews(review_no,job_id,rfq_id,sector,sensitive_technical_data,export_review_required,customer_confidential,medical_review_required,aerospace_quality_requirements,status,created_by) VALUES(NULL,?,?,?,?,?,?,?,?,?,?)',[req.body.job_id||null,req.body.rfq_id||null,sector,flags.sensitive_technical_data?1:0,flags.export_review_required?1:0,flags.customer_confidential?1:0,flags.medical_review_required?1:0,flags.aerospace_quality_requirements?1:0,status,actor(req)]);const no=seq('REG',r.insertId);await pool.query('UPDATE regulatory_reviews SET review_no=? WHERE id=?',[no,r.insertId]);return res.status(201).json({id:r.insertId,review_no:no,status,sector,certification_claims:false})}catch(e){return next(e)}}
async function listRegulatoryReviews(req,res,next){try{await ready();const [rows]=await pool.query('SELECT * FROM regulatory_reviews ORDER BY created_at DESC LIMIT 300');return res.json({reviews:rows,notice:'Sector/review gates do not represent ISO 9001, AS9100, ISO 13485, DISP, TGA/ARTG or export-control certification/approval.'})}catch(e){return next(e)}}
async function decideRegulatoryReview(req,res,next){try{await ready();const status=clean(req.body.status,30).toUpperCase();if(!['CLEARED','RESTRICTED','ESCALATED'].includes(status))return res.status(400).json({message:'status must be CLEARED, RESTRICTED or ESCALATED.'});if(!clean(req.body.decision_basis))return res.status(400).json({message:'decision_basis is required.'});await pool.query('UPDATE regulatory_reviews SET status=?,decision_basis=?,reviewer_user_id=?,reviewed_at=NOW() WHERE id=?',[status,clean(req.body.decision_basis),actor(req),req.params.id]);await logAudit(pool,{...audit(req),action:'REGULATORY_REVIEW_DECIDED',module:'QMS',recordType:'REGULATORY_REVIEW',recordId:String(req.params.id),newValue:{status,decisionBasis:clean(req.body.decision_basis,500)}});return res.json({id:Number(req.params.id),status})}catch(e){return next(e)}}

async function generateNotifications(req,res,next){try{await ready();const inserts=[];const add=async(key,type,severity,title,body,recordType,recordId,dueAt)=>{await pool.query('INSERT IGNORE INTO qms_notifications(dedupe_key,notification_type,severity,title,body,record_type,record_id,due_at) VALUES(?,?,?,?,?,?,?,?)',[key,type,severity,title,body,recordType,recordId,dueAt||null]);inserts.push(key)};const [cal]=await pool.query("SELECT id,equipment_code,next_due FROM measurement_equipment WHERE status='ACTIVE' AND next_due<=DATE_ADD(CURDATE(),INTERVAL 30 DAY)");for(const x of cal)await add(`cal:${x.id}:${x.next_due}`,'CALIBRATION_DUE',x.next_due<new Date()?'HIGH':'WARNING',`Calibration due: ${x.equipment_code}`,'Measurement equipment requires calibration review.','MEASUREMENT_EQUIPMENT',String(x.id),x.next_due);const [maint]=await pool.query("SELECT id,work_order_no,due_at FROM maintenance_work_orders WHERE status NOT IN('COMPLETE','CANCELLED') AND due_at<=DATE_ADD(NOW(),INTERVAL 14 DAY)");for(const x of maint)await add(`maint:${x.id}:${x.due_at}`,'MAINTENANCE_DUE',new Date(x.due_at)<new Date()?'HIGH':'WARNING',`Maintenance due: ${x.work_order_no}`,'Maintenance work order requires attention.','MAINTENANCE',String(x.id),x.due_at);const [capa]=await pool.query("SELECT id,capa_no,due_date FROM capas WHERE status<>'CLOSED' AND due_date IS NOT NULL AND due_date<=DATE_ADD(CURDATE(),INTERVAL 14 DAY)");for(const x of capa)await add(`capa:${x.id}:${x.due_date}`,'CAPA_DUE',new Date(x.due_date)<new Date()?'HIGH':'WARNING',`CAPA due: ${x.capa_no}`,'Corrective action requires review.','CAPA',String(x.id),x.due_date);return res.json({generated:inserts.length})}catch(e){return next(e)}}
async function listNotifications(req,res,next){try{await ready();const [rows]=await pool.query('SELECT * FROM qms_notifications WHERE acknowledged_at IS NULL ORDER BY severity DESC,COALESCE(due_at,created_at) ASC LIMIT 300');return res.json({notifications:rows})}catch(e){return next(e)}}
async function acknowledgeNotification(req,res,next){try{await ready();await pool.query('UPDATE qms_notifications SET acknowledged_at=NOW(),acknowledged_by=? WHERE id=? AND acknowledged_at IS NULL',[actor(req),req.params.id]);return res.json({acknowledged:true})}catch(e){return next(e)}}

async function recallImpact(req,res,next){try{await ready();const lotId=Number(req.params.materialLotId);const [[lot]]=await pool.query('SELECT * FROM material_lots WHERE id=?',[lotId]);if(!lot)return res.status(404).json({message:'Material lot not found.'});const [genealogy]=await pool.query(`SELECT g.*,j.job_no,j.customer_id,j.part_no,j.part_description,j.status job_status,b.build_no,s.serial_no FROM material_genealogy g LEFT JOIN manufacturing_jobs j ON j.id=g.job_id LEFT JOIN job_builds b ON b.id=g.build_id LEFT JOIN job_serials s ON s.build_id=b.id WHERE g.material_lot_id=?`,[lotId]);const jobIds=[...new Set(genealogy.map(x=>x.job_id).filter(Boolean))];let releases=[],cocs=[];if(jobIds.length){const ph=jobIds.map(()=>'?').join(',');[releases]=await pool.query(`SELECT * FROM production_releases WHERE job_id IN (${ph})`,jobIds);[cocs]=await pool.query(`SELECT * FROM certificates_of_conformance WHERE job_id IN (${ph})`,jobIds)}const impact={material_lot:{id:lot.id,lot_no:lot.lot_no,material_code:lot.material_code,supplier_lot:lot.supplier_lot},jobs:genealogy,production_releases:releases,cocs,summary:{jobs:jobIds.length,builds:new Set(genealogy.map(x=>x.build_id).filter(Boolean)).size,serials:new Set(genealogy.map(x=>x.serial_no).filter(Boolean)).size,releases:releases.length,certificates:cocs.length,customers:new Set(genealogy.map(x=>x.customer_id).filter(Boolean)).size}};return res.json(impact)}catch(e){return next(e)}}

module.exports={commandCentre,createAudit,listAudits,addAuditFinding,createManagementReview,listManagementReviews,createChemical,listChemicals,checkInVisitor,checkOutVisitor,activeVisitors,startEmergency,emergencyRollcall,markAccounted,createCriticalService,listContinuity,recordContinuityExercise,createRegulatoryReview,listRegulatoryReviews,decideRegulatoryReview,generateNotifications,listNotifications,acknowledgeNotification,recallImpact};
