const crypto = require('crypto');
const pool = require('../config/db');
const { ensureQmsEnterpriseCompletionSchema } = require('../services/qmsEnterpriseCompletionSchema');
const { logAudit } = require('../services/auditService');
function actor(req){return Number(req.user?.id||req.user?.user_id||0)||null}
function clean(v,max=255){return String(v??'').trim().slice(0,max)}
async function list(req,res,next){try{await ensureQmsEnterpriseCompletionSchema();const [rows]=await pool.query('SELECT * FROM qms_evidence_index WHERE record_type=? AND record_id=? ORDER BY uploaded_at DESC',[clean(req.params.type,80),clean(req.params.id,80)]);return res.json({evidence:rows})}catch(e){return next(e)}}
async function register(req,res,next){try{await ensureQmsEnterpriseCompletionSchema();const recordType=clean(req.body.record_type,80).toUpperCase();const recordId=clean(req.body.record_id,80);const fileHash=clean(req.body.file_hash,64).toLowerCase();if(!recordType||!recordId||!/^[a-f0-9]{64}$/.test(fileHash))return res.status(400).json({message:'record_type, record_id and a valid SHA-256 file_hash are required.'});if(!req.body.secure_document_id)return res.status(400).json({message:'secure_document_id is required. Upload through the existing secure document system first; QMS does not create a second file-upload path.'});const uuid=crypto.randomUUID();const classification=['INTERNAL','CONFIDENTIAL','CUSTOMER_CONFIDENTIAL','RESTRICTED_TECHNICAL'].includes(clean(req.body.classification,40).toUpperCase())?clean(req.body.classification,40).toUpperCase():'INTERNAL';const [r]=await pool.query('INSERT INTO qms_evidence_index(evidence_uuid,record_type,record_id,secure_document_id,file_name,file_hash,classification,revision,malware_status,retention_class,uploaded_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[uuid,recordType,recordId,req.body.secure_document_id,clean(req.body.file_name,255)||null,fileHash,classification,clean(req.body.revision,50)||null,clean(req.body.malware_status,30).toUpperCase()||'PENDING',clean(req.body.retention_class,80)||null,actor(req)]);await logAudit(pool,{actorId:actor(req),ipAddress:req.ip,userAgent:req.get('user-agent'),requestId:req.id||req.get('x-request-id')||null,sessionId:req.session?.id||null,action:'QMS_EVIDENCE_REGISTERED',module:'QMS',recordType,recordId,newValue:{evidenceUuid:uuid,secureDocumentId:req.body.secure_document_id,fileHash,classification}});return res.status(201).json({id:r.insertId,evidence_uuid:uuid})}catch(e){return next(e)}}
module.exports={list,register};
