const pool = require('../config/db');
const { ensureQmsAdvancedSchema } = require('../services/qmsAdvancedSchema');
const { machineReadiness, operatorReadiness } = require('../services/qmsGateService');
const { logAudit } = require('../services/auditService');
function actor(req){return Number(req.user?.id||req.user?.user_id||0)||null}
function clean(v,max=500){return String(v??'').trim().slice(0,max)}
function audit(req){return{actorId:actor(req),ipAddress:req.ip,userAgent:req.get('user-agent'),requestId:req.id||req.get('x-request-id')||null,sessionId:req.session?.id||null}}
async function jobContext(req,res,next){try{await ensureQmsAdvancedSchema();const [[job]]=await pool.query('SELECT * FROM manufacturing_jobs WHERE id=? OR job_no=? LIMIT 1',[req.params.id,req.params.id]);if(!job)return res.status(404).json({message:'Job not found.'});const [operations]=await pool.query('SELECT * FROM job_operations WHERE job_id=? ORDER BY operation_no',[job.id]);const [materials]=await pool.query(`SELECT ml.id,ml.lot_no,ml.material_code,ml.grade,ml.release_status,a.quantity_allocated,a.quantity_consumed FROM job_material_allocations a JOIN material_lots ml ON ml.id=a.material_lot_id WHERE a.job_id=?`,[job.id]);const [builds]=await pool.query('SELECT id,build_no,machine_id,operator_user_id,status,started_at,completed_at FROM job_builds WHERE job_id=? ORDER BY id DESC',[job.id]);const [holds]=await pool.query("SELECT * FROM quality_holds WHERE active=1 AND ((entity_type='JOB' AND entity_id=?) OR (entity_type='BUILD' AND entity_id IN (SELECT CAST(id AS CHAR) FROM job_builds WHERE job_id=?)))",[String(job.id),job.id]);return res.json({job,operations,materials,builds,holds})}catch(e){return next(e)}}
async function machineContext(req,res,next){try{await ensureQmsAdvancedSchema();const gate=await machineReadiness(req.params.id);if(!gate.machine)return res.status(404).json(gate);const [plans]=await pool.query('SELECT id,maintenance_type,next_due_date,blocking_when_overdue,active FROM maintenance_plans WHERE equipment_id=? ORDER BY next_due_date',[gate.machine.id]);const [faults]=await pool.query("SELECT * FROM equipment_faults WHERE equipment_id=? AND status<>'RESOLVED' ORDER BY created_at DESC",[gate.machine.id]);const [loto]=await pool.query('SELECT * FROM loto_permits WHERE equipment_id=? AND active=1',[gate.machine.id]);return res.json({...gate,maintenance:plans,faults,loto})}catch(e){return next(e)}}
async function materialContext(req,res,next){try{await ensureQmsAdvancedSchema();const [[lot]]=await pool.query('SELECT * FROM material_lots WHERE id=? OR lot_no=? LIMIT 1',[req.params.id,req.params.id]);if(!lot)return res.status(404).json({message:'Material lot not found.'});const [genealogy]=await pool.query(`SELECT g.*,j.job_no,b.build_no,s.serial_no FROM material_genealogy g LEFT JOIN manufacturing_jobs j ON j.id=g.job_id LEFT JOIN job_builds b ON b.id=g.build_id LEFT JOIN job_serials s ON s.id=g.serial_id WHERE g.material_lot_id=? ORDER BY g.created_at DESC`,[lot.id]);const [holds]=await pool.query("SELECT * FROM quality_holds WHERE active=1 AND entity_type='MATERIAL_LOT' AND entity_id=?",[String(lot.id)]);return res.json({lot,genealogy,holds,usable:lot.release_status==='RELEASED'&&!holds.length})}catch(e){return next(e)}}
async function transitionOperation(req,res,next){try{await ensureQmsAdvancedSchema();const action=clean(req.body.action,20).toUpperCase();const [[op]]=await pool.query('SELECT jo.*,j.job_no,j.status job_status FROM job_operations jo JOIN manufacturing_jobs j ON j.id=jo.job_id WHERE jo.id=?',[req.params.id]);if(!op)return res.status(404).json({message:'Operation not found.'});const transitions={START:['READY','PLANNED'],PAUSE:['RUNNING'],RESUME:['PAUSED'],COMPLETE:['RUNNING','PAUSED']};if(!transitions[action]||!transitions[action].includes(op.status))return res.status(409).json({message:`Cannot ${action||'transition'} operation from ${op.status}.`});if(['START','RESUME'].includes(action)){
 if(!op.machine_id)return res.status(409).json({message:'A machine must be assigned before starting this operation.'});const machine=await machineReadiness(op.machine_id);if(!machine.allowed)return res.status(409).json({code:'MACHINE_GATE_BLOCKED',message:'Machine readiness gate blocked operation.',reasons:machine.reasons});const operator=await operatorReadiness(actor(req),op.machine_id,op.required_competency_code);if(!operator.allowed)return res.status(409).json({code:'OPERATOR_GATE_BLOCKED',message:'Operator competency/authorisation gate blocked operation.',reasons:operator.reasons});}
 const nextStatus={START:'RUNNING',PAUSE:'PAUSED',RESUME:'RUNNING',COMPLETE:'COMPLETE'}[action];const connection=await pool.getConnection();try{await connection.beginTransaction();await connection.query(`UPDATE job_operations SET status=?,actual_start=IF(?='START' AND actual_start IS NULL,NOW(),actual_start),actual_end=IF(?='COMPLETE',NOW(),actual_end) WHERE id=?`,[nextStatus,action,action,op.id]);await connection.query('INSERT INTO job_operation_events(job_operation_id,event_type,actor_id,metadata_json) VALUES(?,?,?,?)',[op.id,action,actor(req),JSON.stringify({note:clean(req.body.note,500)||null})]);if(['START','RESUME'].includes(action)){await connection.query("UPDATE manufacturing_jobs SET status='IN_PRODUCTION' WHERE id=? AND status NOT IN('QUALITY_HOLD','CANCELLED')",[op.job_id]);await connection.query("UPDATE equipment_assets SET status='RUNNING' WHERE id=?",[op.machine_id]);}if(action==='PAUSE'&&op.machine_id)await connection.query("UPDATE equipment_assets SET status='READY' WHERE id=? AND status='RUNNING'",[op.machine_id]);if(action==='COMPLETE'){if(op.machine_id)await connection.query("UPDATE equipment_assets SET status='READY' WHERE id=? AND status='RUNNING'",[op.machine_id]);const [[remaining]]=await connection.query("SELECT COUNT(*) n FROM job_operations WHERE job_id=? AND id<>? AND status<>'COMPLETE'",[op.job_id,op.id]);if(Number(remaining.n)===0)await connection.query("UPDATE manufacturing_jobs SET status='INSPECTION' WHERE id=? AND status='IN_PRODUCTION'",[op.job_id]);}
 await logAudit(connection,{...audit(req),action:`SHOP_FLOOR_OPERATION_${action}`,module:'QMS',recordType:'JOB_OPERATION',recordId:String(op.id),oldValue:{status:op.status},newValue:{status:nextStatus,jobNo:op.job_no,machineId:op.machine_id}});await connection.commit();return res.json({id:op.id,status:nextStatus,job_id:op.job_id})}catch(e){await connection.rollback();throw e}finally{connection.release()}
 }catch(e){return next(e)}}
module.exports={jobContext,machineContext,materialContext,transitionOperation};
