'use strict';
const fs=require('node:fs');
const path=require('node:path');
const snapshots=require('./financeReportSnapshotService');
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=value=>String(value||'').replace(/_/g,' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const date=value=>String(value||'').slice(0,10)||'—';
const amount=(value,currency)=>`${String(currency||'').toUpperCase()} ${new Intl.NumberFormat('en-AU',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value||0))}`.trim();
function originalLogoData(){return 'data:image/png;base64,'+fs.readFileSync(path.join(__dirname,'..','public','logo.png')).toString('base64');}
function table(title,headers,rows,{full=false,query={},key='page',reportId,anchor='transactions'}={}){
  const size=100,pages=Math.max(1,Math.ceil(rows.length/size));
  const page=Math.max(1,Math.min(pages,Math.floor(Number(query[key])||1)));
  const visible=full?rows:rows.slice((page-1)*size,page*size);
  const link=p=>{const params=new URLSearchParams(Object.entries(query).filter(([k,v])=>/^(page|category_page|merchant_page|section_page)$/.test(k)&&typeof v==='string'));params.set(key,String(p));return snapshots.reportPath(reportId)+'?'+params+'#'+anchor;};
  return `<section class="vr-card" id="${esc(anchor)}"><h2>${esc(title)}</h2><div class="vr-table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${visible.length?visible.map(row=>`<tr>${row.map((value,i)=>`<td data-label="${esc(headers[i])}">${esc(value)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">No data for this section.</td></tr>`}</tbody></table></div>${!full&&rows.length>size?`<nav class="vr-pages" aria-label="${esc(title)} pages">${page>1?`<a href="${esc(link(page-1))}">Previous</a>`:''}<span>Page ${page} of ${pages} · Rows ${(page-1)*size+1}–${Math.min(page*size,rows.length)} of ${rows.length}. Totals cover all records.</span>${page<pages?`<a href="${esc(link(page+1))}">Next</a>`:''}</nav>`:''}</section>`;
}
function sections(saved,options){
  const r=saved.report,m=r.metadata,o={...options,reportId:m.report_id};
  let content='';
  if(r.account_statement){const s=r.account_statement;content+=`<section class="vr-card"><h2>Account statement</h2><dl class="vr-meta"><div><dt>Account holder</dt><dd>${esc(s.account_holder)}</dd></div><div><dt>Account</dt><dd>${esc(s.account_name)} · ${esc(s.account_number_masked||'Masked')}</dd></div><div><dt>Opening balance</dt><dd>${esc(amount(s.opening_running_balance,s.currency))}</dd></div><div><dt>Closing balance</dt><dd>${esc(amount(s.closing_running_balance,s.currency))}</dd></div><div><dt>Total debits</dt><dd>${esc(amount(s.total_debits,s.currency))}</dd></div><div><dt>Total credits</dt><dd>${esc(amount(s.total_credits,s.currency))}</dd></div></dl></section>`;}
  const special={GST_SUMMARY:['GST review',['Currency','Treatment','Transactions','Gross expense','Recorded split GST'],(r.gst_summary||[]).map(x=>[x.currency,x.gst_treatment,x.transaction_count,amount(x.gross_expense,x.currency),amount(x.recorded_split_gst,x.currency)])],
    REIMBURSEMENT:['Reimbursements',['ID','Date','Account','Merchant','Currency','Requested','Paid','Remaining','Status'],(r.reimbursements||[]).map(x=>[x.reimbursement_uid,date(x.transaction_date),x.account_name,x.merchant_name||x.description,x.currency,amount(x.requested_amount,x.currency),amount(x.paid_amount,x.currency),amount(x.remaining_amount,x.currency),x.status])],
    RECONCILIATION:['Reconciliation',['Status','Transactions'],Object.entries(r.reconciliation_summary||{})],
    DATA_QUALITY:['Data quality',['Metric','Value'],Object.entries(r.data_quality||{}).map(([k,v])=>[label(k),v])]};
  if(special[m.report_type]){const [title,headers,rows]=special[m.report_type];content+=table(title,headers,rows,{...o,key:'section_page',anchor:'report-detail'});}
  if(['CASH_FLOW','INCOME_VS_EXPENSE','PERSONAL_MONTHLY_SUMMARY','COMPANY_MONTHLY_SUMMARY'].includes(m.report_type))
    content+=table('Monthly cash flow',['Month','Currency','Transactions','Money in','Ordinary money in','Refunds','Money out','Net cash flow'],(r.monthly||[]).map(x=>[x.month,x.currency,x.transaction_count,amount(x.money_in,x.currency),amount(x.ordinary_money_in,x.currency),amount(x.refund_inflow,x.currency),amount(x.money_out,x.currency),amount(x.net_cash_flow,x.currency)]),{...o,key:'section_page',anchor:'report-detail'});
  if(m.report_type==='CATEGORY'||(r.categories||[]).length)
    content+=table('Category analysis',['Currency','Category','Source transactions','Split lines','Spent'],(r.categories||[]).map(x=>[x.currency,x.category,x.source_transaction_count,x.split_line_count,amount(x.spent,x.currency)]),{...o,key:'category_page',anchor:'categories'});
  if(m.report_type==='MERCHANT')content+=table('Merchant analysis',['Currency','Merchant','Transactions','Spent','Received'],(r.merchants||[]).map(x=>[x.currency,x.merchant,x.transaction_count,amount(x.spent,x.currency),amount(x.received,x.currency)]),{...o,key:'merchant_page',anchor:'merchants'});
  if(!(r.transactions||[]).length)content+='<section class="vr-card vr-empty"><h2>No transactions in this period</h2><p>The saved report contains no transactions matching its filters.</p></section>';
  else content+=table('Transactions',['Date','Posting date','Account','Description','Reference','Category','Currency','Debit','Credit','Running balance','Reconciliation','Receipt'],r.transactions.map(t=>[date(t.transaction_date),date(t.posting_date),t.account_name,t.description||t.merchant_name,t.reference,t.category||'Unclassified',t.currency,amount(t.debit,t.currency),amount(t.credit,t.currency),t.running_balance==null?'Not supplied':amount(t.running_balance,t.currency),t.reconciliation_status,Number(t.has_receipt)?'Attached':'Missing']),{...o,anchor:'transactions'});
  return content;
}
function reportContent(saved,{full=false,query={},canExport=false}={}){
  const r=saved.report,m=r.metadata,d=snapshots.descriptor(saved.row),title=label(m.report_type);
  const selected=new Set((m.account_ids||[]).map(Number));
  const accounts=(r.coverage?.accounts||[]).filter(a=>!selected.size||selected.has(Number(a.account_id))).map(a=>a.account_name||a.account_id).join(', ')||'No permitted accounts';
  const filters=['transaction_type','category','merchant','source','reconciliation_status','receipt_status','q'].filter(k=>m[k]).map(k=>label(k)+': '+m[k]).join(' · ')||'None';
  const actionUrl=format=>`/api/finance/reports/snapshots/${encodeURIComponent(m.report_id)}/download/${format}`;
  const actions=canExport?`<div class="vr-actions" aria-label="Report actions"><button type="button" data-report-print="${esc(actionUrl('print'))}">Print / Save as PDF</button>${['html','csv','xlsx'].map(f=>`<a data-report-download href="${esc(actionUrl(f))}">Download ${f.toUpperCase()}</a>`).join('')}<a data-report-download href="${esc(actionUrl('pdf'))}">${d.pdf_status==='READY'?'Download PDF':d.pdf_status==='UNAVAILABLE'?'Retry PDF':'Generate PDF'}</a><button type="button" data-report-email="${esc(m.report_id)}">Email report</button></div>`:'';
  const summaries=(r.summary_by_currency||[]).map(x=>`<section class="vr-summary"><h2>${esc(x.currency)} summary</h2><dl><div><dt>Transactions</dt><dd>${esc(x.source_transaction_count)}</dd></div><div><dt>Money in</dt><dd>${esc(amount(x.money_in,x.currency))}</dd></div><div><dt>Money out</dt><dd>${esc(amount(x.money_out,x.currency))}</dd></div><div><dt>Net cash flow</dt><dd>${esc(amount(x.net_cash_flow,x.currency))}</dd></div><div><dt>Ordinary income</dt><dd>${esc(amount(x.ordinary_money_in,x.currency))}</dd></div><div><dt>Linked refunds</dt><dd>${esc(amount(x.linked_refund_inflow,x.currency))}</dd></div><div><dt>Transfer movement</dt><dd>${esc(amount(x.transfer_movement,x.currency))}</dd></div></dl></section>`).join('');
  return `<article class="vr-report" data-report-id="${esc(m.report_id)}"><header class="vr-heading"><img src="${esc(saved.profile?.logo_data_uri||'/logo.png')}" alt="Original Voxel Veda logo"><div><p>VOXEL VEDA FINANCE</p><h1>${esc(title)}</h1><span>Saved ${esc(m.generated_at)} · Immutable snapshot</span></div></header><section class="vr-card"><dl class="vr-meta"><div><dt>Report ID</dt><dd>${esc(m.report_id)}</dd></div><div><dt>Period</dt><dd>${esc(m.from||'All history')} to ${esc(m.to||'Latest recorded')}</dd></div><div><dt>Workspace</dt><dd>${esc(m.scope)}</dd></div><div><dt>Accounts</dt><dd>${esc(accounts)}</dd></div><div><dt>Currency</dt><dd>${esc(m.currency||'Native currencies kept separate')}</dd></div><div><dt>Transaction count</dt><dd>${esc(m.source_transaction_count)}</dd></div><div><dt>Filters</dt><dd>${esc(filters)}</dd></div><div><dt>History coverage</dt><dd>${esc(m.history_completeness)} · ${esc(m.history_completeness_note)}</dd></div></dl><p class="vr-note">This is the saved snapshot. Later transaction edits do not change this report.</p>${actions}<p id="vrFeedback" role="status" aria-live="polite">${d.pdf_status==='UNAVAILABLE'?'PDF is currently unavailable. View, Print, HTML, CSV and XLSX remain available.':d.pdf_status==='READY'?`PDF generated and parsed (${d.pdf.pages} pages). Recipient delivery has not been verified.`:'PDF has not been generated. This report is already available to view, print and download.'}</p></section><div class="vr-summaries">${summaries}</div>${sections(saved,{full,query})}<footer class="vr-footer">${esc(saved.profile?.legalName||'Voxel Veda Pty Ltd')} · ${esc(saved.profile?.website||'www.voxelveda.com')} · ${esc(saved.profile?.email||'info@voxelveda.com')}<br>Confidential Financial Information</footer></article>`;
}
function standaloneHtml(saved){
  const css=fs.readFileSync(path.join(__dirname,'..','public','report-viewer.css'),'utf8');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(label(saved.report.metadata.report_type))} | Voxel Veda</title><style>${css}</style></head><body class="vr-standalone">${reportContent(saved,{full:true})}</body></html>`;
}
function viewerDocument(saved,options){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>${esc(label(saved.report.metadata.report_type))} | Voxel Veda</title><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/report-viewer.css?v=20261007"><link rel="stylesheet" href="/step-up.css"></head><body class="finance-os-page report-viewer-page"><div class="app-shell fm-shell"><!-- SHARED_WORKSPACE_NAV --><main class="main fm-main"><!-- SHARED_WORKSPACE_HEADER --><nav class="vr-breadcrumb"><a href="/finance-intelligence#reports">Finance Reports</a><span>Saved report</span></nav>${reportContent(saved,options)}</main></div><script src="/step-up.js" defer></script><script src="/report-viewer.js?v=20261007" defer></script></body></html>`;}
function errorDocument(message,code){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Report unavailable | Voxel Veda</title><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/report-viewer.css"></head><body class="finance-os-page report-viewer-page"><div class="app-shell"><!-- SHARED_WORKSPACE_NAV --><main class="main"><!-- SHARED_WORKSPACE_HEADER --><section class="vr-card vr-error" role="alert"><h1>${code==='REPORT_REVOKED'?'Report revoked':code==='REPORT_EXPIRED'?'Report expired':'Report unavailable'}</h1><p>${esc(message)}</p><p>For an older email, only an existing saved snapshot can reproduce its historical contents. Regenerating from the original filters creates a new report using current records.</p><a href="/finance-intelligence#reports">Open Finance Reports</a><a href="/login">Sign in</a></section></main></div></body></html>`;}
module.exports={reportContent,standaloneHtml,viewerDocument,errorDocument,originalLogoData,esc,label,amount};
