const pool = require('../config/db');

async function ensureQmsAdvancedSchema() {
  const statements = [
    `CREATE TABLE IF NOT EXISTS qms_form_definitions (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      document_id VARCHAR(64) NOT NULL,
      title VARCHAR(255) NOT NULL,
      category VARCHAR(80) NULL,
      source_pack VARCHAR(64) NULL,
      current_revision VARCHAR(32) NOT NULL DEFAULT '1.0',
      active TINYINT(1) NOT NULL DEFAULT 1,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (id), UNIQUE KEY uq_qms_form_document (document_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS qms_form_definition_versions (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      form_definition_id BIGINT UNSIGNED NOT NULL,
      revision VARCHAR(32) NOT NULL,
      definition_json JSON NOT NULL,
      status ENUM('DRAFT','APPROVED','EFFECTIVE','SUPERSEDED') NOT NULL DEFAULT 'DRAFT',
      effective_at DATETIME NULL,
      approved_by BIGINT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id), UNIQUE KEY uq_qms_form_version (form_definition_id,revision),
      CONSTRAINT fk_qms_form_version_def FOREIGN KEY (form_definition_id) REFERENCES qms_form_definitions(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS qms_record_values (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      qms_record_id BIGINT UNSIGNED NOT NULL,
      field_key VARCHAR(160) NOT NULL,
      field_label VARCHAR(255) NULL,
      value_json JSON NULL,
      data_type VARCHAR(32) NOT NULL DEFAULT 'text',
      blocking TINYINT(1) NOT NULL DEFAULT 0,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (id), UNIQUE KEY uq_qms_record_field (qms_record_id,field_key),
      CONSTRAINT fk_qms_value_record FOREIGN KEY (qms_record_id) REFERENCES qms_records(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS qms_record_links (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      qms_record_id BIGINT UNSIGNED NOT NULL,
      entity_type VARCHAR(50) NOT NULL,
      entity_id VARCHAR(100) NOT NULL,
      relation_type VARCHAR(80) NOT NULL DEFAULT 'RELATED_TO',
      created_by BIGINT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id), UNIQUE KEY uq_qms_record_link (qms_record_id,entity_type,entity_id,relation_type),
      KEY idx_qms_link_entity (entity_type,entity_id),
      CONSTRAINT fk_qms_link_record FOREIGN KEY (qms_record_id) REFERENCES qms_records(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS qms_record_evidence (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      qms_record_id BIGINT UNSIGNED NOT NULL,
      evidence_type VARCHAR(80) NOT NULL DEFAULT 'FILE',
      document_security_id BIGINT NULL,
      file_name VARCHAR(255) NULL,
      sha256 CHAR(64) NULL,
      classification VARCHAR(50) NOT NULL DEFAULT 'INTERNAL',
      malware_status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
      retention_class VARCHAR(80) NULL,
      uploaded_by BIGINT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id), KEY idx_qms_evidence_record (qms_record_id,created_at),
      CONSTRAINT fk_qms_evidence_record FOREIGN KEY (qms_record_id) REFERENCES qms_records(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS qms_record_comments (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      qms_record_id BIGINT UNSIGNED NOT NULL,
      comment_text VARCHAR(4000) NOT NULL,
      comment_type VARCHAR(40) NOT NULL DEFAULT 'COMMENT',
      created_by BIGINT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id), KEY idx_qms_comments_record (qms_record_id,created_at),
      CONSTRAINT fk_qms_comment_record FOREIGN KEY (qms_record_id) REFERENCES qms_records(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS qms_record_holds (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      qms_record_id BIGINT UNSIGNED NOT NULL,
      hold_type VARCHAR(50) NOT NULL DEFAULT 'QUALITY_HOLD',
      reason VARCHAR(1000) NOT NULL,
      active TINYINT(1) NOT NULL DEFAULT 1,
      placed_by BIGINT NULL,
      placed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      released_by BIGINT NULL,
      released_at DATETIME NULL,
      release_reason VARCHAR(1000) NULL,
      PRIMARY KEY (id), KEY idx_qms_record_hold_active (qms_record_id,active),
      CONSTRAINT fk_qms_hold_record FOREIGN KEY (qms_record_id) REFERENCES qms_records(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS manufacturing_jobs (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      job_no VARCHAR(50) NOT NULL,
      customer_id BIGINT NULL,
      customer_po VARCHAR(100) NULL,
      rfq_id BIGINT NULL,
      part_no VARCHAR(100) NULL,
      part_description VARCHAR(255) NULL,
      drawing_no VARCHAR(100) NULL,
      drawing_revision VARCHAR(40) NULL,
      quantity DECIMAL(18,4) NULL,
      sector ENUM('GENERAL','AEROSPACE','DEFENCE','MEDICAL','AUTOMOTIVE','OTHER') NOT NULL DEFAULT 'GENERAL',
      confidentiality_classification VARCHAR(50) NOT NULL DEFAULT 'INTERNAL',
      export_review_required TINYINT(1) NOT NULL DEFAULT 0,
      regulatory_review_required TINYINT(1) NOT NULL DEFAULT 0,
      status ENUM('QUOTE','ORDER_CONFIRMED','PLANNING','MATERIAL_WAITING','READY','IN_PRODUCTION','INSPECTION','QUALITY_HOLD','FINAL_RELEASE','PACKING','DISPATCHED','COMPLETE','CANCELLED') NOT NULL DEFAULT 'PLANNING',
      created_by BIGINT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (id), UNIQUE KEY uq_manufacturing_job_no (job_no), KEY idx_mfg_job_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS job_operations (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      job_id BIGINT UNSIGNED NOT NULL,
      operation_no INT NOT NULL,
      operation_name VARCHAR(160) NOT NULL,
      machine_id BIGINT UNSIGNED NULL,
      required_competency_code VARCHAR(80) NULL,
      work_instruction_ref VARCHAR(160) NULL,
      status ENUM('PLANNED','READY','BLOCKED','RUNNING','PAUSED','COMPLETE','REJECTED') NOT NULL DEFAULT 'PLANNED',
      planned_start DATETIME NULL, planned_end DATETIME NULL,
      actual_start DATETIME NULL, actual_end DATETIME NULL,
      PRIMARY KEY (id), UNIQUE KEY uq_job_operation (job_id,operation_no),
      CONSTRAINT fk_job_operation_job FOREIGN KEY (job_id) REFERENCES manufacturing_jobs(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS job_operation_events (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      job_operation_id BIGINT UNSIGNED NOT NULL,
      event_type VARCHAR(50) NOT NULL,
      actor_id BIGINT NULL,
      metadata_json JSON NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id), KEY idx_job_operation_events (job_operation_id,created_at),
      CONSTRAINT fk_job_op_event FOREIGN KEY (job_operation_id) REFERENCES job_operations(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS material_lots (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      lot_no VARCHAR(80) NOT NULL,
      material_code VARCHAR(100) NOT NULL,
      material_description VARCHAR(255) NULL,
      grade VARCHAR(100) NULL,
      supplier_id BIGINT NULL,
      supplier_lot VARCHAR(100) NULL,
      certificate_ref VARCHAR(255) NULL,
      sds_ref VARCHAR(255) NULL,
      quantity_received DECIMAL(18,4) NOT NULL DEFAULT 0,
      quantity_available DECIMAL(18,4) NOT NULL DEFAULT 0,
      unit VARCHAR(30) NULL,
      expiry_date DATE NULL,
      release_status ENUM('INSPECTION_PENDING','RELEASED','QUARANTINED','QUALITY_HOLD','REJECTED','EXPIRED') NOT NULL DEFAULT 'INSPECTION_PENDING',
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id), UNIQUE KEY uq_material_lot_no (lot_no), KEY idx_material_release (release_status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS job_material_allocations (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      job_id BIGINT UNSIGNED NOT NULL,
      material_lot_id BIGINT UNSIGNED NOT NULL,
      quantity_allocated DECIMAL(18,4) NOT NULL,
      quantity_consumed DECIMAL(18,4) NOT NULL DEFAULT 0,
      allocated_by BIGINT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id), KEY idx_job_material_job (job_id), KEY idx_job_material_lot (material_lot_id),
      CONSTRAINT fk_job_material_job FOREIGN KEY (job_id) REFERENCES manufacturing_jobs(id) ON DELETE RESTRICT,
      CONSTRAINT fk_job_material_lot FOREIGN KEY (material_lot_id) REFERENCES material_lots(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS job_builds (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      build_no VARCHAR(80) NOT NULL,
      job_id BIGINT UNSIGNED NOT NULL,
      machine_id BIGINT UNSIGNED NULL,
      operator_user_id BIGINT NULL,
      material_lot_id BIGINT UNSIGNED NULL,
      slicer_name VARCHAR(100) NULL,
      slicer_version VARCHAR(80) NULL,
      profile_revision VARCHAR(80) NULL,
      process_parameters_json JSON NULL,
      status ENUM('PLANNED','READY','RUNNING','INTERRUPTED','COMPLETE','FAILED','QUALITY_HOLD') NOT NULL DEFAULT 'PLANNED',
      started_at DATETIME NULL, completed_at DATETIME NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id), UNIQUE KEY uq_job_build_no (build_no), KEY idx_job_build_job (job_id),
      CONSTRAINT fk_job_build_job FOREIGN KEY (job_id) REFERENCES manufacturing_jobs(id) ON DELETE RESTRICT,
      CONSTRAINT fk_job_build_material FOREIGN KEY (material_lot_id) REFERENCES material_lots(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS job_build_parameters (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      build_id BIGINT UNSIGNED NOT NULL,
      parameter_key VARCHAR(120) NOT NULL,
      parameter_value VARCHAR(1000) NULL,
      unit VARCHAR(40) NULL,
      PRIMARY KEY (id), UNIQUE KEY uq_build_parameter (build_id,parameter_key),
      CONSTRAINT fk_build_parameter_build FOREIGN KEY (build_id) REFERENCES job_builds(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS job_serials (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      job_id BIGINT UNSIGNED NOT NULL,
      build_id BIGINT UNSIGNED NULL,
      serial_no VARCHAR(100) NOT NULL,
      status ENUM('WIP','INSPECTION','RELEASED','QUALITY_HOLD','REWORK','SCRAPPED','DISPATCHED') NOT NULL DEFAULT 'WIP',
      PRIMARY KEY (id), UNIQUE KEY uq_job_serial (serial_no), KEY idx_job_serial_job (job_id),
      CONSTRAINT fk_job_serial_job FOREIGN KEY (job_id) REFERENCES manufacturing_jobs(id) ON DELETE RESTRICT,
      CONSTRAINT fk_job_serial_build FOREIGN KEY (build_id) REFERENCES job_builds(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS material_genealogy (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      material_lot_id BIGINT UNSIGNED NOT NULL,
      job_id BIGINT UNSIGNED NOT NULL,
      build_id BIGINT UNSIGNED NULL,
      serial_id BIGINT UNSIGNED NULL,
      relationship VARCHAR(50) NOT NULL DEFAULT 'CONSUMED_IN',
      quantity DECIMAL(18,4) NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id), KEY idx_genealogy_material (material_lot_id), KEY idx_genealogy_job (job_id),
      CONSTRAINT fk_genealogy_material FOREIGN KEY (material_lot_id) REFERENCES material_lots(id) ON DELETE RESTRICT,
      CONSTRAINT fk_genealogy_job FOREIGN KEY (job_id) REFERENCES manufacturing_jobs(id) ON DELETE RESTRICT,
      CONSTRAINT fk_genealogy_build FOREIGN KEY (build_id) REFERENCES job_builds(id) ON DELETE RESTRICT,
      CONSTRAINT fk_genealogy_serial FOREIGN KEY (serial_id) REFERENCES job_serials(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS quality_holds (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      hold_no VARCHAR(80) NOT NULL,
      entity_type ENUM('MATERIAL_LOT','JOB','BUILD','SERIAL','SHIPMENT','QMS_RECORD') NOT NULL,
      entity_id VARCHAR(100) NOT NULL,
      reason VARCHAR(1000) NOT NULL,
      source_type VARCHAR(50) NULL,
      source_id VARCHAR(100) NULL,
      active TINYINT(1) NOT NULL DEFAULT 1,
      placed_by BIGINT NULL, placed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      released_by BIGINT NULL, released_at DATETIME NULL, release_reason VARCHAR(1000) NULL,
      PRIMARY KEY (id), UNIQUE KEY uq_quality_hold_no (hold_no), KEY idx_quality_hold_entity (entity_type,entity_id,active)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS production_releases (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      release_no VARCHAR(80) NOT NULL,
      job_id BIGINT UNSIGNED NOT NULL,
      quantity_released DECIMAL(18,4) NOT NULL DEFAULT 0,
      final_inspection_run_id BIGINT UNSIGNED NULL,
      concession_ref VARCHAR(100) NULL,
      released_by BIGINT NOT NULL,
      release_integrity_hash CHAR(64) NOT NULL,
      released_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id), UNIQUE KEY uq_production_release_no (release_no),
      CONSTRAINT fk_production_release_job FOREIGN KEY (job_id) REFERENCES manufacturing_jobs(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS equipment_assets (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      equipment_code VARCHAR(80) NOT NULL,
      description VARCHAR(255) NOT NULL,
      manufacturer VARCHAR(120) NULL,
      model VARCHAR(120) NULL,
      serial_no VARCHAR(120) NULL,
      location VARCHAR(160) NULL,
      status ENUM('READY','RUNNING','MAINTENANCE','LOTO','OUT_OF_SERVICE','QUALITY_HOLD','QUARANTINED','DECOMMISSIONED') NOT NULL DEFAULT 'READY',
      commissioned TINYINT(1) NOT NULL DEFAULT 0,
      critical_safety_issue TINYINT(1) NOT NULL DEFAULT 0,
      qr_token CHAR(36) NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id), UNIQUE KEY uq_equipment_code (equipment_code), UNIQUE KEY uq_equipment_qr (qr_token)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS equipment_commissioning (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      equipment_id BIGINT UNSIGNED NOT NULL,
      commissioned_by BIGINT NULL,
      checklist_json JSON NULL,
      approved TINYINT(1) NOT NULL DEFAULT 0,
      commissioned_at DATETIME NULL,
      PRIMARY KEY (id), KEY idx_equipment_commissioning (equipment_id),
      CONSTRAINT fk_equipment_commission_asset FOREIGN KEY (equipment_id) REFERENCES equipment_assets(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS maintenance_plans (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      equipment_id BIGINT UNSIGNED NOT NULL,
      plan_name VARCHAR(160) NOT NULL,
      interval_days INT NULL,
      blocking_when_overdue TINYINT(1) NOT NULL DEFAULT 1,
      next_due_date DATE NULL,
      active TINYINT(1) NOT NULL DEFAULT 1,
      PRIMARY KEY (id), KEY idx_maintenance_plan_due (next_due_date,active),
      CONSTRAINT fk_maintenance_plan_asset FOREIGN KEY (equipment_id) REFERENCES equipment_assets(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS maintenance_work_orders (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      work_order_no VARCHAR(80) NOT NULL,
      equipment_id BIGINT UNSIGNED NOT NULL,
      maintenance_plan_id BIGINT UNSIGNED NULL,
      status ENUM('OPEN','IN_PROGRESS','COMPLETE','CANCELLED') NOT NULL DEFAULT 'OPEN',
      due_date DATE NULL,
      description VARCHAR(1000) NULL,
      opened_by BIGINT NULL, completed_by BIGINT NULL,
      opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at DATETIME NULL,
      PRIMARY KEY (id), UNIQUE KEY uq_maintenance_wo (work_order_no),
      CONSTRAINT fk_maintenance_wo_asset FOREIGN KEY (equipment_id) REFERENCES equipment_assets(id) ON DELETE RESTRICT,
      CONSTRAINT fk_maintenance_wo_plan FOREIGN KEY (maintenance_plan_id) REFERENCES maintenance_plans(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS equipment_faults (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      equipment_id BIGINT UNSIGNED NOT NULL,
      severity ENUM('LOW','MEDIUM','HIGH','CRITICAL') NOT NULL DEFAULT 'MEDIUM',
      description VARCHAR(2000) NOT NULL,
      status ENUM('OPEN','CONTAINED','RESOLVED') NOT NULL DEFAULT 'OPEN',
      reported_by BIGINT NULL, reported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      resolved_by BIGINT NULL, resolved_at DATETIME NULL,
      PRIMARY KEY (id), KEY idx_equipment_fault_open (equipment_id,status),
      CONSTRAINT fk_equipment_fault_asset FOREIGN KEY (equipment_id) REFERENCES equipment_assets(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS loto_permits (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      permit_no VARCHAR(80) NOT NULL,
      equipment_id BIGINT UNSIGNED NOT NULL,
      reason VARCHAR(1000) NOT NULL,
      active TINYINT(1) NOT NULL DEFAULT 1,
      isolated_by BIGINT NULL, isolated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      zero_energy_verified TINYINT(1) NOT NULL DEFAULT 0,
      released_by BIGINT NULL, released_at DATETIME NULL,
      PRIMARY KEY (id), UNIQUE KEY uq_loto_permit_no (permit_no), KEY idx_loto_active (equipment_id,active),
      CONSTRAINT fk_loto_asset FOREIGN KEY (equipment_id) REFERENCES equipment_assets(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS measurement_equipment (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      equipment_code VARCHAR(80) NOT NULL,
      description VARCHAR(255) NOT NULL,
      manufacturer VARCHAR(120) NULL,
      model VARCHAR(120) NULL,
      serial_no VARCHAR(120) NULL,
      range_text VARCHAR(120) NULL,
      resolution_text VARCHAR(120) NULL,
      calibration_source VARCHAR(160) NULL,
      certificate_no VARCHAR(160) NULL,
      last_calibrated DATE NULL,
      due_date DATE NULL,
      status ENUM('VALID','DUE_SOON','EXPIRED','SUSPENDED','OUT_OF_TOLERANCE') NOT NULL DEFAULT 'VALID',
      location VARCHAR(160) NULL,
      owner_user_id BIGINT NULL,
      PRIMARY KEY (id), UNIQUE KEY uq_measurement_equipment_code (equipment_code), KEY idx_measurement_due (due_date,status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS calibration_events (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      measurement_equipment_id BIGINT UNSIGNED NOT NULL,
      event_type ENUM('CALIBRATION','VERIFICATION','OUT_OF_TOLERANCE','SUSPENSION','RETURN_TO_SERVICE') NOT NULL,
      result ENUM('PASS','FAIL','CONDITIONAL') NOT NULL,
      certificate_no VARCHAR(160) NULL,
      performed_by VARCHAR(160) NULL,
      event_date DATE NOT NULL,
      next_due_date DATE NULL,
      notes VARCHAR(2000) NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id), KEY idx_calibration_event_equipment (measurement_equipment_id,event_date),
      CONSTRAINT fk_calibration_equipment FOREIGN KEY (measurement_equipment_id) REFERENCES measurement_equipment(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS out_of_tolerance_events (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      measurement_equipment_id BIGINT UNSIGNED NOT NULL,
      discovered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      last_known_good_at DATETIME NULL,
      impact_assessment_status ENUM('OPEN','IN_REVIEW','COMPLETE') NOT NULL DEFAULT 'OPEN',
      description VARCHAR(2000) NOT NULL,
      PRIMARY KEY (id), KEY idx_oot_equipment (measurement_equipment_id,impact_assessment_status),
      CONSTRAINT fk_oot_equipment FOREIGN KEY (measurement_equipment_id) REFERENCES measurement_equipment(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS competencies (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      competency_code VARCHAR(80) NOT NULL,
      name VARCHAR(255) NOT NULL,
      description VARCHAR(1000) NULL,
      default_valid_days INT NULL,
      active TINYINT(1) NOT NULL DEFAULT 1,
      PRIMARY KEY (id), UNIQUE KEY uq_competency_code (competency_code)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS employee_competencies (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      user_id BIGINT NOT NULL,
      competency_id BIGINT UNSIGNED NOT NULL,
      status ENUM('VALID','EXPIRED','SUSPENDED','PENDING') NOT NULL DEFAULT 'PENDING',
      issued_at DATE NULL, expires_at DATE NULL,
      evidence_ref VARCHAR(255) NULL,
      approved_by BIGINT NULL,
      PRIMARY KEY (id), UNIQUE KEY uq_employee_competency (user_id,competency_id), KEY idx_employee_competency_expiry (expires_at,status),
      CONSTRAINT fk_employee_competency FOREIGN KEY (competency_id) REFERENCES competencies(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS operator_authorisations (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      user_id BIGINT NOT NULL,
      equipment_id BIGINT UNSIGNED NOT NULL,
      competency_id BIGINT UNSIGNED NULL,
      status ENUM('VALID','EXPIRED','SUSPENDED','PENDING') NOT NULL DEFAULT 'PENDING',
      valid_from DATE NULL, valid_until DATE NULL,
      authorised_by BIGINT NULL,
      PRIMARY KEY (id), UNIQUE KEY uq_operator_authorisation (user_id,equipment_id),
      CONSTRAINT fk_operator_auth_asset FOREIGN KEY (equipment_id) REFERENCES equipment_assets(id) ON DELETE RESTRICT,
      CONSTRAINT fk_operator_auth_comp FOREIGN KEY (competency_id) REFERENCES competencies(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS inspection_plans (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      plan_no VARCHAR(80) NOT NULL,
      name VARCHAR(255) NOT NULL,
      inspection_type ENUM('INCOMING','IN_PROCESS','FINAL','FAI') NOT NULL,
      part_no VARCHAR(100) NULL,
      drawing_revision VARCHAR(40) NULL,
      status ENUM('DRAFT','APPROVED','SUPERSEDED') NOT NULL DEFAULT 'DRAFT',
      PRIMARY KEY (id), UNIQUE KEY uq_inspection_plan_no (plan_no)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS inspection_characteristics (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      inspection_plan_id BIGINT UNSIGNED NOT NULL,
      characteristic_no VARCHAR(80) NOT NULL,
      description VARCHAR(255) NOT NULL,
      nominal DECIMAL(18,6) NULL,
      lower_limit DECIMAL(18,6) NULL,
      upper_limit DECIMAL(18,6) NULL,
      unit VARCHAR(40) NULL,
      blocking TINYINT(1) NOT NULL DEFAULT 1,
      sequence_no INT NOT NULL DEFAULT 1,
      PRIMARY KEY (id), UNIQUE KEY uq_inspection_characteristic (inspection_plan_id,characteristic_no),
      CONSTRAINT fk_inspection_characteristic_plan FOREIGN KEY (inspection_plan_id) REFERENCES inspection_plans(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS inspection_runs (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      run_no VARCHAR(80) NOT NULL,
      inspection_plan_id BIGINT UNSIGNED NOT NULL,
      job_id BIGINT UNSIGNED NULL,
      material_lot_id BIGINT UNSIGNED NULL,
      build_id BIGINT UNSIGNED NULL,
      serial_id BIGINT UNSIGNED NULL,
      status ENUM('OPEN','PASS','FAIL','CONDITIONAL','APPROVED') NOT NULL DEFAULT 'OPEN',
      inspected_by BIGINT NULL,
      approved_by BIGINT NULL,
      started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      completed_at DATETIME NULL,
      PRIMARY KEY (id), UNIQUE KEY uq_inspection_run_no (run_no),
      CONSTRAINT fk_inspection_run_plan FOREIGN KEY (inspection_plan_id) REFERENCES inspection_plans(id) ON DELETE RESTRICT,
      CONSTRAINT fk_inspection_run_job FOREIGN KEY (job_id) REFERENCES manufacturing_jobs(id) ON DELETE RESTRICT,
      CONSTRAINT fk_inspection_run_lot FOREIGN KEY (material_lot_id) REFERENCES material_lots(id) ON DELETE RESTRICT,
      CONSTRAINT fk_inspection_run_build FOREIGN KEY (build_id) REFERENCES job_builds(id) ON DELETE RESTRICT,
      CONSTRAINT fk_inspection_run_serial FOREIGN KEY (serial_id) REFERENCES job_serials(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS inspection_measurements (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      inspection_run_id BIGINT UNSIGNED NOT NULL,
      characteristic_id BIGINT UNSIGNED NOT NULL,
      sample_no INT NOT NULL DEFAULT 1,
      actual_value DECIMAL(18,6) NULL,
      text_value VARCHAR(1000) NULL,
      measurement_equipment_id BIGINT UNSIGNED NULL,
      result ENUM('PASS','FAIL','NA') NOT NULL DEFAULT 'NA',
      measured_by BIGINT NULL,
      measured_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id), UNIQUE KEY uq_inspection_measurement (inspection_run_id,characteristic_id,sample_no),
      CONSTRAINT fk_measurement_run FOREIGN KEY (inspection_run_id) REFERENCES inspection_runs(id) ON DELETE RESTRICT,
      CONSTRAINT fk_measurement_characteristic FOREIGN KEY (characteristic_id) REFERENCES inspection_characteristics(id) ON DELETE RESTRICT,
      CONSTRAINT fk_measurement_equipment FOREIGN KEY (measurement_equipment_id) REFERENCES measurement_equipment(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS ncrs (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      ncr_no VARCHAR(80) NOT NULL,
      status ENUM('OPEN','CONTAINMENT_REQUIRED','CONTAINED','INVESTIGATION','DISPOSITION_REQUIRED','REWORK','REINSPECTION','APPROVAL','CLOSED') NOT NULL DEFAULT 'OPEN',
      severity ENUM('MINOR','MAJOR','CRITICAL') NOT NULL DEFAULT 'MINOR',
      job_id BIGINT UNSIGNED NULL,
      material_lot_id BIGINT UNSIGNED NULL,
      build_id BIGINT UNSIGNED NULL,
      inspection_run_id BIGINT UNSIGNED NULL,
      supplier_id BIGINT NULL,
      description VARCHAR(4000) NOT NULL,
      containment VARCHAR(4000) NULL,
      suspected_cause VARCHAR(2000) NULL,
      disposition ENUM('REWORK','SCRAP','RETURN_TO_SUPPLIER','REPAIR','USE_AS_IS_WITH_APPROVED_CONCESSION') NULL,
      concession_ref VARCHAR(120) NULL,
      created_by BIGINT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      closed_by BIGINT NULL, closed_at DATETIME NULL,
      PRIMARY KEY (id), UNIQUE KEY uq_ncr_no (ncr_no), KEY idx_ncr_status (status),
      CONSTRAINT fk_ncr_job FOREIGN KEY (job_id) REFERENCES manufacturing_jobs(id) ON DELETE RESTRICT,
      CONSTRAINT fk_ncr_lot FOREIGN KEY (material_lot_id) REFERENCES material_lots(id) ON DELETE RESTRICT,
      CONSTRAINT fk_ncr_build FOREIGN KEY (build_id) REFERENCES job_builds(id) ON DELETE RESTRICT,
      CONSTRAINT fk_ncr_inspection FOREIGN KEY (inspection_run_id) REFERENCES inspection_runs(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS capas (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      capa_no VARCHAR(80) NOT NULL,
      source_type VARCHAR(50) NOT NULL,
      source_id VARCHAR(100) NULL,
      status ENUM('OPEN','ROOT_CAUSE','ACTION_PLANNED','IMPLEMENTING','EFFECTIVENESS_REVIEW','CLOSED') NOT NULL DEFAULT 'OPEN',
      problem_statement VARCHAR(4000) NOT NULL,
      containment VARCHAR(4000) NULL,
      root_cause_method VARCHAR(80) NULL,
      root_cause VARCHAR(4000) NULL,
      residual_risk VARCHAR(1000) NULL,
      owner_user_id BIGINT NULL,
      due_date DATE NULL,
      created_by BIGINT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      closed_by BIGINT NULL, closed_at DATETIME NULL,
      PRIMARY KEY (id), UNIQUE KEY uq_capa_no (capa_no), KEY idx_capa_status_due (status,due_date)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS capa_actions (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      capa_id BIGINT UNSIGNED NOT NULL,
      action_type ENUM('CORRECTIVE','SYSTEMIC','PREVENTIVE') NOT NULL DEFAULT 'CORRECTIVE',
      action_text VARCHAR(4000) NOT NULL,
      owner_user_id BIGINT NULL,
      due_date DATE NULL,
      status ENUM('OPEN','IN_PROGRESS','COMPLETE','CANCELLED') NOT NULL DEFAULT 'OPEN',
      completed_at DATETIME NULL,
      PRIMARY KEY (id), KEY idx_capa_action_due (capa_id,status,due_date),
      CONSTRAINT fk_capa_action_capa FOREIGN KEY (capa_id) REFERENCES capas(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS capa_effectiveness_checks (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      capa_id BIGINT UNSIGNED NOT NULL,
      planned_date DATE NULL,
      result ENUM('PENDING','EFFECTIVE','INEFFECTIVE') NOT NULL DEFAULT 'PENDING',
      evidence_ref VARCHAR(255) NULL,
      checked_by BIGINT NULL,
      checked_at DATETIME NULL,
      PRIMARY KEY (id), KEY idx_capa_effectiveness (capa_id,result),
      CONSTRAINT fk_capa_effectiveness_capa FOREIGN KEY (capa_id) REFERENCES capas(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`
  ];

  for (const sql of statements) await pool.query(sql);

  const alterStatements = [
    `ALTER TABLE qms_records ADD COLUMN related_customer_id BIGINT NULL`,
    `ALTER TABLE qms_records ADD COLUMN related_supplier_id BIGINT NULL`,
    `ALTER TABLE qms_records ADD COLUMN related_job_id BIGINT UNSIGNED NULL`,
    `ALTER TABLE qms_records ADD COLUMN related_material_lot_id BIGINT UNSIGNED NULL`,
    `ALTER TABLE qms_records ADD COLUMN related_machine_id BIGINT UNSIGNED NULL`,
    `ALTER TABLE qms_records ADD COLUMN related_build_id BIGINT UNSIGNED NULL`,
    `ALTER TABLE qms_records ADD COLUMN related_inspection_id BIGINT UNSIGNED NULL`,
    `ALTER TABLE qms_records ADD COLUMN confidentiality_classification VARCHAR(50) NOT NULL DEFAULT 'INTERNAL'`,
    `ALTER TABLE qms_records ADD COLUMN retention_class VARCHAR(80) NULL`,
    `ALTER TABLE qms_records ADD COLUMN effective_at DATETIME NULL`,
    `ALTER TABLE qms_records ADD COLUMN completed_at DATETIME NULL`
  ];
  for (const sql of alterStatements) {
    try { await pool.query(sql); } catch (error) {
      if (!['ER_DUP_FIELDNAME'].includes(error.code)) throw error;
    }
  }
}

module.exports = { ensureQmsAdvancedSchema };
