const pool = require('../config/db');

async function ensureQmsEnterpriseCompletionSchema() {
  const statements = [
`CREATE TABLE IF NOT EXISTS audit_programmes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, programme_no VARCHAR(50) UNIQUE, title VARCHAR(255) NOT NULL, scope TEXT, criteria TEXT, owner_user_id BIGINT NULL, start_date DATE NULL, end_date DATE NULL, status ENUM('DRAFT','ACTIVE','COMPLETE','CANCELLED') NOT NULL DEFAULT 'DRAFT', created_by BIGINT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
`CREATE TABLE IF NOT EXISTS internal_audits (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, audit_no VARCHAR(50) UNIQUE, programme_id BIGINT UNSIGNED NULL, title VARCHAR(255) NOT NULL, scope TEXT, criteria TEXT, auditor_user_id BIGINT NULL, area_owner_user_id BIGINT NULL, scheduled_at DATETIME NULL, completed_at DATETIME NULL, status ENUM('PLANNED','IN_PROGRESS','FOLLOW_UP','CLOSED','CANCELLED') NOT NULL DEFAULT 'PLANNED', created_by BIGINT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_audit_status(status), CONSTRAINT fk_internal_audit_programme FOREIGN KEY(programme_id) REFERENCES audit_programmes(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
`CREATE TABLE IF NOT EXISTS audit_findings (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, audit_id BIGINT UNSIGNED NOT NULL, finding_no VARCHAR(60) UNIQUE, finding_type ENUM('CONFORMITY','OFI','MINOR_NC','MAJOR_NC') NOT NULL, requirement_ref VARCHAR(255) NULL, evidence TEXT, finding TEXT NOT NULL, capa_id BIGINT UNSIGNED NULL, owner_user_id BIGINT NULL, due_date DATE NULL, status ENUM('OPEN','ACTIONED','VERIFIED','CLOSED') NOT NULL DEFAULT 'OPEN', created_by BIGINT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_finding_audit FOREIGN KEY(audit_id) REFERENCES internal_audits(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
`CREATE TABLE IF NOT EXISTS management_reviews (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, review_no VARCHAR(50) UNIQUE, title VARCHAR(255) NOT NULL, period_start DATE NULL, period_end DATE NULL, scheduled_at DATETIME NULL, held_at DATETIME NULL, status ENUM('DRAFT','SCHEDULED','HELD','CLOSED') NOT NULL DEFAULT 'DRAFT', inputs_json JSON NULL, decisions_json JSON NULL, chair_user_id BIGINT NULL, created_by BIGINT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
`CREATE TABLE IF NOT EXISTS management_review_actions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, review_id BIGINT UNSIGNED NOT NULL, action_text TEXT NOT NULL, owner_user_id BIGINT NULL, due_date DATE NULL, status ENUM('OPEN','IN_PROGRESS','COMPLETE','CANCELLED') NOT NULL DEFAULT 'OPEN', completed_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_review_action FOREIGN KEY(review_id) REFERENCES management_reviews(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
`CREATE TABLE IF NOT EXISTS chemical_products (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, chemical_code VARCHAR(60) UNIQUE, product_name VARCHAR(255) NOT NULL, manufacturer VARCHAR(255) NULL, supplier_id BIGINT NULL, hazard_classification VARCHAR(500) NULL, dg_classification VARCHAR(255) NULL, maximum_quantity DECIMAL(14,3) NULL, current_quantity DECIMAL(14,3) NOT NULL DEFAULT 0, unit VARCHAR(30) NULL, storage_location VARCHAR(255) NULL, ppe_requirements TEXT NULL, spill_controls TEXT NULL, responsible_user_id BIGINT NULL, status ENUM('ACTIVE','REVIEW','QUARANTINED','DISCONTINUED') NOT NULL DEFAULT 'ACTIVE', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
`CREATE TABLE IF NOT EXISTS sds_versions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, chemical_id BIGINT UNSIGNED NOT NULL, version_label VARCHAR(80) NOT NULL, issue_date DATE NULL, review_due DATE NULL, secure_document_id BIGINT NULL, file_hash CHAR(64) NULL, status ENUM('CURRENT','SUPERSEDED','REVIEW_REQUIRED') NOT NULL DEFAULT 'CURRENT', created_by BIGINT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_sds_chemical FOREIGN KEY(chemical_id) REFERENCES chemical_products(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
`CREATE TABLE IF NOT EXISTS chemical_transactions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, chemical_id BIGINT UNSIGNED NOT NULL, transaction_type ENUM('RECEIPT','USE','ADJUSTMENT','DISPOSAL') NOT NULL, quantity DECIMAL(14,3) NOT NULL, reference VARCHAR(255) NULL, performed_by BIGINT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_chemical_tx_product FOREIGN KEY(chemical_id) REFERENCES chemical_products(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
`CREATE TABLE IF NOT EXISTS site_visitors (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, visit_uuid CHAR(36) UNIQUE, visitor_name VARCHAR(255) NOT NULL, company VARCHAR(255) NULL, visitor_type ENUM('VISITOR','CONTRACTOR') NOT NULL DEFAULT 'VISITOR', host_user_id BIGINT NULL, purpose VARCHAR(1000) NULL, nda_required TINYINT(1) NOT NULL DEFAULT 0, induction_required TINYINT(1) NOT NULL DEFAULT 0, induction_completed TINYINT(1) NOT NULL DEFAULT 0, permitted_zones_json JSON NULL, checked_in_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, checked_out_at DATETIME NULL, badge_no VARCHAR(80) NULL, created_by BIGINT NULL, KEY idx_active_visitors(checked_out_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
`CREATE TABLE IF NOT EXISTS emergency_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_no VARCHAR(60) UNIQUE, event_type ENUM('DRILL','EVACUATION','FIRE','CHEMICAL_SPILL','OTHER') NOT NULL, title VARCHAR(255) NOT NULL, status ENUM('ACTIVE','ACCOUNTING','ALL_CLEAR','CLOSED') NOT NULL DEFAULT 'ACTIVE', assembly_point VARCHAR(255) NULL, started_by BIGINT NULL, started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ended_at DATETIME NULL, notes TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
`CREATE TABLE IF NOT EXISTS emergency_rollcall (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, emergency_event_id BIGINT UNSIGNED NOT NULL, person_type ENUM('STAFF','VISITOR','CONTRACTOR') NOT NULL, person_ref VARCHAR(80) NOT NULL, display_name VARCHAR(255) NOT NULL, accounted TINYINT(1) NOT NULL DEFAULT 0, accounted_by BIGINT NULL, accounted_at DATETIME NULL, UNIQUE KEY uq_rollcall_person(emergency_event_id,person_type,person_ref), CONSTRAINT fk_rollcall_event FOREIGN KEY(emergency_event_id) REFERENCES emergency_events(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
`CREATE TABLE IF NOT EXISTS critical_services (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, service_code VARCHAR(60) UNIQUE, service_name VARCHAR(255) NOT NULL, owner_user_id BIGINT NULL, criticality ENUM('LOW','MEDIUM','HIGH','CRITICAL') NOT NULL DEFAULT 'MEDIUM', rto_minutes INT UNSIGNED NULL, rpo_minutes INT UNSIGNED NULL, dependency_json JSON NULL, alternate_method TEXT NULL, status ENUM('ACTIVE','DEGRADED','UNAVAILABLE','RETIRED') NOT NULL DEFAULT 'ACTIVE', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
`CREATE TABLE IF NOT EXISTS continuity_exercises (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, exercise_no VARCHAR(60) UNIQUE, service_id BIGINT UNSIGNED NULL, exercise_type ENUM('TABLETOP','RESTORE_TEST','FAILOVER','SUPPLIER','MACHINE') NOT NULL, scenario TEXT NOT NULL, result ENUM('PASSED','PARTIAL','FAILED') NOT NULL, actual_rto_minutes INT UNSIGNED NULL, actual_rpo_minutes INT UNSIGNED NULL, evidence_ref VARCHAR(255) NULL, lessons TEXT NULL, performed_by BIGINT NULL, performed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, next_due DATE NULL, CONSTRAINT fk_continuity_service FOREIGN KEY(service_id) REFERENCES critical_services(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
`CREATE TABLE IF NOT EXISTS regulatory_reviews (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, review_no VARCHAR(60) UNIQUE, job_id BIGINT UNSIGNED NULL, rfq_id BIGINT NULL, sector ENUM('GENERAL','AEROSPACE','DEFENCE','MEDICAL','AUTOMOTIVE','OTHER') NOT NULL DEFAULT 'GENERAL', sensitive_technical_data TINYINT(1) NOT NULL DEFAULT 0, export_review_required TINYINT(1) NOT NULL DEFAULT 0, customer_confidential TINYINT(1) NOT NULL DEFAULT 0, medical_review_required TINYINT(1) NOT NULL DEFAULT 0, aerospace_quality_requirements TINYINT(1) NOT NULL DEFAULT 0, status ENUM('PENDING','UNDER_REVIEW','CLEARED','RESTRICTED','ESCALATED') NOT NULL DEFAULT 'PENDING', decision_basis TEXT NULL, reviewer_user_id BIGINT NULL, reviewed_at DATETIME NULL, created_by BIGINT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
`CREATE TABLE IF NOT EXISTS qms_notifications (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, dedupe_key VARCHAR(160) NOT NULL UNIQUE, notification_type VARCHAR(80) NOT NULL, severity ENUM('INFO','WARNING','HIGH','CRITICAL') NOT NULL DEFAULT 'INFO', title VARCHAR(255) NOT NULL, body TEXT NULL, record_type VARCHAR(80) NULL, record_id VARCHAR(80) NULL, target_user_id BIGINT NULL, due_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, acknowledged_at DATETIME NULL, acknowledged_by BIGINT NULL, KEY idx_qms_notification_open(acknowledged_at,due_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
`CREATE TABLE IF NOT EXISTS qms_evidence_index (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, evidence_uuid CHAR(36) UNIQUE, record_type VARCHAR(80) NOT NULL, record_id VARCHAR(80) NOT NULL, secure_document_id BIGINT NULL, file_name VARCHAR(255) NULL, file_hash CHAR(64) NOT NULL, classification ENUM('INTERNAL','CONFIDENTIAL','CUSTOMER_CONFIDENTIAL','RESTRICTED_TECHNICAL') NOT NULL DEFAULT 'INTERNAL', revision VARCHAR(50) NULL, malware_status ENUM('PENDING','CLEAN','REVIEW_REQUIRED','REJECTED') NOT NULL DEFAULT 'PENDING', retention_class VARCHAR(80) NULL, uploaded_by BIGINT NULL, uploaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, replaced_by BIGINT UNSIGNED NULL, KEY idx_evidence_record(record_type,record_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
`CREATE TABLE IF NOT EXISTS recall_assessments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, assessment_no VARCHAR(60) UNIQUE, material_lot_id BIGINT UNSIGNED NULL, reason TEXT NOT NULL, status ENUM('DRAFT','ASSESSING','HOLD_APPLIED','CLOSED') NOT NULL DEFAULT 'DRAFT', impact_json JSON NULL, created_by BIGINT NULL, approved_by BIGINT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, closed_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`
  ];
  for (const sql of statements) await pool.query(sql);
}
module.exports = { ensureQmsEnterpriseCompletionSchema };
