const pool = require('../config/db');

async function ensureQmsQualityGovernanceSchema() {
  const statements = [
    `CREATE TABLE IF NOT EXISTS concessions (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      concession_no VARCHAR(80) NOT NULL,
      status ENUM('DRAFT','INTERNAL_REVIEW','CUSTOMER_REVIEW','APPROVED','REJECTED','EXPIRED','CLOSED') NOT NULL DEFAULT 'DRAFT',
      job_id BIGINT UNSIGNED NULL,
      ncr_id BIGINT UNSIGNED NULL,
      affected_requirement VARCHAR(2000) NOT NULL,
      actual_condition VARCHAR(2000) NOT NULL,
      affected_quantity DECIMAL(18,4) NULL,
      affected_lot VARCHAR(120) NULL,
      technical_justification VARCHAR(4000) NOT NULL,
      risk_assessment VARCHAR(4000) NOT NULL,
      validity_scope VARCHAR(2000) NOT NULL,
      customer_approval_required TINYINT(1) NOT NULL DEFAULT 0,
      customer_approval_ref VARCHAR(255) NULL,
      valid_until DATE NULL,
      requested_by BIGINT NULL,
      internally_approved_by BIGINT NULL,
      internally_approved_at DATETIME NULL,
      approved_by BIGINT NULL,
      approved_at DATETIME NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id), UNIQUE KEY uq_concession_no (concession_no), KEY idx_concession_job_status (job_id,status),
      CONSTRAINT fk_concession_job FOREIGN KEY (job_id) REFERENCES manufacturing_jobs(id) ON DELETE RESTRICT,
      CONSTRAINT fk_concession_ncr FOREIGN KEY (ncr_id) REFERENCES ncrs(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS certificates_of_conformance (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      coc_no VARCHAR(80) NOT NULL,
      job_id BIGINT UNSIGNED NOT NULL,
      production_release_id BIGINT UNSIGNED NOT NULL,
      revision INT UNSIGNED NOT NULL DEFAULT 1,
      customer_id BIGINT NULL,
      customer_po VARCHAR(100) NULL,
      part_no VARCHAR(100) NULL,
      part_description VARCHAR(255) NULL,
      drawing_no VARCHAR(100) NULL,
      drawing_revision VARCHAR(40) NULL,
      quantity DECIMAL(18,4) NOT NULL DEFAULT 0,
      material_trace_json JSON NULL,
      manufacturing_process VARCHAR(1000) NULL,
      applicable_specifications VARCHAR(2000) NULL,
      inspection_refs_json JSON NULL,
      fai_ref VARCHAR(120) NULL,
      concession_refs_json JSON NULL,
      conformity_statement VARCHAR(4000) NOT NULL,
      integrity_hash CHAR(64) NOT NULL,
      issued_by BIGINT NOT NULL,
      issued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      voided_at DATETIME NULL,
      void_reason VARCHAR(1000) NULL,
      PRIMARY KEY (id), UNIQUE KEY uq_coc_no_revision (coc_no,revision), KEY idx_coc_job (job_id),
      CONSTRAINT fk_coc_job FOREIGN KEY (job_id) REFERENCES manufacturing_jobs(id) ON DELETE RESTRICT,
      CONSTRAINT fk_coc_release FOREIGN KEY (production_release_id) REFERENCES production_releases(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS supplier_approvals (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      supplier_id BIGINT NOT NULL,
      status ENUM('PENDING','APPROVED','CONDITIONAL','SUSPENDED','REJECTED') NOT NULL DEFAULT 'PENDING',
      risk_level ENUM('LOW','MEDIUM','HIGH','CRITICAL') NOT NULL DEFAULT 'MEDIUM',
      approval_scope VARCHAR(4000) NULL,
      restrictions VARCHAR(4000) NULL,
      approved_by BIGINT NULL,
      approved_at DATETIME NULL,
      review_due DATE NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (id), KEY idx_supplier_approval (supplier_id,status,review_due)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS supplier_certifications (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      supplier_id BIGINT NOT NULL,
      certification_name VARCHAR(160) NOT NULL,
      certificate_no VARCHAR(160) NULL,
      issuing_body VARCHAR(160) NULL,
      scope_text VARCHAR(2000) NULL,
      issue_date DATE NULL,
      expiry_date DATE NULL,
      evidence_ref VARCHAR(255) NULL,
      status ENUM('VALID','EXPIRING','EXPIRED','UNVERIFIED') NOT NULL DEFAULT 'UNVERIFIED',
      PRIMARY KEY (id), KEY idx_supplier_cert_expiry (supplier_id,expiry_date,status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS supplier_quality_events (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      supplier_id BIGINT NOT NULL,
      event_type ENUM('INCOMING_ACCEPT','INCOMING_REJECT','LATE_DELIVERY','DOCUMENT_ERROR','CUSTOMER_ESCAPE','SCAR','OTHER') NOT NULL,
      severity ENUM('LOW','MEDIUM','HIGH','CRITICAL') NOT NULL DEFAULT 'MEDIUM',
      reference_type VARCHAR(50) NULL,
      reference_id VARCHAR(100) NULL,
      quantity DECIMAL(18,4) NULL,
      description VARCHAR(2000) NULL,
      occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      recorded_by BIGINT NULL,
      PRIMARY KEY (id), KEY idx_supplier_quality_event (supplier_id,occurred_at,event_type)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS supplier_scorecards (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      supplier_id BIGINT NOT NULL,
      period_start DATE NOT NULL,
      period_end DATE NOT NULL,
      quality_score DECIMAL(6,2) NOT NULL DEFAULT 100,
      delivery_score DECIMAL(6,2) NOT NULL DEFAULT 100,
      documentation_score DECIMAL(6,2) NOT NULL DEFAULT 100,
      scar_score DECIMAL(6,2) NOT NULL DEFAULT 100,
      certification_score DECIMAL(6,2) NOT NULL DEFAULT 100,
      overall_score DECIMAL(6,2) NOT NULL DEFAULT 100,
      risk_level ENUM('LOW','MEDIUM','HIGH','CRITICAL') NOT NULL DEFAULT 'LOW',
      generated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id), UNIQUE KEY uq_supplier_scorecard_period (supplier_id,period_start,period_end)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS supplier_scars (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      scar_no VARCHAR(80) NOT NULL,
      supplier_id BIGINT NOT NULL,
      ncr_id BIGINT UNSIGNED NULL,
      status ENUM('ISSUED','ACKNOWLEDGED','CONTAINMENT_RECEIVED','ROOT_CAUSE_RECEIVED','CORRECTIVE_ACTION_RECEIVED','EFFECTIVENESS_REVIEW','CLOSED') NOT NULL DEFAULT 'ISSUED',
      problem_statement VARCHAR(4000) NOT NULL,
      due_date DATE NULL,
      supplier_response VARCHAR(4000) NULL,
      containment VARCHAR(4000) NULL,
      root_cause VARCHAR(4000) NULL,
      corrective_action VARCHAR(4000) NULL,
      effectiveness_result VARCHAR(2000) NULL,
      issued_by BIGINT NULL,
      issued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      closed_by BIGINT NULL,
      closed_at DATETIME NULL,
      PRIMARY KEY (id), UNIQUE KEY uq_supplier_scar_no (scar_no), KEY idx_scar_supplier_status (supplier_id,status,due_date),
      CONSTRAINT fk_scar_ncr FOREIGN KEY (ncr_id) REFERENCES ncrs(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS controlled_documents (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      document_id VARCHAR(80) NOT NULL,
      title VARCHAR(255) NOT NULL,
      department VARCHAR(100) NULL,
      owner_user_id BIGINT NULL,
      current_revision VARCHAR(40) NOT NULL DEFAULT '1.0',
      status ENUM('DRAFT','REVIEW','APPROVED','EFFECTIVE','SUPERSEDED','OBSOLETE','WITHDRAWN') NOT NULL DEFAULT 'DRAFT',
      effective_date DATE NULL,
      next_review_date DATE NULL,
      retention_class VARCHAR(80) NULL,
      training_impact TINYINT(1) NOT NULL DEFAULT 0,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (id), UNIQUE KEY uq_controlled_document_id (document_id), KEY idx_controlled_document_status (status,next_review_date)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS document_revisions (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      controlled_document_id BIGINT UNSIGNED NOT NULL,
      revision VARCHAR(40) NOT NULL,
      status ENUM('DRAFT','REVIEW','APPROVED','EFFECTIVE','SUPERSEDED','OBSOLETE','WITHDRAWN') NOT NULL DEFAULT 'DRAFT',
      change_reason VARCHAR(2000) NOT NULL,
      content_hash CHAR(64) NOT NULL,
      secure_document_id BIGINT NULL,
      created_by BIGINT NULL,
      approved_by BIGINT NULL,
      approved_at DATETIME NULL,
      effective_date DATE NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id), UNIQUE KEY uq_document_revision (controlled_document_id,revision),
      CONSTRAINT fk_document_revision_master FOREIGN KEY (controlled_document_id) REFERENCES controlled_documents(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS document_change_requests (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      request_no VARCHAR(80) NOT NULL,
      controlled_document_id BIGINT UNSIGNED NOT NULL,
      requested_change VARCHAR(4000) NOT NULL,
      reason VARCHAR(4000) NOT NULL,
      impact_summary VARCHAR(4000) NULL,
      status ENUM('REQUESTED','IMPACT_ASSESSMENT','REVIEW','APPROVED','REJECTED','IMPLEMENTED','CLOSED') NOT NULL DEFAULT 'REQUESTED',
      requested_by BIGINT NULL,
      approved_by BIGINT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      closed_at DATETIME NULL,
      PRIMARY KEY (id), UNIQUE KEY uq_doc_change_request_no (request_no),
      CONSTRAINT fk_doc_change_master FOREIGN KEY (controlled_document_id) REFERENCES controlled_documents(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS record_retention_rules (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      retention_class VARCHAR(80) NOT NULL,
      record_type VARCHAR(100) NOT NULL,
      retention_years INT NULL,
      legal_hold_overrides TINYINT(1) NOT NULL DEFAULT 1,
      disposition_method VARCHAR(255) NULL,
      owner_user_id BIGINT NULL,
      active TINYINT(1) NOT NULL DEFAULT 1,
      PRIMARY KEY (id), UNIQUE KEY uq_retention_rule (retention_class,record_type)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS configuration_changes (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      change_no VARCHAR(80) NOT NULL,
      change_type ENUM('DRAWING','CAD','BOM','MATERIAL','SUPPLIER','MACHINE','FIRMWARE','SLICER','PROFILE','PROCESS_SETTINGS','POST_PROCESSING','INSPECTION_PLAN','PACKAGING','SOFTWARE','FACILITY','OTHER') NOT NULL,
      entity_type VARCHAR(80) NOT NULL,
      entity_id VARCHAR(120) NOT NULL,
      current_revision VARCHAR(80) NULL,
      proposed_revision VARCHAR(80) NULL,
      description VARCHAR(4000) NOT NULL,
      reason VARCHAR(4000) NOT NULL,
      impact_assessment_json JSON NULL,
      validation_plan VARCHAR(4000) NULL,
      rollback_plan VARCHAR(4000) NULL,
      status ENUM('REQUESTED','IMPACT_ASSESSMENT','REVIEW','VALIDATION','APPROVAL','IMPLEMENTED','VERIFIED','EFFECTIVE','REJECTED','CANCELLED') NOT NULL DEFAULT 'REQUESTED',
      requested_by BIGINT NULL,
      approved_by BIGINT NULL,
      implemented_by BIGINT NULL,
      verified_by BIGINT NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      effective_at DATETIME NULL,
      PRIMARY KEY (id), UNIQUE KEY uq_configuration_change_no (change_no), KEY idx_config_change_entity (entity_type,entity_id,status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS change_impacts (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      configuration_change_id BIGINT UNSIGNED NOT NULL,
      impact_type ENUM('WIP','OPEN_JOB','DOCUMENT','TRAINING','MACHINE','INVENTORY','SUPPLIER','CUSTOMER','REGULATORY','OTHER') NOT NULL,
      entity_id VARCHAR(120) NULL,
      description VARCHAR(2000) NOT NULL,
      disposition VARCHAR(2000) NULL,
      resolved TINYINT(1) NOT NULL DEFAULT 0,
      PRIMARY KEY (id), KEY idx_change_impact_change (configuration_change_id,resolved),
      CONSTRAINT fk_change_impact_change FOREIGN KEY (configuration_change_id) REFERENCES configuration_changes(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`
  ];
  for (const sql of statements) await pool.query(sql);
}

module.exports = { ensureQmsQualityGovernanceSchema };
