const PERMISSIONS = Object.freeze([
  'VIEW_DASHBOARD', 'VIEW_FINANCE', 'EDIT_FINANCE', 'POST_TRANSACTION', 'VOID_TRANSACTION', 'OVERRIDE_TAX',
  'VIEW_BANKING', 'VIEW_BANK_DETAILS', 'EDIT_BANK_DETAILS', 'APPROVE_PAYMENT', 'EXPORT_ABA',
  'VIEW_PAYROLL', 'EDIT_PAYROLL', 'VIEW_PAYROLL_BANKING', 'APPROVE_PAYROLL_BANK_CHANGE', 'VIEW_STAFF_HR', 'EDIT_STAFF_HR', 'MANAGE_USERS',
  'MANAGE_ROLES', 'MANAGE_SECURITY', 'VIEW_AUDIT_LOG', 'EXPORT_FINANCIAL_DATA',
  'VIEW_CUSTOMERS', 'EDIT_CUSTOMERS', 'MANAGE_JOBS', 'MANAGE_TEAM_JOBS', 'VIEW_OWN_JOBS',
  'VIEW_CONFIDENTIAL_FILES', 'VIEW_OWN_TIMESHEET', 'VIEW_TEAM_TIMESHEET',
  'VIEW_ALL_TIMESHEETS', 'APPROVE_TEAM_TIMESHEET', 'APPROVE_ALL_TIMESHEETS',
  'VIEW_SUPPLIERS', 'EDIT_SUPPLIERS', 'VIEW_RFQS', 'EDIT_RFQS', 'VIEW_INVENTORY',
  'EDIT_INVENTORY', 'VIEW_MEETINGS', 'MANAGE_MEETINGS', 'VIEW_COMPLIANCE',
  'EDIT_COMPLIANCE', 'VIEW_ATTENDANCE', 'EDIT_ATTENDANCE', 'SEND_COMPANY_EMAIL',
  'MANAGE_COMPANY_EMAIL'
]);

const HIGH_RISK_PERMISSIONS = new Set([
  'EXPORT_ABA', 'MANAGE_SECURITY', 'MANAGE_USERS', 'MANAGE_ROLES', 'EDIT_BANK_DETAILS',
  'APPROVE_PAYMENT', 'VIEW_PAYROLL', 'EDIT_PAYROLL', 'VIEW_PAYROLL_BANKING',
  'APPROVE_PAYROLL_BANK_CHANGE', 'EXPORT_FINANCIAL_DATA', 'OVERRIDE_TAX'
]);

const ROLE_TEMPLATES = Object.freeze({
  super_admin: PERMISSIONS,
  admin: PERMISSIONS.filter((permission) => !['MANAGE_SECURITY', 'EXPORT_ABA'].includes(permission)),
  finance_admin: ['VIEW_DASHBOARD', 'VIEW_FINANCE', 'EDIT_FINANCE', 'POST_TRANSACTION', 'VOID_TRANSACTION', 'OVERRIDE_TAX', 'VIEW_BANKING', 'VIEW_BANK_DETAILS', 'EDIT_BANK_DETAILS', 'APPROVE_PAYMENT', 'EXPORT_FINANCIAL_DATA', 'VIEW_PAYROLL', 'VIEW_SUPPLIERS', 'EDIT_SUPPLIERS', 'SEND_COMPANY_EMAIL'],
  finance_user: ['VIEW_DASHBOARD', 'VIEW_FINANCE', 'EDIT_FINANCE', 'POST_TRANSACTION', 'VIEW_BANKING', 'VIEW_SUPPLIERS', 'SEND_COMPANY_EMAIL'],
  accountant: ['VIEW_DASHBOARD', 'VIEW_FINANCE', 'VIEW_BANKING', 'VIEW_BANK_DETAILS', 'EXPORT_FINANCIAL_DATA', 'VIEW_PAYROLL'],
  hr: ['VIEW_DASHBOARD', 'VIEW_STAFF_HR', 'EDIT_STAFF_HR', 'VIEW_PAYROLL', 'EDIT_PAYROLL', 'VIEW_PAYROLL_BANKING', 'APPROVE_PAYROLL_BANK_CHANGE', 'VIEW_ALL_TIMESHEETS', 'APPROVE_ALL_TIMESHEETS', 'VIEW_ATTENDANCE'],
  manager: ['VIEW_DASHBOARD', 'VIEW_CUSTOMERS', 'EDIT_CUSTOMERS', 'MANAGE_TEAM_JOBS', 'VIEW_TEAM_TIMESHEET', 'APPROVE_TEAM_TIMESHEET', 'VIEW_MEETINGS', 'MANAGE_MEETINGS', 'VIEW_ATTENDANCE'],
  supervisor: ['VIEW_DASHBOARD', 'MANAGE_TEAM_JOBS', 'VIEW_TEAM_TIMESHEET', 'APPROVE_TEAM_TIMESHEET', 'VIEW_MEETINGS', 'VIEW_ATTENDANCE'],
  sales: ['VIEW_DASHBOARD', 'VIEW_CUSTOMERS', 'EDIT_CUSTOMERS', 'VIEW_RFQS', 'EDIT_RFQS', 'VIEW_MEETINGS'],
  production: ['VIEW_DASHBOARD', 'VIEW_INVENTORY', 'EDIT_INVENTORY', 'VIEW_OWN_JOBS', 'VIEW_OWN_TIMESHEET', 'VIEW_ATTENDANCE'],
  staff: ['VIEW_DASHBOARD', 'VIEW_OWN_JOBS', 'VIEW_OWN_TIMESHEET', 'VIEW_MEETINGS', 'VIEW_ATTENDANCE'],
  viewer: ['VIEW_DASHBOARD'],
  view_only: ['VIEW_DASHBOARD']
});

const LEGACY_PERMISSION_MAP = Object.freeze({
  dashboard: ['VIEW_DASHBOARD'], finance: ['VIEW_FINANCE'], finance_input: ['EDIT_FINANCE'],
  finance_post_transaction: ['POST_TRANSACTION'], finance_void: ['VOID_TRANSACTION'],
  finance_reconcile: ['VIEW_BANKING'], finance_export: ['EXPORT_FINANCIAL_DATA'],
  finance_view_payroll: ['VIEW_PAYROLL'], finance_lock_period: ['EDIT_FINANCE'],
  finance_setup: ['EDIT_FINANCE'], finance_create_journal: ['EDIT_FINANCE'],
  customers: ['VIEW_CUSTOMERS'], customers_input: ['EDIT_CUSTOMERS'], tasks: ['VIEW_OWN_JOBS'],
  tasks_input: ['MANAGE_JOBS'], staff: ['VIEW_STAFF_HR'], settings: ['MANAGE_USERS'],
  suppliers: ['VIEW_SUPPLIERS'], suppliers_input: ['EDIT_SUPPLIERS'], rfqs: ['VIEW_RFQS'],
  rfqs_input: ['EDIT_RFQS'], invoices: ['VIEW_FINANCE'], invoices_input: ['EDIT_FINANCE'],
  expenses: ['VIEW_FINANCE'], expenses_input: ['EDIT_FINANCE'], stock: ['VIEW_INVENTORY'],
  stock_in: ['VIEW_INVENTORY'], stock_out: ['VIEW_INVENTORY'], raw_material: ['VIEW_INVENTORY'],
  packaging: ['VIEW_INVENTORY'], stock_in_input: ['EDIT_INVENTORY'], stock_out_input: ['EDIT_INVENTORY'],
  raw_material_input: ['EDIT_INVENTORY'], packaging_input: ['EDIT_INVENTORY'],
  attendance: ['VIEW_ATTENDANCE'], attendance_input: ['EDIT_ATTENDANCE'], roster: ['VIEW_ATTENDANCE'],
  roster_input: ['EDIT_ATTENDANCE'], meetings: ['VIEW_MEETINGS'], meetings_input: ['MANAGE_MEETINGS'],
  compliance: ['VIEW_COMPLIANCE'], compliance_input: ['EDIT_COMPLIANCE'],
  competitors: ['VIEW_CUSTOMERS'], competitors_input: ['EDIT_CUSTOMERS']
});

module.exports = { HIGH_RISK_PERMISSIONS, LEGACY_PERMISSION_MAP, PERMISSIONS, ROLE_TEMPLATES };
