const crypto = require('crypto');
const pool = require('../../config/db');
const { ensureQmsQualityGovernanceSchema } = require('../../services/qmsQualityGovernanceSchema');
const { logAudit } = require('../../services/auditService');

function actor(req){return Number(req.user?.id||req.user?.user_id||0)||null}
function clean(v,max=1000){return String(v??'').trim().slice(0,max)}
function seq(prefix,id){return `${prefix}-${new Date().getUTCFullYear()}-${String(id).padStart(6,'0')}`}
function audit(req){return{actorId:actor(req),ipAddress:req.ip,userAgent:req.get('user-agent'),requestId:req.id||req.get('x-request-id')||null,sessionId:req.session?.id||null}}
async function ready(){await ensureQmsQualityGovernanceSchema()}

async function supplierOverview(req,res,next){
  try{await ready();const supplierId=req.params.id;const [[approval]]=await pool.query('SELECT * FROM supplier_approvals WHERE supplier_id=? ORDER BY id DESC LIMIT 1',[supplierId]);const [certs]=await pool.query('SELECT * FROM supplier_certifications WHERE supplier_id=? ORDER BY expiry_date',[supplierId]);const [events]=await pool.query('SELECT * FROM supplier_quality_events WHERE supplier_id=? ORDER BY occurred_at DESC LIMIT 100',[supplierId]);const [scars]=await pool.query("SELECT * FROM supplier_scars WHERE supplier_id=? ORDER BY issued_at DESC",[supplierId]);const [[score]]=await pool.query('SELECT * FROM supplier_scorecards WHERE supplier_id=? ORDER BY period_end DESC LIMIT 1',[supplierId]);return res.json({approval,certifications:certs,events,scars,scorecard:score||null})
  }catch(e){return next(e)}}
async function approveSupplier(req,res,next){
  try{await ready();const status=clean(req.body.status,20).toUpperCase();if(!['APPROVED','CONDITIONAL','SUSPENDED','REJECTED'].includes(status))return res.status(400).json({message:'Invalid supplier approval status.'});const [r]=await pool.query('INSERT INTO supplier_approvals(supplier_id,status,risk_level,approval_scope,restrictions,approved_by,approved_at,review_due) VALUES(?,?,?,?,?,?,NOW(),?)',[req.params.id,status,clean(req.body.risk_level||'MEDIUM',20),clean(req.body.approval_scope,4000)||null,clean(req.body.restrictions,4000)||null,actor(req),req.body.review_due||null]);await logAudit(pool,{...audit(req),action:`SUPPLIER_${status}`,module:'QMS',recordType:'SUPPLIER',recordId:String(req.params.id),newValue:{approvalId:r.insertId,riskLevel:req.body.risk_level||'MEDIUM'}});return res.status(201).json({id:r.insertId,status})
  }catch(e){return next(e)}}
async function addSupplierEvent(req,res,next){try{await ready();const type=clean(req.body.event_type,40).toUpperCase();if(!['INCOMING_ACCEPT','INCOMING_REJECT','LATE_DELIVERY','DOCUMENT_ERROR','CUSTOMER_ESCAPE','SCAR','OTHER'].includes(type))return res.status(400).json({message:'Invalid supplier quality event type.'});const [r]=await pool.query('INSERT INTO supplier_quality_events(supplier_id,event_type,severity,reference_type,reference_id,quantity,description,recorded_by) VALUES(?,?,?,?,?,?,?,?)',[req.params.id,type,clean(req.body.severity||'MEDIUM',20),clean(req.body.reference_type,50)||null,clean(req.body.reference_id,100)||null,req.body.quantity??null,clean(req.body.description,2000)||null,actor(req)]);return res.status(201).json({id:r.insertId})}catch(e){return next(e)}}
async function generateSupplierScore(req,res,next){
  try{await ready();const start=req.body.period_start;const end=req.body.period_end;if(!start||!end)return res.status(400).json({message:'period_start and period_end are required.'});const [events]=await pool.query('SELECT event_type,severity,quantity FROM supplier_quality_events WHERE supplier_id=? AND occurred_at>=? AND occurred_at<DATE_ADD(?,INTERVAL 1 DAY)',[req.params.id,start,end]);const penalties={INCOMING_REJECT:8,LATE_DELIVERY:5,DOCUMENT_ERROR:4,CUSTOMER_ESCAPE:15,SCAR:10,OTHER:2};let quality=100,delivery=100,docs=100,scar=100;for(const e of events){const mult=e.severity==='CRITICAL'?2:e.severity==='HIGH'?1.5:e.severity==='LOW'?.5:1;const p=(penalties[e.event_type]||0)*mult;if(['INCOMING_REJECT','CUSTOMER_ESCAPE'].includes(e.event_type))quality-=p;if(e.event_type==='LATE_DELIVERY')delivery-=p;if(e.event_type==='DOCUMENT_ERROR')docs-=p;if(e.event_type==='SCAR')scar-=p}const [[cert]]=await pool.query("SELECT COUNT(*) total,SUM(status='EXPIRED' OR (expiry_date IS NOT NULL AND expiry_date<CURDATE())) bad FROM supplier_certifications WHERE supplier_id=?",[req.params.id]);const certScore=Number(cert.total)?Math.max(0,100-(Number(cert.bad||0)*20)):80;quality=Math.max(0,quality);delivery=Math.max(0,delivery);docs=Math.max(0,docs);scar=Math.max(0,scar);const overall=(quality*.35+delivery*.2+docs*.15+scar*.15+certScore*.15);const risk=overall>=90?'LOW':overall>=75?'MEDIUM':overall>=55?'HIGH':'CRITICAL';await pool.query(`INSERT INTO supplier_scorecards(supplier_id,period_start,period_end,quality_score,delivery_score,documentation_score,scar_score,certification_score,overall_score,risk_level) VALUES(?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE quality_score=VALUES(quality_score),delivery_score=VALUES(delivery_score),documentation_score=VALUES(documentation_score),scar_score=VALUES(scar_score),certification_score=VALUES(certification_score),overall_score=VALUES(overall_score),risk_level=VALUES(risk_level),generated_at=NOW()`,[req.params.id,start,end,quality,delivery,docs,scar,certScore,overall,risk]);return res.json({quality_score:quality,delivery_score:delivery,documentation_score:docs,scar_score:scar,certification_score:certScore,overall_score:Number(overall.toFixed(2)),risk_level:risk})
  }catch(e){return next(e)}}
async function createScar(req,res,next){try{await ready();const problem=clean(req.body.problem_statement,4000);if(!problem)return res.status(400).json({message:'problem_statement is required.'});const [r]=await pool.query('INSERT INTO supplier_scars(scar_no,supplier_id,ncr_id,problem_statement,due_date,issued_by) VALUES(NULL,?,?,?,?,?)',[req.params.id,req.body.ncr_id||null,problem,req.body.due_date||null,actor(req)]);const no=seq('SCAR',r.insertId);await pool.query('UPDATE supplier_scars SET scar_no=? WHERE id=?',[no,r.insertId]);await pool.query("INSERT INTO supplier_quality_events(supplier_id,event_type,severity,reference_type,reference_id,description,recorded_by) VALUES(?,'SCAR','HIGH','SCAR',?,?,?)",[req.params.id,no,problem.slice(0,1900),actor(req)]);await logAudit(pool,{...audit(req),action:'SCAR_ISSUED',module:'QMS',recordType:'SCAR',recordId:no,newValue:{supplierId:Number(req.params.id),dueDate:req.body.due_date||null}});return res.status(201).json({id:r.insertId,scar_no:no,status:'ISSUED'})}catch(e){return next(e)}}
async function transitionScar(req,res,next){const flow={ISSUED:'ACKNOWLEDGED',ACKNOWLEDGED:'CONTAINMENT_RECEIVED',CONTAINMENT_RECEIVED:'ROOT_CAUSE_RECEIVED',ROOT_CAUSE_RECEIVED:'CORRECTIVE_ACTION_RECEIVED',CORRECTIVE_ACTION_RECEIVED:'EFFECTIVENESS_REVIEW',EFFECTIVENESS_REVIEW:'CLOSED'};try{await ready();const [[s]]=await pool.query('SELECT * FROM supplier_scars WHERE id=?',[req.params.id]);if(!s)return res.status(404).json({message:'SCAR not found.'});const target=clean(req.body.status,40).toUpperCase();if(flow[s.status]!==target)return res.status(409).json({message:`Invalid SCAR transition ${s.status} → ${target}.`});const fields={supplier_response:clean(req.body.supplier_response,4000)||null,containment:clean(req.body.containment,4000)||null,root_cause:clean(req.body.root_cause,4000)||null,corrective_action:clean(req.body.corrective_action,4000)||null,effectiveness_result:clean(req.body.effectiveness_result,2000)||null};await pool.query('UPDATE supplier_scars SET status=?,supplier_response=COALESCE(?,supplier_response),containment=COALESCE(?,containment),root_cause=COALESCE(?,root_cause),corrective_action=COALESCE(?,corrective_action),effectiveness_result=COALESCE(?,effectiveness_result),closed_by=IF(?=\'CLOSED\',?,closed_by),closed_at=IF(?=\'CLOSED\',NOW(),closed_at) WHERE id=?',[target,fields.supplier_response,fields.containment,fields.root_cause,fields.corrective_action,fields.effectiveness_result,target,actor(req),target,s.id]);await logAudit(pool,{...audit(req),action:`SCAR_${target}`,module:'QMS',recordType:'SCAR',recordId:s.scar_no,newValue:{status:target}});return res.json({id:s.id,status:target})}catch(e){return next(e)}}

async function listDocuments(req,res,next){try{await ready();const [rows]=await pool.query('SELECT * FROM controlled_documents ORDER BY document_id');return res.json({documents:rows})}catch(e){return next(e)}}
async function createDocument(req,res,next){try{await ready();const docId=clean(req.body.document_id,80),title=clean(req.body.title,255),reason=clean(req.body.change_reason||'Initial issue',2000);if(!docId||!title)return res.status(400).json({message:'document_id and title are required.'});const contentHash=clean(req.body.content_hash,64)||crypto.createHash('sha256').update(`${docId}|${title}|${req.body.revision||'1.0'}`).digest('hex');const connection=await pool.getConnection();try{await connection.beginTransaction();const [r]=await connection.query('INSERT INTO controlled_documents(document_id,title,department,owner_user_id,current_revision,status,next_review_date,retention_class,training_impact) VALUES(?,?,?,?,?,\'DRAFT\',?,?,?)',[docId,title,clean(req.body.department,100)||null,req.body.owner_user_id||actor(req),clean(req.body.revision||'1.0',40),req.body.next_review_date||null,clean(req.body.retention_class,80)||null,req.body.training_impact?1:0]);await connection.query('INSERT INTO document_revisions(controlled_document_id,revision,status,change_reason,content_hash,secure_document_id,created_by) VALUES(?,?,\'DRAFT\',?,?,?,?)',[r.insertId,clean(req.body.revision||'1.0',40),reason,contentHash,req.body.secure_document_id||null,actor(req)]);await logAudit(connection,{...audit(req),action:'CONTROLLED_DOCUMENT_CREATED',module:'QMS',recordType:'DOCUMENT',recordId:docId,newValue:{revision:req.body.revision||'1.0'}});await connection.commit();return res.status(201).json({id:r.insertId,document_id:docId,status:'DRAFT'})}catch(e){await connection.rollback();throw e}finally{connection.release()}}catch(e){return next(e)}}
async function approveDocument(req,res,next){try{await ready();const [[d]]=await pool.query('SELECT * FROM controlled_documents WHERE id=?',[req.params.id]);if(!d)return res.status(404).json({message:'Controlled document not found.'});if(Number(d.owner_user_id)===actor(req))return res.status(409).json({message:'Separation of duties: document owner cannot provide final approval alone.'});const [[rev]]=await pool.query('SELECT * FROM document_revisions WHERE controlled_document_id=? AND revision=?',[d.id,d.current_revision]);if(!rev)return res.status(409).json({message:'Current document revision not found.'});await pool.query("UPDATE document_revisions SET status='EFFECTIVE',approved_by=?,approved_at=NOW(),effective_date=COALESCE(effective_date,CURDATE()) WHERE id=?",[actor(req),rev.id]);await pool.query("UPDATE controlled_documents SET status='EFFECTIVE',effective_date=COALESCE(effective_date,CURDATE()) WHERE id=?",[d.id]);await logAudit(pool,{...audit(req),action:'CONTROLLED_DOCUMENT_APPROVED',module:'QMS',recordType:'DOCUMENT',recordId:d.document_id,newValue:{revision:d.current_revision,contentHash:rev.content_hash}});return res.json({id:d.id,status:'EFFECTIVE'})}catch(e){return next(e)}}
async function createDocumentChange(req,res,next){try{await ready();const change=clean(req.body.requested_change,4000),reason=clean(req.body.reason,4000);if(!change||!reason)return res.status(400).json({message:'requested_change and reason are required.'});const [r]=await pool.query('INSERT INTO document_change_requests(request_no,controlled_document_id,requested_change,reason,impact_summary,requested_by) VALUES(NULL,?,?,?,?,?)',[req.params.id,change,reason,clean(req.body.impact_summary,4000)||null,actor(req)]);const no=seq('DCR',r.insertId);await pool.query('UPDATE document_change_requests SET request_no=? WHERE id=?',[no,r.insertId]);return res.status(201).json({id:r.insertId,request_no:no,status:'REQUESTED'})}catch(e){return next(e)}}

async function listChanges(req,res,next){try{await ready();const [rows]=await pool.query('SELECT * FROM configuration_changes ORDER BY created_at DESC LIMIT 500');return res.json({changes:rows})}catch(e){return next(e)}}
async function createChange(req,res,next){try{await ready();const type=clean(req.body.change_type,40).toUpperCase(),entityType=clean(req.body.entity_type,80),entityId=clean(req.body.entity_id,120),description=clean(req.body.description,4000),reason=clean(req.body.reason,4000);if(!type||!entityType||!entityId||!description||!reason)return res.status(400).json({message:'change_type, entity_type, entity_id, description and reason are required.'});if(!clean(req.body.rollback_plan,4000)||!clean(req.body.validation_plan,4000))return res.status(400).json({message:'rollback_plan and validation_plan are required.'});const [r]=await pool.query('INSERT INTO configuration_changes(change_no,change_type,entity_type,entity_id,current_revision,proposed_revision,description,reason,impact_assessment_json,validation_plan,rollback_plan,requested_by) VALUES(NULL,?,?,?,?,?,?,?,?,?,?,?)',[type,entityType,entityId,clean(req.body.current_revision,80)||null,clean(req.body.proposed_revision,80)||null,description,reason,JSON.stringify(req.body.impact_assessment||{}),clean(req.body.validation_plan,4000),clean(req.body.rollback_plan,4000),actor(req)]);const no=seq('CHG',r.insertId);await pool.query('UPDATE configuration_changes SET change_no=? WHERE id=?',[no,r.insertId]);if(Array.isArray(req.body.impacts))for(const impact of req.body.impacts.slice(0,100)){await pool.query('INSERT INTO change_impacts(configuration_change_id,impact_type,entity_id,description,disposition) VALUES(?,?,?,?,?)',[r.insertId,clean(impact.impact_type||'OTHER',40),clean(impact.entity_id,120)||null,clean(impact.description,2000)||'Impact identified',clean(impact.disposition,2000)||null])}await logAudit(pool,{...audit(req),action:'CONFIGURATION_CHANGE_REQUESTED',module:'QMS',recordType:type,recordId:no,newValue:{entityType,entityId}});return res.status(201).json({id:r.insertId,change_no:no,status:'REQUESTED'})}catch(e){return next(e)}}
async function transitionChange(req,res,next){const flow={REQUESTED:['IMPACT_ASSESSMENT','REJECTED','CANCELLED'],IMPACT_ASSESSMENT:['REVIEW','REJECTED'],REVIEW:['VALIDATION','APPROVAL','REJECTED'],VALIDATION:['APPROVAL','REJECTED'],APPROVAL:['IMPLEMENTED','REJECTED'],IMPLEMENTED:['VERIFIED'],VERIFIED:['EFFECTIVE']};try{await ready();const [[c]]=await pool.query('SELECT * FROM configuration_changes WHERE id=?',[req.params.id]);if(!c)return res.status(404).json({message:'Configuration change not found.'});const target=clean(req.body.status,40).toUpperCase();if(!(flow[c.status]||[]).includes(target))return res.status(409).json({message:`Invalid change transition ${c.status} → ${target}.`});if(target==='IMPLEMENTED'&&Number(c.requested_by)===actor(req))return res.status(409).json({message:'Separation of duties: requester cannot implement an approved high-risk change alone.'});if(target==='EFFECTIVE'){const [[open]]=await pool.query('SELECT COUNT(*) total FROM change_impacts WHERE configuration_change_id=? AND resolved=0',[c.id]);if(Number(open.total))return res.status(409).json({message:'All identified change impacts must be resolved before the change becomes effective.',open_impacts:Number(open.total)})}await pool.query(`UPDATE configuration_changes SET status=?,approved_by=IF(?='APPROVAL',?,approved_by),implemented_by=IF(?='IMPLEMENTED',?,implemented_by),verified_by=IF(?='VERIFIED',?,verified_by),effective_at=IF(?='EFFECTIVE',NOW(),effective_at) WHERE id=?`,[target,target,actor(req),target,actor(req),target,actor(req),target,c.id]);await logAudit(pool,{...audit(req),action:`CONFIGURATION_CHANGE_${target}`,module:'QMS',recordType:c.change_type,recordId:c.change_no,oldValue:{status:c.status},newValue:{status:target}});return res.json({id:c.id,status:target})}catch(e){return next(e)}}

module.exports={supplierOverview,approveSupplier,addSupplierEvent,generateSupplierScore,createScar,transitionScar,listDocuments,createDocument,approveDocument,createDocumentChange,listChanges,createChange,transitionChange};
