const pool = require('../../config/db');
const { ensureQmsAdvancedSchema } = require('../../services/qmsAdvancedSchema');
const { measurementEquipmentReadiness } = require('../../services/qmsGateService');
const { logAudit } = require('../../services/auditService');

function actor(req){return Number(req.user?.id||req.user?.user_id||0)||null}
function clean(v,max=1000){return String(v??'').trim().slice(0,max)}
function no(prefix,id){return `${prefix}-${new Date().getUTCFullYear()}-${String(id).padStart(6,'0')}`}
function audit(req){return{actorId:actor(req),ipAddress:req.ip,userAgent:req.get('user-agent'),requestId:req.id||req.get('x-request-id')||null,sessionId:req.session?.id||null}}

async function listPlans(req,res,next){try{await ensureQmsAdvancedSchema();const [rows]=await pool.query('SELECT * FROM inspection_plans ORDER BY id DESC LIMIT 500');return res.json({plans:rows})}catch(e){return next(e)}}
async function createPlan(req,res,next){
  try{await ensureQmsAdvancedSchema();const name=clean(req.body.name,255);const type=clean(req.body.inspection_type,20).toUpperCase();if(!name||!['INCOMING','IN_PROCESS','FINAL','FAI'].includes(type))return res.status(400).json({message:'name and valid inspection_type are required.'});
    const [r]=await pool.query('INSERT INTO inspection_plans(plan_no,name,inspection_type,part_no,drawing_revision,status) VALUES(NULL,?,?,?,?,\'DRAFT\')',[name,type,clean(req.body.part_no,100)||null,clean(req.body.drawing_revision,40)||null]);const planNo=no('INSP',r.insertId);await pool.query('UPDATE inspection_plans SET plan_no=? WHERE id=?',[planNo,r.insertId]);await logAudit(pool,{...audit(req),action:'INSPECTION_PLAN_CREATED',module:'QMS',recordType:type,recordId:planNo,newValue:{name}});return res.status(201).json({id:r.insertId,plan_no:planNo,status:'DRAFT'});
  }catch(e){return next(e)}}
async function addCharacteristic(req,res,next){
  try{await ensureQmsAdvancedSchema();const description=clean(req.body.description,255);const charNo=clean(req.body.characteristic_no,80);if(!description||!charNo)return res.status(400).json({message:'characteristic_no and description are required.'});const [r]=await pool.query(`INSERT INTO inspection_characteristics(inspection_plan_id,characteristic_no,description,nominal,lower_limit,upper_limit,unit,blocking,sequence_no) VALUES(?,?,?,?,?,?,?,?,?)`,[req.params.id,charNo,description,req.body.nominal??null,req.body.lower_limit??null,req.body.upper_limit??null,clean(req.body.unit,40)||null,req.body.blocking===false?0:1,Number(req.body.sequence_no||1)]);return res.status(201).json({id:r.insertId})
  }catch(e){return next(e)}}
async function approvePlan(req,res,next){try{await ensureQmsAdvancedSchema();const [[p]]=await pool.query('SELECT * FROM inspection_plans WHERE id=?',[req.params.id]);if(!p)return res.status(404).json({message:'Inspection plan not found.'});const [[count]]=await pool.query('SELECT COUNT(*) total FROM inspection_characteristics WHERE inspection_plan_id=?',[p.id]);if(!Number(count.total))return res.status(409).json({message:'Inspection plan must contain at least one characteristic.'});await pool.query("UPDATE inspection_plans SET status='APPROVED' WHERE id=?",[p.id]);await logAudit(pool,{...audit(req),action:'INSPECTION_PLAN_APPROVED',module:'QMS',recordType:p.inspection_type,recordId:p.plan_no,newValue:{status:'APPROVED'}});return res.json({id:p.id,status:'APPROVED'})}catch(e){return next(e)}}
async function createRun(req,res,next){
  try{await ensureQmsAdvancedSchema();const [[plan]]=await pool.query("SELECT * FROM inspection_plans WHERE id=? AND status='APPROVED'",[req.body.inspection_plan_id]);if(!plan)return res.status(409).json({message:'An approved inspection plan is required.'});const [r]=await pool.query(`INSERT INTO inspection_runs(run_no,inspection_plan_id,job_id,material_lot_id,build_id,serial_id,inspected_by) VALUES(NULL,?,?,?,?,?,?)`,[plan.id,req.body.job_id||null,req.body.material_lot_id||null,req.body.build_id||null,req.body.serial_id||null,actor(req)]);const runNo=no(plan.inspection_type==='FAI'?'FAI':'IR',r.insertId);await pool.query('UPDATE inspection_runs SET run_no=? WHERE id=?',[runNo,r.insertId]);await logAudit(pool,{...audit(req),action:'INSPECTION_RUN_CREATED',module:'QMS',recordType:plan.inspection_type,recordId:runNo,newValue:{planNo:plan.plan_no}});return res.status(201).json({id:r.insertId,run_no:runNo,status:'OPEN'})
  }catch(e){return next(e)}}
async function recordMeasurement(req,res,next){
  try{await ensureQmsAdvancedSchema();const [[run]]=await pool.query('SELECT * FROM inspection_runs WHERE id=?',[req.params.id]);if(!run||run.status!=='OPEN')return res.status(409).json({message:'An open inspection run is required.'});const [[ch]]=await pool.query('SELECT * FROM inspection_characteristics WHERE id=? AND inspection_plan_id=?',[req.body.characteristic_id,run.inspection_plan_id]);if(!ch)return res.status(400).json({message:'Characteristic is not part of this inspection plan.'});
    if(req.body.measurement_equipment_id){const gate=await measurementEquipmentReadiness(req.body.measurement_equipment_id);if(!gate.allowed)return res.status(409).json({code:'CALIBRATION_GATE_BLOCKED',message:'Measurement equipment is not valid for inspection.',reasons:gate.reasons})}
    let result='NA';const actual=req.body.actual_value;
    if(actual!==undefined&&actual!==null&&actual!==''){const n=Number(actual);if(Number.isNaN(n))return res.status(400).json({message:'actual_value must be numeric.'});result=((ch.lower_limit===null||n>=Number(ch.lower_limit))&&(ch.upper_limit===null||n<=Number(ch.upper_limit)))?'PASS':'FAIL'}
    await pool.query(`INSERT INTO inspection_measurements(inspection_run_id,characteristic_id,sample_no,actual_value,text_value,measurement_equipment_id,result,measured_by) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE actual_value=VALUES(actual_value),text_value=VALUES(text_value),measurement_equipment_id=VALUES(measurement_equipment_id),result=VALUES(result),measured_by=VALUES(measured_by),measured_at=NOW()`,[run.id,ch.id,Number(req.body.sample_no||1),actual??null,clean(req.body.text_value,1000)||null,req.body.measurement_equipment_id||null,result,actor(req)]);return res.json({result})
  }catch(e){return next(e)}}
async function completeRun(req,res,next){
  try{await ensureQmsAdvancedSchema();const [[run]]=await pool.query('SELECT ir.*,ip.inspection_type,ip.plan_no FROM inspection_runs ir JOIN inspection_plans ip ON ip.id=ir.inspection_plan_id WHERE ir.id=?',[req.params.id]);if(!run)return res.status(404).json({message:'Inspection run not found.'});if(run.status!=='OPEN')return res.status(409).json({message:'Only open inspection runs can be completed.'});const [chars]=await pool.query('SELECT id,blocking FROM inspection_characteristics WHERE inspection_plan_id=?',[run.inspection_plan_id]);const [ms]=await pool.query('SELECT characteristic_id,result FROM inspection_measurements WHERE inspection_run_id=?',[run.id]);const by=new Map(ms.map(x=>[Number(x.characteristic_id),x.result]));const missing=chars.filter(c=>c.blocking&&!by.has(Number(c.id)));if(missing.length)return res.status(409).json({code:'INSPECTION_INCOMPLETE',message:'Blocking inspection characteristics are incomplete.',missing_characteristic_ids:missing.map(x=>x.id)});const failed=chars.some(c=>c.blocking&&by.get(Number(c.id))==='FAIL');const status=failed?'FAIL':'PASS';await pool.query('UPDATE inspection_runs SET status=?,completed_at=NOW() WHERE id=?',[status,run.id]);await logAudit(pool,{...audit(req),action:`INSPECTION_${status}`,module:'QMS',recordType:run.inspection_type,recordId:run.run_no,newValue:{status}});return res.json({id:run.id,run_no:run.run_no,status})
  }catch(e){return next(e)}}
async function approveRun(req,res,next){try{await ensureQmsAdvancedSchema();const [[run]]=await pool.query('SELECT ir.*,ip.inspection_type FROM inspection_runs ir JOIN inspection_plans ip ON ip.id=ir.inspection_plan_id WHERE ir.id=?',[req.params.id]);if(!run)return res.status(404).json({message:'Inspection run not found.'});if(run.status!=='PASS')return res.status(409).json({message:'Only a passing inspection can be approved.'});if(Number(run.inspected_by)===actor(req))return res.status(409).json({message:'Separation of duties: the inspector cannot provide final approval.'});await pool.query("UPDATE inspection_runs SET status='APPROVED',approved_by=? WHERE id=?",[actor(req),run.id]);await logAudit(pool,{...audit(req),action:run.inspection_type==='FAI'?'FAI_APPROVED':'INSPECTION_APPROVED',module:'QMS',recordType:run.inspection_type,recordId:run.run_no,newValue:{status:'APPROVED'}});return res.json({id:run.id,status:'APPROVED'})}catch(e){return next(e)}}
async function getRun(req,res,next){try{await ensureQmsAdvancedSchema();const [[run]]=await pool.query('SELECT ir.*,ip.plan_no,ip.name,ip.inspection_type FROM inspection_runs ir JOIN inspection_plans ip ON ip.id=ir.inspection_plan_id WHERE ir.id=?',[req.params.id]);if(!run)return res.status(404).json({message:'Inspection run not found.'});const [rows]=await pool.query(`SELECT ic.characteristic_no,ic.description,ic.nominal,ic.lower_limit,ic.upper_limit,ic.unit,ic.blocking,im.sample_no,im.actual_value,im.text_value,im.measurement_equipment_id,im.result,im.measured_at FROM inspection_characteristics ic LEFT JOIN inspection_measurements im ON im.characteristic_id=ic.id AND im.inspection_run_id=? WHERE ic.inspection_plan_id=? ORDER BY ic.sequence_no,ic.id`,[run.id,run.inspection_plan_id]);return res.json({run,characteristics:rows})}catch(e){return next(e)}}

module.exports={listPlans,createPlan,addCharacteristic,approvePlan,createRun,recordMeasurement,completeRun,approveRun,getRun};
